name: Claude Bot Request
description: Request Claude AI to help implement a feature or fix
title: "[Claude]: "
labels: ["claude-request"]
body:
  - type: markdown
    attributes:
      value: |
        Request Claude AI to help with code changes. Include `@claude` in your request description to trigger the bot.

        **Note:** Claude will analyze the request and create a pull request with proposed changes.

  - type: dropdown
    id: request-type
    attributes:
      label: Request Type
      description: What type of help do you need from Claude?
      options:
        - Implement new cmdlet
        - Fix a bug
        - Add tests for existing cmdlet
        - Improve documentation
        - Refactor code
        - Other
    validations:
      required: true

  - type: textarea
    id: request
    attributes:
      label: Request for Claude
      description: |
        Describe what you want Claude to do. Be specific about:
        - What files or cmdlets are involved
        - What the expected behavior should be
        - Any constraints or requirements

        **Remember to include `@claude` in your description!**
      placeholder: |
        @claude Please implement a new cmdlet `Get-ZoomDashboardMeetings` that wraps the Zoom Dashboard Meetings API endpoint.

        Requirements:
        - Follow existing cmdlet patterns in the codebase
        - Include comment-based help with examples
        - Add parameter validation
        - Support pipeline input
    validations:
      required: true

  - type: textarea
    id: api-reference
    attributes:
      label: API Reference (if applicable)
      description: Link to relevant Zoom API documentation
      placeholder: https://developers.zoom.us/docs/api/rest/reference/...

  - type: textarea
    id: existing-code
    attributes:
      label: Related Existing Code
      description: Reference any existing cmdlets or files that Claude should use as examples
      placeholder: |
        - PSZoom/Public/Meetings/Get-ZoomMeeting.ps1
        - PSZoom/Public/Reports/Get-ZoomDailyUsageReport.ps1

  - type: checkboxes
    id: requirements
    attributes:
      label: Requirements Checklist
      description: What should be included in Claude's PR?
      options:
        - label: Include unit tests
          required: false
        - label: Include documentation updates
          required: false
        - label: Follow existing code patterns
          required: true
        - label: Maintain backward compatibility
          required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other information that would help Claude understand the request
