{
 "openapi": "3.0.0",
 "info": {
  "title": "Auto Dialer",
  "description": "",
  "termsOfService": "https://zoom.us/docs/en-us/zoom_api_license_and_tou.html",
  "contact": {
   "name": "Zoom Developers",
   "url": "https://developer.zoom.us/"
  },
  "version": "2"
 },
 "servers": [
  {
   "url": "https://api.zoom.us/v2"
  }
 ],
 "paths": {
  "/dialer/call-histories/{callHistoryId}": {
   "get": {
    "tags": [
     "Call History & Reporting"
    ],
    "summary": "Get Call History by ID",
    "description": "Retrieve call history for a call history ID.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `dialer:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_auto_dialer:read:call_history:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "GetCallDetailsbyCallID",
    "security": [
     {
      "openapi_oauth": [
       "dialer:read:admin",
       "zoom_auto_dialer:read:call_history:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "dialer:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_auto_dialer:read:call_history:admin"
     ]
    }
   }
  },
  "/dialer/call-history": {
   "get": {
    "tags": [
     "Call History & Reporting"
    ],
    "summary": "Get Call History",
    "description": "Retrieve call history with pagination and various filtering options. Supports filtering by user, call list ID, or call ID, but not all three simultaneously.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `dialer:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_auto_dialer:read:call_history:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-lim[...]",
    "operationId": "GetCallHistory",
    "security": [
     {
      "openapi_oauth": [
       "dialer:read:admin",
       "zoom_auto_dialer:read:call_history:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "dialer:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_auto_dialer:read:call_history:admin"
     ]
    }
   }
  },
  "/dialer/call-lists": {
   "get": {
    "tags": [
     "Call List Management"
    ],
    "summary": "List Call Lists",
    "description": "Retrieve all call lists in the account. Optionally filter by user IDs/emails and source.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `dialer:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_auto_dialer:read:call_lists:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "ListCallLists",
    "security": [
     {
      "openapi_oauth": [
       "dialer:read:admin",
       "zoom_auto_dialer:read:call_lists:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "dialer:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_auto_dialer:read:call_lists:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Call List Management"
    ],
    "summary": "Create Call List",
    "description": "Create a new call list\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `dialer:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_auto_dialer:write:call_lists:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "CreateCallList",
    "security": [
     {
      "openapi_oauth": [
       "dialer:write:admin",
       "zoom_auto_dialer:write:call_lists:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "dialer:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_auto_dialer:write:call_lists:admin"
     ]
    }
   }
  },
  "/dialer/call-lists/{callListId}": {
   "get": {
    "tags": [
     "Call List Management"
    ],
    "summary": "Get Call List by ID",
    "description": "Retrieve details of a specific call list by its ID\n\nError Conditions:\nInvalid callListId\nUser is not Zoom Owner or Admin\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `dialer:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_auto_dialer:read:call_lists:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "GetCallListbyID",
    "security": [
     {
      "openapi_oauth": [
       "dialer:read:admin",
       "zoom_auto_dialer:read:call_lists:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "dialer:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_auto_dialer:read:call_lists:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Call List Management"
    ],
    "summary": "Delete Call List",
    "description": "Delete a call list and all its associated prospects.\n\n**Limitation:** Currently, deletion is supported only for call lists created through Open APIs. Future updates will expand support to all call lists.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `dialer:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_auto_dialer:delete:call_lists:admin`\n\n**[Rate Limit Label](https[...]",
    "operationId": "DeleteCallList",
    "security": [
     {
      "openapi_oauth": [
       "dialer:write:admin",
       "zoom_auto_dialer:delete:call_lists:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "dialer:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_auto_dialer:delete:call_lists:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Call List Management"
    ],
    "summary": "Update Call List",
    "description": "Update an existing call list.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `dialer:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_auto_dialer:update:call_lists:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "UpdateCallList",
    "security": [
     {
      "openapi_oauth": [
       "dialer:write:admin",
       "zoom_auto_dialer:update:call_lists:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "dialer:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_auto_dialer:update:call_lists:admin"
     ]
    }
   }
  },
  "/dialer/call-lists/{callListId}/prospects": {
   "get": {
    "tags": [
     "Prospect Management"
    ],
    "summary": "List All Prospects in Call List",
    "description": "Retrieve all prospects in a specific call list.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `dialer:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_auto_dialer:read:prospects:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "ListAllProspectsInCallList",
    "security": [
     {
      "openapi_oauth": [
       "dialer:read:admin",
       "zoom_auto_dialer:read:prospects:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "dialer:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_auto_dialer:read:prospects:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Prospect Management"
    ],
    "summary": "Create Prospect",
    "description": "Create and add a prospect to a call list\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `dialer:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_auto_dialer:write:prospects:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "CreateProspect",
    "security": [
     {
      "openapi_oauth": [
       "dialer:write:admin",
       "zoom_auto_dialer:write:prospects:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "dialer:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_auto_dialer:write:prospects:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Prospect Management"
    ],
    "summary": "Update Prospects batch",
    "description": "Batch update existing prospects. Can also reassign prospects to a different call list.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `dialer:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_auto_dialer:update:prospects:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "UpdateProspects",
    "security": [
     {
      "openapi_oauth": [
       "dialer:write:admin",
       "zoom_auto_dialer:update:prospects:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "dialer:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_auto_dialer:update:prospects:admin"
     ]
    }
   }
  },
  "/dialer/call-lists/{callListId}/prospects/batch": {
   "post": {
    "tags": [
     "Prospect Management"
    ],
    "summary": "Create Prospects batch",
    "description": "Batch call to add prospects to a call list.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `dialer:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_auto_dialer:write:prospects:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "CreateProspects",
    "security": [
     {
      "openapi_oauth": [
       "dialer:write:admin",
       "zoom_auto_dialer:write:prospects:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "dialer:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_auto_dialer:write:prospects:admin"
     ]
    }
   }
  },
  "/dialer/call-lists/{callListId}/prospects/{prospectId}": {
   "delete": {
    "tags": [
     "Prospect Management"
    ],
    "summary": "Delete Prospect",
    "description": "Delete a single prospect from a call list by its ID.\n\n**Limitation:** Currently, deletion is supported only for prospects belonging to call lists created through Open APIs. A future update will expand support to all call lists.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `dialer:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_auto_dialer:delete:prospects:admin`\n\n**[[...]",
    "operationId": "DeleteProspect",
    "security": [
     {
      "openapi_oauth": [
       "dialer:write:admin",
       "zoom_auto_dialer:delete:prospects:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "dialer:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_auto_dialer:delete:prospects:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Prospect Management"
    ],
    "summary": "Update Prospect",
    "description": "Update an existing prospect. Can also reassign prospect to a different call list.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `dialer:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_auto_dialer:update:prospects:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "UpdateProspect",
    "security": [
     {
      "openapi_oauth": [
       "dialer:write:admin",
       "zoom_auto_dialer:update:prospects:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "dialer:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_auto_dialer:update:prospects:admin"
     ]
    }
   }
  },
  "/dialer/prospects/{prospectId}": {
   "get": {
    "tags": [
     "Prospect Management"
    ],
    "summary": "Get Prospect by ID",
    "description": "Retrieve details of a specific prospect.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `dialer:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_auto_dialer:read:prospects:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "GetProspectbyID",
    "security": [
     {
      "openapi_oauth": [
       "dialer:read:admin",
       "zoom_auto_dialer:read:prospects:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "dialer:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_auto_dialer:read:prospects:admin"
     ]
    }
   }
  }
 },
 "components": {
  "securitySchemes": {
   "openapi_authorization": {
    "type": "apiKey",
    "name": "Authorization",
    "in": "header"
   },
   "openapi_oauth": {
    "type": "oauth2",
    "flows": {
     "authorizationCode": {
      "authorizationUrl": "/",
      "tokenUrl": "",
      "refreshUrl": "",
      "scopes": {
       "dialer:read:admin": "dialer:read:admin",
       "zoom_auto_dialer:read:call_history:admin": "zoom_auto_dialer:read:call_history:admin",
       "dialer:write:admin": "dialer:write:admin",
       "zoom_auto_dialer:write:call_lists:admin": "zoom_auto_dialer:write:call_lists:admin",
       "zoom_auto_dialer:read:call_lists:admin": "zoom_auto_dialer:read:call_lists:admin",
       "zoom_auto_dialer:delete:call_lists:admin": "zoom_auto_dialer:delete:call_lists:admin",
       "zoom_auto_dialer:update:call_lists:admin": "zoom_auto_dialer:update:call_lists:admin",
       "zoom_auto_dialer:read:prospects:admin": "zoom_auto_dialer:read:prospects:admin",
       "zoom_auto_dialer:write:prospects:admin": "zoom_auto_dialer:write:prospects:admin",
       "zoom_auto_dialer:update:prospects:admin": "zoom_auto_dialer:update:prospects:admin",
       "zoom_auto_dialer:delete:prospects:admin": "zoom_auto_dialer:delete:prospects:admin"
      }
     }
    }
   }
  }
 }
}