{
 "openapi": "3.0.0",
 "info": {
  "title": "Commerce",
  "description": "[Zoom Commerce](https://developers.zoom.us/docs/commerce/) APIs allows partners to manage subscriptions, enable intergrations, and more.",
  "termsOfService": "https://zoom.us/docs/en-us/zoom_api_license_and_tou.html",
  "contact": {
   "name": "Zoom Developers",
   "url": "https://developer.zoom.us/"
  },
  "version": "2"
 },
 "servers": [
  {
   "url": "https://api.zoom.us/v2"
  }
 ],
 "paths": {
  "/commerce/account": {
   "post": {
    "tags": [
     "Account Management"
    ],
    "summary": "Create an end customer account",
    "description": "Creates an end customer account. \n**Note** Please check the base URL for sandbox and production environments under Zoom Commerce section [here](/docs/api).\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:write:sub_account:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rat[...]",
    "operationId": "createAccount",
    "security": [
     {
      "openapi_oauth": [
       "zoom_commerce:write:admin",
       "zoom_commerce:write:sub_account:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_commerce:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_commerce:write:sub_account:admin"
     ]
    }
   }
  },
  "/commerce/account/{accountKey}/contacts": {
   "post": {
    "tags": [
     "Account Management"
    ],
    "summary": "Add contacts to an existing end customer or your own account.",
    "description": "Add contacts to an existing end customer or your own account. <br><b>Note:</b> Check the base URL for sandbox and production environments under Zoom Commerce section [here](https://developers.zoom.us/docs/api).\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:update:account:admin`\n\n**[Rate Limit Label][...]",
    "operationId": "addAccountContact",
    "security": [
     {
      "openapi_oauth": [
       "zoom_commerce:write:admin",
       "zoom_commerce:update:account:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_commerce:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_commerce:update:account:admin"
     ]
    }
   }
  },
  "/commerce/accounts": {
   "get": {
    "tags": [
     "Account Management"
    ],
    "summary": "Get the list of all accounts associated with a Zoom Partner/Sub-Reseller, by the account type",
    "description": "Returns the list of all accounts associated with a Zoom Partner and Sub-Reseller, by the account type - endCustomer, subReseller, and relatedPartner. <br><b>Note:</b> Please check the base URL for sandbox and production environments under Zoom Commerce section [here](https://developers.zoom.us/docs/api).\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integr[...]",
    "operationId": "getAllAccounts",
    "security": [
     {
      "openapi_oauth": [
       "zoom_commerce:read:admin",
       "zoom_commerce:read:account:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_commerce:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_commerce:read:account:admin"
     ]
    }
   }
  },
  "/commerce/accounts/{accountKey}": {
   "get": {
    "tags": [
     "Account Management"
    ],
    "summary": "Get the account details for a Zoom Partner/Subreseller/End Customer",
    "description": "Returns the account details for a Zoom Partner, Subreseller, and End Customer. <br><b>Note:</b> Please check the base URL for sandbox and production environments under Zoom Commerce section [here](/docs/api).\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:read:account:admin`\n\n**[Rate Limit Label](http[...]",
    "operationId": "getAccountDetails",
    "security": [
     {
      "openapi_oauth": [
       "zoom_commerce:read:admin",
       "zoom_commerce:read:account:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_commerce:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_commerce:read:account:admin"
     ]
    }
   }
  },
  "/commerce/billing_documents": {
   "get": {
    "tags": [
     "Billing"
    ],
    "summary": "Gets all billing documents for a distributor or a reseller",
    "description": "Returns all billing documents for a distributor or a reseller. \n\nBilling Documents represent the end customer's invoices, credit memos and debit memos. The response can be filtered by status, document date etc. By default, the list of unpaid invoices in the last 1 month are retrieved. \n\n<br><b>Note:</b> Check the base URL for sandbox and production environments under Zoom Commerce section [here](https://developers.zoom.us/docs/api).\n\n**[Scopes](https://developers.zoom.u[...]",
    "operationId": "getAllBillingDocs",
    "security": [
     {
      "openapi_oauth": [
       "zoom_commerce:read:admin",
       "zoom_commerce:read:billing_documents:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_commerce:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_commerce:read:billing_documents:admin"
     ]
    }
   }
  },
  "/commerce/billing_documents/{documentNumber}/document": {
   "get": {
    "tags": [
     "Billing"
    ],
    "summary": "Gets the PDF document for the billing document ID",
    "description": "Returns the PDF document for the billing document ID. \n\n<br><b>Note:</b> Check the base URL for sandbox and production environments under Zoom Commerce section [here](https://developers.zoom.us/docs/api). \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:read:billing_documents:admin`\n\n**[Rate Limit La[...]",
    "operationId": "downloadBillingDoc",
    "security": [
     {
      "openapi_oauth": [
       "zoom_commerce:read:admin",
       "zoom_commerce:read:billing_documents:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_commerce:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_commerce:read:billing_documents:admin"
     ]
    }
   }
  },
  "/commerce/invoices/{invoiceNumber}": {
   "get": {
    "tags": [
     "Billing"
    ],
    "summary": "Get detailed information about a specific invoice for a distributor or a reseller",
    "description": "Returns detailed information about a specific invoice for a distributor or a reseller. \n\nTo filter the details for a particular end customer provide the end customer Zoom account number or CRM account number. \n<br><b>Note:</b> Check the base URL for sandbox and production environments under Zoom Commerce section [here](https://developers.zoom.us/docs/api).\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:read:admin`\n\n**[...]",
    "operationId": "getInvoiceDetail",
    "security": [
     {
      "openapi_oauth": [
       "zoom_commerce:read:admin",
       "zoom_commerce:read:billing_documents:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_commerce:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_commerce:read:billing_documents:admin"
     ]
    }
   }
  },
  "/commerce/campaigns": {
   "get": {
    "tags": [
     "Deal Registration"
    ],
    "summary": "Retrieves all valid Zoom Campaigns which a deal registration can be associated with.",
    "description": "Retrieves all valid Zoom Campaigns which a deal registration can be associated with. <br><b>Note:</b> Please check the base URL for sandbox and production environments under Zoom Commerce section [here](https://developers.zoom.us/docs/api).\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:read:deal_regist[...]",
    "operationId": "getCampaigns",
    "security": [
     {
      "openapi_oauth": [
       "zoom_commerce:read:admin",
       "zoom_commerce:read:deal_registration:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_commerce:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_commerce:read:deal_registration:admin"
     ]
    }
   }
  },
  "/commerce/deal_registration": {
   "post": {
    "tags": [
     "Deal Registration"
    ],
    "summary": "Creates a new deal registration for a partner",
    "description": "Creates a new Deal Registration for a partner. <br><b>Note:</b> Check the base URL for sandbox and production environments under Zoom Commerce section [here](https://developers.zoom.us/docs/api).\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:write:deal_registration:admin`\n\n**[Rate Limit Label](https[...]",
    "operationId": "createDealReg",
    "security": [
     {
      "openapi_oauth": [
       "zoom_commerce:write:admin",
       "zoom_commerce:write:deal_registration:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_commerce:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_commerce:write:deal_registration:admin"
     ]
    }
   }
  },
  "/commerce/deal_registrations": {
   "get": {
    "tags": [
     "Deal Registration"
    ],
    "summary": "Gets all valid Deal Registrations for a partner",
    "description": "Retrieves all valid deal registrations for a partner. <br><b>Note:</b> Please check the base URL for sandbox and production environments under the Zoom Commerce section [here](https://developers.zoom.us/docs/api).\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:read:deal_registration:admin`\n\n**[Rate Li[...]",
    "operationId": "getAllDealRegs",
    "security": [
     {
      "openapi_oauth": [
       "zoom_commerce:read:admin",
       "zoom_commerce:read:deal_registration:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_commerce:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_commerce:read:deal_registration:admin"
     ]
    }
   }
  },
  "/commerce/deal_registrations/{dealRegKey}": {
   "get": {
    "tags": [
     "Deal Registration"
    ],
    "summary": "Gets details of a deal registration by the deal registration",
    "description": "Gets details for a deal registration by the deal registration number. <br><b>Note:</b> Check the base URL for sandbox and production environments under the Zoom Commerce section [here](https://developers.zoom.us/docs/api).\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:read:deal_registration:admin`\n\n*[...]",
    "operationId": "getDealRegDetails",
    "security": [
     {
      "openapi_oauth": [
       "zoom_commerce:read:admin",
       "zoom_commerce:read:deal_registration:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_commerce:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_commerce:read:deal_registration:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Deal Registration"
    ],
    "summary": "Updates an existing deal registration",
    "description": "Updates an existing deal registration that has been returned (Deal status = returned). <br><b>Note:</b> Please check the base URL for sandbox and production environments under Zoom Commerce section [here](https://developers.zoom.us/docs/api).\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:write:deal_re[...]",
    "operationId": "Updatesanexistingdealregistration",
    "security": [
     {
      "openapi_oauth": [
       "zoom_commerce:write:admin",
       "zoom_commerce:write:deal_registration:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_commerce:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_commerce:write:deal_registration:admin"
     ]
    }
   }
  },
  "/commerce/order": {
   "post": {
    "tags": [
     "Order"
    ],
    "summary": "Create a subscription order for a Zoom partner",
    "description": "Create a subscription order for a Zoom partner's end customers. One order can have more than one subscription for more than one end customer. The same order can create a new subscription and also amend an existing subscription. \n**Note** Check the base URL for sandbox and production environments under Zoom Commerce section [here](https://developers.zoom.us/docs/api/).\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:write:a[...]",
    "operationId": "createOrder",
    "security": [
     {
      "openapi_oauth": [
       "zoom_commerce:write:admin",
       "zoom_commerce:write:order:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_commerce:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_commerce:write:order:admin"
     ]
    }
   }
  },
  "/commerce/order/preview": {
   "post": {
    "tags": [
     "Order"
    ],
    "summary": "Preview delta order metrics and subscriptions in an order ",
    "description": "Previews the delta order metrics and subscriptions in an order. Validates the order and gets the metrics like TCV, applicable discounts, and net MRR before placing the order for provisioning. This operation is only an order preview, and no order is submitted for fulfillment. To submit the order, use the [order API](/docs/api/commerce/#tag/order/POST/commerce/order/preview). \\n**Note** Please check the base URL for sandbox and production environments under Zoom Commerce secti[...]",
    "operationId": "createOrderPreview",
    "security": [
     {
      "openapi_oauth": [
       "zoom_commerce:write:admin",
       "zoom_commerce:write:order:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_commerce:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_commerce:write:order:admin"
     ]
    }
   }
  },
  "/commerce/orders": {
   "get": {
    "tags": [
     "Order"
    ],
    "summary": "Gets all orders for a Zoom partner.",
    "description": "Returns all orders for a Zoom partner based on specified filters. <br><b>Note:</b> Please check the base URL for sandbox and production environments under Zoom Commerce section [here](https://developers.zoom.us/docs/api).\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:read:order:admin`\n\n**[Rate Limit [...]",
    "operationId": "getAllOrders",
    "security": [
     {
      "openapi_oauth": [
       "zoom_commerce:read:admin",
       "zoom_commerce:read:order:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_commerce:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_commerce:read:order:admin"
     ]
    }
   }
  },
  "/commerce/orders/{orderReferenceId}": {
   "get": {
    "tags": [
     "Order"
    ],
    "summary": "Get order details by order reference ID",
    "description": "Gets order details by order reference ID. <br><b>Note:</b> Please check the base URL for sandbox and production environments under Zoom Commerce section [here](https://developers.zoom.us/docs/api).\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:read:order:admin`\n\n**[Rate Limit Label](https://marketpla[...]",
    "operationId": "getOrderDetails",
    "security": [
     {
      "openapi_oauth": [
       "zoom_commerce:read:admin",
       "zoom_commerce:read:order:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_commerce:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_commerce:read:order:admin"
     ]
    }
   }
  },
  "/commerce/file": {
   "post": {
    "tags": [
     "Platform"
    ],
    "summary": "Upload an attachment pdf file in context of a deal registration or quote",
    "description": "\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:write:file:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`\n\n**Not supported in Gov cluster** ",
    "operationId": "uploadFile",
    "security": [
     {
      "openapi_oauth": [
       "zoom_commerce:write:admin",
       "zoom_commerce:write:file:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_commerce:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_commerce:write:file:admin"
     ]
    }
   }
  },
  "/commerce/files/{associatedReferenceId}/details": {
   "get": {
    "tags": [
     "Platform"
    ],
    "summary": "Gets details of all files associated with a quote or deal registration",
    "description": "\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:read:file:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "allFileDetails",
    "security": [
     {
      "openapi_oauth": [
       "zoom_commerce:read:admin",
       "zoom_commerce:read:file:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_commerce:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_commerce:read:file:admin"
     ]
    }
   }
  },
  "/commerce/files/{documentReferenceId}": {
   "get": {
    "tags": [
     "Platform"
    ],
    "summary": "Download a file associated with a quote or deal registration.",
    "description": "Download a file associated with a quote or deal registration.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:read:file:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`\n\n**Not supported in Gov cluster** ",
    "operationId": "downloadFile.",
    "security": [
     {
      "openapi_oauth": [
       "zoom_commerce:read:admin",
       "zoom_commerce:read:file:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_commerce:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_commerce:read:file:admin"
     ]
    }
   }
  },
  "/commerce/catalog": {
   "post": {
    "tags": [
     "Product Catalog"
    ],
    "summary": "Gets Zoom Product Catalog for a Zoom Partner",
    "description": "Returns the Zoom product catalog for a Zoom Partner. <br><b>Note:</b> Please check the base URL for sandbox and production environments under Zoom Commerce section [here](https://developers.zoom.us/docs/api).\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:read:product_catalog:admin`\n\n**[Rate Limit Lab[...]",
    "operationId": "getOffers",
    "security": [
     {
      "openapi_oauth": [
       "zoom_commerce:read:admin",
       "zoom_commerce:read:product_catalog:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_commerce:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_commerce:read:product_catalog:admin"
     ]
    }
   }
  },
  "/commerce/catalog/{offerId}": {
   "get": {
    "tags": [
     "Product Catalog"
    ],
    "summary": "Gets the details for a Zoom product or offer.",
    "description": "Returns the details for a Zoom product or offer. Each offer is identified by a unique ID. <br><b>Note:</b> Please check the base URL for sandbox and production environments under Zoom Commerce section [here](https://developers.zoom.us/docs/api).\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:read:produc[...]",
    "operationId": "getOfferDetail",
    "security": [
     {
      "openapi_oauth": [
       "zoom_commerce:read:admin",
       "zoom_commerce:read:product_catalog:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_commerce:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_commerce:read:product_catalog:admin"
     ]
    }
   }
  },
  "/commerce/pricebooks": {
   "get": {
    "tags": [
     "Product Catalog"
    ],
    "summary": "Gets the pricebook in a downloadable file",
    "description": "Returns the pricebook in a CSV or Excel format including list price and discounted price based on the partner type. <br><b>Note:</b> Please check the base URL for sandbox and production environments under Zoom Commerce section [here](https://developers.zoom.us/docs/api).\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** [...]",
    "operationId": "downloadPricebook",
    "security": [
     {
      "openapi_oauth": [
       "zoom_commerce:read:admin",
       "zoom_commerce:read:product_catalog:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_commerce:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_commerce:read:product_catalog:admin"
     ]
    }
   }
  },
  "/commerce/quote": {
   "post": {
    "tags": [
     "Quote"
    ],
    "summary": "Create a subscription quote for a Zoom Partner",
    "description": "Create a subscription quote for a Zoom partner's end customers.\n**Note** Check the base URL for sandbox and production environments under Zoom Commerce section [here](/docs/api/).\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:write:quote:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs[...]",
    "operationId": "createQuote",
    "security": [
     {
      "openapi_oauth": [
       "zoom_commerce:write:admin",
       "zoom_commerce:write:quote:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_commerce:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_commerce:write:quote:admin"
     ]
    }
   }
  },
  "/commerce/quote/preview": {
   "post": {
    "tags": [
     "Quote"
    ],
    "summary": "Preview delta quote metrics and subscriptions in a quote ",
    "description": "Previews the delta quote metrics, and subscriptions in a quote. The API can be used to validate the quote and get the metrics like TCV, applicable discounts, and net MRR, before submitting the quote for actual creation and provisioning. This operation is only a quote preview and no quote is submitted for approval and fulfillment. For submitting the quote use the quote API. <br><b>Note:</b> Please check the base URL for sandbox and production environments under Zoom Commerce s[...]",
    "operationId": "createQuotePreview",
    "security": [
     {
      "openapi_oauth": [
       "zoom_commerce:write:admin",
       "zoom_commerce:write:quote:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_commerce:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_commerce:write:quote:admin"
     ]
    }
   }
  },
  "/commerce/quotes": {
   "get": {
    "tags": [
     "Quote"
    ],
    "summary": "Gets all quotes for a Zoom partner",
    "description": "Returns all quotes for a Zoom partner based on specified filters. <br><b>Note:</b> Please check the base URL for sandbox and production environments under Zoom Commerce section [here](https://developers.zoom.us/docs/api). \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:read:quote:admin`\n\n**[Rate Limit[...]",
    "operationId": "getAllQuotes",
    "security": [
     {
      "openapi_oauth": [
       "zoom_commerce:read:admin",
       "zoom_commerce:read:quote:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_commerce:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_commerce:read:quote:admin"
     ]
    }
   }
  },
  "/commerce/quotes/{quoteReferenceId}": {
   "get": {
    "tags": [
     "Quote"
    ],
    "summary": "Get quote details by quote reference ID",
    "description": "Get quote details by quote reference ID. \n**Note** Check the base URL for sandbox and production environments under Zoom Commerce section [here](/docs/api).\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:read:quote:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limit[...]",
    "operationId": "getQuoteDetails",
    "security": [
     {
      "openapi_oauth": [
       "zoom_commerce:read:admin",
       "zoom_commerce:read:quote:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_commerce:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_commerce:read:quote:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Quote"
    ],
    "summary": "Update a subscription quote for a Zoom partner",
    "description": "Update a subscription quote for a Zoom partner's end customers. Approved quotes cannot be updated.<br><b>Note:</b> Check the base URL for sandbox and production environments under Zoom Commerce section [here](https://developers.zoom.us/docs/api/).\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:write:qu[...]",
    "operationId": "updateQuote",
    "security": [
     {
      "openapi_oauth": [
       "zoom_commerce:write:admin",
       "zoom_commerce:write:quote:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_commerce:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_commerce:write:quote:admin"
     ]
    }
   }
  },
  "/commerce/quotes/{quoteReferenceId}/fulfillment": {
   "patch": {
    "tags": [
     "Quote"
    ],
    "summary": "Submits a subscription quote for provisioning",
    "description": "Submits a subscription quote for provisioning. Only approved quotes can be submitted for fulfillment. <br><b>Note:</b> Check the base URL for sandbox and production environments under Zoom Commerce section [here](https://developers.zoom.us/docs/api/).\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:writ[...]",
    "operationId": "provisionQuote",
    "security": [
     {
      "openapi_oauth": [
       "zoom_commerce:write:admin",
       "zoom_commerce:write:quote:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_commerce:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_commerce:write:quote:admin"
     ]
    }
   }
  },
  "/commerce/subscriptions": {
   "get": {
    "tags": [
     "Subscription"
    ],
    "summary": "Gets paid subscriptions for a Zoom partner.",
    "description": "Returns paid subscriptions for a distributor or a reseller. The subscriptions list can be filtered by end customer account number, subscription status, subscription number, start and end dates. By default, the list of active subscriptions in the last 1 month are retrieved. <br><b>Note:</b> Please check the base URL for sandbox and production environments under Zoom Commerce section [here](https://developers.zoom.us/docs/api). \n\n**[Scopes](https://developers.zoom.us/docs/int[...]",
    "operationId": "getAllSubscriptions",
    "security": [
     {
      "openapi_oauth": [
       "zoom_commerce:read:admin",
       "zoom_commerce:read:subscription:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_commerce:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_commerce:read:subscription:admin"
     ]
    }
   }
  },
  "/commerce/subscriptions/{subscriptionNumber}": {
   "get": {
    "tags": [
     "Subscription"
    ],
    "summary": "Gets subscription details for a given subscription number",
    "description": "Returns the subscription details for a given subscription number. <br><b>Note:</b> Please check the base URL for sandbox and production environments under Zoom Commerce section [here](https://developers.zoom.us/docs/api/).\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:read:subscription:admin`\n\n**[Rat[...]",
    "operationId": "getSubscriptionDetails",
    "security": [
     {
      "openapi_oauth": [
       "zoom_commerce:read:admin",
       "zoom_commerce:read:subscription:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_commerce:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_commerce:read:subscription:admin"
     ]
    }
   }
  },
  "/commerce/subscriptions/{subscriptionNumber}/versions": {
   "get": {
    "tags": [
     "Subscription"
    ],
    "summary": "Gets subscription changes/versions for a given subscription number.",
    "description": "Returns the subscription changes or versions for a given subscription number. <br><b>Note:</b> Please check the base URL for sandbox and production environments under Zoom Commerce section here - https://developers.zoom.us/docs/api\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:read:subscription:admin`\[...]",
    "operationId": "getSubscriptionVersions",
    "security": [
     {
      "openapi_oauth": [
       "zoom_commerce:read:admin",
       "zoom_commerce:read:subscription:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_commerce:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_commerce:read:subscription:admin"
     ]
    }
   }
  },
  "/commerce/trials": {
   "get": {
    "tags": [
     "Subscription"
    ],
    "summary": "Get trial subscriptions for a Zoom partner",
    "description": "Returns trial subscriptions for a distributor or a reseller. The subscriptions list can be filtered by end customer account number, subscription status, subscription number, start and end dates. By default, the list of active subscriptions in the last 1 month are retrieved. <br><b>Note:</b> Please check the base URL for sandbox and production environments under Zoom Commerce section [here](https://developers.zoom.us/docs/api). \n\n**[Scopes](https://developers.zoom.us/docs/in[...]",
    "operationId": "getAllTrialSubscriptions",
    "security": [
     {
      "openapi_oauth": [
       "zoom_commerce:read:admin",
       "zoom_commerce:read:subscription:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_commerce:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_commerce:read:subscription:admin"
     ]
    }
   }
  },
  "/commerce/trials/{trialReferenceId}": {
   "get": {
    "tags": [
     "Subscription"
    ],
    "summary": "Get trial details for an end customer ZAN",
    "description": "Returns the trial details for an end customer. <br><b>Note:</b> Please check the base URL for sandbox and production environments under Zoom Commerce section [here](https://developers.zoom.us/docs/api/).\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_commerce:read:subscription:admin`\n\n**[Rate Limit Label](http[...]",
    "operationId": "getTrialDetails",
    "security": [
     {
      "openapi_oauth": [
       "zoom_commerce:read:admin",
       "zoom_commerce:read:subscription:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_commerce:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_commerce:read:subscription:admin"
     ]
    }
   }
  }
 },
 "components": {
  "securitySchemes": {
   "openapi_authorization": {
    "type": "apiKey",
    "name": "Authorization",
    "in": "header"
   },
   "openapi_oauth": {
    "type": "oauth2",
    "flows": {
     "authorizationCode": {
      "authorizationUrl": "/",
      "tokenUrl": "",
      "refreshUrl": "",
      "scopes": {
       "zoom_commerce:write:admin": "zoom_commerce:write:admin",
       "zoom_commerce:write:sub_account:admin": "zoom_commerce:write:sub_account:admin",
       "zoom_commerce:update:account:admin": "zoom_commerce:update:account:admin",
       "zoom_commerce:read:admin": "zoom_commerce:read:admin",
       "zoom_commerce:read:account:admin": "zoom_commerce:read:account:admin",
       "zoom_commerce:read:billing_documents:admin": "zoom_commerce:read:billing_documents:admin",
       "zoom_commerce:read:deal_registration:admin": "zoom_commerce:read:deal_registration:admin",
       "zoom_commerce:write:deal_registration:admin": "zoom_commerce:write:deal_registration:admin",
       "zoom_commerce:write:order:admin": "zoom_commerce:write:order:admin",
       "zoom_commerce:read:order:admin": "zoom_commerce:read:order:admin",
       "zoom_commerce:write:file:admin": "zoom_commerce:write:file:admin",
       "zoom_commerce:read:file:admin": "zoom_commerce:read:file:admin",
       "zoom_commerce:read:product_catalog:admin": "zoom_commerce:read:product_catalog:admin",
       "zoom_commerce:write:quote:admin": "zoom_commerce:write:quote:admin",
       "zoom_commerce:read:quote:admin": "zoom_commerce:read:quote:admin",
       "zoom_commerce:read:subscription:admin": "zoom_commerce:read:subscription:admin"
      }
     }
    }
   }
  }
 }
}