{
 "openapi": "3.0.0",
 "info": {
  "title": "Contact Center",
  "description": "The Contact Center APIs allow developers to interface with [Contact Center](https://developers.zoom.us/docs/contact-center/) features programmatically.",
  "termsOfService": "https://zoom.us/docs/en-us/zoom_api_license_and_tou.html",
  "contact": {
   "name": "Zoom Developers",
   "url": "https://developer.zoom.us/"
  },
  "version": "2"
 },
 "servers": [
  {
   "url": "https://api.zoom.us/v2"
  }
 ],
 "paths": {
  "/contact_center/address_books": {
   "get": {
    "tags": [
     "Address Books"
    ],
    "summary": "List address books",
    "description": "Return a list of all address books. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_contact:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:list_address_books:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "listAddressBooks",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_contact:read:admin",
       "contact_center:read:list_address_books:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_contact:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:list_address_books:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Address Books"
    ],
    "summary": "Create an address book",
    "description": "Create an [address book](https://support.zoom.us/hc/en-us/articles/4471544949389). An address book is a collection of consumer information like display names, phone numbers, and locations. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_contact:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:write:address_book:admin`\n\n**[Rate Limit Label](h[...]",
    "operationId": "createAddressBook",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_contact:write:admin",
       "contact_center:write:address_book:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_contact:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:address_book:admin"
     ]
    }
   }
  },
  "/contact_center/address_books/contacts/{contactId}/custom_fields": {
   "get": {
    "tags": [
     "Address Books"
    ],
    "summary": "List a contact's custom fields",
    "description": "List all custom fields on a contact.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_contact:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:address_book_custom_field:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "ListContactCustomFields",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_contact:read:admin",
       "contact_center:read:address_book_custom_field:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_contact:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:address_book_custom_field:admin"
     ]
    }
   }
  },
  "/contact_center/address_books/custom_fields": {
   "get": {
    "tags": [
     "Address Books"
    ],
    "summary": "List an address book's custom fields",
    "description": "Return all address book custom fields.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_contact:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:address_book_custom_field:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "Listaddressbookcustomfields",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_contact:read:admin",
       "contact_center:read:address_book_custom_field:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_contact:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:address_book_custom_field:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Address Books"
    ],
    "summary": "Create an address book custom field",
    "description": "Create an address book custom field.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_contact:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:write:address_book_custom_field:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "Createacustomfield",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_contact:write:admin",
       "contact_center:write:address_book_custom_field:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_contact:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:address_book_custom_field:admin"
     ]
    }
   }
  },
  "/contact_center/address_books/custom_fields/{customFieldId}": {
   "get": {
    "tags": [
     "Address Books"
    ],
    "summary": "Get an address book's custom field",
    "description": "Get information about an address book's custom field.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_contact:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:address_book_custom_field:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "Getaaddressbookcustomfield",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_contact:read:admin",
       "contact_center:read:address_book_custom_field:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_contact:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:address_book_custom_field:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Address Books"
    ],
    "summary": "Delete an address book custom field",
    "description": "Delete an address book custom field.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_contact:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:address_book_custom_field:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "Deleteancustomfield",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_contact:write:admin",
       "contact_center:delete:address_book_custom_field:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_contact:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:address_book_custom_field:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Address Books"
    ],
    "summary": "Update an address book custom field",
    "description": "Update an address book custom field.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_contact:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:update:address_book_custom_field:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "Updateacustomfield",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_contact:write:admin",
       "contact_center:update:address_book_custom_field:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_contact:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:update:address_book_custom_field:admin"
     ]
    }
   }
  },
  "/contact_center/address_books/units": {
   "get": {
    "tags": [
     "Address Books"
    ],
    "summary": "List address book units",
    "description": "Return all address book units. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_contact:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:list_address_book_units:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "listUnits",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_contact:read:admin",
       "contact_center:read:list_address_book_units:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_contact:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:list_address_book_units:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Address Books"
    ],
    "summary": "Create an address book unit",
    "description": "Create an [address book unit](https://support.zoom.us/hc/en-us/articles/4471495629837-Managing-address-book-units). Admins can use address book units to organize several [address books](https://support.zoom.us/hc/en-us/articles/4471544949389#:~:text=An%20address%20book%20is%20a%20collection%20of%20consumer%20information%20like%20display%20names%2C%20phone%20numbers%2C%20and%20locations.). \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/)[...]",
    "operationId": "createUnit",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_contact:write:admin",
       "contact_center:write:address_book_unit:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_contact:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:address_book_unit:admin"
     ]
    }
   }
  },
  "/contact_center/address_books/units/{unitId}": {
   "get": {
    "tags": [
     "Address Books"
    ],
    "summary": "Get an address book unit",
    "description": "Get information about an address book unit. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_contact:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:address_book_unit:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "getUnit",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_contact:read:admin",
       "contact_center:read:address_book_unit:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_contact:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:address_book_unit:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Address Books"
    ],
    "summary": "Delete an address book unit",
    "description": "Delete an address book unit. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_contact:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:address_book_unit:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "deleteUnit",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_contact:write:admin",
       "contact_center:delete:address_book_unit:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_contact:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:address_book_unit:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Address Books"
    ],
    "summary": "Update an address book unit",
    "description": "Update an address book unit. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_contact:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:update:address_book_unit:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "updateUnit",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_contact:write:admin",
       "contact_center:update:address_book_unit:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_contact:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:update:address_book_unit:admin"
     ]
    }
   }
  },
  "/contact_center/address_books/{addressBookId}": {
   "get": {
    "tags": [
     "Address Books"
    ],
    "summary": "Get an address book",
    "description": "Get information about an address book. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_contact:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:address_book:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "getAddressBook",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_contact:read:admin",
       "contact_center:read:address_book:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_contact:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:address_book:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Address Books"
    ],
    "summary": "Delete an address book",
    "description": "Delete an address book. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_contact:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:address_book:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "deleteAddressBook",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_contact:write:admin",
       "contact_center:delete:address_book:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_contact:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:address_book:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Address Books"
    ],
    "summary": "Update an address book",
    "description": "Update an address book's information. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_contact:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:update:address_book:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "updateAddressBook",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_contact:write:admin",
       "contact_center:update:address_book:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_contact:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:update:address_book:admin"
     ]
    }
   }
  },
  "/contact_center/address_books/{addressBookId}/contacts": {
   "get": {
    "tags": [
     "Address Books"
    ],
    "summary": "List address book contacts",
    "description": "When the `emails` or `phone_numbers` query parameter is included, the address book returns a maximum of 10,000 contacts.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_contact:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:list_address_book_contacts:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate[...]",
    "operationId": "listContacts",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_contact:read:admin",
       "contact_center:read:list_address_book_contacts:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_contact:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:list_address_book_contacts:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Address Books"
    ],
    "summary": "Create an address book contact",
    "description": "Create a new contact in an [address book](https://support.zoom.us/hc/en-us/articles/4471544949389). During an active engagement, the Zoom desktop client will display information from the address book if that customer is a contact in the address book. If the consumer is not in the address book, agents can add a new contact and choose which address book the contact belongs to. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_c[...]",
    "operationId": "createContact",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_contact:write:admin",
       "contact_center:write:address_book_contact:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_contact:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:address_book_contact:admin"
     ]
    }
   }
  },
  "/contact_center/address_books/{addressBookId}/contacts/{contactId}": {
   "get": {
    "tags": [
     "Address Books"
    ],
    "summary": "Get an address book contact",
    "description": "Use this API to get information about an address book's contact. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_contact:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:address_book_contact:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "getContact",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_contact:read:admin",
       "contact_center:read:address_book_contact:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_contact:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:address_book_contact:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Address Books"
    ],
    "summary": "Delete an address book contact",
    "description": "Delete an contact from an address book. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_contact:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:address_book_contact:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "contactDelete",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_contact:write:admin",
       "contact_center:delete:address_book_contact:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_contact:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:address_book_contact:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Address Books"
    ],
    "summary": "Update an address book contact",
    "description": "Use this API to update an address book's contact. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_contact:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:update:address_book_contact:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "updateContact",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_contact:write:admin",
       "contact_center:update:address_book_contact:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_contact:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:update:address_book_contact:admin"
     ]
    }
   }
  },
  "/contact_center/system_statuses": {
   "get": {
    "tags": [
     "Agent Statuses"
    ],
    "summary": "List system statuses",
    "description": "Get a list of system statuses. Administrators can create system statuses, such as **Maintenance**.  \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_preference:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:list_system_statues:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "listSystemStatus",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_preference:read:admin",
       "contact_center:read:list_system_statues:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_preference:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:list_system_statues:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Agent Statuses"
    ],
    "summary": "Create a system status",
    "description": "Create custom statuses for the `agent_status` and `queue_opt_out_and_not_ready_status` categories. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_preference:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:write:system_status:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "createSystemStatus",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_preference:write:admin",
       "contact_center:write:system_status:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_preference:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:system_status:admin"
     ]
    }
   }
  },
  "/contact_center/system_statuses/{statusId}": {
   "get": {
    "tags": [
     "Agent Statuses"
    ],
    "summary": "Get a system status",
    "description": "Get information about a system status. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_preference:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:system_status:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "getAStatus",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_preference:read:admin",
       "contact_center:read:system_status:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_preference:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:system_status:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Agent Statuses"
    ],
    "summary": "Delete a system status",
    "description": "Delete a custom status for the `agent_status` and `queue_opt_out_and_not_ready_status categories`.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_preference:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:system_status:admin`",
    "operationId": "deleteSystemStatus",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_preference:write:admin",
       "contact_center:delete:system_status:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_preference:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:system_status:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Agent Statuses"
    ],
    "summary": "Update a system status",
    "description": "Update a custom status for the `agent_status` and `queue_opt_out_and_not_ready_status` categories. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_preference:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:update:system_status:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "updateSystemStatus",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_preference:write:admin",
       "contact_center:update:system_status:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_preference:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:update:system_status:admin"
     ]
    }
   }
  },
  "/contact_center/asset_library/assets": {
   "get": {
    "tags": [
     "Asset Library"
    ],
    "summary": "List assets",
    "description": "List Contact Center assets.\n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_asset_library:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:asset_library:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "listAssets",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_asset_library:read:admin",
       "contact_center:read:asset_library:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_asset_library:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:asset_library:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Asset Library"
    ],
    "summary": "Create an asset",
    "description": "Create a asset.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_asset_library:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:write:asset_library:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "createAnAsset",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_asset_library:write:admin",
       "contact_center:write:asset_library:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_asset_library:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:asset_library:admin"
     ]
    }
   }
  },
  "/contact_center/asset_library/assets/{assetId}": {
   "get": {
    "tags": [
     "Asset Library"
    ],
    "summary": "Get an asset",
    "description": "Get information about an asset. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_asset_library:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:asset_library:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "getAnAsset",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_asset_library:read:admin",
       "contact_center:read:asset_library:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_asset_library:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:asset_library:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Asset Library"
    ],
    "summary": "Delete an asset",
    "description": "Delete or achive an existing asset. \r\nYou can only operate assets that have not been assigned to other modules.\r\nOnly assets in archived status can be deleted. Set the asset to `archived` through this API before deleting.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_asset_library:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:asset_l[...]",
    "operationId": "deleteAnAsset",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_asset_library:write:admin",
       "contact_center:delete:asset_library:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_asset_library:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:asset_library:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Asset Library"
    ],
    "summary": "Update an asset",
    "description": "Update an asset.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_asset_library:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:write:asset_library:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "updateAnAsset",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_asset_library:write:admin",
       "contact_center:write:asset_library:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_asset_library:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:asset_library:admin"
     ]
    }
   }
  },
  "/contact_center/asset_library/assets/{assetId}/items": {
   "delete": {
    "tags": [
     "Asset Library"
    ],
    "summary": "Delete asset items",
    "description": "Delete specific asset items.\nThe default asset item can't be deleted.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_asset_library:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:write:asset_library:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "Deleteassetitems",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_asset_library:write:admin",
       "contact_center:write:asset_library:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_asset_library:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:asset_library:admin"
     ]
    }
   }
  },
  "/contact_center/asset_library/categories": {
   "get": {
    "tags": [
     "Asset Library"
    ],
    "summary": "List asset categories",
    "description": "List asset categories. \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_asset_library:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:asset_library:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "listAssetCategories",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_asset_library:read:admin",
       "contact_center:read:asset_library:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_asset_library:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:asset_library:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Asset Library"
    ],
    "summary": "Create an asset category",
    "description": "Create an asset category.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_asset_library:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:write:asset_library:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "createAnAssetCategory",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_asset_library:write:admin",
       "contact_center:write:asset_library:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_asset_library:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:asset_library:admin"
     ]
    }
   }
  },
  "/contact_center/asset_library/categories/{categoryId}": {
   "get": {
    "tags": [
     "Asset Library"
    ],
    "summary": "Get an asset category",
    "description": "Get an asset category.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_asset_library:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:asset_library:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "getAnAssetCategory",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_asset_library:read:admin",
       "contact_center:read:asset_library:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_asset_library:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:asset_library:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Asset Library"
    ],
    "summary": "Delete an asset category",
    "description": "Delete an existing asset category.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_asset_library:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:asset_library:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "deleteAnAssetCategory",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_asset_library:write:admin",
       "contact_center:delete:asset_library:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_asset_library:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:asset_library:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Asset Library"
    ],
    "summary": "Update an asset category",
    "description": "Update an asset category.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_asset_library:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:write:asset_library:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "updateAnAssetCategory",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_asset_library:write:admin",
       "contact_center:write:asset_library:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_asset_library:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:asset_library:admin"
     ]
    }
   }
  },
  "/contact_center/engagements/{engagementId}/recording/{command}": {
   "put": {
    "tags": [
     "Call Control"
    ],
    "summary": "Control an engagement's recording",
    "description": "Controls the recording state for an engagement.\n\nThis request is only valid for video and voice engagements. Calling this API for other channel types is invalid.\n\nAcceptance of a request and response of `HTTP 204 No Content` only ensures there were no validation errors with the request.\n\n**Note:** The **Control an engagement's recording** API only works with third-party apps if the account admin has enabled the **Allow Open API to pause and resume automatic call recordi[...]",
    "operationId": "engagementRecordingControl",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_engagement:write:admin",
       "contact_center:update:engagement_recording_control:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_engagement:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:update:engagement_recording_control:admin"
     ]
    }
   }
  },
  "/contact_center/users/{userId}/commands": {
   "post": {
    "tags": [
     "Call Control"
    ],
    "summary": "Command control of a user",
    "description": "Initiate a manually assigned control command.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_user:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:write:user_control:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "userControl",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_user:write:admin",
       "contact_center:write:user_control:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_user:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:user_control:admin"
     ]
    }
   }
  },
  "/contact_center/users/{userId}/devices": {
   "get": {
    "tags": [
     "Call Control"
    ],
    "summary": "List user's devices ",
    "description": "Retrieve user device information.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_user:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:user_device:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "Listuserdevices",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_user:read:admin",
       "contact_center:read:user_device:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_user:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:user_device:admin"
     ]
    }
   }
  },
  "/contact_center/outbound_campaign/campaigns": {
   "get": {
    "tags": [
     "Campaigns"
    ],
    "summary": "List outbound campaigns",
    "description": "List Contact Center outbound campaigns.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_outbound_campaign:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:outbound_campaign:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "listOutboundCampaigns",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_outbound_campaign:read:admin",
       "contact_center:read:outbound_campaign:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_outbound_campaign:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:outbound_campaign:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Campaigns"
    ],
    "summary": "Create an outbound campaign",
    "description": "Create an outbound Contact Center campaign.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_outbound_campaign:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:write:outbound_campaign:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "createOutboundCampaign",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_outbound_campaign:write:admin",
       "contact_center:write:outbound_campaign:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_outbound_campaign:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:outbound_campaign:admin"
     ]
    }
   }
  },
  "/contact_center/outbound_campaign/campaigns/{campaignId}": {
   "get": {
    "tags": [
     "Campaigns"
    ],
    "summary": "Get an outbound campaign",
    "description": "Get a Contact Center outbound campaign.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_outbound_campaign:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:outbound_campaign:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "getOutboundCampaign",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_outbound_campaign:read:admin",
       "contact_center:read:outbound_campaign:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_outbound_campaign:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:outbound_campaign:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Campaigns"
    ],
    "summary": "Delete an outbound campaign",
    "description": "Delete a Contact Center's outbound campaign.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_outbound_campaign:delete:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:outbound_campaign:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "deleteOutboundCampaign",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_outbound_campaign:delete:admin",
       "contact_center:delete:outbound_campaign:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_outbound_campaign:delete:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:outbound_campaign:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Campaigns"
    ],
    "summary": "Update an outbound campaign",
    "description": "Update an outbound Contact Center campaign.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_outbound_campaign:update:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:update:outbound_campaign:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "updateOutboundCampaign",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_outbound_campaign:update:admin",
       "contact_center:update:outbound_campaign:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_outbound_campaign:update:admin"
     ],
     "x-granular-scopes": [
      "contact_center:update:outbound_campaign:admin"
     ]
    }
   }
  },
  "/contact_center/outbound_campaign/contact_lists": {
   "get": {
    "tags": [
     "Campaigns"
    ],
    "summary": "List campaign contact lists",
    "description": "List campaign contact lists.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_outbound_campaign_contactlist:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:outbound_campaign_contactlist:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "listCampaignContactLists",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_outbound_campaign_contactlist:read:admin",
       "contact_center:read:outbound_campaign_contactlist:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_outbound_campaign_contactlist:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:outbound_campaign_contactlist:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Campaigns"
    ],
    "summary": "Create a campaign contact list",
    "description": "Create a campaign contact list. Supports only contact list, NOT Do Not Contact Lists\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_outbound_campaign_contactlist:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:write:outbound_campaign_contactlist:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):[...]",
    "operationId": "createCampaignContactList",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_outbound_campaign_contactlist:write:admin",
       "contact_center:write:outbound_campaign_contactlist:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_outbound_campaign_contactlist:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:outbound_campaign_contactlist:admin"
     ]
    }
   }
  },
  "/contact_center/outbound_campaign/contact_lists/{contactListId}": {
   "get": {
    "tags": [
     "Campaigns"
    ],
    "summary": "Get a campaign contact list",
    "description": "Get a campaign contact list.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_outbound_campaign_contactlist:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:outbound_campaign_contactlist:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "getCampaignContactList",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_outbound_campaign_contactlist:read:admin",
       "contact_center:read:outbound_campaign_contactlist:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_outbound_campaign_contactlist:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:outbound_campaign_contactlist:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Campaigns"
    ],
    "summary": "Remove a campaign contact list",
    "description": "Delete a campaign contact list\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_outbound_campaign_contactlist:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:outbound_campaign_contactlist:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "deleteCampaignContactList",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_outbound_campaign_contactlist:write:admin",
       "contact_center:delete:outbound_campaign_contactlist:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_outbound_campaign_contactlist:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:outbound_campaign_contactlist:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Campaigns"
    ],
    "summary": "Update a campaign contact list",
    "description": "Update a campaign contact list\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_outbound_campaign_contactlist:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:update:outbound_campaign_contactlist:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "updateCampaignContactList",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_outbound_campaign_contactlist:write:admin",
       "contact_center:update:outbound_campaign_contactlist:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_outbound_campaign_contactlist:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:update:outbound_campaign_contactlist:admin"
     ]
    }
   }
  },
  "/contact_center/outbound_campaign/contact_lists/{contactListId}/contacts": {
   "get": {
    "tags": [
     "Campaigns"
    ],
    "summary": "List campaign contact list contacts",
    "description": "List contacts on a campaign contact list.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_outbound_campaign_contacts:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:outbound_campaign_contacts:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "listCampaignContactListContacts",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_outbound_campaign_contacts:read:admin",
       "contact_center:read:outbound_campaign_contacts:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_outbound_campaign_contacts:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:outbound_campaign_contacts:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Campaigns"
    ],
    "summary": "Create a campaign contact list's contact",
    "description": "Add a new contact to a campaign contact list.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_outbound_campaign_contacts:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:write:outbound_campaign_contacts:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "createCampaignContactListContact",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_outbound_campaign_contacts:write:admin",
       "contact_center:write:outbound_campaign_contacts:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_outbound_campaign_contacts:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:outbound_campaign_contacts:admin"
     ]
    }
   }
  },
  "/contact_center/outbound_campaign/contact_lists/{contactListId}/contacts/{contactId}": {
   "get": {
    "tags": [
     "Campaigns"
    ],
    "summary": "Get a campaign contact list's contact",
    "description": "Get a contact on a campaign contact list.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_outbound_campaign_contacts:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:outbound_campaign_contacts:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "getCampaignContactListContact",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_outbound_campaign_contacts:read:admin",
       "contact_center:read:outbound_campaign_contacts:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_outbound_campaign_contacts:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:outbound_campaign_contacts:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Campaigns"
    ],
    "summary": "Remove campaign contact list's contact",
    "description": "Remove a contact by ID from a campaign contact list.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_outbound_campaign_contacts:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:outbound_campaign_contacts:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "deleteCampaigncontactListContact",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_outbound_campaign_contacts:write:admin",
       "contact_center:delete:outbound_campaign_contacts:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_outbound_campaign_contacts:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:outbound_campaign_contacts:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Campaigns"
    ],
    "summary": "Update contact on a campaign contact list",
    "description": "Update a contact on a campaign contact list.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_outbound_campaign_contacts:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:update:outbound_campaign_contacts:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "updateCampaignContactListContact",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_outbound_campaign_contacts:write:admin",
       "contact_center:update:outbound_campaign_contacts:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_outbound_campaign_contacts:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:update:outbound_campaign_contacts:admin"
     ]
    }
   }
  },
  "/contact_center/dispositions": {
   "get": {
    "tags": [
     "Dispositions"
    ],
    "summary": "List dispositions",
    "description": "Return a list of available dispositions. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_disposition:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:list_dispositions:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "listDispositions",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_disposition:read:admin",
       "contact_center:read:list_dispositions:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_disposition:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:list_dispositions:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Dispositions"
    ],
    "summary": "Create a disposition",
    "description": "Create a new [disposition](https://support.zoom.us/hc/en-us/articles/4470153057549-Managing-dispositions). Dispositions let agents assign an outcome or topic to each engagement. After creating dispositions, you can add them to queues. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_disposition:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:w[...]",
    "operationId": "createDisposition",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_disposition:write:admin",
       "contact_center:write:disposition:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_disposition:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:disposition:admin"
     ]
    }
   }
  },
  "/contact_center/dispositions/sets": {
   "get": {
    "tags": [
     "Dispositions"
    ],
    "summary": "List disposition sets",
    "description": "Return a list of available disposition sets. Use sets to organize dispositions into groups.\n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_disposition:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:list_disposition_sets:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "listSets",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_disposition:read:admin",
       "contact_center:read:list_disposition_sets:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_disposition:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:list_disposition_sets:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Dispositions"
    ],
    "summary": "Create a disposition set",
    "description": "Create a new disposition set.\n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_disposition:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:write:disposition_set:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "createSet",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_disposition:write:admin",
       "contact_center:write:disposition_set:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_disposition:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:disposition_set:admin"
     ]
    }
   }
  },
  "/contact_center/dispositions/sets/{dispositionSetId}": {
   "get": {
    "tags": [
     "Dispositions"
    ],
    "summary": "Get a disposition set",
    "description": "Retrieve information about a disposition set. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_disposition:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:disposition_set:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "getSet",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_disposition:read:admin",
       "contact_center:read:disposition_set:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_disposition:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:disposition_set:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Dispositions"
    ],
    "summary": "Delete a disposition set",
    "description": "Delete a disposition set. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_disposition:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:disposition_set:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "deleteSet",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_disposition:write:admin",
       "contact_center:delete:disposition_set:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_disposition:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:disposition_set:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Dispositions"
    ],
    "summary": "Update a disposition set",
    "description": "Update an existing disposition set. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_disposition:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:update:disposition_set:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "updateSet",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_disposition:write:admin",
       "contact_center:update:disposition_set:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_disposition:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:update:disposition_set:admin"
     ]
    }
   }
  },
  "/contact_center/dispositions/{dispositionId}": {
   "get": {
    "tags": [
     "Dispositions"
    ],
    "summary": "Get a disposition",
    "description": "Retrieve information about a disposition. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_disposition:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:disposition:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "getDisposition",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_disposition:read:admin",
       "contact_center:read:disposition:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_disposition:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:disposition:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Dispositions"
    ],
    "summary": "Delete a disposition",
    "description": "Delete an existing disposition. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_disposition:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:disposition:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "deleteDisposition",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_disposition:write:admin",
       "contact_center:delete:disposition:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_disposition:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:disposition:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Dispositions"
    ],
    "summary": "Update a disposition",
    "description": "Update an existing disposition. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_disposition:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:update:disposition:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "updateDisposition",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_disposition:write:admin",
       "contact_center:update:disposition:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_disposition:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:update:disposition:admin"
     ]
    }
   }
  },
  "/contact_center/engagement": {
   "post": {
    "tags": [
     "Engagements"
    ],
    "summary": "Start an engagement",
    "description": "Start an engagement. Currently only supports the `Work Item` channel.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_engagement:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:write:engagement:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "Startworkitemengagement",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_engagement:write:admin",
       "contact_center:write:engagement:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_engagement:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:engagement:admin"
     ]
    }
   }
  },
  "/contact_center/engagements": {
   "get": {
    "tags": [
     "Engagements"
    ],
    "summary": "List engagements",
    "description": "Return a list of engagements.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:list_engagements:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "listEngagements",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_report:read:admin",
       "contact_center:read:list_engagements:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_report:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:list_engagements:admin"
     ]
    }
   }
  },
  "/contact_center/engagements/{engagementId}": {
   "get": {
    "tags": [
     "Engagements"
    ],
    "summary": "Get an engagement",
    "description": "Retrieve information about an engagement. Engagements are available via API once they are completed.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:engagement:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "getEngagement",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_report:read:admin",
       "contact_center:read:engagement:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_report:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:engagement:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Engagements"
    ],
    "summary": "Update an engagement",
    "description": "Update an active engagement's status.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_engagement:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:update:engagement:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "updateEngagement",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_engagement:write:admin",
       "contact_center:update:engagement:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_engagement:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:update:engagement:admin"
     ]
    }
   }
  },
  "/contact_center/engagements/{engagementId}/events": {
   "get": {
    "tags": [
     "Engagements"
    ],
    "summary": "Get an engagement's events",
    "description": "Retrieve information about an engagement's events.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:engagement:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "getEngagementEvents",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_report:read:admin",
       "contact_center:read:engagement:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_report:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:engagement:admin"
     ]
    }
   }
  },
  "/contact_center/engagements/{engagementId}/recordings/status": {
   "get": {
    "tags": [
     "Engagements"
    ],
    "summary": "Poll an engagement recording's status",
    "description": "Polls a video or voice engagement's recordings' status.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_engagement:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:engagement_recording_status:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "EngagementRecordingStatus",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_engagement:read:admin",
       "contact_center:read:engagement_recording_status:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_engagement:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:engagement_recording_status:admin"
     ]
    }
   }
  },
  "/contact_center/engagements/{engagementId}/survey": {
   "get": {
    "tags": [
     "Engagements"
    ],
    "summary": "Get an engagement's survey",
    "description": "Get an engagement's survey\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_engagement:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:engagement:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "getEngagementSurvey",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_engagement:read:admin",
       "contact_center:read:engagement:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_engagement:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:engagement:admin"
     ]
    }
   }
  },
  "/contact_center/flows": {
   "get": {
    "tags": [
     "Flows"
    ],
    "summary": "List flows",
    "description": "Return a list of flows. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_flow:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:list_flows:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "listFlows",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_flow:read:admin",
       "contact_center:read:list_flows:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_flow:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:list_flows:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Flows"
    ],
    "summary": "Import a flow",
    "description": "Import and create a flow, using content from another flow's exported JSON.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_flow:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:write:flow:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "ImportFlow",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_flow:write:admin",
       "contact_center:write:flow:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_flow:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:flow:admin"
     ]
    }
   }
  },
  "/contact_center/flows/{flowId}": {
   "get": {
    "tags": [
     "Flows"
    ],
    "summary": "Get a flow",
    "description": "Get information about a flow. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_flow:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:flow:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "getAFlow",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_flow:read:admin",
       "contact_center:read:flow:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_flow:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:flow:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Flows"
    ],
    "summary": "Delete a flow",
    "description": "Delete a flow.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_flow:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:flow:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "DeleteFlow",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_flow:write:admin",
       "contact_center:delete:flow:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_flow:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:flow:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Flows"
    ],
    "summary": "Edit a flow",
    "description": "Edit a flow's attributes.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_flow:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:update:flow:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "EditFlow",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_flow:write:admin",
       "contact_center:update:flow:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_flow:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:update:flow:admin"
     ]
    }
   }
  },
  "/contact_center/flows/{flowId}/entry_points": {
   "get": {
    "tags": [
     "Flows"
    ],
    "summary": "List flow's entry points",
    "description": "Retrieve a list of the entry points bound to the current flow.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_flow:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:flow:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "ListFlowEntryPoints",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_flow:read:admin",
       "contact_center:read:flow:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_flow:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:flow:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Flows"
    ],
    "summary": "Add flow entry points",
    "description": "Add entry points to a flow.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_flow:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:write:flow:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "AddFlowEntryPoints",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_flow:write:admin",
       "contact_center:write:flow:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_flow:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:flow:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Flows"
    ],
    "summary": "Remove flow entry points",
    "description": "Remove entry points to a flow.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_flow:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:flow:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "RemoveFlowEntryPoints",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_flow:write:admin",
       "contact_center:delete:flow:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_flow:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:flow:admin"
     ]
    }
   }
  },
  "/contact_center/flows/{flowId}/export": {
   "get": {
    "tags": [
     "Flows"
    ],
    "summary": "Export a flow",
    "description": "Export a flow's content as JSON.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_flow:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:flow:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "ExportFlow",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_flow:read:admin",
       "contact_center:read:flow:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_flow:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:flow:admin"
     ]
    }
   }
  },
  "/contact_center/flows/{flowId}/publish": {
   "put": {
    "tags": [
     "Flows"
    ],
    "summary": "Publish a flow",
    "description": "Publish a flow version. Any other published version of the flow will be replaced with the one specified in this request.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_flow:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:update:flow:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "PublishFlow",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_flow:write:admin",
       "contact_center:update:flow:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_flow:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:update:flow:admin"
     ]
    }
   }
  },
  "/contact_center/flows_entry_points": {
   "get": {
    "tags": [
     "Flows"
    ],
    "summary": "List entry points",
    "description": "Retrieve a list of entry points.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_flow:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:flow:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "ListentryPoints",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_flow:read:admin",
       "contact_center:read:flow:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_flow:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:flow:admin"
     ]
    }
   }
  },
  "/contact_center/inboxes": {
   "get": {
    "tags": [
     "Inboxes"
    ],
    "summary": "List inboxes",
    "description": "Return a list of inboxes. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_inbox:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:list_inboxes:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "listInbox",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_inbox:read:admin",
       "contact_center:read:list_inboxes:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-macro-scopes": [
      "contact_center_inbox:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:list_inboxes:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Inboxes"
    ],
    "summary": "Create an inbox",
    "description": "Create a new inbox. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_inbox:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:write:inbox:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "inboxCreate",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_inbox:write:admin",
       "contact_center:write:inbox:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_inbox:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:inbox:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Inboxes"
    ],
    "summary": "Delete inboxes",
    "description": "Delete one or more inboxes. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_inbox:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:inbox:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "inboxesDelete",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_inbox:write:admin",
       "contact_center:delete:inbox:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-macro-scopes": [
      "contact_center_inbox:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:inbox:admin"
     ]
    }
   }
  },
  "/contact_center/inboxes/messages": {
   "get": {
    "tags": [
     "Inboxes"
    ],
    "summary": "List an account's inbox messages",
    "description": "Return all messages in an inbox. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_inbox:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:inbox_messages:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "listInboxesMessages",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_inbox:read:admin",
       "contact_center:read:inbox_messages:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_inbox:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:inbox_messages:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Inboxes"
    ],
    "summary": "Delete inbox messages",
    "description": "Delete messages. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_inbox:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:inbox_messages:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "inboxesMessagesDelete",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_inbox:write:admin",
       "contact_center:delete:inbox_messages:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_inbox:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:inbox_messages:admin"
     ]
    }
   }
  },
  "/contact_center/inboxes/{inboxId}": {
   "get": {
    "tags": [
     "Inboxes"
    ],
    "summary": "Get an inbox",
    "description": "Retrieve an inbox. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_inbox:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:inbox:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "getInbox",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_inbox:read:admin",
       "contact_center:read:inbox:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_inbox:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:inbox:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Inboxes"
    ],
    "summary": "Update an inbox",
    "description": "Update an inbox. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_inbox:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:update:inbox:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "inboxUpdate",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_inbox:write:admin",
       "contact_center:update:inbox:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_inbox:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:update:inbox:admin"
     ]
    }
   }
  },
  "/contact_center/inboxes/{inboxId}/email_notification": {
   "patch": {
    "tags": [
     "Inboxes"
    ],
    "summary": "Update an inbox email notification",
    "description": "Update an inbox email notification.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_inbox:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:update:inbox:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "Updateaninboxemailnotification",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_inbox:write:admin",
       "contact_center:update:inbox:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_inbox:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:update:inbox:admin"
     ]
    }
   }
  },
  "/contact_center/inboxes/{inboxId}/email_notifications": {
   "get": {
    "tags": [
     "Inboxes"
    ],
    "summary": "Get inbox email notification list",
    "description": "Retrieve a list ov inbox email notifications.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_inbox:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:inbox:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "Getinboxemailnotificationlist",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_inbox:read:admin",
       "contact_center:read:inbox:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_inbox:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:inbox:admin"
     ]
    }
   }
  },
  "/contact_center/inboxes/{inboxId}/messages": {
   "get": {
    "tags": [
     "Inboxes"
    ],
    "summary": "List an inbox's messages",
    "description": "Return a list of all messages in an inbox. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_inbox:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:inbox_messages:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "listInboxMessages",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_inbox:read:admin",
       "contact_center:read:inbox_messages:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_inbox:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:inbox_messages:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Inboxes"
    ],
    "summary": "Delete an inbox's messages",
    "description": "Delete messages in an inbox. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_inbox:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:inbox_messages:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "inboxMessagesDelete",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_inbox:write:admin",
       "contact_center:delete:inbox_messages:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-macro-scopes": [
      "contact_center_inbox:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:inbox_messages:admin"
     ]
    }
   }
  },
  "/contact_center/inboxes/{inboxId}/messages/{messageId}": {
   "delete": {
    "tags": [
     "Inboxes"
    ],
    "summary": "Delete an inbox message",
    "description": "Delete a single message in an inbox. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_inbox:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:inbox_message:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "inboxMessageDelete",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_inbox:write:admin",
       "contact_center:delete:inbox_message:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-macro-scopes": [
      "contact_center_inbox:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:inbox_message:admin"
     ]
    }
   }
  },
  "/contact_center/inboxes/{inboxId}/queues": {
   "get": {
    "tags": [
     "Inboxes"
    ],
    "summary": "Get inbox access queues",
    "description": "Retrieve a list of queues that have access to an inbox. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:list_inbox_queues:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "listInboxQueues",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:read:admin",
       "contact_center:read:list_inbox_queues:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:list_inbox_queues:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Inboxes"
    ],
    "summary": "Assign inbox access queues",
    "description": "Assign queues access to an inbox. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:write:inbox_queue:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "assignInboxQueues",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:write:admin",
       "contact_center:write:inbox_queue:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:inbox_queue:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Inboxes"
    ],
    "summary": "Remove inbox access queues",
    "description": "Remove queues' access to an inbox. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:inbox_queue:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "unassignInboxQueues",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:write:admin",
       "contact_center:delete:inbox_queue:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:inbox_queue:admin"
     ]
    }
   }
  },
  "/contact_center/inboxes/{inboxId}/users": {
   "get": {
    "tags": [
     "Inboxes"
    ],
    "summary": "Get an inbox's users",
    "description": "Retrieve a list of users assigned to an inbox. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_user:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:inbox_user:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "listInboxUsers",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_user:read:admin",
       "contact_center:read:inbox_user:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-macro-scopes": [
      "contact_center_user:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:inbox_user:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Inboxes"
    ],
    "summary": "Assign inbox access users",
    "description": "Assign a user's access to an inbox. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_user:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:write:inbox_user:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "assignInboxUsers",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_user:write:admin",
       "contact_center:write:inbox_user:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-macro-scopes": [
      "contact_center_user:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:inbox_user:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Inboxes"
    ],
    "summary": "Unassign inbox access users",
    "description": "Remove users' access to an inbox. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_user:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:inbox_user:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "unassignInboxUsers",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_user:write:admin",
       "contact_center:delete:inbox_user:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-macro-scopes": [
      "contact_center_user:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:inbox_user:admin"
     ]
    }
   }
  },
  "/contact_center/email/messages": {
   "get": {
    "tags": [
     "Logs"
    ],
    "summary": "List email message history",
    "description": "Retrieve the list of messages exchanged during a specific email engagement.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_messaging:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:engagement_log:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "getEmailMessageHistory",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_messaging:read:admin",
       "contact_center:read:engagement_log:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_messaging:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:engagement_log:admin"
     ]
    }
   }
  },
  "/contact_center/messaging/messages": {
   "get": {
    "tags": [
     "Logs"
    ],
    "summary": "List message history",
    "description": "Retrieve the list of messages exchanged during a specific messaging engagement.\nNote: This endpoint currently supports headless messaging only.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_messaging:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:messaging:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-li[...]",
    "operationId": "getMessageHistory",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_messaging:read:admin",
       "contact_center:read:messaging:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_messaging:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:messaging:admin"
     ]
    }
   }
  },
  "/contact_center/sms": {
   "get": {
    "tags": [
     "Logs"
    ],
    "summary": "List SMS logs",
    "description": "Returns a list of SMS engagement logs. Engagement data are available via API once they are completed.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_sms:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:sms_log:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "listSMS",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_sms:read:admin",
       "contact_center:read:sms_log:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_sms:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:sms_log:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "SMS"
    ],
    "summary": "Send an SMS",
    "description": "Send an SMS message.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_sms:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:write:sms:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "contactCenterSMS",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_sms:write:admin",
       "contact_center:write:sms:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_sms:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:sms:admin"
     ]
    }
   }
  },
  "/contact_center/voice_calls": {
   "get": {
    "tags": [
     "Logs"
    ],
    "summary": "List voice call logs",
    "description": "Returns a list of voice call engagement logs. Engagement data is available via API once it is completed. **Note** These fields - `agents.user_ip_address`, `agents.user_device_mac_address`, `agents.user_registered_sip_zone`, `agents.sip_zone_ip_address`, `sbcInfos.session_border_controller_name`, `sbcInfos.session_border_controller_ip_address`, `sbcInfos.consumer_zoom_trunk_name` and `sbcInfos.consumer_sbc_ip_address` - are only available to accounts which have enabled an inte[...]",
    "operationId": "listVoiceCall",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_voice_call:read:admin",
       "contact_center:read:voice_call_log:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_voice_call:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:voice_call_log:admin"
     ]
    }
   }
  },
  "/contact_center/engagements/notes": {
   "get": {
    "tags": [
     "Notes"
    ],
    "summary": "List notes",
    "description": "Return a list of notes. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_note:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:list_notes:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "notes",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_note:read:admin",
       "contact_center:read:list_notes:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_note:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:list_notes:admin"
     ]
    }
   }
  },
  "/contact_center/engagements/{engagementId}/notes": {
   "get": {
    "tags": [
     "Notes"
    ],
    "summary": "List engagement notes",
    "description": "Return a list of notes under an engagement. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_note:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:list_notes:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "engagementNotes",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_note:read:admin",
       "contact_center:read:list_notes:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_note:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:list_notes:admin"
     ]
    }
   }
  },
  "/contact_center/engagements/{engagementId}/notes/{noteId}": {
   "get": {
    "tags": [
     "Notes"
    ],
    "summary": "Get a note",
    "description": "Retrieve a note. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_note:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:note:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "getNote",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_note:read:admin",
       "contact_center:read:note:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_note:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:note:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Notes"
    ],
    "summary": "Update a note",
    "description": "Update a note. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_note:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:update:note`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "noteUpdate",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_note:write",
       "contact_center:update:note"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_note:write"
     ],
     "x-granular-scopes": [
      "contact_center:update:note"
     ]
    }
   }
  },
  "/contact_center/business_hours": {
   "get": {
    "tags": [
     "Operating Hours"
    ],
    "summary": "List business hours",
    "description": "Get a list of business hours. Admins can create business hours to select, such as the business hours &quot;Default Hours&quot;. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_operating_hours:read:admin`,`contact_center_queue:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:list_business_hours:admin`\n\n**[Rate Limit Label](https://marketp[...]",
    "operationId": "listBusinessHours",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_operating_hours:read:admin",
       "contact_center_queue:read:admin",
       "contact_center:read:list_business_hours:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_operating_hours:read:admin",
      "contact_center_queue:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:list_business_hours:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Operating Hours"
    ],
    "summary": "Create business hours",
    "description": "Create new business hours. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_operating_hours:write:admin`,`contact_center_queue:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:write:business_hour:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "businessHourCreate",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_operating_hours:write:admin",
       "contact_center_queue:write:admin",
       "contact_center:write:business_hour:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_operating_hours:write:admin",
      "contact_center_queue:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:business_hour:admin"
     ]
    }
   }
  },
  "/contact_center/business_hours/{businessHourId}": {
   "get": {
    "tags": [
     "Operating Hours"
    ],
    "summary": "Get business hours",
    "description": "Get information about business hours. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_operating_hours:read:admin`,`contact_center_queue:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:business_hour:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "getABusinessHour",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_operating_hours:read:admin",
       "contact_center_queue:read:admin",
       "contact_center:read:business_hour:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_operating_hours:read:admin",
      "contact_center_queue:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:business_hour:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Operating Hours"
    ],
    "summary": "Delete business hours",
    "description": "Delete business hours. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_operating_hours:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:business_hour:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "businessHourDelete",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_operating_hours:write:admin",
       "contact_center:delete:business_hour:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_operating_hours:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:business_hour:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Operating Hours"
    ],
    "summary": "Update business hours",
    "description": "Update business hours.   \n   \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_operating_hours:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:update:business_hour:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "businessHourUpdate",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_operating_hours:write:admin",
       "contact_center:update:business_hour:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_operating_hours:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:update:business_hour:admin"
     ]
    }
   }
  },
  "/contact_center/business_hours/{businessHourId}/flows": {
   "get": {
    "tags": [
     "Operating Hours"
    ],
    "summary": "List the business hours' flows",
    "description": "Show a list of flows using business hours. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_flow:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:business_hours_flow:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "listBusinessHourFlows",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_flow:read:admin",
       "contact_center:read:business_hours_flow:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_flow:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:business_hours_flow:admin"
     ]
    }
   }
  },
  "/contact_center/business_hours/{businessHourId}/queues": {
   "get": {
    "tags": [
     "Operating Hours"
    ],
    "summary": "List the business hours' queues",
    "description": "Show a list of queues using business hours. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:business_hours_queue:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "listBusinessHourQueues",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:read:admin",
       "contact_center:read:business_hours_queue:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:business_hours_queue:admin"
     ]
    }
   }
  },
  "/contact_center/closures": {
   "get": {
    "tags": [
     "Operating Hours"
    ],
    "summary": "List closures",
    "description": "Get a list of closures. Admins can create closures to select. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:read:admin`,`contact_center_operating_hours:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:list_closure_hours:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM[...]",
    "operationId": "listClosures",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:read:admin",
       "contact_center_operating_hours:read:admin",
       "contact_center:read:list_closure_hours:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:read:admin",
      "contact_center_operating_hours:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:list_closure_hours:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Operating Hours"
    ],
    "summary": "Create a closure set",
    "description": "Create a new closure set. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:write:admin`,`contact_center_operating_hours:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:write:closure_hour:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "closuresSetCreate",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:write:admin",
       "contact_center_operating_hours:write:admin",
       "contact_center:write:closure_hour:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:write:admin",
      "contact_center_operating_hours:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:closure_hour:admin"
     ]
    }
   }
  },
  "/contact_center/closures/{closureSetId}": {
   "get": {
    "tags": [
     "Operating Hours"
    ],
    "summary": "Get a closure set",
    "description": "Get information about a closure set.  \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:read:admin`,`contact_center_operating_hours:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:closure_hour:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "getAClosureSet",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:read:admin",
       "contact_center_operating_hours:read:admin",
       "contact_center:read:closure_hour:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:read:admin",
      "contact_center_operating_hours:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:closure_hour:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Operating Hours"
    ],
    "summary": "Delete a closure set",
    "description": "Delete closure sets. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_operating_hours:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:closure_hour:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "closureSetDelete",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_operating_hours:write:admin",
       "contact_center:delete:closure_hour:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_operating_hours:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:closure_hour:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Operating Hours"
    ],
    "summary": "Update a closure set",
    "description": "Update information about a closure set.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_operating_hours:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:update:closure_hour:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "closureSetUpdate",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_operating_hours:write:admin",
       "contact_center:update:closure_hour:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_operating_hours:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:update:closure_hour:admin"
     ]
    }
   }
  },
  "/contact_center/closures/{closureSetId}/flows": {
   "get": {
    "tags": [
     "Operating Hours"
    ],
    "summary": "List the closures' flows",
    "description": "Show a list of flows using closures. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_flow:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:clousre_hour_flow:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "listClosureSetFlows",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_flow:read:admin",
       "contact_center:read:clousre_hour_flow:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_flow:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:clousre_hour_flow:admin"
     ]
    }
   }
  },
  "/contact_center/closures/{closureSetId}/queues": {
   "get": {
    "tags": [
     "Operating Hours"
    ],
    "summary": "List the closures' queues",
    "description": "Show a list of queues using closures. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:closure_hour_queue:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "listClosureSetQueues",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:read:admin",
       "contact_center:read:closure_hour_queue:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:closure_hour_queue:admin"
     ]
    }
   }
  },
  "/contact_center/queue_templates": {
   "get": {
    "tags": [
     "Queues"
    ],
    "summary": "List queue templates",
    "description": "Retrieve a list of queue templates.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:queue:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "Listqueuetemplates",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:read:admin",
       "contact_center:read:queue:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:queue:admin"
     ]
    }
   }
  },
  "/contact_center/queues": {
   "get": {
    "tags": [
     "Queues"
    ],
    "summary": "List queues",
    "description": "Get information about all available queues. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:list_queues:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "listQueues",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:read:admin",
       "contact_center:read:list_queues:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:list_queues:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Queues"
    ],
    "summary": "Create a queue",
    "description": "Create an agent [queue](https://support.zoom.us/hc/en-us/articles/4423986595085) to determine which agents calls are routed to. Queues also link to an existing routing profile to determine how calls are routed. \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:write:queue:admin`\n\n**[Rate Limit [...]",
    "operationId": "queueCreate",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:write:admin",
       "contact_center:write:queue:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:queue:admin"
     ]
    }
   }
  },
  "/contact_center/queues/batch": {
   "post": {
    "tags": [
     "Queues"
    ],
    "summary": "Batch create queues with a template",
    "description": "Create bulk of contact center queues with templateId.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:write:queue:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "Batchcreatequeueswithatemplate",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:write:admin",
       "contact_center:write:queue:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:queue:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Queues"
    ],
    "summary": "Batch delete queues",
    "description": "Delete bulk of Contact Center queues.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:queue:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "Batchdeletequeues",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:write:admin",
       "contact_center:delete:queue:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:queue:admin"
     ]
    }
   }
  },
  "/contact_center/queues/{queueId}": {
   "get": {
    "tags": [
     "Queues"
    ],
    "summary": "Get a queue",
    "description": "Get information about a queue.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:queue:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "getAQueue",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:read:admin",
       "contact_center:read:queue:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:queue:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Queues"
    ],
    "summary": "Delete a queue",
    "description": "Delete a specified queue. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:queue:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "queueDelete",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:write:admin",
       "contact_center:delete:queue:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:queue:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Queues"
    ],
    "summary": "Update a queue",
    "description": "Update a queue's settings.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:update:queue:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "queueUpdate",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:write:admin",
       "contact_center:update:queue:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:update:queue:admin"
     ]
    }
   }
  },
  "/contact_center/queues/{queueId}/agents": {
   "get": {
    "tags": [
     "Queues"
    ],
    "summary": "List queue agents",
    "description": "Retrieve the list of a queue's assigned agents. \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:list_queue_agents:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "getQueueAgents",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:read:admin",
       "contact_center:read:list_queue_agents:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:list_queue_agents:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Queues"
    ],
    "summary": "Assign queue agents",
    "description": "Add agents to a queue. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:write:queue_agent:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "assignQueueAgents",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:write:admin",
       "contact_center:write:queue_agent:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:queue_agent:admin"
     ]
    }
   }
  },
  "/contact_center/queues/{queueId}/agents/{userId}": {
   "delete": {
    "tags": [
     "Queues"
    ],
    "summary": "Unassign a queue agent",
    "description": "Remove an agent from a queue. \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:queue_agent:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "deleteQueueAgent",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:write:admin",
       "contact_center:delete:queue_agent:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:queue_agent:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Queues"
    ],
    "summary": "Update a queue agent",
    "description": "Update the list of agents in a queue. \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:update:queue_agent:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "updateQueueAgent",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:write:admin",
       "contact_center:update:queue_agent:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:update:queue_agent:admin"
     ]
    }
   }
  },
  "/contact_center/queues/{queueId}/dispositions": {
   "get": {
    "tags": [
     "Queues"
    ],
    "summary": "List queue dispositions",
    "description": "Return a list of queue's [dispositions](https://support.zoom.us/hc/en-us/articles/4470153057549-Managing-dispositions). \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:list_dispositions:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limit[...]",
    "operationId": "getQueueDispositions",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:read:admin",
       "contact_center:read:list_dispositions:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:list_dispositions:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Queues"
    ],
    "summary": "Assign queue dispositions",
    "description": "Add dispositions to a queue. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:write:queue disposition:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "assignQueueDispositions",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:write:admin",
       "contact_center:write:queue disposition:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:queue disposition:admin"
     ]
    }
   }
  },
  "/contact_center/queues/{queueId}/dispositions/sets": {
   "get": {
    "tags": [
     "Queues"
    ],
    "summary": "List queue disposition sets",
    "description": "Return a list of queue's disposition sets(https://support.zoom.us/hc/en-us/articles/4470153057549-Managing-dispositions). \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:list_disposition_sets:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate[...]",
    "operationId": "getQueueDispositionSets",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:read:admin",
       "contact_center:read:list_disposition_sets:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:list_disposition_sets:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Queues"
    ],
    "summary": "Assign a queue disposition set",
    "description": "Add a disposition set to a queue. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:write:queue_disposition_set:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "assignQueueDispositionSets",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:write:admin",
       "contact_center:write:queue_disposition_set:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:queue_disposition_set:admin"
     ]
    }
   }
  },
  "/contact_center/queues/{queueId}/dispositions/sets/{dispositionSetId}": {
   "delete": {
    "tags": [
     "Queues"
    ],
    "summary": "Unassign a queue disposition set",
    "description": "Delete a disposition set from a queue. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:queue_disposition_set:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "deleteQueueDispositionSet",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:write:admin",
       "contact_center:delete:queue_disposition_set:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:queue_disposition_set:admin"
     ]
    }
   }
  },
  "/contact_center/queues/{queueId}/dispositions/{dispositionId}": {
   "delete": {
    "tags": [
     "Queues"
    ],
    "summary": "Unassign a queue disposition",
    "description": "Delete a disposition from a queue. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:queue_disposition:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "deleteQueueDisposition",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:write:admin",
       "contact_center:delete:queue_disposition:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:queue_disposition:admin"
     ]
    }
   }
  },
  "/contact_center/queues/{queueId}/interrupt_menu": {
   "post": {
    "tags": [
     "Queues"
    ],
    "summary": "Assign a queue menu based interrupt",
    "description": "Create a menu of options to offer to consumers during the queue waiting experience. Currently, the only support for queue channel type is voice.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:update:queue:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#[...]",
    "operationId": "assignQueueMenuBasedInterrupt",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:write:admin",
       "contact_center:update:queue:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:update:queue:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Queues"
    ],
    "summary": "Delete a queue's interrupt menu configuration",
    "description": "Deletes the interrupt menu configuration for a specific queue. This removes all menu-based interrupt settings including menu options, callback settings, voice prompts, and timing configurations.\n\nThis operation only works for voice queues. Other channel types will return an error.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-s[...]",
    "operationId": "deleteQueueInterruptMenu",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:write:admin",
       "contact_center:delete:queue:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:queue:admin"
     ]
    }
   }
  },
  "/contact_center/queues/{queueId}/operating_hours": {
   "get": {
    "tags": [
     "Queues"
    ],
    "summary": "Get a queue's operating hours",
    "description": "Get information about a queue's operating hours. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:queue_operating_hours:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "getAQueueOperatingHours",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:read:admin",
       "contact_center:read:queue_operating_hours:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:queue_operating_hours:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Queues"
    ],
    "summary": "Update a queue's operating hours",
    "description": "Update a queue's operating hours. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:patch:queue_operating_hours:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "QueueOperatingHoursUpdate",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:write:admin",
       "contact_center:patch:queue_operating_hours:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:patch:queue_operating_hours:admin"
     ]
    }
   }
  },
  "/contact_center/queues/{queueId}/scheduled_callbacks/events": {
   "post": {
    "tags": [
     "Queues"
    ],
    "summary": "Schedule a callback on a queue",
    "description": "Schedule a callback on a queue.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:write:queue:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "Scheduleacallbackonaqueue",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:write:admin",
       "contact_center:write:queue:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:queue:admin"
     ]
    }
   }
  },
  "/contact_center/queues/{queueId}/scheduled_callbacks/supportive_slots": {
   "get": {
    "tags": [
     "Queues"
    ],
    "summary": "List a queue's scheduled callbacks availability",
    "description": "List scheduled callbacks booking slots for a scheduler set up under a queue.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:queue:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "Listqueuescheduledcallbacksavailability",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:read:admin",
       "contact_center:read:queue:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:queue:admin"
     ]
    }
   }
  },
  "/contact_center/queues/{queueId}/supervisors": {
   "get": {
    "tags": [
     "Queues"
    ],
    "summary": "List queue supervisors",
    "description": "Return a list of a queue's assigned supervisors. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:queue_supervisor:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "getQueueSupervisors",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:read:admin",
       "contact_center:delete:queue_supervisor:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:queue_supervisor:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Queues"
    ],
    "summary": "Assign queue supervisors",
    "description": "Add supervisors to a queue. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:queue_supervisor:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "assignQueueSupervisors",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:write:admin",
       "contact_center:delete:queue_supervisor:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:queue_supervisor:admin"
     ]
    }
   }
  },
  "/contact_center/queues/{queueId}/supervisors/{userId}": {
   "delete": {
    "tags": [
     "Queues"
    ],
    "summary": "Unassign a queue supervisor",
    "description": "Remove a supervisor from a queue. \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:queue_supervisor:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "deleteQueueSupervisor",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:write:admin",
       "contact_center:delete:queue_supervisor:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:queue_supervisor:admin"
     ]
    }
   }
  },
  "/contact_center/queues/{queueId}/teams": {
   "post": {
    "tags": [
     "Queues"
    ],
    "summary": "Assign queue teams",
    "description": "Add teams to a queue.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:write:queue_team:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "assignQueueTeams",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:write:admin",
       "contact_center:write:queue_team:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:queue_team:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Queues"
    ],
    "summary": "Unassign multiple teams in a queue",
    "description": "Remove teams from a queue.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:queue_team:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "batchDeleteQueueTeams",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:write:admin",
       "contact_center:delete:queue_team:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:queue_team:admin"
     ]
    }
   }
  },
  "/contact_center/queues/{queueId}/teams/{teamId}": {
   "delete": {
    "tags": [
     "Queues"
    ],
    "summary": "Unassign a queue team",
    "description": "Remove a team from a queue.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_queue:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:queue_team:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "deleteQueueTeam",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_queue:write:admin",
       "contact_center:delete:queue_team:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_queue:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:queue_team:admin"
     ]
    }
   }
  },
  "/contact_center/engagements/{engagementId}/recordings": {
   "get": {
    "tags": [
     "Recordings"
    ],
    "summary": "List engagement recordings",
    "description": "Return a list of all of an engagement's recordings. \n\n**Note:** Use recording-related APIs to manipulate data whose recording was created after July 18, 2022. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_recording:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:list_recordings:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.u[...]",
    "operationId": "listEngagementRecordings",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_recording:read:admin",
       "contact_center:read:list_recordings:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_recording:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:list_recordings:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Recordings"
    ],
    "summary": "Delete engagement recordings",
    "description": "Delete all recordings in a given engagement.  \n\n**Note**: Use recording-related APIs to manipulate data whose recording creation time is after 2022-07-18. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_recording:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:recording:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/[...]",
    "operationId": "deleteEngagementRecordings",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_recording:write:admin",
       "contact_center:delete:recording:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-macro-scopes": [
      "contact_center_recording:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:recording:admin"
     ]
    }
   }
  },
  "/contact_center/queues/{queueId}/recordings": {
   "get": {
    "tags": [
     "Recordings"
    ],
    "summary": "List queue recordings",
    "description": "Return a list of all recordings in a queue. \n\n**Note:** Use recording-related APIs to manipulate data whose recording was created after July 18, 2022. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_recording:read:admin`,`contact_center_recording:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:list_recordings:admin`,`contact_center:read:list_[...]",
    "operationId": "listQueueRecordings",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_recording:read:admin",
       "contact_center_recording:read",
       "contact_center:read:list_recordings:admin",
       "contact_center:read:list_recordings"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_recording:read:admin",
      "contact_center_recording:read"
     ],
     "x-granular-scopes": [
      "contact_center:read:list_recordings:admin",
      "contact_center:read:list_recordings"
     ]
    }
   },
   "delete": {
    "tags": [
     "Recordings"
    ],
    "summary": "Delete queue recordings",
    "description": "Delete all recordings in a queue. \n\n**Note**: Use recording-related APIs to manipulate data whose recording creation time is after 2022-07-18. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_recording:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:recording:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-referenc[...]",
    "operationId": "deleteQueueRecordings",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_recording:write:admin",
       "contact_center:delete:recording:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_recording:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:recording:admin"
     ]
    }
   }
  },
  "/contact_center/recordings": {
   "get": {
    "tags": [
     "Recordings"
    ],
    "summary": "List recordings",
    "description": "Return a list of available recordings. \n\n**Note** Use recording-related APIs to manipulate data whose recording was created after July 18, 2022. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_recording:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:list_recordings:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-ref[...]",
    "operationId": "listRecordings",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_recording:read:admin",
       "contact_center:read:list_recordings:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_recording:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:list_recordings:admin"
     ]
    }
   }
  },
  "/contact_center/recordings/{recordingId}": {
   "delete": {
    "tags": [
     "Recordings"
    ],
    "summary": "Delete a recording",
    "description": "Delete a selected recording. \n\n**Note**: Use recording-related APIs to manipulate data whose recording creation time is after 2022-07-18. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_recording:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:recording:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rat[...]",
    "operationId": "deleteRecording",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_recording:write:admin",
       "contact_center:delete:recording:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-macro-scopes": [
      "contact_center_recording:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:recording:admin"
     ]
    }
   }
  },
  "/contact_center/users/{userId}/recordings": {
   "get": {
    "tags": [
     "Recordings"
    ],
    "summary": "List a user's recordings",
    "description": "Get a user's recordings. \n\n**Note** Use recording-related APIs to manipulate data whose recording creation time is after 2022-07-18. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_recording:read`,`contact_center_recording:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:list_recordings:admin`,`contact_center:read:list_recordings`\n\n**[[...]",
    "operationId": "listUserRecordings",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_recording:read",
       "contact_center_recording:read:admin",
       "contact_center:read:list_recordings:admin",
       "contact_center:read:list_recordings"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_recording:read",
      "contact_center_recording:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:list_recordings:admin",
      "contact_center:read:list_recordings"
     ]
    }
   },
   "delete": {
    "tags": [
     "Recordings"
    ],
    "summary": "Delete a user's recordings",
    "description": "Delete all of a given user's recordings.  \n\n**Note** Use recording-related APIs to manipulate data whose recording creation time is after 2022-07-18. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_recording:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:recording:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-r[...]",
    "operationId": "deleteUserRecordings",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_recording:write:admin",
       "contact_center:delete:recording:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_recording:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:recording:admin"
     ]
    }
   }
  },
  "/contact_center/regions": {
   "get": {
    "tags": [
     "Regions"
    ],
    "summary": "List regions",
    "description": "Get information about all available regions.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_region:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:list_regions:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "ListRegions",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_region:read:admin",
       "contact_center:read:list_regions:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_region:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:list_regions:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Regions"
    ],
    "summary": "Create a region",
    "description": "Create a new region.  \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_region:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:write:region:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "CreateARegion",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_region:write:admin",
       "contact_center:write:region:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_region:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:region:admin"
     ]
    }
   }
  },
  "/contact_center/regions/{regionId}": {
   "get": {
    "tags": [
     "Regions"
    ],
    "summary": "Get a region",
    "description": "Get information about a region.  \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_region:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:region:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "GetARegion",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_region:read:admin",
       "contact_center:read:region:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_region:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:region:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Regions"
    ],
    "summary": "Delete a region",
    "description": "Delete a site and move its members to another region.   \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_region:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:region:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "DeleteARegion",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_region:write:admin",
       "contact_center:delete:region:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_region:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:region:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Regions"
    ],
    "summary": "Update a region",
    "description": "Update information for a region.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_region:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:udpate:region:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "UpdateARegion",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_region:write:admin",
       "contact_center:udpate:region:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_region:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:udpate:region:admin"
     ]
    }
   }
  },
  "/contact_center/regions/{regionId}/users": {
   "get": {
    "tags": [
     "Regions"
    ],
    "summary": "List a region's users",
    "description": "Retrieve the list of a region's assigned agents. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_region:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:list_region_users:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "ListRegion'sUsers",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_region:read:admin",
       "contact_center:read:list_region_users:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_region:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:list_region_users:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Regions"
    ],
    "summary": "Assign users to a region",
    "description": "Assign users to a region.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_region:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:write:region_user:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "AssignUsersToARegion",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_region:write:admin",
       "contact_center:write:region_user:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_region:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:region_user:admin"
     ]
    }
   }
  },
  "/contact_center/analytics/dataset/historical/agent_performance": {
   "get": {
    "tags": [
     "Reports V2(CX Analytics)"
    ],
    "summary": "List historical agent performance dataset data",
    "description": "Generate a list of agent performance dataset raw data.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:dataset_agent_performance:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "Listhistoricalagentperformancedatasetdata",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_report:read:admin",
       "contact_center:read:dataset_agent_performance:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_report:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:dataset_agent_performance:admin"
     ]
    }
   }
  },
  "/contact_center/analytics/dataset/historical/agent_timecard": {
   "get": {
    "tags": [
     "Reports V2(CX Analytics)"
    ],
    "summary": "List historical agent timecard dataset data",
    "description": "Generate a list of agent timecard dataset raw data.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:dataset_agent_timecard:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "Listhistoricalagenttimecarddatasetdata",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_report:read:admin",
       "contact_center:read:dataset_agent_timecard:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_report:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:dataset_agent_timecard:admin"
     ]
    }
   }
  },
  "/contact_center/analytics/dataset/historical/engagement": {
   "get": {
    "tags": [
     "Reports V2(CX Analytics)"
    ],
    "summary": "List historical engagement dataset data",
    "description": "Generate a list of engagement dataset raw data.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:dataset_engagement:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "Listengagementdatasetdata",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_report:read:admin",
       "contact_center:read:dataset_engagement:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_report:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:dataset_engagement:admin"
     ]
    }
   }
  },
  "/contact_center/analytics/dataset/historical/flow_performance": {
   "get": {
    "tags": [
     "Reports V2(CX Analytics)"
    ],
    "summary": "List historical flow performance dataset data",
    "description": "Generate a list of flow performance dataset raw data.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:dataset_flow_performance:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "Listhistoricalflowperformancedatasetdata",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_report:read:admin",
       "contact_center:read:dataset_flow_performance:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_report:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:dataset_flow_performance:admin"
     ]
    }
   }
  },
  "/contact_center/analytics/dataset/historical/outbound_dialer_performance": {
   "get": {
    "tags": [
     "Reports V2(CX Analytics)"
    ],
    "summary": "List historical outbound dialer performance dataset data",
    "description": "Generate a list of outbound dialer performance dataset raw data.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:dataset_outbound_dialer_performance:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "Listhistoricaloutbounddialerperformancedatasetdata",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_report:read:admin",
       "contact_center:read:dataset_outbound_dialer_performance:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_report:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:dataset_outbound_dialer_performance:admin"
     ]
    }
   }
  },
  "/contact_center/analytics/dataset/historical/queue_performance": {
   "get": {
    "tags": [
     "Reports V2(CX Analytics)"
    ],
    "summary": "List historical queue performance dataset data",
    "description": "Generate a list of queue performance dataset raw data.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:dataset_queue_performance:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "Listhistoricalqueueperformancedatasetdata",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_report:read:admin",
       "contact_center:read:dataset_queue_performance:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_report:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:dataset_queue_performance:admin"
     ]
    }
   }
  },
  "/contact_center/analytics/log/historical/engagement": {
   "get": {
    "tags": [
     "Reports V2(CX Analytics)"
    ],
    "summary": "List historical engagement log data",
    "description": "Retrieve a list of all historical engagement log data. The log captures all details of closed engagements, including a timeline and key events, providing a clear record for tracking and analysis.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:engagement_log:admin`\n\n**[Rate Limit Label](h[...]",
    "operationId": "Listhistoricalengagementlogs",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_report:read:admin",
       "contact_center:read:engagement_log:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_report:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:engagement_log:admin"
     ]
    }
   }
  },
  "/contact_center/analytics/log/historical/journey": {
   "get": {
    "tags": [
     "Reports V2(CX Analytics)"
    ],
    "summary": "List historical Zoom Phone to Contact Center call journey data",
    "description": "View the complete customer journey of a call across both Contact Center and Zoom Phone.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:call_journey_log:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "ListhistoricalZoomphonetozcccalljourneydata",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_report:read:admin",
       "contact_center:read:call_journey_log:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_report:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:call_journey_log:admin"
     ]
    }
   }
  },
  "/contact_center/reports/operation_logs": {
   "get": {
    "tags": [
     "Reports V2(CX Analytics)"
    ],
    "summary": "List operation logs",
    "description": "Retrieve the Zoom Contact Center management system operation logs report. \n\n The Zoom Contact Center management system operation logs report lets account owners and admins view monthly Zoom Contact Center related admin operation details.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_operation_logs:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:[...]",
    "operationId": "listOperationLogs",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_operation_logs:read:admin",
       "contact_center:read:operation_logs:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_operation_logs:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:operation_logs:admin"
     ]
    }
   }
  },
  "/contact_center/analytics/agents/leg_metrics": {
   "get": {
    "tags": [
     "Reports(Legacy Reports)"
    ],
    "summary": "List agent leg reports",
    "description": "Generate a list of agent's leg reports.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:agent_report:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "listAgentLegMetric",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_report:read:admin",
       "contact_center:read:agent_report:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_report:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:agent_report:admin"
     ]
    }
   }
  },
  "/contact_center/analytics/agents/status_history": {
   "get": {
    "tags": [
     "Reports(Legacy Reports)"
    ],
    "summary": "List agent's status history reports",
    "description": "Generate a list of an agent's status history reports. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:agent_status_report:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "listAgentStatusHistory",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_report:read:admin",
       "contact_center:read:agent_status_report:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_report:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:agent_status_report:admin"
     ]
    }
   }
  },
  "/contact_center/analytics/agents/time_sheets": {
   "get": {
    "tags": [
     "Reports(Legacy Reports)"
    ],
    "summary": "List agent's time sheet reports",
    "description": "Generate a list of an agent's time sheet reports. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:agent_report:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "listAgentTimeSheet",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_report:read:admin",
       "contact_center:read:agent_report:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_report:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:agent_report:admin"
     ]
    }
   }
  },
  "/contact_center/analytics/historical/details/metrics": {
   "get": {
    "tags": [
     "Reports(Legacy Reports)"
    ],
    "summary": "List historical detail reports",
    "description": "Generates a list of historical detail reports.  \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:engagement_report:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "listHistoricalDetailMetric",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_report:read:admin",
       "contact_center:read:engagement_report:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_report:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:engagement_report:admin"
     ]
    }
   }
  },
  "/contact_center/analytics/historical/queues/agents/metrics": {
   "get": {
    "tags": [
     "Reports(Legacy Reports)"
    ],
    "summary": "List historical agent reports by queue",
    "description": "Generate detailed historical reports of agents from a specific queue.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:agent_report:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "listQueueAgentsMetrics",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_report:read:admin",
       "contact_center:read:agent_report:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_report:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:agent_report:admin"
     ]
    }
   }
  },
  "/contact_center/analytics/historical/queues/metrics": {
   "get": {
    "tags": [
     "Reports(Legacy Reports)"
    ],
    "summary": "List historical queue reports",
    "description": "Generate a list of historical queue reports. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:queue_report:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "listHistoricalQueueMetric",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_report:read:admin",
       "contact_center:read:queue_report:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_report:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:queue_report:admin"
     ]
    }
   }
  },
  "/contact_center/analytics/historical/queues/{queueId}/agents/metrics": {
   "get": {
    "tags": [
     "Reports(Legacy Reports)"
    ],
    "summary": "List historical queue's agents reports",
    "description": "Generate a list of a historical queue's agent reports.  \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:agent_report:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "listQueueAgentMetric",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_report:read:admin",
       "contact_center:read:agent_report:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_report:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:agent_report:admin"
     ]
    }
   }
  },
  "/contact_center/roles": {
   "get": {
    "tags": [
     "Roles"
    ],
    "summary": "List roles",
    "description": "Use this API to return a list of roles. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_role:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:list_roles:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "listRoles",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_role:read:admin",
       "contact_center:read:list_roles:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_role:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:list_roles:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Roles"
    ],
    "summary": "Create a role",
    "description": "Create a new [role](https://support.zoom.us/hc/en-us/articles/4471054202253-Using-role-management). Admins can use the role management feature to control access to features and settings in the Zoom web portal. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_role:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:write:role:admin`\n\n**[Rate Limi[...]",
    "operationId": "createRole",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_role:write:admin",
       "contact_center:write:role:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_role:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:role:admin"
     ]
    }
   }
  },
  "/contact_center/roles/duplicate": {
   "post": {
    "tags": [
     "Roles"
    ],
    "summary": "Duplicate a role",
    "description": "Duplicate the role specified by the original role name and assign it a new name. All settings, permissions, and configurations of the original role will be copied to the new role.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_role:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:write:role:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us[...]",
    "operationId": "Duplicatearole",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_role:write:admin",
       "contact_center:write:role:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_role:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:write:role:admin"
     ]
    }
   }
  },
  "/contact_center/roles/{roleId}": {
   "get": {
    "tags": [
     "Roles"
    ],
    "summary": "Get a role",
    "description": "Get information about a role. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_role:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:read:role:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "getRole",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_role:read:admin",
       "contact_center:read:role:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_role:read:admin"
     ],
     "x-granular-scopes": [
      "contact_center:read:role:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Roles"
    ],
    "summary": "Delete a role",
    "description": "Delete a role. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_role:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:delete:role:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "deleteRole",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_role:write:admin",
       "contact_center:delete:role:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_role:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:delete:role:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Roles"
    ],
    "summary": "Update a role",
    "description": "Update a role. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center_role:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_center:update:role:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "updateRole",
    "security": [
     {
      "openapi_oauth": [
       "contact_center_role:write:admin",
       "contact_center:update:role:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "contact_center_role:write:admin"
     ],
     "x-granular-scopes": [
      "contact_center:update:role:admin"
     ]
    }
   }
  },
  "/contact_center/roles/{roleId}/privileges": {
   "delete": {
    "tags": [
     "Roles"
    ],
    "summary": "Delete role privileges",
[...]
