{
 "openapi": "3.0.0",
 "info": {
  "title": "Events",
  "description": " The Webinars Plus & Events APIs let developers integrate [Zoom Webinars Plus & Events](https://developers.zoom.us/docs/events/) to create, manage, and customize virtual event experiences in their apps and services.",
  "termsOfService": "https://zoom.us/docs/en-us/zoom_api_license_and_tou.html",
  "contact": {
   "name": "Zoom Developers",
   "url": "https://developer.zoom.us/"
  },
  "version": "2"
 },
 "servers": [
  {
   "url": "https://api.zoom.us/v2"
  }
 ],
 "paths": {
  "/zoom_events/events/{eventId}/attendee_action": {
   "get": {
    "tags": [
     "Attendee Actions"
    ],
    "summary": "List event attendee actions",
    "description": "Retrieves the attendee actions performed by the host for an event.\n \n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_attendee_actions:read`,`zoom_events_attendee_actions:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:list_attendee_actions`,`zoom_events:read:[...]",
    "operationId": "ListEventAttendeeActions",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_attendee_actions:read",
       "zoom_events_attendee_actions:read:admin",
       "zoom_events:read:list_attendee_actions",
       "zoom_events:read:list_attendee_actions:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_attendee_actions:read",
      "zoom_events_attendee_actions:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:list_attendee_actions",
      "zoom_events:read:list_attendee_actions:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Attendee Actions"
    ],
    "summary": "Update event attendee actions",
    "description": "Retrieves attendee onsite action for an event. You can perform actions such as onsite check-in for a single attendee or up to 300 attendees in a batch operation. In the case of a batch operation, the API response can be a partial success.  Any errors are returned in the **errors** object.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_even[...]",
    "operationId": "UpdateEventAttendeeActions",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_attendee_actions:write",
       "zoom_events_attendee_actions:write:admin",
       "zoom_events:update:batch_attendee_actions",
       "zoom_events:update:batch_attendee_actions:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_attendee_actions:write",
      "zoom_events_attendee_actions:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:update:batch_attendee_actions",
      "zoom_events:update:batch_attendee_actions:admin"
     ]
    }
   }
  },
  "/zoom_events/events/{eventId}/sessions/{sessionId}/attendee_action": {
   "get": {
    "tags": [
     "Attendee Actions"
    ],
    "summary": "List session attendee actions",
    "description": "Retrieves the attendee actions performed by the host for an event session.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_attendee_actions:read`,`zoom_events_attendee_actions:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:list_session_attendee_actions`,`zo[...]",
    "operationId": "ListSessionAttendeeActions",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_attendee_actions:read",
       "zoom_events_attendee_actions:read:admin",
       "zoom_events:read:list_session_attendee_actions",
       "zoom_events:read:list_session_attendee_actions:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_attendee_actions:read",
      "zoom_events_attendee_actions:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:list_session_attendee_actions",
      "zoom_events:read:list_session_attendee_actions:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Attendee Actions"
    ],
    "summary": "Update session attendee actions",
    "description": "Performs attendee onsite action for an event session. You can perform actions such as onsite check-in for a single attendee or up to 300 attendees in a batch operation. In the case of a batch operation, the API response can be a partial success.  Any errors are returned in the **errors** object.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zo[...]",
    "operationId": "UpdateSessionAttendeeActions",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_attendee_actions:write",
       "zoom_events_attendee_actions:write:admin",
       "zoom_events:update:batch_session_attendee_actions",
       "zoom_events:update:batch_session_attendee_actions:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_attendee_actions:write",
      "zoom_events_attendee_actions:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:update:batch_session_attendee_actions",
      "zoom_events:update:batch_session_attendee_actions:admin"
     ]
    }
   }
  },
  "/zoom_events/events/{eventId}/coeditors": {
   "get": {
    "tags": [
     "Co Editors"
    ],
    "summary": "  List coeditors",
    "description": "Retrieves the list of co-editors and their edit permissions for an event.   Co-editors can make changes to the event details. Co-editors have view permission to all sections of the event.\n\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_coeditors:read`,`zoom_events_coeditors:read:admin`\n\n**[Granular Scopes](https://developers.zoom[...]",
    "operationId": "getCoEditors",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_coeditors:read",
       "zoom_events_coeditors:read:admin",
       "zoom_events:read:list_coeditors",
       "zoom_events:read:list_coeditors:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_coeditors:read",
      "zoom_events_coeditors:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:list_coeditors",
      "zoom_events:read:list_coeditors:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Co Editors"
    ],
    "summary": " Add or remove event co-editors",
    "description": "Adds or removes event co-editor actions.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_coeditor:write`,`zoom_events_coeditor:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:write:coeditor`,`zoom_events:write:coeditor:admin`\n\n**[Rate Limit Label](https://mark[...]",
    "operationId": "coeditoractions",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_coeditor:write",
       "zoom_events_coeditor:write:admin",
       "zoom_events:write:coeditor",
       "zoom_events:write:coeditor:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_coeditor:write",
      "zoom_events_coeditor:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:write:coeditor",
      "zoom_events:write:coeditor:admin"
     ]
    }
   }
  },
  "/zoom_events/events/{eventId}/email_types": {
   "get": {
    "tags": [
     "Emails"
    ],
    "summary": "List event email types",
    "description": "Get the list of email types defined for an event.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_email:read`,`zoom_events_email:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:list_email_types`,`zoom_events:read:list_email_types:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "listEmailTypes",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_email:read",
       "zoom_events_email:read:admin",
       "zoom_events:read:list_email_types",
       "zoom_events:read:list_email_types:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_email:read",
      "zoom_events_email:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:list_email_types",
      "zoom_events:read:list_email_types:admin"
     ]
    }
   }
  },
  "/zoom_events/events/{eventId}/email_types/{emailTypeId}/send_status": {
   "get": {
    "tags": [
     "Emails"
    ],
    "summary": "List event emails sent status",
    "description": "Get the list of email sent status for an event email type.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_email:read`,`zoom_events_email:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:list_emails_status`,`zoom_events:read:list_emails_status:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LI[...]",
    "operationId": "listEmailSentStatuses",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_email:read",
       "zoom_events_email:read:admin",
       "zoom_events:read:list_emails_status",
       "zoom_events:read:list_emails_status:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_email:read",
      "zoom_events_email:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:list_emails_status",
      "zoom_events:read:list_emails_status:admin"
     ]
    }
   }
  },
  "/zoom_events/events/{eventId}/access_links": {
   "get": {
    "tags": [
     "Event Access"
    ],
    "summary": "List event access links",
    "description": "Retrieves a list of all the event's access links associated with the event.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus or Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_access_links:read:admin`,`zoom_events_access_links:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:list_access_links`,`zoom_events:read:lis[...]",
    "operationId": "getEventAccessLinks",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_access_links:read:admin",
       "zoom_events_access_links:read",
       "zoom_events:read:list_access_links",
       "zoom_events:read:list_access_links:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_access_links:read:admin",
      "zoom_events_access_links:read"
     ],
     "x-granular-scopes": [
      "zoom_events:read:list_access_links",
      "zoom_events:read:list_access_links:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Event Access"
    ],
    "summary": "Create event access link",
    "description": "Creates an access link for an event.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_access_links:write`,`zoom_events_access_links:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:write:access_links`,`zoom_events:write:access_links:admin`\n\n**[Rate Limit Label]([...]",
    "operationId": "createEventAccessLink",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_access_links:write",
       "zoom_events_access_links:write:admin",
       "zoom_events:write:access_links",
       "zoom_events:write:access_links:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_access_links:write",
      "zoom_events_access_links:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:write:access_links",
      "zoom_events:write:access_links:admin"
     ]
    }
   }
  },
  "/zoom_events/events/{eventId}/access_links/{accessLinkId}": {
   "get": {
    "tags": [
     "Event Access"
    ],
    "summary": "Get event access link",
    "description": "Retrieves event access link information.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_access_links:read`,`zoom_events_access_links:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:access_links`,`zoom_events:read:access_links:admin`\n\n**[Rate Limit Label]([...]",
    "operationId": "GetEventAccessLink",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_access_links:read",
       "zoom_events_access_links:read:admin",
       "zoom_events:read:access_links",
       "zoom_events:read:access_links:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_access_links:read",
      "zoom_events_access_links:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:access_links",
      "zoom_events:read:access_links:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Event Access"
    ],
    "summary": "Delete event access link",
    "description": "Deletes an event access link.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus or Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_access_links:write`,`zoom_events_access_links:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:delete:access_links`,`zoom_events:delete:access_links:admin`\n\n**[Rate Limit Label](http[...]",
    "operationId": "deleteEventAccessLink",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_access_links:write",
       "zoom_events_access_links:write:admin",
       "zoom_events:delete:access_links",
       "zoom_events:delete:access_links:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_access_links:write",
      "zoom_events_access_links:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:delete:access_links",
      "zoom_events:delete:access_links:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Event Access"
    ],
    "summary": "Update event access",
    "description": "Updates the event access for an event ID.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_access_links:write`,`zoom_events_access_links:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:update:access_links`,`zoom_events:update:access_links:admin`\n\n**[Rate Limit [...]",
    "operationId": "updateEventAccess",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_access_links:write",
       "zoom_events_access_links:write:admin",
       "zoom_events:update:access_links",
       "zoom_events:update:access_links:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_access_links:write",
      "zoom_events_access_links:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:update:access_links",
      "zoom_events:update:access_links:admin"
     ]
    }
   }
  },
  "/zoom_events/events": {
   "get": {
    "tags": [
     "Events"
    ],
    "summary": "List events",
    "description": "Retrieves all events associated with the user.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus or Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_basic:read`,`zoom_events_basic:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:list_events`,`zoom_events:read:list_events:admin`\n\n**[Rate Limit Label](https://m[...]",
    "operationId": "getEvents",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_basic:read",
       "zoom_events_basic:read:admin",
       "zoom_events:read:list_events",
       "zoom_events:read:list_events:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_basic:read",
      "zoom_events_basic:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:list_events",
      "zoom_events:read:list_events:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Events"
    ],
    "summary": "Create an event",
    "description": "Creates an event.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus or Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_basic:write`,`zoom_events_basic:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:write:event`,`zoom_events:write:event:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference[...]",
    "operationId": "createEvent",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_basic:write",
       "zoom_events_basic:write:admin",
       "zoom_events:write:event",
       "zoom_events:write:event:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_basic:write",
      "zoom_events_basic:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:write:event",
      "zoom_events:write:event:admin"
     ]
    }
   }
  },
  "/zoom_events/events/{eventId}": {
   "get": {
    "tags": [
     "Events"
    ],
    "summary": "Get an event",
    "description": "Returns information on a specified event.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus or Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_basic:read`,`zoom_events_basic:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:event`,`zoom_events:read:event:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.u[...]",
    "operationId": "getEventInfo",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_basic:read",
       "zoom_events_basic:read:admin",
       "zoom_events:read:event",
       "zoom_events:read:event:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_basic:read",
      "zoom_events_basic:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:event",
      "zoom_events:read:event:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Events"
    ],
    "summary": "Delete an event",
    "description": "Delete a draft event.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus or Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_basic:write`,`zoom_events_basic:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:delete:event`,`zoom_events:delete:event:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-ref[...]",
    "operationId": "deleteEvent",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_basic:write",
       "zoom_events_basic:write:admin",
       "zoom_events:delete:event",
       "zoom_events:delete:event:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_basic:write",
      "zoom_events_basic:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:delete:event",
      "zoom_events:delete:event:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Events"
    ],
    "summary": "Update an event",
    "description": "Updates an event.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_basic:write`,`zoom_events_basic:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:update:event`,`zoom_events:update:event:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-referenc[...]",
    "operationId": "updateEvent",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_basic:write",
       "zoom_events_basic:write:admin",
       "zoom_events:update:event",
       "zoom_events:update:event:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_basic:write",
      "zoom_events_basic:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:update:event",
      "zoom_events:update:event:admin"
     ]
    }
   }
  },
  "/zoom_events/events/{eventId}/event_actions": {
   "post": {
    "tags": [
     "Events"
    ],
    "summary": "Event actions",
    "description": "Updates the event actions that the host performs for an event.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_basic:write`,`zoom_events_basic:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:write:event`,`zoom_events:write:event:admin`\n\n**[Rate Limit Label](ht[...]",
    "operationId": "EventActions",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_basic:write",
       "zoom_events_basic:write:admin",
       "zoom_events:write:event",
       "zoom_events:write:event:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_basic:write",
      "zoom_events_basic:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:write:event",
      "zoom_events:write:event:admin"
     ]
    }
   }
  },
  "/zoom_events/events/{eventId}/exhibitors": {
   "get": {
    "tags": [
     "Exhibitors"
    ],
    "summary": "List exhibitors",
    "description": "Lists all exhibitors associated with an event.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus or Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_exhibitors:read:admin`,`zoom_events_exhibitors:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:list_exhibitors`,`zoom_events:read:list_exhibitors:admin`\n\n**[Rate Limi[...]",
    "operationId": "getExhibitors",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_exhibitors:read:admin",
       "zoom_events_exhibitors:read",
       "zoom_events:read:list_exhibitors",
       "zoom_events:read:list_exhibitors:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_exhibitors:read:admin",
      "zoom_events_exhibitors:read"
     ],
     "x-granular-scopes": [
      "zoom_events:read:list_exhibitors",
      "zoom_events:read:list_exhibitors:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Exhibitors"
    ],
    "summary": "Create an exhibitor",
    "description": "Creates an exhibitor for a multi-session and conference-type event.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_exhibitors:write`,`zoom_events_exhibitors:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:write:exhibitor`,`zoom_events:write:exhibitor:admin`\n\n[...]",
    "operationId": "createExhibitor",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_exhibitors:write",
       "zoom_events_exhibitors:write:admin",
       "zoom_events:write:exhibitor",
       "zoom_events:write:exhibitor:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_exhibitors:write",
      "zoom_events_exhibitors:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:write:exhibitor",
      "zoom_events:write:exhibitor:admin"
     ]
    }
   }
  },
  "/zoom_events/events/{eventId}/exhibitors/{exhibitorId}": {
   "get": {
    "tags": [
     "Exhibitors"
    ],
    "summary": "Get an exhibitor",
    "description": "Returns the exhibitor information of a specified event.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus or Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_exhibitors:read`,`zoom_events_exhibitors:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:exhibitor`,`zoom_events:read:exhibitor:admin`\n\n**[Rate Limit L[...]",
    "operationId": "getExhibitorInfo",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_exhibitors:read",
       "zoom_events_exhibitors:read:admin",
       "zoom_events:read:exhibitor",
       "zoom_events:read:exhibitor:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_exhibitors:read",
      "zoom_events_exhibitors:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:exhibitor",
      "zoom_events:read:exhibitor:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Exhibitors"
    ],
    "summary": "Delete an exhibitor",
    "description": "Deletes an exhibitor.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_exhibitors:write`,`zoom_events_exhibitors:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:delete:exhibitor`,`zoom_events:delete:exhibitor:admin`\n\n**[Rate Limit Label](https://marketplace.zoo[...]",
    "operationId": "deleteExhibitor",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_exhibitors:write",
       "zoom_events_exhibitors:write:admin",
       "zoom_events:delete:exhibitor",
       "zoom_events:delete:exhibitor:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_exhibitors:write",
      "zoom_events_exhibitors:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:delete:exhibitor",
      "zoom_events:delete:exhibitor:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Exhibitors"
    ],
    "summary": "Update exhibitor for an event",
    "description": "Updates the exhibitor for an event ID. This operation is only allowed for a multi-session event type.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus or Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_exhibitors:write`,`zoom_events_exhibitors:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:update:exhibitor`,`zo[...]",
    "operationId": "updateExhibitor",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_exhibitors:write",
       "zoom_events_exhibitors:write:admin",
       "zoom_events:update:exhibitor",
       "zoom_events:update:exhibitor:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_exhibitors:write",
      "zoom_events_exhibitors:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:update:exhibitor",
      "zoom_events:update:exhibitor:admin"
     ]
    }
   }
  },
  "/zoom_events/events/{eventId}/sponsor_tiers": {
   "get": {
    "tags": [
     "Exhibitors"
    ],
    "summary": "List sponsor tiers",
    "description": "Lists all sponsor tiers associated with an event.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus or Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_exhibitors:read:admin`,`zoom_events_exhibitors:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:list_sponsor_tiers`,`zoom_events:read:list_sponsor_tiers:admin`\n\n**[[...]",
    "operationId": "ListSponsorTiers",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_exhibitors:read:admin",
       "zoom_events_exhibitors:read",
       "zoom_events:read:list_sponsor_tiers",
       "zoom_events:read:list_sponsor_tiers:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_exhibitors:read:admin",
      "zoom_events_exhibitors:read"
     ],
     "x-granular-scopes": [
      "zoom_events:read:list_sponsor_tiers",
      "zoom_events:read:list_sponsor_tiers:admin"
     ]
    }
   }
  },
  "/zoom_events/files": {
   "post": {
    "tags": [
     "Files"
    ],
    "summary": "Upload events file",
    "description": "Uploads a file to Zoom Events. \n\n **Note:**  \n* Base URL: `https://fileapi.zoom.us/v2/`.  \n* The rate limit is 20 requests per second or 2000 requests per second per IP address or 50 requests per user within a 24-hour period\n* The caller must support HTTP 30x redirects. \n* The caller must retain the Authorization header when redirected to a different hostname. \n* Supported video formats: `.mp4`, `.webm`.\n* When your object size reaches 2 GB, you should use multipart u[...]",
    "operationId": "uploadEventFile",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_file:write",
       "zoom_events_file:write:admin",
       "zoom_events:write:file_upload",
       "zoom_events:write:file_upload:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_file:write",
      "zoom_events_file:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:write:file_upload",
      "zoom_events:write:file_upload:admin"
     ]
    }
   }
  },
  "/zoom_events/files/multipart": {
   "post": {
    "tags": [
     "Files"
    ],
    "summary": "Upload events multipart files",
    "description": "Uploads a multipart file. \n\n **Note:** \n* The base URL for this API is `https://fileapi.zoom.us/v2/`. \n* The rate limit of this API is 20 requests per second or 2000 requests per second per IP address or 50 requests per user within a 24-hour period. \n* The caller must support HTTP 30x redirects. \n* The caller must retain the authorization header when redirected to a different hostname. \n* Video can be in `.mp4`, `.webm` format.\n* In general, when your object size reac[...]",
    "operationId": "uploadMultipartEventFile",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_file:write:admin",
       "zoom_events_file:write",
       "zoom_events:write:file_upload",
       "zoom_events:write:file_upload:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_file:write:admin",
      "zoom_events_file:write"
     ],
     "x-granular-scopes": [
      "zoom_events:write:file_upload",
      "zoom_events:write:file_upload:admin"
     ]
    }
   }
  },
  "/zoom_events/files/multipart/upload": {
   "post": {
    "tags": [
     "Files"
    ],
    "summary": "Initiate and complete the multipart file upload ",
    "description": "**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license \n\n **Note:** \n* The base URL for this API is `https://fileapi.zoom.us/v2/`. \n* The caller must support HTTP 30x redirects. \n* The caller must retain the authorization header when redirected to a different hostname. \n* Once initiated, the multipart upload must complete within 7 days. \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_ev[...]",
    "operationId": "initiateAndCompleteAEventMultipartUpload.",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_file:write:admin",
       "zoom_events_file:write",
       "zoom_events:write:file_upload",
       "zoom_events:write:file_upload:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_file:write:admin",
      "zoom_events_file:write"
     ],
     "x-granular-scopes": [
      "zoom_events:write:file_upload",
      "zoom_events:write:file_upload:admin"
     ]
    }
   }
  },
  "/zoom_events/hubs": {
   "get": {
    "tags": [
     "Hubs"
    ],
    "summary": "List hubs",
    "description": "Retrieves a list of event hubs.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus or Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_hubs:read`,`zoom_events_hubs:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:list_hubs`,`zoom_events:read:list_hubs:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/do[...]",
    "operationId": "getHubList",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_hubs:read",
       "zoom_events_hubs:read:admin",
       "zoom_events:read:list_hubs",
       "zoom_events:read:list_hubs:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_hubs:read",
      "zoom_events_hubs:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:list_hubs",
      "zoom_events:read:list_hubs:admin"
     ]
    }
   }
  },
  "/zoom_events/hubs/{hubId}/hosts": {
   "get": {
    "tags": [
     "Hubs"
    ],
    "summary": "List hub Hosts",
    "description": "Retrieves a list of hub hosts.\n\n**Prerequisites**\n\n* A Pro or higher account plan\n\n* A Zoom Webinars Plus/Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_hubs:read:admin`,`zoom_events_hubs:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:list_hub_hosts`,`zoom_events:read:list_hub_hosts:admin`\n\n**[Rate Limit Label](https://marketplace.[...]",
    "operationId": "gethubhostList",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_hubs:read:admin",
       "zoom_events_hubs:read",
       "zoom_events:read:list_hub_hosts",
       "zoom_events:read:list_hub_hosts:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_hubs:read:admin",
      "zoom_events_hubs:read"
     ],
     "x-granular-scopes": [
      "zoom_events:read:list_hub_hosts",
      "zoom_events:read:list_hub_hosts:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Hubs"
    ],
    "summary": "Creates a new hub host",
    "description": "Add a host to the hub.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus or Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_hub:write`,`zoom_events_hub:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:write:hub_host`,`zoom_events:write:hub_host:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-re[...]",
    "operationId": "createHubHost",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_hub:write",
       "zoom_events_hub:write:admin",
       "zoom_events:write:hub_host",
       "zoom_events:write:hub_host:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_hub:write",
      "zoom_events_hub:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:write:hub_host",
      "zoom_events:write:hub_host:admin"
     ]
    }
   }
  },
  "/zoom_events/hubs/{hubId}/hosts/{hostUserId}": {
   "delete": {
    "tags": [
     "Hubs"
    ],
    "summary": "Remove hub host",
    "description": "Delete a host from the hub.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus or Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_hub:write`,`zoom_events_hub:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:delete:hub_host`,`zoom_events:delete:hub_host:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs[...]",
    "operationId": "deleteHubHost",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_hub:write",
       "zoom_events_hub:write:admin",
       "zoom_events:delete:hub_host",
       "zoom_events:delete:hub_host:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_hub:write",
      "zoom_events_hub:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:delete:hub_host",
      "zoom_events:delete:hub_host:admin"
     ]
    }
   }
  },
  "/zoom_events/hubs/{hubId}/videos": {
   "get": {
    "tags": [
     "Hubs"
    ],
    "summary": "List hub videos",
    "description": "Lists the video/recording resources of a hub.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus or Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_hubs:read`,`zoom_events_hubs:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:list_hub_videos`,`zoom_events:read:list_hub_videos:admin`\n\n**[Rate Limit Label](http[...]",
    "operationId": "ListHubVideos",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_hubs:read",
       "zoom_events_hubs:read:admin",
       "zoom_events:read:list_hub_videos",
       "zoom_events:read:list_hub_videos:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_hubs:read",
      "zoom_events_hubs:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:list_hub_videos",
      "zoom_events:read:list_hub_videos:admin"
     ]
    }
   }
  },
  "/zoom_events/events/{eventId}/registrants": {
   "get": {
    "tags": [
     "Registrants"
    ],
    "summary": "List registrants",
    "description": "Retrieves event registrants.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_registrants:read`,`zoom_events_registrants:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:list_registrants`,`zoom_events:read:list_registrants:admin`\n\n**[Rate Limit Label](https:[...]",
    "operationId": "getRegistrants",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_registrants:read",
       "zoom_events_registrants:read:admin",
       "zoom_events:read:list_registrants",
       "zoom_events:read:list_registrants:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_registrants:read",
      "zoom_events_registrants:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:list_registrants",
      "zoom_events:read:list_registrants:admin"
     ]
    }
   }
  },
  "/zoom_events/events/{eventId}/sessions/{sessionId}/attendees": {
   "get": {
    "tags": [
     "Registrants"
    ],
    "summary": "List session attendees",
    "description": "Retrieves session attendees.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_registrants:read`,`zoom_events_registrants:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:list_session_attendees`,`zoom_events:read:list_session_attendees:admin`\n\n**[Rate Limit L[...]",
    "operationId": "getSessionAttendeeList",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_registrants:read",
       "zoom_events_registrants:read:admin",
       "zoom_events:read:list_session_attendees",
       "zoom_events:read:list_session_attendees:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_registrants:read",
      "zoom_events_registrants:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:list_session_attendees",
      "zoom_events:read:list_session_attendees:admin"
     ]
    }
   }
  },
  "/zoom_events/events/{eventId}/reports/chat_transcripts": {
   "get": {
    "tags": [
     "Reports"
    ],
    "summary": "Get chat transcripts report",
    "description": "Retrieves the chat transcripts report for an event.  \nAt present, this API returns data only for users who have enabled the [meeting and webinar cloud archiving feature](https://support.zoom.us/hc/en-us/articles/360061037572-Configuring-archival-settings-for-meetings-and-webinars).  \nThe meeting and webinar cloud archiving feature determines whether users can download in-meeting, private 1:1, and private group chats.  \n Below, chat-type data is returned based on the event [...]",
    "operationId": "ChatTranscriptsReport",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_reports:read",
       "zoom_events_reports:read:admin",
       "zoom_events:read:chat_transcripts",
       "zoom_events:read:chat_transcripts:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_reports:read",
      "zoom_events_reports:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:chat_transcripts",
      "zoom_events:read:chat_transcripts:admin"
     ]
    }
   }
  },
  "/zoom_events/events/{eventId}/reports/custom_reports/{customReportId}": {
   "get": {
    "tags": [
     "Reports"
    ],
    "summary": "Get custom report",
    "description": "Retrieves data for the custom report for the given report ID.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_reports:read`,`zoom_events_reports:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:custom_report`,`zoom_events:read:custom_report:admin`\n\n**[Rate [...]",
    "operationId": "getCustomEventReport",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_reports:read",
       "zoom_events_reports:read:admin",
       "zoom_events:read:custom_report",
       "zoom_events:read:custom_report:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_reports:read",
      "zoom_events_reports:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:custom_report",
      "zoom_events:read:custom_report:admin"
     ]
    }
   }
  },
  "/zoom_events/events/{eventId}/reports/event_attendance": {
   "get": {
    "tags": [
     "Reports"
    ],
    "summary": "Get event attendance (Live or Lobby) report",
    "description": "Retrieves the event attendance (live or lobby) report for the event.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_reports:read`,`zoom_events_reports:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:event_attendance`,`zoom_events:read:event_attendance:admin[...]",
    "operationId": "EventAttendanceReport",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_reports:read",
       "zoom_events_reports:read:admin",
       "zoom_events:read:event_attendance",
       "zoom_events:read:event_attendance:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_reports:read",
      "zoom_events_reports:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:event_attendance",
      "zoom_events:read:event_attendance:admin"
     ]
    }
   }
  },
  "/zoom_events/events/{eventId}/reports/sessions/{sessionId}/attendance": {
   "get": {
    "tags": [
     "Reports"
    ],
    "summary": "Get session attendance report",
    "description": "Retrieves a session attendance report.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_reports:read`,`zoom_events_reports:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:session_attendance`,`zoom_events:read:session_attendance:admin`\n\n**[Rate Limit Label]([...]",
    "operationId": "SessionAttendanceReport",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_reports:read",
       "zoom_events_reports:read:admin",
       "zoom_events:read:session_attendance",
       "zoom_events:read:session_attendance:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_reports:read",
      "zoom_events_reports:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:session_attendance",
      "zoom_events:read:session_attendance:admin"
     ]
    }
   }
  },
  "/zoom_events/events/{eventId}/reports/survey": {
   "get": {
    "tags": [
     "Reports"
    ],
    "summary": "Get event survey report",
    "description": "Retrieve event and session survey information.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_reports:read`,`zoom_events_reports:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:list_session_surveys`,`zoom_events:read:list_session_surveys:admin`\n\n**[Rate L[...]",
    "operationId": "EventSurveyReportApi",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_reports:read",
       "zoom_events_reports:read:admin",
       "zoom_events:read:list_session_surveys",
       "zoom_events:read:list_session_surveys:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_reports:read",
      "zoom_events_reports:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:list_session_surveys",
      "zoom_events:read:list_session_surveys:admin"
     ]
    }
   }
  },
  "/zoom_events/events/{eventId}/reports/ticket_registration": {
   "get": {
    "tags": [
     "Reports"
    ],
    "summary": "Get event registrations report",
    "description": "Retrieves event ticket registrations.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_reports:read`,`zoom_events_reports:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:event_registration`,`zoom_events:read:event_registration:admin`\n\n**[Rate Limit Label](h[...]",
    "operationId": "EventRegistrationsReport",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_reports:read",
       "zoom_events_reports:read:admin",
       "zoom_events:read:event_registration",
       "zoom_events:read:event_registration:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_reports:read",
      "zoom_events_reports:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:event_registration",
      "zoom_events:read:event_registration:admin"
     ]
    }
   }
  },
  "/zoom_events/hubs/{hubId}/vod_channels/{channelId}/reports/registrations": {
   "get": {
    "tags": [
     "Reports"
    ],
    "summary": "Get VOD channel registration report",
    "description": "Retrieves VOD channel registrations and view duration information.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_vod_reports:read`,`zoom_events_vod_reports:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:vod_registrations`,`zoom_events:read:vod_registratio[...]",
    "operationId": "VodChannelReigistration",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_vod_reports:read",
       "zoom_events_vod_reports:read:admin",
       "zoom_events:read:vod_registrations",
       "zoom_events:read:vod_registrations:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_vod_reports:read",
      "zoom_events_vod_reports:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:vod_registrations",
      "zoom_events:read:vod_registrations:admin"
     ]
    }
   }
  },
  "/zoom_events/events/{eventId}/sessions": {
   "get": {
    "tags": [
     "Sessions"
    ],
    "summary": "List sessions",
    "description": "Retrieves the sessions in an event. Event hosts and special-role ticket users, such as speakers and co-hosts, can access this API. Users will not need to provide any special query parameters. The API internally identifies based on the user role and provides the session information for the event. \n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `z[...]",
    "operationId": "getEventSessionList",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_sessions:read",
       "zoom_events_sessions:read:admin",
       "zoom_events:read:list_sessions",
       "zoom_events:read:list_sessions:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_sessions:read",
      "zoom_events_sessions:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:list_sessions",
      "zoom_events:read:list_sessions:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Sessions"
    ],
    "summary": "Create a session",
    "description": "Creates a session. This operation is not available for a single session event type.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_sessions:write:admin`,`zoom_events_sessions:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:write:session`,`zoom_events:write:session:ad[...]",
    "operationId": "createEventSession",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_sessions:write:admin",
       "zoom_events_sessions:write",
       "zoom_events:write:session",
       "zoom_events:write:session:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_sessions:write:admin",
      "zoom_events_sessions:write"
     ],
     "x-granular-scopes": [
      "zoom_events:write:session",
      "zoom_events:write:session:admin"
     ]
    }
   }
  },
  "/zoom_events/events/{eventId}/sessions/{sessionId}": {
   "get": {
    "tags": [
     "Sessions"
    ],
    "summary": "Get the session information",
    "description": "Returns the session information.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_sessions:read`,`zoom_events_sessions:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:session`,`zoom_events:read:session:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.u[...]",
    "operationId": "getEventSessionInfo",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_sessions:read",
       "zoom_events_sessions:read:admin",
       "zoom_events:read:session",
       "zoom_events:read:session:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_sessions:read",
      "zoom_events_sessions:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:session",
      "zoom_events:read:session:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Sessions"
    ],
    "summary": "Delete a session",
    "description": "Deletes a session. Not allowed for a single session event type.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_sessions:write`,`zoom_events_sessions:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:delete:session`,`zoom_events:delete:session:admin`\n\n**[Rate Li[...]",
    "operationId": "deleteEventSession",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_sessions:write",
       "zoom_events_sessions:write:admin",
       "zoom_events:delete:session",
       "zoom_events:delete:session:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_sessions:write",
      "zoom_events_sessions:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:delete:session",
      "zoom_events:delete:session:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Sessions"
    ],
    "summary": "Update a session",
    "description": "Updates an existing session in an event. \n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_sessions:write`,`zoom_events_sessions:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:update:session`,`zoom_events:update:session:admin`\n\n**[Rate Limit Label](https://mar[...]",
    "operationId": "updateEventSession",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_sessions:write",
       "zoom_events_sessions:write:admin",
       "zoom_events:update:session",
       "zoom_events:update:session:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_sessions:write",
      "zoom_events_sessions:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:update:session",
      "zoom_events:update:session:admin"
     ]
    }
   }
  },
  "/zoom_events/events/{eventId}/sessions/{sessionId}/interpreters": {
   "get": {
    "tags": [
     "Sessions"
    ],
    "summary": "List session interpreters",
    "description": "Retrieves interpreters in a session.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus /Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_sessions:read`,`zoom_events_sessions:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:list_session_interpreters`,`zoom_events:read:list_session_interpreters:admin`\n\n**[Rate [...]",
    "operationId": "getSessionInterpreterList",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_sessions:read",
       "zoom_events_sessions:read:admin",
       "zoom_events:read:list_session_interpreters",
       "zoom_events:read:list_session_interpreters:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_sessions:read",
      "zoom_events_sessions:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:list_session_interpreters",
      "zoom_events:read:list_session_interpreters:admin"
     ]
    }
   },
   "put": {
    "tags": [
     "Sessions"
    ],
    "summary": "Create or update session interpreters",
    "description": "Creates or updates the list of interpreters for the session.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_sessions:write`,`zoom_events_sessions:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:update:session_interpreter`,`zoom_events:update:session_interpreter[...]",
    "operationId": "updateSessionInterpreters",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_sessions:write",
       "zoom_events_sessions:write:admin",
       "zoom_events:update:session_interpreter",
       "zoom_events:update:session_interpreter:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_sessions:write",
      "zoom_events_sessions:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:update:session_interpreter",
      "zoom_events:update:session_interpreter:admin"
     ]
    }
   }
  },
  "/zoom_events/events/{eventId}/sessions/{sessionId}/join_token": {
   "get": {
    "tags": [
     "Sessions"
    ],
    "summary": "Get ticket session join token by Event ID and Session ID",
    "description": "Retrieves the join token to join an event session.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_sessions:read`,`zoom_events_sessions:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:session_token`,`zoom_events:read:session_token:admin`\n\n**[Rate Limit Lab[...]",
    "operationId": "getSessionJoinToken",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_sessions:read",
       "zoom_events_sessions:read:admin",
       "zoom_events:read:session_token",
       "zoom_events:read:session_token:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_sessions:read",
      "zoom_events_sessions:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:session_token",
      "zoom_events:read:session_token:admin"
     ]
    }
   }
  },
  "/zoom_events/events/{eventId}/sessions/{sessionId}/livestream": {
   "get": {
    "tags": [
     "Sessions"
    ],
    "summary": "Get session livestream configuration",
    "description": "List the livestream configuration for the given session. RTMP Incoming livestream will only work for webinar sessions (not meetings). Please check [RTMP livesteam](https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0077038) for the feature details.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_sessions:read`,`zoom_ev[...]",
    "operationId": "getSessionLivestreamConfiguration",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_sessions:read",
       "zoom_events_sessions:read:admin",
       "zoom_events:read:session_livestream_config",
       "zoom_events:read:session_livestream_config:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_sessions:read",
      "zoom_events_sessions:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:session_livestream_config",
      "zoom_events:read:session_livestream_config:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Sessions"
    ],
    "summary": "Update session livestream configuration",
    "description": "Update the livestream configuration for the given session. RTMP Incoming livestream will only work for webinar sessions (not meetings). Please check [RTMP livestream](https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0077038) for the feature details.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_sessions:write`,`zoo[...]",
    "operationId": "UpdateSessionLivestreamConfiguration",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_sessions:write",
       "zoom_events_sessions:write:admin",
       "zoom_events:update:session_livestream_config",
       "zoom_events:update:session_livestream_config:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_sessions:write",
      "zoom_events_sessions:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:update:session_livestream_config",
      "zoom_events:update:session_livestream_config:admin"
     ]
    }
   }
  },
  "/zoom_events/events/{eventId}/sessions/{sessionId}/polls": {
   "get": {
    "tags": [
     "Sessions"
    ],
    "summary": "List session polls",
    "description": "List all the polls of a session.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_sessions:read`,`zoom_events_sessions:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:list_session_polls`,`zoom_events:read:list_session_polls:admin`\n\n**[Rate Limit Label](http[...]",
    "operationId": "getSessionPolls",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_sessions:read",
       "zoom_events_sessions:read:admin",
       "zoom_events:read:list_session_polls",
       "zoom_events:read:list_session_polls:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_sessions:read",
      "zoom_events_sessions:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:list_session_polls",
      "zoom_events:read:list_session_polls:admin"
     ]
    }
   },
   "put": {
    "tags": [
     "Sessions"
    ],
    "summary": "Create or update session polls",
    "description": "Create or update the list of polls for the session.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_sessions:write`,`zoom_events_sessions:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:update:session_poll`,`zoom_events:update:session_poll:admin`\n\n**[Rate Limi[...]",
    "operationId": "updateSessionPolls",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_sessions:write",
       "zoom_events_sessions:write:admin",
       "zoom_events:update:session_poll",
       "zoom_events:update:session_poll:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_sessions:write",
      "zoom_events_sessions:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:update:session_poll",
      "zoom_events:update:session_poll:admin"
     ]
    }
   }
  },
  "/zoom_events/events/{eventId}/sessions/{sessionId}/reservations": {
   "get": {
    "tags": [
     "Sessions"
    ],
    "summary": "List session reservations",
    "description": "Retrieves the list of reservations made by registrants for the session.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_sessions:read`,`zoom_events_sessions:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:list_session_reservations`,`zoom_events:read:list_ses[...]",
    "operationId": "ListSessionReservations",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_sessions:read",
       "zoom_events_sessions:read:admin",
       "zoom_events:read:list_session_reservations",
       "zoom_events:read:list_session_reservations:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_sessions:read",
      "zoom_events_sessions:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:list_session_reservations",
      "zoom_events:read:list_session_reservations:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Sessions"
    ],
    "summary": "Add session reservations",
    "description": "Reserve a spot for a user in the given session. As a host, reserve registrants for a particular session. Session reservation needs to be enabled before using this API.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_sessions:write`,`zoom_events_sessions:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/[...]",
    "operationId": "AddSessionReservations",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_sessions:write",
       "zoom_events_sessions:write:admin",
       "zoom_events:write:session_reservations",
       "zoom_events:write:session_reservations:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_sessions:write",
      "zoom_events_sessions:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:write:session_reservations",
      "zoom_events:write:session_reservations:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Sessions"
    ],
    "summary": "Delete session reservations",
    "description": "This tool removes a user's reservation spot for a given session. As a host, you can use it to remove reservations of registrants for a particular session.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_sessions:write`,`zoom_events_sessions:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes[...]",
    "operationId": "DeleteSessionReservations",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_sessions:write",
       "zoom_events_sessions:write:admin",
       "zoom_events:delete:session_reservations",
       "zoom_events:delete:session_reservations:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_sessions:write",
      "zoom_events_sessions:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:delete:session_reservations",
      "zoom_events:delete:session_reservations:admin"
     ]
    }
   }
  },
  "/zoom_events/events/{eventId}/speakers": {
   "get": {
    "tags": [
     "Speakers"
    ],
    "summary": "List speakers",
    "description": "Retrieves a list of speakers for an event.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus or Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_speakers:read`,`zoom_events_speakers:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:list_speakers`,`zoom_events:read:list_speakers:admin`\n\n**[Rate Limit Label](htt[...]",
    "operationId": "getSpeakers",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_speakers:read",
       "zoom_events_speakers:read:admin",
       "zoom_events:read:list_speakers",
       "zoom_events:read:list_speakers:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_speakers:read",
      "zoom_events_speakers:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:list_speakers",
      "zoom_events:read:list_speakers:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Speakers"
    ],
    "summary": "Create a speaker",
    "description": "Creates a speaker for an event.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_speakers:write`,`zoom_events_speakers:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:write:speaker`,`zoom_events:write:speaker:admin`\n\n**[Rate Limit Label](https://marketplace.zoo[...]",
    "operationId": "createSpeaker",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_speakers:write",
       "zoom_events_speakers:write:admin",
       "zoom_events:write:speaker",
       "zoom_events:write:speaker:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_speakers:write",
      "zoom_events_speakers:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:write:speaker",
      "zoom_events:write:speaker:admin"
     ]
    }
   }
  },
  "/zoom_events/events/{eventId}/speakers/{speakerId}": {
   "get": {
    "tags": [
     "Speakers"
    ],
    "summary": "Get a speaker",
    "description": "Returns information on a specific speaker.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_speakers:read`,`zoom_events_speakers:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:speaker`,`zoom_events:read:speaker:admin`\n\n**[Rate Limit Label](https://marketpl[...]",
    "operationId": "getSpeaker",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_speakers:read",
       "zoom_events_speakers:read:admin",
       "zoom_events:read:speaker",
       "zoom_events:read:speaker:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_speakers:read",
      "zoom_events_speakers:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:speaker",
      "zoom_events:read:speaker:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Speakers"
    ],
    "summary": "Delete a speaker",
    "description": "Deletes a speaker.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_speakers:write`,`zoom_events_speakers:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:delete:speaker`,`zoom_events:delete:speaker:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/a[...]",
    "operationId": "deleteSpeaker",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_speakers:write",
       "zoom_events_speakers:write:admin",
       "zoom_events:delete:speaker",
       "zoom_events:delete:speaker:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_speakers:write",
      "zoom_events_speakers:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:delete:speaker",
      "zoom_events:delete:speaker:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Speakers"
    ],
    "summary": "Update a speaker",
    "description": "Updates the speaker information.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_speakers:write`,`zoom_events_speakers:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:update:speaker`,`zoom_events:update:speaker:admin`\n\n**[Rate Limit Label](https://marketplace.[...]",
    "operationId": "updateSpeaker",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_speakers:write",
       "zoom_events_speakers:write:admin",
       "zoom_events:update:speaker",
       "zoom_events:update:speaker:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_speakers:write",
      "zoom_events_speakers:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:update:speaker",
      "zoom_events:update:speaker:admin"
     ]
    }
   }
  },
  "/zoom_events/events/{eventId}/questions": {
   "get": {
    "tags": [
     "Ticket Types"
    ],
    "summary": "List registration questions for an event",
    "description": "List registration questions and fields that are to be answered by users while registering for an event. These questions are setup during the event level.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_ticket_types:read`,`zoom_events_ticket_types:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-sc[...]",
    "operationId": "getRegistrationQuestionsForEvent",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_ticket_types:read",
       "zoom_events_ticket_types:read:admin",
       "zoom_events:read:list_registration_questions",
       "zoom_events:read:list_registration_questions:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_ticket_types:read",
      "zoom_events_ticket_types:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:list_registration_questions",
      "zoom_events:read:list_registration_questions:admin"
     ]
    }
   },
   "put": {
    "tags": [
     "Ticket Types"
    ],
    "summary": "Update registration questions for an event",
    "description": "Updates registration questions and fields that are to be answered by users while registering for an event. These questions are setup at event level.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_ticket_types:write`,`zoom_events_ticket_types:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scope[...]",
    "operationId": "updateRegistrationQuestionsForEvent",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_ticket_types:write",
       "zoom_events_ticket_types:write:admin",
       "zoom_events:update:registraion_question",
       "zoom_events:update:registraion_question:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_ticket_types:write",
      "zoom_events_ticket_types:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:update:registraion_question",
      "zoom_events:update:registraion_question:admin"
     ]
    }
   }
  },
  "/zoom_events/events/{eventId}/ticket_types": {
   "get": {
    "tags": [
     "Ticket Types"
    ],
    "summary": "List ticket types",
    "description": "Lists all ticket types associated with an event.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus or Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_ticket_types:read`,`zoom_events_ticket_types:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:list_ticket_types`,`zoom_events:read:list_ticket_types:admin`\n\n**[...]",
    "operationId": "getEventTicketTypes",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_ticket_types:read",
       "zoom_events_ticket_types:read:admin",
       "zoom_events:read:list_ticket_types",
       "zoom_events:read:list_ticket_types:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_ticket_types:read",
      "zoom_events_ticket_types:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:list_ticket_types",
      "zoom_events:read:list_ticket_types:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Ticket Types"
    ],
    "summary": "Create an event ticket type",
    "description": "Creates a ticket type for the event ID that is not allowed for single session and recurring event types.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_ticket_types:write`,`zoom_events_ticket_types:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:write:ticket_ty[...]",
    "operationId": "createTicketType",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_ticket_types:write",
       "zoom_events_ticket_types:write:admin",
       "zoom_events:write:ticket_type",
       "zoom_events:write:ticket_type:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_ticket_types:write",
      "zoom_events_ticket_types:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:write:ticket_type",
      "zoom_events:write:ticket_type:admin"
     ]
    }
   }
  },
  "/zoom_events/events/{eventId}/ticket_types/{ticketTypeId}": {
   "delete": {
    "tags": [
     "Ticket Types"
    ],
    "summary": "Delete a ticket type",
    "description": "Deletes a ticket type of an event that is not allowed for a single session event type.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_ticket_types:write`,`zoom_events_ticket_types:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:delete:ticket_type`,`zoom_events:[...]",
    "operationId": "deleteEventTicketType",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_ticket_types:write",
       "zoom_events_ticket_types:write:admin",
       "zoom_events:delete:ticket_type",
       "zoom_events:delete:ticket_type:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_ticket_types:write",
      "zoom_events_ticket_types:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:delete:ticket_type",
      "zoom_events:delete:ticket_type:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Ticket Types"
    ],
    "summary": "Update ticket type for an event",
    "description": "Updates the ticket type for an event ID not allowed for a single session event type.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus or Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_ticket_types:write`,`zoom_events_ticket_types:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:update:ticket_type`,`zoom_events:u[...]",
    "operationId": "updateTicketType",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_ticket_types:write",
       "zoom_events_ticket_types:write:admin",
       "zoom_events:update:ticket_type",
       "zoom_events:update:ticket_type:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_ticket_types:write",
      "zoom_events_ticket_types:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:update:ticket_type",
      "zoom_events:update:ticket_type:admin"
     ]
    }
   }
  },
  "/zoom_events/events/{eventId}/ticket_types/{ticketTypeId}/questions": {
   "get": {
    "tags": [
     "Ticket Types"
    ],
    "summary": "List registration questions for ticket type",
    "description": "List registration questions and fields that are to be answered by users while registering for an event. These questions are setup at ticket_type level.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_ticket_types:read`,`zoom_events_ticket_types:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scop[...]",
    "operationId": "getRegistrationQuestionsForTicketType",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_ticket_types:read",
       "zoom_events_ticket_types:read:admin",
       "zoom_events:read:list_registration_questions",
       "zoom_events:read:list_registration_questions:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_ticket_types:read",
      "zoom_events_ticket_types:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:list_registration_questions",
      "zoom_events:read:list_registration_questions:admin"
     ]
    }
   },
   "put": {
    "tags": [
     "Ticket Types"
    ],
    "summary": "Update registration questions for ticket type",
    "description": "Updates registration questions and fields that are to be answered by users while registering for an event. These questions are setup at ticket_type level. This API is not allowed for single session event type.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_ticket_types:write`,`zoom_events_ticket_types:write:admin`\n\n**[Granular Sco[...]",
    "operationId": "updateRegistrationQuestionsForTicketType",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_ticket_types:write",
       "zoom_events_ticket_types:write:admin",
       "zoom_events:update:registraion_question",
       "zoom_events:update:registraion_question:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_ticket_types:write",
      "zoom_events_ticket_types:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:update:registraion_question",
      "zoom_events:update:registraion_question:admin"
     ]
    }
   }
  },
  "/zoom_events/events/{eventId}/tickets": {
   "get": {
    "tags": [
     "Tickets"
    ],
    "summary": "List tickets",
    "description": "Retrieves the ticket information of an event.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus/ Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_tickets:read`,`zoom_events_tickets:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:list_tickets`,`zoom_events:read:list_tickets:admin`\n\n**[Rate Limit Label](https:[...]",
    "operationId": "getTickets",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_tickets:read",
       "zoom_events_tickets:read:admin",
       "zoom_events:read:list_tickets",
       "zoom_events:read:list_tickets:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_tickets:read",
      "zoom_events_tickets:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:list_tickets",
      "zoom_events:read:list_tickets:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Tickets"
    ],
    "summary": "Create tickets",
    "description": "Creates tickets for an event. You can add a single ticket or up to 30 tickets in a batch operation. Please note that this request uses the [`pre-registration`](https://support.zoom.us/hc/en-us/articles/13475985512973-Pre-registering-Zoom-Events-guests) flow. \n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus or Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_tickets:write`,`zoom_event[...]",
    "operationId": "createTickets",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_tickets:write",
       "zoom_events_tickets:write:admin",
       "zoom_events:write:ticket",
       "zoom_events:write:ticket:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_tickets:write",
      "zoom_events_tickets:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:write:ticket",
      "zoom_events:write:ticket:admin"
     ]
    }
   }
  },
  "/zoom_events/events/{eventId}/tickets/{ticketId}": {
   "get": {
    "tags": [
     "Tickets"
    ],
    "summary": "Get a ticket",
    "description": "Retrieves information on a specific ticket.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus or Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_tickets:read`,`zoom_events_tickets:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:ticket`,`zoom_events:read:ticket:admin`\n\n**[Rate Limit Label](https://marketplac[...]",
    "operationId": "getTicketDetails",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_tickets:read",
       "zoom_events_tickets:read:admin",
       "zoom_events:read:ticket",
       "zoom_events:read:ticket:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_tickets:read",
      "zoom_events_tickets:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:ticket",
      "zoom_events:read:ticket:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Tickets"
    ],
    "summary": "Delete a ticket",
    "description": "Deletes a ticket.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus or Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_tickets:write`,`zoom_events_tickets:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:delete:ticket`,`zoom_events:delete:ticket:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-r[...]",
    "operationId": "deleteTicket",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_tickets:write",
       "zoom_events_tickets:write:admin",
       "zoom_events:delete:ticket",
       "zoom_events:delete:ticket:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_tickets:write",
      "zoom_events_tickets:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:delete:ticket",
      "zoom_events:delete:ticket:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Tickets"
    ],
    "summary": "Update ticket",
    "description": "Updates ticket questions for the given ticket ID and event ID.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_tickets:write`,`zoom_events_tickets:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:write:ticket`,`zoom_events:write:ticket:admin`\n\n**[Rate Limit Lab[...]",
    "operationId": "Updateticket",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_tickets:write",
       "zoom_events_tickets:write:admin",
       "zoom_events:write:ticket",
       "zoom_events:write:ticket:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_tickets:write",
      "zoom_events_tickets:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:write:ticket",
      "zoom_events:write:ticket:admin"
     ]
    }
   }
  },
  "/zoom_events/hubs/{hubId}/vod_channels": {
   "get": {
    "tags": [
     "Video On-Demand"
    ],
    "summary": "List channels",
    "description": "Retrieves the channel information for a hub.\n\n**Prerequisites**\n\n* A Pro or higher account plan\n\n* A Zoom Webinars Plus or Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_vod_channels:read`,`zoom_events_vod_channels:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:list_all_vod_channels`,`zoom_events:read:list_all_vod_channels:admi[...]",
    "operationId": "getVODChannels",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_vod_channels:read",
       "zoom_events_vod_channels:read:admin",
       "zoom_events:read:list_all_vod_channels",
       "zoom_events:read:list_all_vod_channels:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_vod_channels:read",
      "zoom_events_vod_channels:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:list_all_vod_channels",
      "zoom_events:read:list_all_vod_channels:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Video On-Demand"
    ],
    "summary": "Create VOD channel",
    "description": "Creates a channel for managing hub videos. Please check this support page for details about a [video channel](https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0057579#h_01HBVW2WZ06MFH7KHGPSJC9YKG).\n\n**Prerequisites**\n\n* A Pro or higher account plan\n\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_vod_channels:write`,`zoom_events_vod_channels:write:admin`\n\n**[Gra[...]",
    "operationId": "createVodChannel",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_vod_channels:write",
       "zoom_events_vod_channels:write:admin",
       "zoom_events:write:vod_channel",
       "zoom_events:write:vod_channel:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_vod_channels:write",
      "zoom_events_vod_channels:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:write:vod_channel",
      "zoom_events:write:vod_channel:admin"
     ]
    }
   }
  },
  "/zoom_events/hubs/{hubId}/vod_channels/{channelId}": {
   "get": {
    "tags": [
     "Video On-Demand"
    ],
    "summary": "Get VOD channel details",
    "description": "Returns VOD channel details.\n\n**Prerequisites**\n\n* A Pro or higher account plan\n\n* A Zoom Webinars Plus or Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_vod_channels:read`,`zoom_events_vod_channels:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:vod_channel`,`zoom_events:read:vod_channel:admin`\n\n**[Rate Limit Label](https://m[...]",
    "operationId": "getVODChannelDetail",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_vod_channels:read",
       "zoom_events_vod_channels:read:admin",
       "zoom_events:read:vod_channel",
       "zoom_events:read:vod_channel:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_vod_channels:read",
      "zoom_events_vod_channels:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:vod_channel",
      "zoom_events:read:vod_channel:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Video On-Demand"
    ],
    "summary": "Delete VOD Channel",
    "description": "Deletes a video channel. Please check this support page for details about a [video channel](https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0057579#h_01HBVW2WZ06MFH7KHGPSJC9YKG).\n\n**Prerequisites**\n\n* A Pro or higher account plan\n\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_vod_channels:write`,`zoom_events_vod_channels:write:admin`\n\n**[Granular Scopes](http[...]",
    "operationId": "DeleteVODChannel",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_vod_channels:write",
       "zoom_events_vod_channels:write:admin",
       "zoom_events:delete:vod_channel",
       "zoom_events:delete:vod_channel:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_vod_channels:write",
      "zoom_events_vod_channels:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:delete:vod_channel",
      "zoom_events:delete:vod_channel:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Video On-Demand"
    ],
    "summary": "Update VOD channel",
    "description": "Updates a hub video channel. Please check this support page for details about a [video channel](https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0057579#h_01HBVW2WZ06MFH7KHGPSJC9YKG).\n\n**Prerequisites**\n\n* A Pro or higher account plan\n\n* A Zoom Webinars Plus or Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_vod_channels:write`,`zoom_events_vod_channels:write:admin`\n\n**[Granular Scopes][...]",
    "operationId": "UpdateVideoChannel",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_vod_channels:write",
       "zoom_events_vod_channels:write:admin",
       "zoom_events:update:vod_channel",
       "zoom_events:update:vod_channel:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_vod_channels:write",
      "zoom_events_vod_channels:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:update:vod_channel",
      "zoom_events:update:vod_channel:admin"
     ]
    }
   }
  },
  "/zoom_events/hubs/{hubId}/vod_channels/{channelId}/actions": {
   "post": {
    "tags": [
     "Video On-Demand"
    ],
    "summary": " VOD channel actions",
    "description": "Returns VOD channel action result.\n\n**Prerequisites**:\n* A Pro or higher account plan.\n* A Zoom Webinars Plus or Events license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_vod_channels:write`,`zoom_events_vod_channels:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:update:vod_channel`,`zoom_events:update:vod_channel:admin`\n\n**[Rate Limit Label[...]",
    "operationId": "vodChannelActions",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_vod_channels:write",
       "zoom_events_vod_channels:write:admin",
       "zoom_events:update:vod_channel",
       "zoom_events:update:vod_channel:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_vod_channels:write",
      "zoom_events_vod_channels:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:update:vod_channel",
      "zoom_events:update:vod_channel:admin"
     ]
    }
   }
  },
  "/zoom_events/hubs/{hubId}/vod_channels/{channelId}/videos": {
   "get": {
    "tags": [
     "Video On-Demand"
    ],
    "summary": "List VOD channel videos",
    "description": "Lists VOD channel videos.\n\n**Prerequisites**\n\n* A Pro or higher account plan\n\n* A Zoom Webinars Plus or Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_vod_channels:read`,`zoom_events_vod_channels:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:list_vod_channel_videos`,`zoom_events:read:list_vod_channel_videos:admin`\n\n**[Rate L[...]",
    "operationId": "ListVODChannelVideos",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_vod_channels:read",
       "zoom_events_vod_channels:read:admin",
       "zoom_events:read:list_vod_channel_videos",
       "zoom_events:read:list_vod_channel_videos:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_vod_channels:read",
      "zoom_events_vod_channels:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:list_vod_channel_videos",
      "zoom_events:read:list_vod_channel_videos:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Video On-Demand"
    ],
    "summary": "Add VOD channel videos",
    "description": "Adds videos to the VOD channel.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus / Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_vod_channels:write`,`zoom_events_vod_channels:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:write:vod_channel_videos`,`zoom_events:write:vod_channel_videos:admin`\n\n**[Rate Limit [...]",
    "operationId": "AddVODChannelVideos",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_vod_channels:write",
       "zoom_events_vod_channels:write:admin",
       "zoom_events:write:vod_channel_videos",
       "zoom_events:write:vod_channel_videos:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_vod_channels:write",
      "zoom_events_vod_channels:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:write:vod_channel_videos",
      "zoom_events:write:vod_channel_videos:admin"
     ]
    }
   }
  },
  "/zoom_events/hubs/{hubId}/vod_channels/{channelId}/videos/{videoId}": {
   "delete": {
    "tags": [
     "Video On-Demand"
    ],
    "summary": "Delete VOD channel video",
    "description": "Removes video from the VOD channel.\n\n**Prerequisites**\n\n* A Pro or higher account plan\n\n* A Zoom Webinars Plus or Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_vod_channels:write`,`zoom_events_vod_channels:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:delete:vod_channel_videos`,`zoom_events:delete:vod_channel_videos:admin`\n\n**[[...]",
    "operationId": "DeleteVODChannelVideo",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_vod_channels:write",
       "zoom_events_vod_channels:write:admin",
       "zoom_events:delete:vod_channel_videos",
       "zoom_events:delete:vod_channel_videos:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_vod_channels:write",
      "zoom_events_vod_channels:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:delete:vod_channel_videos",
      "zoom_events:delete:vod_channel_videos:admin"
     ]
    }
   }
  },
  "/zoom_events/hubs/{hubId}/vod_channels/{channelId}/registration_questions": {
   "get": {
    "tags": [
     "Video On-Demand Registrations"
    ],
    "summary": "Get VOD Registration Questions",
    "description": "List registration questions and fields that are to be answered by users while registering for a vod channel. These questions are configured for the VOD channel after or before publishing the channel.\n\n**Prerequisites**\n* A Pro or higher account plan\n* A Zoom Webinars Plus or Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_vod_registration:read`,`zoom_events_vod_registration:read:admin`\n\n**[Granular Scopes[...]",
    "operationId": "getRegistrationQuestionsForVODChannel",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_vod_registration:read",
       "zoom_events_vod_registration:read:admin",
       "zoom_events:read:vod_registration_questions",
       "zoom_events:read:vod_registration_questions:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_vod_registration:read",
      "zoom_events_vod_registration:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:vod_registration_questions",
      "zoom_events:read:vod_registration_questions:admin"
     ]
    }
   },
   "put": {
    "tags": [
     "Video On-Demand Registrations"
    ],
    "summary": "update VOD channel registration questions",
    "description": "Updates registration questions and fields that are to be answered by users while registering for a VOD channel. These questions are setup at VOD channel level.\n\n**Prerequisites**\n\n* A Pro or higher account plan\n\n* A Zoom Webinars Plus or Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_vod_registration:write`,`zoom_events_vod_registration:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/[...]",
    "operationId": "updateRegistrationQuestionsForVODchannel",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_vod_registration:write",
       "zoom_events_vod_registration:write:admin",
       "zoom_events:update:vod_registration_questions",
       "zoom_events:update:vod_registration_questions:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_vod_registration:write",
      "zoom_events_vod_registration:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:update:vod_registration_questions",
      "zoom_events:update:vod_registration_questions:admin"
     ]
    }
   }
  },
  "/zoom_events/hubs/{hubId}/vod_channels/{channelId}/registrations": {
   "get": {
    "tags": [
     "Video On-Demand Registrations"
    ],
    "summary": "List VOD Registration",
    "description": "Retrieves the VOD registration information of a channel.\n\n**Prerequisites**\n\n* A Pro or higher account plan\n\n* A Zoom Webinars Plus or Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_vod_registration:read`,`zoom_events_vod_registration:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events:read:vod_registrations`,`zoom_events:read:vod_regist[...]",
    "operationId": "ListVODRegistration",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_vod_registration:read",
       "zoom_events_vod_registration:read:admin",
       "zoom_events:read:vod_registrations",
       "zoom_events:read:vod_registrations:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_vod_registration:read",
      "zoom_events_vod_registration:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:read:vod_registrations",
      "zoom_events:read:vod_registrations:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Video On-Demand Registrations"
    ],
    "summary": "VOD channel registration",
    "description": "Creates registrations for a VOD channel. You can add a single registrant or up to 30 registrants in a batch operation.\n\n**Prerequisites**\n\n* A Pro or higher account plan\n\n* A Zoom Webinars Plus or Events license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_events_vod_registration:write`,`zoom_events_vod_registration:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `[...]",
    "operationId": "VODTicketRegistration",
    "security": [
     {
      "openapi_oauth": [
       "zoom_events_vod_registration:write",
       "zoom_events_vod_registration:write:admin",
       "zoom_events:write:vod_registration",
       "zoom_events:write:vod_registration:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zoom_events_vod_registration:write",
      "zoom_events_vod_registration:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_events:write:vod_registration",
      "zoom_events:write:vod_registration:admin"
     ]
    }
   }
  }
 },
 "components": {
  "securitySchemes": {
   "openapi_authorization": {
    "type": "apiKey",
    "name": "Authorization",
    "in": "header"
   },
   "openapi_oauth": {
    "type": "oauth2",
    "flows": {
     "authorizationCode": {
      "authorizationUrl": "/",
      "tokenUrl": "",
      "refreshUrl": "",
      "scopes": {
       "zoom_events_attendee_actions:read": "zoom_events_attendee_actions:read",
       "zoom_events_attendee_actions:read:admin": "zoom_events_attendee_actions:read:admin",
       "zoom_events:read:list_attendee_actions": "zoom_events:read:list_attendee_actions",
       "zoom_events:read:list_attendee_actions:admin": "zoom_events:read:list_attendee_actions:admin",
       "zoom_events_attendee_actions:write": "zoom_events_attendee_actions:write",
       "zoom_events_attendee_actions:write:admin": "zoom_events_attendee_actions:write:admin",
       "zoom_events:update:batch_attendee_actions": "zoom_events:update:batch_attendee_actions",
       "zoom_events:update:batch_attendee_actions:admin": "zoom_events:update:batch_attendee_actions:admin",
       "zoom_events:update:batch_session_attendee_actions": "zoom_events:update:batch_session_attendee_actions",
       "zoom_events:update:batch_session_attendee_actions:admin": "zoom_events:update:batch_session_attendee_actions:admin",
       "zoom_events:read:list_session_attendee_actions": "zoom_events:read:list_session_attendee_actions",
       "zoom_events:read:list_session_attendee_actions:admin": "zoom_events:read:list_session_attendee_actions:admin",
       "zoom_events_coeditor:write": "zoom_events_coeditor:write",
       "zoom_events_coeditor:write:admin": "zoom_events_coeditor:write:admin",
       "zoom_events:write:coeditor": "zoom_events:write:coeditor",
       "zoom_events:write:coeditor:admin": "zoom_events:write:coeditor:admin",
       "zoom_events_coeditors:read": "zoom_events_coeditors:read",
       "zoom_events_coeditors:read:admin": "zoom_events_coeditors:read:admin",
       "zoom_events:read:list_coeditors": "zoom_events:read:list_coeditors",
       "zoom_events:read:list_coeditors:admin": "zoom_events:read:list_coeditors:admin",
       "zoom_events_email:read": "zoom_events_email:read",
       "zoom_events_email:read:admin": "zoom_events_email:read:admin",
       "zoom_events:read:list_email_types": "zoom_events:read:list_email_types",
       "zoom_events:read:list_email_types:admin": "zoom_events:read:list_email_types:admin",
       "zoom_events:read:list_emails_status": "zoom_events:read:list_emails_status",
       "zoom_events:read:list_emails_status:admin": "zoom_events:read:list_emails_status:admin",
       "zoom_events_access_links:write": "zoom_events_access_links:write",
       "zoom_events_access_links:write:admin": "zoom_events_access_links:write:admin",
       "zoom_events:write:access_links": "zoom_events:write:access_links",
       "zoom_events:write:access_links:admin": "zoom_events:write:access_links:admin",
       "zoom_events_access_links:read:admin": "zoom_events_access_links:read:admin",
       "zoom_events_access_links:read": "zoom_events_access_links:read",
       "zoom_events:read:list_access_links": "zoom_events:read:list_access_links",
       "zoom_events:read:list_access_links:admin": "zoom_events:read:list_access_links:admin",
       "zoom_events:update:access_links": "zoom_events:update:access_links",
       "zoom_events:update:access_links:admin": "zoom_events:update:access_links:admin",
       "zoom_events:delete:access_links": "zoom_events:delete:access_links",
       "zoom_events:delete:access_links:admin": "zoom_events:delete:access_links:admin",
       "zoom_events:read:access_links": "zoom_events:read:access_links",
       "zoom_events:read:access_links:admin": "zoom_events:read:access_links:admin",
       "zoom_events_basic:write": "zoom_events_basic:write",
       "zoom_events_basic:write:admin": "zoom_events_basic:write:admin",
       "zoom_events:write:event": "zoom_events:write:event",
       "zoom_events:write:event:admin": "zoom_events:write:event:admin",
       "zoom_events_basic:read": "zoom_events_basic:read",
       "zoom_events_basic:read:admin": "zoom_events_basic:read:admin",
       "zoom_events:read:list_events": "zoom_events:read:list_events",
       "zoom_events:read:list_events:admin": "zoom_events:read:list_events:admin",
       "zoom_events:update:event": "zoom_events:update:event",
       "zoom_events:update:event:admin": "zoom_events:update:event:admin",
       "zoom_events:read:event": "zoom_events:read:event",
       "zoom_events:read:event:admin": "zoom_events:read:event:admin",
       "zoom_events:delete:event": "zoom_events:delete:event",
       "zoom_events:delete:event:admin": "zoom_events:delete:event:admin",
       "zoom_events_exhibitors:write": "zoom_events_exhibitors:write",
       "zoom_events_exhibitors:write:admin": "zoom_events_exhibitors:write:admin",
       "zoom_events:write:exhibitor": "zoom_events:write:exhibitor",
       "zoom_events:write:exhibitor:admin": "zoom_events:write:exhibitor:admin",
       "zoom_events_exhibitors:read:admin": "zoom_events_exhibitors:read:admin",
       "zoom_events_exhibitors:read": "zoom_events_exhibitors:read",
       "zoom_events:read:list_exhibitors": "zoom_events:read:list_exhibitors",
       "zoom_events:read:list_exhibitors:admin": "zoom_events:read:list_exhibitors:admin",
       "zoom_events:update:exhibitor": "zoom_events:update:exhibitor",
       "zoom_events:update:exhibitor:admin": "zoom_events:update:exhibitor:admin",
       "zoom_events:delete:exhibitor": "zoom_events:delete:exhibitor",
       "zoom_events:delete:exhibitor:admin": "zoom_events:delete:exhibitor:admin",
       "zoom_events:read:exhibitor": "zoom_events:read:exhibitor",
       "zoom_events:read:exhibitor:admin": "zoom_events:read:exhibitor:admin",
       "zoom_events:read:list_sponsor_tiers": "zoom_events:read:list_sponsor_tiers",
       "zoom_events:read:list_sponsor_tiers:admin": "zoom_events:read:list_sponsor_tiers:admin",
       "zoom_events_file:write": "zoom_events_file:write",
       "zoom_events_file:write:admin": "zoom_events_file:write:admin",
       "zoom_events:write:file_upload": "zoom_events:write:file_upload",
       "zoom_events:write:file_upload:admin": "zoom_events:write:file_upload:admin",
       "zoom_events_hubs:read": "zoom_events_hubs:read",
       "zoom_events_hubs:read:admin": "zoom_events_hubs:read:admin",
       "zoom_events:read:list_hubs": "zoom_events:read:list_hubs",
       "zoom_events:read:list_hubs:admin": "zoom_events:read:list_hubs:admin",
       "zoom_events:read:list_hub_hosts": "zoom_events:read:list_hub_hosts",
       "zoom_events:read:list_hub_hosts:admin": "zoom_events:read:list_hub_hosts:admin",
       "zoom_events_hub:write": "zoom_events_hub:write",
       "zoom_events_hub:write:admin": "zoom_events_hub:write:admin",
       "zoom_events:write:hub_host": "zoom_events:write:hub_host",
       "zoom_events:write:hub_host:admin": "zoom_events:write:hub_host:admin",
       "zoom_events:delete:hub_host": "zoom_events:delete:hub_host",
       "zoom_events:delete:hub_host:admin": "zoom_events:delete:hub_host:admin",
       "zoom_events:read:list_hub_videos": "zoom_events:read:list_hub_videos",
       "zoom_events:read:list_hub_videos:admin": "zoom_events:read:list_hub_videos:admin",
       "zoom_events_registrants:read": "zoom_events_registrants:read",
       "zoom_events_registrants:read:admin": "zoom_events_registrants:read:admin",
       "zoom_events:read:list_registrants": "zoom_events:read:list_registrants",
       "zoom_events:read:list_registrants:admin": "zoom_events:read:list_registrants:admin",
       "zoom_events:read:list_session_attendees": "zoom_events:read:list_session_attendees",
       "zoom_events:read:list_session_attendees:admin": "zoom_events:read:list_session_attendees:admin",
       "zoom_events_reports:read": "zoom_events_reports:read",
       "zoom_events_reports:read:admin": "zoom_events_reports:read:admin",
       "zoom_events:read:chat_transcripts": "zoom_events:read:chat_transcripts",
       "zoom_events:read:chat_transcripts:admin": "zoom_events:read:chat_transcripts:admin",
       "zoom_events:read:custom_report": "zoom_events:read:custom_report",
       "zoom_events:read:custom_report:admin": "zoom_events:read:custom_report:admin",
       "zoom_events:read:event_attendance": "zoom_events:read:event_attendance",
       "zoom_events:read:event_attendance:admin": "zoom_events:read:event_attendance:admin",
       "zoom_events:read:session_attendance": "zoom_events:read:session_attendance",
       "zoom_events:read:session_attendance:admin": "zoom_events:read:session_attendance:admin",
       "zoom_events:read:list_session_surveys": "zoom_events:read:list_session_surveys",
       "zoom_events:read:list_session_surveys:admin": "zoom_events:read:list_session_surveys:admin",
       "zoom_events:read:event_registration": "zoom_events:read:event_registration",
       "zoom_events:read:event_registration:admin": "zoom_events:read:event_registration:admin",
       "zoom_events_vod_reports:read": "zoom_events_vod_reports:read",
       "zoom_events_vod_reports:read:admin": "zoom_events_vod_reports:read:admin",
       "zoom_events:read:vod_registrations": "zoom_events:read:vod_registrations",
       "zoom_events:read:vod_registrations:admin": "zoom_events:read:vod_registrations:admin",
       "zoom_events_sessions:write:admin": "zoom_events_sessions:write:admin",
       "zoom_events_sessions:write": "zoom_events_sessions:write",
       "zoom_events:write:session": "zoom_events:write:session",
       "zoom_events:write:session:admin": "zoom_events:write:session:admin",
       "zoom_events_sessions:read": "zoom_events_sessions:read",
       "zoom_events_sessions:read:admin": "zoom_events_sessions:read:admin",
       "zoom_events:read:list_sessions": "zoom_events:read:list_sessions",
       "zoom_events:read:list_sessions:admin": "zoom_events:read:list_sessions:admin",
       "zoom_events:update:session": "zoom_events:update:session",
       "zoom_events:update:session:admin": "zoom_events:update:session:admin",
       "zoom_events:delete:session": "zoom_events:delete:session",
       "zoom_events:delete:session:admin": "zoom_events:delete:session:admin",
       "zoom_events:read:session": "zoom_events:read:session",
       "zoom_events:read:session:admin": "zoom_events:read:session:admin",
       "zoom_events:update:session_interpreter": "zoom_events:update:session_interpreter",
       "zoom_events:update:session_interpreter:admin": "zoom_events:update:session_interpreter:admin",
       "zoom_events:read:list_session_interpreters": "zoom_events:read:list_session_interpreters",
       "zoom_events:read:list_session_interpreters:admin": "zoom_events:read:list_session_interpreters:admin",
       "zoom_events:read:session_token": "zoom_events:read:session_token",
       "zoom_events:read:session_token:admin": "zoom_events:read:session_token:admin",
       "zoom_events:update:session_livestream_config": "zoom_events:update:session_livestream_config",
       "zoom_events:update:session_livestream_config:admin": "zoom_events:update:session_livestream_config:admin",
       "zoom_events:read:session_livestream_config": "zoom_events:read:session_livestream_config",
       "zoom_events:read:session_livestream_config:admin": "zoom_events:read:session_livestream_config:admin",
       "zoom_events:update:session_poll": "zoom_events:update:session_poll",
       "zoom_events:update:session_poll:admin": "zoom_events:update:session_poll:admin",
       "zoom_events:read:list_session_polls": "zoom_events:read:list_session_polls",
       "zoom_events:read:list_session_polls:admin": "zoom_events:read:list_session_polls:admin",
       "zoom_events:read:list_session_reservations": "zoom_events:read:list_session_reservations",
       "zoom_events:read:list_session_reservations:admin": "zoom_events:read:list_session_reservations:admin",
       "zoom_events:delete:session_reservations": "zoom_events:delete:session_reservations",
       "zoom_events:delete:session_reservations:admin": "zoom_events:delete:session_reservations:admin",
       "zoom_events:write:session_reservations": "zoom_events:write:session_reservations",
       "zoom_events:write:session_reservations:admin": "zoom_events:write:session_reservations:admin",
       "zoom_events_speakers:write": "zoom_events_speakers:write",
       "zoom_events_speakers:write:admin": "zoom_events_speakers:write:admin",
       "zoom_events:write:speaker": "zoom_events:write:speaker",
       "zoom_events:write:speaker:admin": "zoom_events:write:speaker:admin",
       "zoom_events_speakers:read": "zoom_events_speakers:read",
       "zoom_events_speakers:read:admin": "zoom_events_speakers:read:admin",
       "zoom_events:read:list_speakers": "zoom_events:read:list_speakers",
       "zoom_events:read:list_speakers:admin": "zoom_events:read:list_speakers:admin",
       "zoom_events:update:speaker": "zoom_events:update:speaker",
       "zoom_events:update:speaker:admin": "zoom_events:update:speaker:admin",
       "zoom_events:delete:speaker": "zoom_events:delete:speaker",
       "zoom_events:delete:speaker:admin": "zoom_events:delete:speaker:admin",
       "zoom_events:read:speaker": "zoom_events:read:speaker",
       "zoom_events:read:speaker:admin": "zoom_events:read:speaker:admin",
       "zoom_events_ticket_types:read": "zoom_events_ticket_types:read",
       "zoom_events_ticket_types:read:admin": "zoom_events_ticket_types:read:admin",
       "zoom_events:read:list_registration_questions": "zoom_events:read:list_registration_questions",
       "zoom_events:read:list_registration_questions:admin": "zoom_events:read:list_registration_questions:admin",
       "zoom_events_ticket_types:write": "zoom_events_ticket_types:write",
       "zoom_events_ticket_types:write:admin": "zoom_events_ticket_types:write:admin",
       "zoom_events:update:registraion_question": "zoom_events:update:registraion_question",
       "zoom_events:update:registraion_question:admin": "zoom_events:update:registraion_question:admin",
       "zoom_events:read:list_ticket_types": "zoom_events:read:list_ticket_types",
       "zoom_events:read:list_ticket_types:admin": "zoom_events:read:list_ticket_types:admin",
       "zoom_events:write:ticket_type": "zoom_events:write:ticket_type",
       "zoom_events:write:ticket_type:admin": "zoom_events:write:ticket_type:admin",
       "zoom_events:delete:ticket_type": "zoom_events:delete:ticket_type",
       "zoom_events:delete:ticket_type:admin": "zoom_events:delete:ticket_type:admin",
       "zoom_events:update:ticket_type": "zoom_events:update:ticket_type",
       "zoom_events:update:ticket_type:admin": "zoom_events:update:ticket_type:admin",
       "zoom_events_tickets:read": "zoom_events_tickets:read",
       "zoom_events_tickets:read:admin": "zoom_events_tickets:read:admin",
       "zoom_events:read:list_tickets": "zoom_events:read:list_tickets",
       "zoom_events:read:list_tickets:admin": "zoom_events:read:list_tickets:admin",
       "zoom_events_tickets:write": "zoom_events_tickets:write",
       "zoom_events_tickets:write:admin": "zoom_events_tickets:write:admin",
       "zoom_events:write:ticket": "zoom_events:write:ticket",
       "zoom_events:write:ticket:admin": "zoom_events:write:ticket:admin",
       "zoom_events:read:ticket": "zoom_events:read:ticket",
       "zoom_events:read:ticket:admin": "zoom_events:read:ticket:admin",
       "zoom_events:delete:ticket": "zoom_events:delete:ticket",
       "zoom_events:delete:ticket:admin": "zoom_events:delete:ticket:admin",
       "zoom_events_vod_channels:read": "zoom_events_vod_channels:read",
       "zoom_events_vod_channels:read:admin": "zoom_events_vod_channels:read:admin",
       "zoom_events:read:list_all_vod_channels": "zoom_events:read:list_all_vod_channels",
       "zoom_events:read:list_all_vod_channels:admin": "zoom_events:read:list_all_vod_channels:admin",
       "zoom_events_vod_channels:write": "zoom_events_vod_channels:write",
       "zoom_events_vod_channels:write:admin": "zoom_events_vod_channels:write:admin",
       "zoom_events:write:vod_channel": "zoom_events:write:vod_channel",
       "zoom_events:write:vod_channel:admin": "zoom_events:write:vod_channel:admin",
       "zoom_events:read:vod_channel": "zoom_events:read:vod_channel",
       "zoom_events:read:vod_channel:admin": "zoom_events:read:vod_channel:admin",
       "zoom_events:delete:vod_channel": "zoom_events:delete:vod_channel",
       "zoom_events:delete:vod_channel:admin": "zoom_events:delete:vod_channel:admin",
       "zoom_events:update:vod_channel": "zoom_events:update:vod_channel",
       "zoom_events:update:vod_channel:admin": "zoom_events:update:vod_channel:admin",
       "zoom_events:read:list_vod_channel_videos": "zoom_events:read:list_vod_channel_videos",
       "zoom_events:read:list_vod_channel_videos:admin": "zoom_events:read:list_vod_channel_videos:admin",
       "zoom_events:write:vod_channel_videos": "zoom_events:write:vod_channel_videos",
       "zoom_events:write:vod_channel_videos:admin": "zoom_events:write:vod_channel_videos:admin",
       "zoom_events:delete:vod_channel_videos": "zoom_events:delete:vod_channel_videos",
       "zoom_events:delete:vod_channel_videos:admin": "zoom_events:delete:vod_channel_videos:admin",
       "zoom_events_vod_registration:write": "zoom_events_vod_registration:write",
       "zoom_events_vod_registration:write:admin": "zoom_events_vod_registration:write:admin",
       "zoom_events:update:vod_registration_questions": "zoom_events:update:vod_registration_questions",
       "zoom_events:update:vod_registration_questions:admin": "zoom_events:update:vod_registration_questions:admin",
       "zoom_events_vod_registration:read": "zoom_events_vod_registration:read",
       "zoom_events_vod_registration:read:admin": "zoom_events_vod_registration:read:admin",
       "zoom_events:read:vod_registration_questions": "zoom_events:read:vod_registration_questions",
       "zoom_events:read:vod_registration_questions:admin": "zoom_events:read:vod_registration_questions:admin",
       "zoom_events:write:vod_registration": "zoom_events:write:vod_registration",
       "zoom_events:write:vod_registration:admin": "zoom_events:write:vod_registration:admin"
      }
     }
    }
   }
  }
 }
}