{
 "openapi": "3.0.0",
 "info": {
  "title": "Marketplace",
  "description": "The Marketplace APIs allow developers to access data related to their app and its usage in the marketplace.",
  "termsOfService": "https://zoom.us/docs/en-us/zoom_api_license_and_tou.html",
  "contact": {
   "name": "Zoom Developers",
   "url": "https://developer.zoom.us/"
  },
  "version": "2"
 },
 "servers": [
  {
   "url": "https://api.zoom.us/v2"
  }
 ],
 "paths": {
  "/app/notifications": {
   "post": {
    "tags": [
     "App"
    ],
    "summary": "Send app notifications",
    "description": "Send app notifications to the Zoom Activity Center. (Note: This API endpoint only supports OAuth 2.0.)\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `app:notification:read`,`app:notification:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace:write:notifications`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "Sendappnotifications",
    "security": [
     {
      "openapi_oauth": [
       "app:notification:read",
       "app:notification:write",
       "marketplace:write:notifications"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "app:notification:read",
      "app:notification:write"
     ],
     "x-granular-scopes": [
      "marketplace:write:notifications"
     ]
    }
   }
  },
  "/marketplace/app/custom_fields": {
   "get": {
    "tags": [
     "App"
    ],
    "summary": "Get user's custom field values",
    "description": "Get custom field values for user.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace_custom_fields:read`,`marketplace_custom_fields:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace:read:custom_fields:admin`,`marketplace:read:custom_fields`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "getCustomFieldValues",
    "security": [
     {
      "openapi_oauth": [
       "marketplace_custom_fields:read",
       "marketplace_custom_fields:read:admin",
       "marketplace:read:custom_fields:admin",
       "marketplace:read:custom_fields"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "marketplace_custom_fields:read",
      "marketplace_custom_fields:read:admin"
     ],
     "x-granular-scopes": [
      "marketplace:read:custom_fields:admin",
      "marketplace:read:custom_fields"
     ]
    }
   }
  },
  "/marketplace/app/event_subscription": {
   "get": {
    "tags": [
     "App"
    ],
    "summary": "Get user or account event subscription",
    "description": "Returns event subscriptions for users or accounts.\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "getUserEventSubscriptions",
    "security": [
     {
      "openapi_oauth": [],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": []
    }
   },
   "post": {
    "tags": [
     "App"
    ],
    "summary": "Create an event subscription",
    "description": "Create an event subscription.\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "createEventSubscription",
    "security": [
     {
      "openapi_oauth": [],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": []
    }
   },
   "delete": {
    "tags": [
     "App"
    ],
    "summary": "Unsubscribe app event subscription",
    "description": "Unsubscribe an event subscription.\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "unSubscribeEventSubscription",
    "security": [
     {
      "openapi_oauth": [],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": []
    }
   }
  },
  "/marketplace/app/event_subscription/{eventSubscriptionId}": {
   "delete": {
    "tags": [
     "App"
    ],
    "summary": "Delete an event subscription",
    "description": "Delete an event subscription.\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "deleteEventSubscription",
    "security": [
     {
      "openapi_oauth": [],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": []
    }
   },
   "patch": {
    "tags": [
     "App"
    ],
    "summary": "Subscribe an event subscription",
    "description": "Subscribe to an event subscription.\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "subscribeEventSubscription",
    "security": [
     {
      "openapi_oauth": [],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": []
    }
   }
  },
  "/marketplace/apps": {
   "get": {
    "tags": [
     "App"
    ],
    "summary": "List apps",
    "description": "List all active and past app requests, or list all approved public and private apps. \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace_app:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace:read:list_apps:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "ListApps",
    "security": [
     {
      "openapi_oauth": [
       "marketplace_app:read:admin",
       "marketplace:read:list_apps:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "MarketPlace:Read"
     ],
     "x-macro-scopes": [
      "marketplace_app:read:admin"
     ],
     "x-granular-scopes": [
      "marketplace:read:list_apps:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "App"
    ],
    "summary": "Create apps",
    "description": "Create `Server to Server OAuth`, `Meeting SDK` or `General` apps in the Zoom Marketplace. \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace_app:write`,`marketplace_app:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace:write:app`,`marketplace:write:app:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `[...]",
    "operationId": "CreateApps",
    "security": [
     {
      "openapi_oauth": [
       "marketplace_app:write",
       "marketplace_app:write:admin",
       "marketplace:write:app",
       "marketplace:write:app:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "marketplace_app:write",
      "marketplace_app:write:admin"
     ],
     "x-granular-scopes": [
      "marketplace:write:app",
      "marketplace:write:app:admin"
     ]
    }
   }
  },
  "/marketplace/apps/{appId}": {
   "get": {
    "tags": [
     "App"
    ],
    "summary": "Get information about an app",
    "description": "Use this API to get app information. \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace_app:read:admin`,`marketplace_app:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace:read:app`,`marketplace:read:app:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "getAppInfo",
    "security": [
     {
      "openapi_oauth": [
       "marketplace_app:read:admin",
       "marketplace_app:read",
       "marketplace:read:app",
       "marketplace:read:app:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "MarketPlace:Read"
     ],
     "x-macro-scopes": [
      "marketplace_app:read:admin",
      "marketplace_app:read"
     ],
     "x-granular-scopes": [
      "marketplace:read:app",
      "marketplace:read:app:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "App"
    ],
    "summary": "Deletes an app",
    "description": "Permanently delete an app on behalf of a user.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace_app:write`,`marketplace_app:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace:write:app`,`marketplace:write:app:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "deleteApp",
    "security": [
     {
      "openapi_oauth": [
       "marketplace_app:write",
       "marketplace_app:write:admin",
       "marketplace:write:app",
       "marketplace:write:app:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "marketplace_app:write",
      "marketplace_app:write:admin"
     ],
     "x-granular-scopes": [
      "marketplace:write:app",
      "marketplace:write:app:admin"
     ]
    }
   }
  },
  "/marketplace/apps/{appId}/api_call_logs": {
   "get": {
    "tags": [
     "App"
    ],
    "summary": "Get API call logs",
    "description": "Get log of app's API calls.\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace:read:list_api_logs:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "Getapicalllogs",
    "security": [
     {
      "openapi_oauth": [
       "marketplace:read:list_api_logs:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "MarketPlace:Edit"
     ],
     "x-granular-scopes": [
      "marketplace:read:list_api_logs:admin"
     ]
    }
   }
  },
  "/marketplace/apps/{appId}/deeplink": {
   "post": {
    "tags": [
     "App"
    ],
    "summary": "Generate Zoom App Deeplink",
    "description": "Create a Zoom App Deeplink.\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace_app:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace:write:app_deeplink:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "GenerateZoomAppDeeplink",
    "security": [
     {
      "openapi_oauth": [
       "marketplace_app:write:admin",
       "marketplace:write:app_deeplink:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "marketplace_app:write:admin"
     ],
     "x-granular-scopes": [
      "marketplace:write:app_deeplink:admin"
     ]
    }
   }
  },
  "/marketplace/apps/{appId}/preApprove": {
   "post": {
    "tags": [
     "App"
    ],
    "summary": "Update app pre approval setting ",
    "description": "This API supports modifying the pre approval configuration of the app, including turning on the setting  to the  account, to specified users, to specified user groups, and turning off the pre approval.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace_app:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace:write:app_pre_approve:admin`\n\n**[Rate Limit Label](h[...]",
    "operationId": "Updateapppreapprovalsetting",
    "security": [
     {
      "openapi_oauth": [
       "marketplace_app:write:admin",
       "marketplace:write:app_pre_approve:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "MarketPlace:Edit"
     ],
     "x-macro-scopes": [
      "marketplace_app:write:admin"
     ],
     "x-granular-scopes": [
      "marketplace:write:app_pre_approve:admin"
     ]
    }
   }
  },
  "/marketplace/apps/{appId}/requests": {
   "get": {
    "tags": [
     "App"
    ],
    "summary": "Get an app's user requests",
    "description": "Use this API to get an app's user requests and the status of their approval. \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace_app:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace:read:app_request:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "getAppUserRequests",
    "security": [
     {
      "openapi_oauth": [
       "marketplace_app:read:admin",
       "marketplace:read:app_request:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "MarketPlace:Read"
     ],
     "x-macro-scopes": [
      "marketplace_app:read:admin"
     ],
     "x-granular-scopes": [
      "marketplace:read:app_request:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "App"
    ],
    "summary": "Add app allow requests for users",
    "description": "Use this API to add app allow requests for all users, groups of users, or specific users. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace_app:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace:write:app_request:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "AddAppAllowRequestsForUsers",
    "security": [
     {
      "openapi_oauth": [
       "marketplace_app:write:admin",
       "marketplace:write:app_request:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "MarketPlace:Edit"
     ],
     "x-macro-scopes": [
      "marketplace_app:write:admin"
     ],
     "x-granular-scopes": [
      "marketplace:write:app_request:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "App"
    ],
    "summary": "Update app's request status",
    "description": "Use this API to update an app's request status or update app status. Administrators can only agree to user-level apps.\n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace_app:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace:update:app_request:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`[...]",
    "operationId": "updateAppRequestStatus",
    "security": [
     {
      "openapi_oauth": [
       "marketplace_app:write:admin",
       "marketplace:update:app_request:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "MarketPlace:Edit"
     ],
     "x-macro-scopes": [
      "marketplace_app:write:admin"
     ],
     "x-granular-scopes": [
      "marketplace:update:app_request:admin"
     ]
    }
   }
  },
  "/marketplace/apps/{appId}/rotate_client_secret": {
   "post": {
    "tags": [
     "App"
    ],
    "summary": "Rotate client secret",
    "description": "Create or update a marketplace application's client secret rotating schedule. \nTo call this API, users need to use an OAuth token. The token's `grant_type` should be `client_credentials`. \nUsers can only change client secret rotate schedule 3 times in 15 minutes.\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace:update:client_secret`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#r[...]",
    "operationId": "RotateClientSecret",
    "security": [
     {
      "openapi_oauth": [
       "marketplace:update:client_secret"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-granular-scopes": [
      "marketplace:update:client_secret"
     ]
    }
   }
  },
  "/marketplace/apps/{appId}/webhook_logs": {
   "get": {
    "tags": [
     "App"
    ],
    "summary": "Get webhook logs",
    "description": "Get users' webhook call logs and query records from the past 7 days. \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace_app:read`,`marketplace_app:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "getWebhookLogs",
    "security": [
     {
      "openapi_oauth": [
       "marketplace_app:read",
       "marketplace_app:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "MarketPlace:Read"
     ],
     "x-macro-scopes": [
      "marketplace_app:read",
      "marketplace_app:read:admin"
     ]
    }
   }
  },
  "/marketplace/monetization/entitlements": {
   "get": {
    "tags": [
     "App"
    ],
    "summary": "Get app user entitlements",
    "description": "Get the app user's entitlements information.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace_entitlement:read:admin`,`marketplace_entitlement:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace:read:list_user_entitlements`,`marketplace:read:list_user_entitlements:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):[...]",
    "operationId": "getAppUserEntitlementRequests",
    "security": [
     {
      "openapi_oauth": [
       "marketplace_entitlement:read:admin",
       "marketplace_entitlement:read",
       "marketplace:read:list_user_entitlements",
       "marketplace:read:list_user_entitlements:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "Marketplace:Edit"
     ],
     "x-macro-scopes": [
      "marketplace_entitlement:read:admin",
      "marketplace_entitlement:read"
     ],
     "x-granular-scopes": [
      "marketplace:read:list_user_entitlements",
      "marketplace:read:list_user_entitlements:admin"
     ]
    }
   }
  },
  "/marketplace/users/{userId}/apps": {
   "get": {
    "tags": [
     "App"
    ],
    "summary": "Get a user's app requests",
    "description": "Use this API to get all of a user's app requests. \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace_app:read:admin`,`marketplace_app:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace:read:list_user_app_requests:admin`,`marketplace:read:list_user_app_requests`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `ME[...]",
    "operationId": "getUserAppRequests",
    "security": [
     {
      "openapi_oauth": [
       "marketplace_app:read:admin",
       "marketplace_app:read",
       "marketplace:read:list_user_app_requests:admin",
       "marketplace:read:list_user_app_requests"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "MarketPlace:Read"
     ],
     "x-macro-scopes": [
      "marketplace_app:read:admin",
      "marketplace_app:read"
     ],
     "x-granular-scopes": [
      "marketplace:read:list_user_app_requests:admin",
      "marketplace:read:list_user_app_requests"
     ]
    }
   }
  },
  "/marketplace/users/{userId}/apps/{appId}/subscription": {
   "patch": {
    "tags": [
     "App"
    ],
    "summary": "Enable or disable user app subscription",
    "description": "Enable or disable a user's app subscription.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace_app:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace:write:app:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "Enable/Disableuserappsubscription",
    "security": [
     {
      "openapi_oauth": [
       "marketplace_app:write:admin",
       "marketplace:write:app:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "MarketPlace:Edit"
     ],
     "x-macro-scopes": [
      "marketplace_app:write:admin"
     ],
     "x-granular-scopes": [
      "marketplace:write:app:admin"
     ]
    }
   }
  },
  "/marketplace/users/{userId}/entitlements": {
   "get": {
    "tags": [
     "App"
    ],
    "summary": "Get a user's entitlements",
    "description": "Get a user's entitlements. \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace_entitlement:read`,`marketplace_entitlement:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace:read:list_user_entitlements`,`marketplace:read:list_user_entitlements:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "getUserEntitlementRequests",
    "security": [
     {
      "openapi_oauth": [
       "marketplace_entitlement:read",
       "marketplace_entitlement:read:admin",
       "marketplace:read:list_user_entitlements",
       "marketplace:read:list_user_entitlements:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "MarketPlace:Edit"
     ],
     "x-macro-scopes": [
      "marketplace_entitlement:read",
      "marketplace_entitlement:read:admin"
     ],
     "x-granular-scopes": [
      "marketplace:read:list_user_entitlements",
      "marketplace:read:list_user_entitlements:admin"
     ]
    }
   }
  },
  "/zoomapp/deeplink": {
   "post": {
    "tags": [
     "Apps"
    ],
    "summary": "Generate an app deeplink",
    "description": "Create an app deeplink. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `app:deeplink:write`,`app:deeplink:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "generateAppDeeplink",
    "security": [
     {
      "openapi_oauth": [
       "app:deeplink:write",
       "app:deeplink:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-macro-scopes": [
      "app:deeplink:write",
      "app:deeplink:write:admin"
     ]
    }
   }
  },
  "/marketplace/apps/manifest/validate": {
   "post": {
    "tags": [
     "Manifest"
    ],
    "summary": "Validate an app manifest",
    "description": "Validates an app manifest.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace_app:read`,`marketplace_app:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace:read:app`,`marketplace:read:app:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "validatingManifest",
    "security": [
     {
      "openapi_oauth": [
       "marketplace_app:read",
       "marketplace_app:read:admin",
       "marketplace:read:app",
       "marketplace:read:app:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "MarketPlace:Read"
     ],
     "x-macro-scopes": [
      "marketplace_app:read",
      "marketplace_app:read:admin"
     ],
     "x-granular-scopes": [
      "marketplace:read:app",
      "marketplace:read:app:admin"
     ]
    }
   }
  },
  "/marketplace/apps/{appId}/manifest": {
   "get": {
    "tags": [
     "Manifest"
    ],
    "summary": "Export an app manifest from an existing app",
    "description": "Exports an app's manifest file.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace_app:read`,`marketplace_app:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace:read:app`,`marketplace:read:app:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "getAppManifest",
    "security": [
     {
      "openapi_oauth": [
       "marketplace_app:read",
       "marketplace_app:read:admin",
       "marketplace:read:app",
       "marketplace:read:app:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "marketplace_app:read",
      "marketplace_app:read:admin"
     ],
     "x-granular-scopes": [
      "marketplace:read:app",
      "marketplace:read:app:admin"
     ]
    }
   },
   "put": {
    "tags": [
     "Manifest"
    ],
    "summary": "Update an app by manifest",
    "description": "Updates an app from an app manifest\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace_app:write`,`marketplace_app:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `marketplace:write:app`,`marketplace:write:app:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "updateAppByManifest",
    "security": [
     {
      "openapi_oauth": [
       "marketplace_app:write",
       "marketplace_app:write:admin",
       "marketplace:write:app",
       "marketplace:write:app:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "marketplace_app:write",
      "marketplace_app:write:admin"
     ],
     "x-granular-scopes": [
      "marketplace:write:app",
      "marketplace:write:app:admin"
     ]
    }
   }
  }
 },
 "components": {
  "securitySchemes": {
   "openapi_authorization": {
    "type": "apiKey",
    "name": "Authorization",
    "in": "header"
   },
   "openapi_oauth": {
    "type": "oauth2",
    "flows": {
     "authorizationCode": {
      "authorizationUrl": "/",
      "tokenUrl": "",
      "refreshUrl": "",
      "scopes": {
       "app:notification:read": "app:notification:read",
       "app:notification:write": "app:notification:write",
       "marketplace:write:notifications": "marketplace:write:notifications",
       "marketplace_custom_fields:read": "marketplace_custom_fields:read",
       "marketplace_custom_fields:read:admin": "marketplace_custom_fields:read:admin",
       "marketplace:read:custom_fields:admin": "marketplace:read:custom_fields:admin",
       "marketplace:read:custom_fields": "marketplace:read:custom_fields",
       "marketplace_app:write": "marketplace_app:write",
       "marketplace_app:write:admin": "marketplace_app:write:admin",
       "marketplace:write:app": "marketplace:write:app",
       "marketplace:write:app:admin": "marketplace:write:app:admin",
       "marketplace_app:read:admin": "marketplace_app:read:admin",
       "marketplace:read:list_apps:admin": "marketplace:read:list_apps:admin",
       "marketplace_app:read": "marketplace_app:read",
       "marketplace:read:app": "marketplace:read:app",
       "marketplace:read:app:admin": "marketplace:read:app:admin",
       "marketplace:read:list_api_logs:admin": "marketplace:read:list_api_logs:admin",
       "marketplace:write:app_deeplink:admin": "marketplace:write:app_deeplink:admin",
       "marketplace:write:app_pre_approve:admin": "marketplace:write:app_pre_approve:admin",
       "marketplace:read:app_request:admin": "marketplace:read:app_request:admin",
       "marketplace:write:app_request:admin": "marketplace:write:app_request:admin",
       "marketplace:update:app_request:admin": "marketplace:update:app_request:admin",
       "marketplace:update:client_secret": "marketplace:update:client_secret",
       "marketplace_entitlement:read:admin": "marketplace_entitlement:read:admin",
       "marketplace_entitlement:read": "marketplace_entitlement:read",
       "marketplace:read:list_user_entitlements": "marketplace:read:list_user_entitlements",
       "marketplace:read:list_user_entitlements:admin": "marketplace:read:list_user_entitlements:admin",
       "marketplace:read:list_user_app_requests:admin": "marketplace:read:list_user_app_requests:admin",
       "marketplace:read:list_user_app_requests": "marketplace:read:list_user_app_requests",
       "app:deeplink:write": "app:deeplink:write",
       "app:deeplink:write:admin": "app:deeplink:write:admin"
      }
     }
    }
   }
  }
 }
}