{
 "openapi": "3.0.0",
 "info": {
  "title": "Number Management",
  "description": "Number Management APIs are part of Zoom's API suite. They let developers manage and provision phone numbers in a Zoom Phone, Contact Center, or Meetings account programmatically. They also help businesses and service providers automate phone number operations at scale.",
  "termsOfService": "https://zoom.us/docs/en-us/zoom_api_license_and_tou.html",
  "contact": {
   "name": "Zoom Developers",
   "url": "https://developer.zoom.us/"
  },
  "version": "2"
 },
 "servers": [
  {
   "url": "https://api.zoom.us/v2"
  }
 ],
 "paths": {
  "/number_management/carrier/peering_numbers": {
   "get": {
    "tags": [
     "Cloud Peering Provider Exchange"
    ],
    "summary": "List peering phone numbers for provider",
    "description": "Returns phone numbers the carrier pushes to different customers.\n\n**Prerequisites** \n* [Enable Number Management](https://zoom.us/cpw/page/phoneNumbers#/number-list)\n* Developer is a provider exchange partner, with the cloud peering infrastructure established with Zoom.\n* Zoom account needs to have a Zoom Phone license or a Zoom Contact Center license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `number_management_numbers:read:ad[...]",
    "operationId": "Listpeeringphonenumbersforprovider",
    "security": [
     {
      "openapi_oauth": [
       "number_management_numbers:read:admin",
       "number_management:read:list_carrier_peering_numbers:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ProviderPortal:Read"
     ],
     "x-macro-scopes": [
      "number_management_numbers:read:admin"
     ],
     "x-granular-scopes": [
      "number_management:read:list_carrier_peering_numbers:admin"
     ]
    }
   }
  },
  "/number_management/peering_numbers": {
   "get": {
    "tags": [
     "Cloud Peering Provider Exchange"
    ],
    "summary": "List peering phone numbers",
    "description": "Returns the details associated with a specific phone number, or all the phone numbers the partner previously provisioned for the Zoom customer account.\n\n**Prerequisites:** \n* [Enable Number Management](https://zoom.us/cpw/page/phoneNumbers#/number-list)\n* Developer is a provider exchange partner, with the cloud peering infrastructure established with Zoom.\n* Zoom account needs to have a Zoom Phone license or a Zoom Contact Center license. \n\n**[Scopes](https://developer[...]",
    "operationId": "listPeeringPhoneNumbers",
    "security": [
     {
      "openapi_oauth": [
       "number_management_numbers:read:admin",
       "number_management:read:list_peering_numbers:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "PbxAdmin:Read",
      "ContactCenterMgt:Edit"
     ],
     "x-macro-scopes": [
      "number_management_numbers:read:admin"
     ],
     "x-granular-scopes": [
      "number_management:read:list_peering_numbers:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Cloud Peering Provider Exchange"
    ],
    "summary": "Add peering phone numbers",
    "description": "Allows provider exchange partners to add phone numbers to Zoom account. \n\n**Prerequisites** \n* [Enable Number Management](https://zoom.us/cpw/page/phoneNumbers#/number-list)\n* Developer is a provider exchange partner, with the cloud peering infrastructure established with Zoom.\n* Zoom account needs to have a Zoom Phone license or a Zoom Contact Center license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `number_management_numbers[...]",
    "operationId": "addPeeringPhoneNumbers",
    "security": [
     {
      "openapi_oauth": [
       "number_management_numbers:write:admin",
       "number_management:write:peering_number:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "PbxAdmin:Edit",
      "ContactCenterMgt:Edit"
     ],
     "x-macro-scopes": [
      "number_management_numbers:write:admin"
     ],
     "x-granular-scopes": [
      "number_management:write:peering_number:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Cloud Peering Provider Exchange"
    ],
    "summary": "Remove peering phone numbers",
    "description": "Removes the phone number from the Zoom customer account. \n\nPartners can remove only the phone numbers they have previously added to Zoom account.\n\n**Prerequisites:** \n* [Enable Number Management](https://zoom.us/cpw/page/phoneNumbers#/number-list)\n* Developer is a provider exchange partner, with the cloud peering infrastructure established with Zoom.\n* Zoom account needs to have a Zoom Phone license or a Zoom Contact Center license. \n\n**[Scopes](https://developers.zo[...]",
    "operationId": "deletePeeringPhoneNumbers",
    "security": [
     {
      "openapi_oauth": [
       "number_management_numbers:write:admin",
       "number_management:delete:peering_number:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ContactCenterMgt:Edit",
      "PbxAdmin:Edit"
     ],
     "x-macro-scopes": [
      "number_management_numbers:write:admin"
     ],
     "x-granular-scopes": [
      "number_management:delete:peering_number:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Cloud Peering Provider Exchange"
    ],
    "summary": "Update peering phone numbers",
    "description": "Allows partners to update the status or details associated with the phone numbers.\n\n**Prerequisites** \n* [Enable Number Management](https://zoom.us/cpw/page/phoneNumbers#/number-list)\n* Developer is a provider exchange partner, with the cloud peering infrastructure established with Zoom.\n* Zoom account needs to have a Zoom Phone license or a Zoom Contact Center license. \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `number_manag[...]",
    "operationId": "updatePeeringPhoneNumbers",
    "security": [
     {
      "openapi_oauth": [
       "number_management_numbers:write:admin",
       "number_management:update:peering_number:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ContactCenterMgt:Edit",
      "PbxAdmin:Edit"
     ],
     "x-macro-scopes": [
      "number_management_numbers:write:admin"
     ],
     "x-granular-scopes": [
      "number_management:update:peering_number:admin"
     ]
    }
   }
  },
  "/number_management/allocation": {
   "patch": {
    "tags": [
     "Phone Numbers"
    ],
    "summary": "Allocate/Unallocate phone numbers",
    "description": "Allocates or unallocates phone numbers for those with CPL routing.\n\n<p>Note: When allocating phone numbers, if there are any native numbers, they must belong to the same country or region, and have the same number plan.</p>\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `number_management_numbers:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `number_management:write:numbers:[...]",
    "operationId": "AllocateNumber",
    "security": [
     {
      "openapi_oauth": [
       "number_management_numbers:write:admin",
       "number_management:write:numbers:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "PbxAdmin:Edit",
      "ContactCenterMgt:Edit"
     ],
     "x-macro-scopes": [
      "number_management_numbers:write:admin"
     ],
     "x-granular-scopes": [
      "number_management:write:numbers:admin"
     ]
    }
   }
  },
  "/number_management/byoc_numbers": {
   "post": {
    "tags": [
     "Phone Numbers"
    ],
    "summary": "Add BYOC phone numbers",
    "description": "Adds BYOC (Bring Your Own Carrier) phone numbers to Zoom Phone.\n\n**Prerequisites:** \n* A Business or Enterprise plan \n* A Zoom Phone license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `number_management_numbers:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `number_management:write:byoc_numbers:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-referenc[...]",
    "operationId": "AddBYOCPhoneNumber",
    "security": [
     {
      "openapi_oauth": [
       "number_management_numbers:write:admin",
       "number_management:write:byoc_numbers:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "PbxAdmin:Edit",
      "ContactCenterMgt:Edit"
     ],
     "x-macro-scopes": [
      "number_management_numbers:write:admin"
     ],
     "x-granular-scopes": [
      "number_management:write:byoc_numbers:admin"
     ]
    }
   }
  },
  "/number_management/numbers": {
   "get": {
    "tags": [
     "Phone Numbers"
    ],
    "summary": "List phone numbers",
    "description": "Returns a list of phone numbers in an account. See section <b>Information in the phone number table</b> of [Using Number Management for managing phone numbers](https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0074457#h_60222313850311712763891581) for more details.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `number_management_numbers:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth[...]",
    "operationId": "listPhoneNumbers",
    "security": [
     {
      "openapi_oauth": [
       "number_management_numbers:read:admin",
       "number_management:read:list_numbers:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ContactCenterMgt:Edit",
      "PbxAdmin:Read"
     ],
     "x-macro-scopes": [
      "number_management_numbers:read:admin"
     ],
     "x-granular-scopes": [
      "number_management:read:list_numbers:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Phone Numbers"
    ],
    "summary": "Delete phone numbers",
    "description": "Deletes phone numbers.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `number_management_numbers:write:master`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `number_management:delete:numbers:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "DeleteNumbers",
    "security": [
     {
      "openapi_oauth": [
       "number_management_numbers:write:master",
       "number_management:delete:numbers:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "PbxAdmin:Edit",
      "ContactCenterMgt:Edit"
     ],
     "x-macro-scopes": [
      "number_management_numbers:write:master"
     ],
     "x-granular-scopes": [
      "number_management:delete:numbers:admin"
     ]
    }
   }
  },
  "/number_management/numbers/{phoneNumberId}": {
   "get": {
    "tags": [
     "Phone Numbers"
    ],
    "summary": "Get a phone number",
    "description": "Returns information about an account's phone number. \n\nFor more details, see the section <b>Information in the phone number table</b> in [Using Number Management for managing phone numbers](https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0074457#h_60222313850311712763891581).\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `number_management_numbers:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/int[...]",
    "operationId": "getPhoneNumber",
    "security": [
     {
      "openapi_oauth": [
       "number_management_numbers:read:admin",
       "number_management:read:numbers:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ContactCenterMgt:Edit",
      "PbxAdmin:Read"
     ],
     "x-macro-scopes": [
      "number_management_numbers:read:admin"
     ],
     "x-granular-scopes": [
      "number_management:read:numbers:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Phone Numbers"
    ],
    "summary": "Update a phone number",
    "description": "Updates a phone number's information.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `number_management_numbers:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `number_management:update:numbers:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "updatePhoneNumberDetail",
    "security": [
     {
      "openapi_oauth": [
       "number_management_numbers:write:admin",
       "number_management:update:numbers:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "PbxAdmin:Edit",
      "ContactCenterMgt:Edit"
     ],
     "x-macro-scopes": [
      "number_management_numbers:write:admin"
     ],
     "x-granular-scopes": [
      "number_management:update:numbers:admin"
     ]
    }
   }
  },
  "/number_management/plan": {
   "get": {
    "tags": [
     "Phone Plan"
    ],
    "summary": "List phone number plan information",
    "description": "Retrieves an account's  phone number plan information, phone number usage, and availability.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `number_management_numbers:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `number_management:read:numbers_plan:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "Listphonenumberplaninformation",
    "security": [
     {
      "openapi_oauth": [
       "number_management_numbers:read:admin",
       "number_management:read:numbers_plan:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "PbxAdmin:Read",
      "ContactCenterMgt:Edit"
     ],
     "x-macro-scopes": [
      "number_management_numbers:read:admin"
     ],
     "x-granular-scopes": [
      "number_management:read:numbers_plan:admin"
     ]
    }
   }
  },
  "/number_management/sms_campaigns": {
   "get": {
    "tags": [
     "SMS Campaigns"
    ],
    "summary": "List SMS campaigns",
    "description": "Returns a list of all SMS campaigns in a Zoom account.\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `number_management_numbers:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `number_management:read:list_sms_campaigns:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "listAccountSMSCampaigns",
    "security": [
     {
      "openapi_oauth": [
       "number_management_numbers:read:admin",
       "number_management:read:list_sms_campaigns:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "SmsCampaigns:Read"
     ],
     "x-macro-scopes": [
      "number_management_numbers:read:admin"
     ],
     "x-granular-scopes": [
      "number_management:read:list_sms_campaigns:admin"
     ]
    }
   }
  },
  "/number_management/sms_campaigns/{smsCampaignId}": {
   "get": {
    "tags": [
     "SMS Campaigns"
    ],
    "summary": "Get an SMS campaign",
    "description": "Returns a specific SMS campaign.\n\n**Prerequisites** \n* A Pro or higher account plan \n* A Zoom Phone license\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `number_management_numbers:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `number_management:read:sms_campaign:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `[...]",
    "operationId": "GetSMSCampaign",
    "security": [
     {
      "openapi_oauth": [
       "number_management_numbers:read:admin",
       "number_management:read:sms_campaign:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "SmsCampaigns:Read"
     ],
     "x-macro-scopes": [
      "number_management_numbers:read:admin"
     ],
     "x-granular-scopes": [
      "number_management:read:sms_campaign:admin"
     ]
    }
   }
  },
  "/number_management/sms_campaigns/{smsCampaignId}/phone_numbers": {
   "post": {
    "tags": [
     "SMS Campaigns"
    ],
    "summary": "Assign a phone number to SMS campaign",
    "description": "[Assigns a phone number to the SMS campaign](https://support.zoom.us/hc/en-us/articles/5016496738445-SMS-MMS-10DLC-Compliance-for-Zoom-Phone-and-Zoom-Contact-Center#h_01FYVVQM1WMW5JD48YNY3J581B).\n\n**Prerequisites** \n* A Business or Enterprise account \n* A Zoom Phone license\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `number_management_numbers:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oau[...]",
    "operationId": "assignCampaignPhoneNumbers",
    "security": [
     {
      "openapi_oauth": [
       "number_management_numbers:write:admin",
       "number_management:update:numbers:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "PbxAdmin:Edit",
      "ContactCenterMgt:Edit"
     ],
     "x-macro-scopes": [
      "number_management_numbers:write:admin"
     ],
     "x-granular-scopes": [
      "number_management:update:numbers:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "SMS Campaigns"
    ],
    "summary": "Unassign phone number from SMS campaign",
    "description": "[Unassigns a phone number from an SMS campaign](https://support.zoom.us/hc/en-us/articles/5016496738445-SMS-MMS-10DLC-Compliance-for-Zoom-Phone-and-Zoom-Contact-Center#h_01FYVVSPVM8MZN4Y9EW5690QHH).\n\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license \n* The campaign must have been previously assigned a Zoom Phone number\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `number_management_numbers:write:[...]",
    "operationId": "unassignCampaignPhoneNumber",
    "security": [
     {
      "openapi_oauth": [
       "number_management_numbers:write:admin",
       "number_management:update:numbers:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "PbxAdmin:Edit",
      "ContactCenterMgt:Edit"
     ],
     "x-macro-scopes": [
      "number_management_numbers:write:admin"
     ],
     "x-granular-scopes": [
      "number_management:update:numbers:admin"
     ]
    }
   }
  },
  "/number_management/ported_numbers/orders": {
   "get": {
    "tags": [
     "Setting"
    ],
    "summary": "List ported numbers",
    "description": "Returns a list of ported numbers in a Zoom account.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `number_management_numbers:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `number_management:read:list_ported_numbers:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "Listportednumbers",
    "security": [
     {
      "openapi_oauth": [
       "number_management_numbers:read:admin",
       "number_management:read:list_ported_numbers:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "PbxAdmin:Read",
      "ContactCenterMgt:Edit"
     ],
     "x-macro-scopes": [
      "number_management_numbers:read:admin"
     ],
     "x-granular-scopes": [
      "number_management:read:list_ported_numbers:admin"
     ]
    }
   }
  },
  "/number_management/ported_numbers/orders/{orderId}": {
   "get": {
    "tags": [
     "Setting"
    ],
    "summary": "Get ported numbers details",
    "description": "Returns the details on the ported numbers by specifying `order_id`. \n\n **Prerequisites** \n * A Pro or higher account plan \n * A Zoom phone license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `number_management_numbers:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `number_management:read:ported_number:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-ref[...]",
    "operationId": "Getportednumbersdetails",
    "security": [
     {
      "openapi_oauth": [
       "number_management_numbers:read:admin",
       "number_management:read:ported_number:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "PbxAdmin:Read",
      "ContactCenterMgt:Edit"
     ],
     "x-macro-scopes": [
      "number_management_numbers:read:admin"
     ],
     "x-granular-scopes": [
      "number_management:read:ported_number:admin"
     ]
    }
   }
  },
  "/number_management/sip_groups": {
   "get": {
    "tags": [
     "Setting"
    ],
    "summary": "List SIP groups",
    "description": "Returns a list of SIP (Session Initiation Protocol) groups.\n\n**Prerequisites** \n* Pro or a higher account with Zoom Phone license\n* Account owner or admin permissions\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `number_management_numbers:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `number_management:read:list_sip_groups:admin`\n\n**[Rate Limit Label](https://marketplac[...]",
    "operationId": "ListSIPgroups",
    "security": [
     {
      "openapi_oauth": [
       "number_management_numbers:read:admin",
       "number_management:read:list_sip_groups:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "PbxAdmin:Read",
      "ContactCenterMgt:Edit"
     ],
     "x-macro-scopes": [
      "number_management_numbers:read:admin"
     ],
     "x-granular-scopes": [
      "number_management:read:list_sip_groups:admin"
     ]
    }
   }
  },
  "/number_management/sip_trunks": {
   "get": {
    "tags": [
     "Setting"
    ],
    "summary": "List BYOC SIP trunks",
    "description": "Returns a list of an account's assigned BYOC (Bring Your Own Carrier) SIP (Session Initiation Protocol) trunks.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `number_management_numbers:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `number_management:read:list_sip_trunks:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `L[...]",
    "operationId": "ListBYOCSIPtrunks",
    "security": [
     {
      "openapi_oauth": [
       "number_management_numbers:read:admin",
       "number_management:read:list_sip_trunks:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "PbxAdmin:Read",
      "ContactCenterMgt:Edit"
     ],
     "x-macro-scopes": [
      "number_management_numbers:read:admin"
     ],
     "x-granular-scopes": [
      "number_management:read:list_sip_trunks:admin"
     ]
    }
   }
  }
 },
 "components": {
  "securitySchemes": {
   "openapi_authorization": {
    "type": "apiKey",
    "name": "Authorization",
    "in": "header"
   },
   "openapi_oauth": {
    "type": "oauth2",
    "flows": {
     "authorizationCode": {
      "authorizationUrl": "/",
      "tokenUrl": "",
      "refreshUrl": "",
      "scopes": {
       "number_management_numbers:read:admin": "number_management_numbers:read:admin",
       "number_management:read:list_carrier_peering_numbers:admin": "number_management:read:list_carrier_peering_numbers:admin",
       "number_management:read:list_peering_numbers:admin": "number_management:read:list_peering_numbers:admin",
       "number_management_numbers:write:admin": "number_management_numbers:write:admin",
       "number_management:delete:peering_number:admin": "number_management:delete:peering_number:admin",
       "number_management:write:peering_number:admin": "number_management:write:peering_number:admin",
       "number_management:update:peering_number:admin": "number_management:update:peering_number:admin",
       "number_management:write:numbers:admin": "number_management:write:numbers:admin",
       "number_management:write:byoc_numbers:admin": "number_management:write:byoc_numbers:admin",
       "number_management:read:list_numbers:admin": "number_management:read:list_numbers:admin",
       "number_management_numbers:write:master": "number_management_numbers:write:master",
       "number_management:delete:numbers:admin": "number_management:delete:numbers:admin",
       "number_management:read:numbers:admin": "number_management:read:numbers:admin",
       "number_management:update:numbers:admin": "number_management:update:numbers:admin",
       "number_management:read:numbers_plan:admin": "number_management:read:numbers_plan:admin",
       "number_management:read:list_sms_campaigns:admin": "number_management:read:list_sms_campaigns:admin",
       "number_management:read:sms_campaign:admin": "number_management:read:sms_campaign:admin",
       "number_management:read:list_ported_numbers:admin": "number_management:read:list_ported_numbers:admin",
       "number_management:read:ported_number:admin": "number_management:read:ported_number:admin",
       "number_management:read:list_sip_groups:admin": "number_management:read:list_sip_groups:admin",
       "number_management:read:list_sip_trunks:admin": "number_management:read:list_sip_trunks:admin"
      }
     }
    }
   }
  }
 }
}