{
  "source": "phone",
  "sourceUrl": "https://developers.zoom.us/api-hub/phone/methods/endpoints.json",
  "downloadedAt": "2025-12-12T01:50:09.1786484Z",
  "specVersion": "3.0.0",
  "spec": {
    "openapi": "3.0.0",
    "info": {
      "title": "Phone",
      "description": "You can access information from Zoom with Zoom Phone APIs to build private services or public applications on the [Zoom App Marketplace](https://marketplace.zoom.us/).\n\n  To learn how to get your credentials and create private or public applications, see Zoom APIs use [OAuth 2.0 authorization](https://developers.zoom.us/docs/integrations/oauth/). \n\n  All endpoints are available through `https` at `api.zoom.us/v2/`. For instance, `https://api.zoom.us/v2/users/` returns a[...]",
      "termsOfService": "https://zoom.us/docs/en-us/zoom_api_license_and_tou.html",
      "contact": {
        "name": "Zoom Developers",
        "url": "https://developer.zoom.us/"
      },
      "version": "2"
    },
    "servers": [
      {
        "url": "https://api.zoom.us/v2"
      }
    ],
    "paths": {
      "/phone/account_settings": {
        "get": {
          "tags": [
            "Accounts"
          ],
          "summary": "List an account's Zoom phone settings",
          "description": "Returns an account's Zoom phone settings.\n\n**Prerequisites:**\n* A Business or Enterprise account \n* A Zoom Phone license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:list_account_settings:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
          "operationId": "listZoomPhoneAccountSettings",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:list_account_settings:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:list_account_settings:admin"
            ]
          }
        }
      },
      "/phone/outbound_caller_id/customized_numbers": {
        "get": {
          "tags": [
            "Accounts"
          ],
          "summary": "List an account's customized outbound caller ID phone numbers",
          "description": "Retrieves phone numbers that can be used as the `account-level` customized outbound caller ID. Note that when multiple sites policy is enabled, users cannot manage the `account-level` configuration. The system will throw an exception. \n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license.\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zo[...]",
          "operationId": "listCustomizeOutboundCallerNumbers",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:list_customized_number:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:list_customized_number:admin"
            ]
          }
        },
        "post": {
          "tags": [
            "Accounts"
          ],
          "summary": "Add phone numbers for an account's customized outbound caller ID",
          "description": "Adds the `account-level` customized outbound caller ID phone numbers. Note that when multiple sites policy is enabled, users cannot manage the `account-level` configuration. The system will throw an exception.\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license.\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/o[...]",
          "operationId": "addOutboundCallerNumbers",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:write:customized_number:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:write:customized_number:admin"
            ]
          }
        },
        "delete": {
          "tags": [
            "Accounts"
          ],
          "summary": "Delete phone numbers for an account's customized outbound caller ID",
          "description": "Deletes the `account-level` customized outbound caller ID phone numbers. Note that when multiple sites policy is enabled, users cannot manage the `account-level` configuration. The system will throw an exception.\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license.\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integration[...]",
          "operationId": "deleteOutboundCallerNumbers",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:delete:customized_number:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:delete:customized_number:admin"
            ]
          }
        }
      },
      "/phone/alert_settings": {
        "get": {
          "tags": [
            "Alerts"
          ],
          "summary": "List alert settings with paging query",
          "description": "Gets [alert settings](https://support.zoom.us/hc/en-us/articles/7146944434445) for an account with paging query.\n\n**Prerequisites**\n* Pro or a higher account with Zoom Phone license\n* Account owner or admin permissions\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:list_alert_settings:admin`\n\n**[Rate L[...]",
          "operationId": "ListAlertSettingsWithPagingQuery",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:list_alert_settings:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:list_alert_settings:admin"
            ]
          }
        },
        "post": {
          "tags": [
            "Alerts"
          ],
          "summary": "Add an alert setting",
          "description": "[Adds an alert setting](https://support.zoom.us/hc/en-us/articles/7146944434445).\n\n**Prerequisites:**  \n \n* Pro or a higher account with Zoom Phone license\n* Account owner or admin permissions\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:alert_setting:admin`\n\n**[Rate Limit Label](https://marketpla[...]",
          "operationId": "AddAnAlertSetting",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:write:alert_setting:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:write:alert_setting:admin"
            ]
          }
        }
      },
      "/phone/alert_settings/{alertSettingId}": {
        "get": {
          "tags": [
            "Alerts"
          ],
          "summary": "Get alert setting details",
          "description": "Returns detailed information about a specific [alert setting](https://support.zoom.us/hc/en-us/articles/7146944434445).\n\n**Prerequisites:**\n\n* Pro or a higher account with Zoom Phone license \n* Account owner or admin permissions\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:alert_setting:admin`\n\n**[R[...]",
          "operationId": "GetAlertSettingDetails",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:alert_setting:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:alert_setting:admin"
            ]
          }
        },
        "delete": {
          "tags": [
            "Alerts"
          ],
          "summary": "Delete an alert setting",
          "description": "Deletes an [alert setting](https://support.zoom.us/hc/en-us/articles/7146944434445).\n\n**Prerequisites:**\n* Pro or a higher account with Zoom Phone license\n* Account owner or admin permissions.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:delete:alert_setting:admin`\n\n**[Rate Limit Label](https://marketpla[...]",
          "operationId": "DeleteAnAlertSetting",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:delete:alert_setting:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:delete:alert_setting:admin"
            ]
          }
        },
        "patch": {
          "tags": [
            "Alerts"
          ],
          "summary": "Update an alert setting",
          "description": "Updates information of an [Alert setting](https://support.zoom.us/hc/en-us/articles/7146944434445).\n\n**Prerequisites:**  \n \n* Pro or a higher account with Zoom Phone license\n* Account owner or admin permissions\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:patch:alert_setting:admin`\n\n**[Rate Limit Label][...]",
          "operationId": "UpdateAnAlertSetting",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:patch:alert_setting:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:patch:alert_setting:admin"
            ]
          }
        }
      },
      "/phone/audios/{audioId}": {
        "get": {
          "tags": [
            "Audio Library"
          ],
          "summary": "Get an audio item",
          "description": "Returns an audio item. Only the admin or user can access your audio.\n\n**Prerequisites:**\n* Business or Education account\n* Zoom Phone license \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read`,`phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:audio`,`phone:read:audio:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-refer[...]",
          "operationId": "GetAudioItem",
          "security": [
            {
              "openapi_oauth": [
                "phone:read",
                "phone:read:admin",
                "phone:read:audio",
                "phone:read:audio:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read",
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:audio",
              "phone:read:audio:admin"
            ]
          }
        },
        "delete": {
          "tags": [
            "Audio Library"
          ],
          "summary": "Delete an audio item",
          "description": "Deletes an audio item. Only the admin or user can delete your audio.\n\n**Prerequisites:**\n* Business, or Education account\n* Zoom Phone license \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write`,`phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:delete:audio`,`phone:delete:audio:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/ap[...]",
          "operationId": "DeleteAudioItem",
          "security": [
            {
              "openapi_oauth": [
                "phone:write",
                "phone:write:admin",
                "phone:delete:audio",
                "phone:delete:audio:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write",
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:delete:audio",
              "phone:delete:audio:admin"
            ]
          }
        },
        "patch": {
          "tags": [
            "Audio Library"
          ],
          "summary": "Update an audio item",
          "description": "Updates an audio item. Only the admin or user can update your audio.\n\n**Prerequisites:**\n* Business or Education account\n* Zoom Phone license \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write`,`phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:update:audio`,`phone:update:audio:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api[...]",
          "operationId": "UpdateAudioItem",
          "security": [
            {
              "openapi_oauth": [
                "phone:write",
                "phone:write:admin",
                "phone:update:audio",
                "phone:update:audio:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write",
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:update:audio",
              "phone:update:audio:admin"
            ]
          }
        }
      },
      "/phone/users/{userId}/audios": {
        "get": {
          "tags": [
            "Audio Library"
          ],
          "summary": "List audio items",
          "description": "Returns personal audios. \n\nOnly the admin or user can query your audios and directly pass the `me` value instead of the `userId` parameter.\n\n**Prerequisites:**\n* Business or Education account\n* Zoom Phone license \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read`,`phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:list_audios`,`phone:read:[...]",
          "operationId": "ListAudioItems",
          "security": [
            {
              "openapi_oauth": [
                "phone:read",
                "phone:read:admin",
                "phone:read:list_audios",
                "phone:read:list_audios:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read",
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:list_audios",
              "phone:read:list_audios:admin"
            ]
          }
        },
        "post": {
          "tags": [
            "Audio Library"
          ],
          "summary": "Add an audio item for text-to-speech conversion",
          "description": "Adds an audio item for [text-to-speech conversion](https://support.zoom.us/hc/en-us/articles/4402414203533-Using-the-audio-library-to-customize-audio#h_01F8B0D2ZJBKEDH10DFZ7J2CM7). Only the admin or user can add your audio and directly pass the `me` value instead of the `userId` parameter.\n\n**Prerequisites:**\n* Business or Education account\n* Zoom Phone license \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write`,`[...]",
          "operationId": "AddAnAudio",
          "security": [
            {
              "openapi_oauth": [
                "phone:write",
                "phone:write:admin",
                "phone:write:audio",
                "phone:write:audio:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write",
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:write:audio",
              "phone:write:audio:admin"
            ]
          }
        }
      },
      "/phone/users/{userId}/audios/batch": {
        "post": {
          "tags": [
            "Audio Library"
          ],
          "summary": "Add audio items",
          "description": "Adds the audio items. You can only upload voice files at this time. Only the admin or user can add your audio and directly pass the `me` value instead of the `userId` parameter.\n\n**Prerequisites:**\n* Business or Education account\n* Zoom Phone license \n\n**Size and quantity limits for audio attachments:**\n* Up to 5 attachments\n* Each file size should be no more than 1MB\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:wr[...]",
          "operationId": "AddAudioItem",
          "security": [
            {
              "openapi_oauth": [
                "phone:write",
                "phone:write:admin",
                "phone:write:batch_audios",
                "phone:write:batch_audios:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write",
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:write:batch_audios",
              "phone:write:batch_audios:admin"
            ]
          }
        }
      },
      "/phone/auto_receptionists": {
        "get": {
          "tags": [
            "Auto Receptionists"
          ],
          "summary": "List auto receptionists",
          "description": "Returns a list of auto receptionists.\n\n**Prerequisites:**\n* Pro or a higher account with Zoom Phone license.\n* Account owner or admin permissions.\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:list_auto_receptionists:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-[...]",
          "operationId": "listAutoReceptionists",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:list_auto_receptionists:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:list_auto_receptionists:admin"
            ]
          }
        },
        "post": {
          "tags": [
            "Auto Receptionists"
          ],
          "summary": "Add an auto receptionist",
          "description": "Adds an [auto receptionist](https://support.zoom.us/hc/en-us/articles/360021121312-Managing-Auto-Receptionists-and-Interactive-Voice-Response-IVR-) to a Zoom Phone. Auto receptionists answer calls with a personalized recording and routes calls to a phone user, call queue, common area, voicemail or an IVR system. \n\n**Prerequisites:**\n* Pro or higher account with Zoom Phone license.\n* Account owner or admin privileges \n\n\n\n**[Scopes](https://developers.zoom.us/docs[...]",
          "operationId": "addAutoReceptionist",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:write:auto_receptionist:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:write:auto_receptionist:admin"
            ]
          }
        }
      },
      "/phone/auto_receptionists/{autoReceptionistId}": {
        "get": {
          "tags": [
            "Auto Receptionists"
          ],
          "summary": "Get an auto receptionist",
          "description": "Returns information on a specific auto receptionist.\n\n**Prerequisites:**\n* Pro or a higher account with Zoom Phone license\n* Account owner or admin permissions\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:auto_receptionist:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/ra[...]",
          "operationId": "getAutoReceptionistDetail",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:auto_receptionist:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:auto_receptionist:admin"
            ]
          }
        },
        "delete": {
          "tags": [
            "Auto Receptionists"
          ],
          "summary": "Delete a non-primary auto receptionist",
          "description": "[Deletes a non-primary auto receptionist](https://support.zoom.us/hc/en-us/articles/360021121312-Managing-Auto-Receptionists-and-Interactive-Voice-Response-IVR-#h_1d5ffc56-6ba3-4ce5-9d86-4a1a1ee743f3).\n\nAn auto receptionist answers calls with a personalized recording and routes calls to a phone user, call queue, common area (phone), or to a voicemail. An auto receptionist can also be set up so that it routes calls to an interactive voice response (IVR) system to allow[...]",
          "operationId": "deleteAutoReceptionist",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:delete:auto_receptionist:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:delete:auto_receptionist:admin"
            ]
          }
        },
        "patch": {
          "tags": [
            "Auto Receptionists"
          ],
          "summary": "Update an auto receptionist",
          "description": "[Changes information](https://support.zoom.us/hc/en-us/articles/360021121312-Managing-Auto-Receptionists-and-Interactive-Voice-Response-IVR-#h_1d5ffc56-6ba3-4ce5-9d86-4a1a1ee743f3) such as the display name and the extension number assigned to the main auto receptionist.\n\nAn auto receptionist answers calls with a personalized recording. And it routes calls to a phone user, call queue, common area, or voicemail. An auto receptionist can also be set up so that it routes [...]",
          "operationId": "updateAutoReceptionist",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:update:auto_receptionist:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:update:auto_receptionist:admin"
            ]
          }
        }
      },
      "/phone/auto_receptionists/{autoReceptionistId}/phone_numbers": {
        "post": {
          "tags": [
            "Auto Receptionists"
          ],
          "summary": "Assign phone numbers",
          "description": "Assigns available phone numbers to an [auto receptionist](https://support.zoom.us/hc/en-us/articles/360021121312-Managing-Auto-Receptionists-and-Interactive-Voice-Response-IVR-). The available numbers can be retrieved using the List Phone Numbers API with `type` query parameter set to &quot;unassigned&quot;.\n\n**Prerequisites:**\n* Pro or higher account plan with Zoom Phone License\n* Account owner or admin permissions  \n \n\n\n**[Scopes](https://developers.zoom.us/do[...]",
          "operationId": "assignPhoneNumbersAutoReceptionist",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:write:auto_receptionist_number:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:write:auto_receptionist_number:admin"
            ]
          }
        },
        "delete": {
          "tags": [
            "Auto Receptionists"
          ],
          "summary": "Unassign all phone numbers",
          "description": "Unassigns all phone numbers that were previously assigned to an [auto receptionist](https://support.zoom.us/hc/en-us/articles/360021121312-Managing-Auto-Receptionists-and-Interactive-Voice-Response-IVR-). \n\n**Prerequisites:**\n* Pro or higher account plan with Zoom Phone License\n* Account owner or admin permissions  \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers[...]",
          "operationId": "unassignAllPhoneNumsAutoReceptionist",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:delete:auto_receptionist_number:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:delete:auto_receptionist_number:admin"
            ]
          }
        }
      },
      "/phone/auto_receptionists/{autoReceptionistId}/phone_numbers/{phoneNumberId}": {
        "delete": {
          "tags": [
            "Auto Receptionists"
          ],
          "summary": "Unassign a phone number",
          "description": "Unassigns a specific phone number that was previously assigned to an [auto receptionist](https://support.zoom.us/hc/en-us/articles/360021121312-Managing-Auto-Receptionists-and-Interactive-Voice-Response-IVR-). \n\n**Prerequisites:**\n* Pro or higher account plan with Zoom Phone License\n* Account owner or admin permissions  \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://devel[...]",
          "operationId": "unassignAPhoneNumAutoReceptionist",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:delete:auto_receptionist_number:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:delete:auto_receptionist_number:admin"
            ]
          }
        }
      },
      "/phone/auto_receptionists/{autoReceptionistId}/policies": {
        "get": {
          "tags": [
            "Auto Receptionists"
          ],
          "summary": "Get an auto receptionist policy",
          "description": "Returns the policy setting of a specific [auto receptionist](https://support.zoom.us/hc/en-us/articles/360021121312-Managing-Auto-Receptionists-and-Interactive-Voice-Response-IVR-).\n\n**Prerequisites:**\n* Pro or a higher account with Zoom Phone license\n* Account owner or admin permissions\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oaut[...]",
          "operationId": "getAutoReceptionistsPolicy",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:auto_receptionist_policy:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:auto_receptionist_policy:admin"
            ]
          }
        },
        "patch": {
          "tags": [
            "Auto Receptionists"
          ],
          "summary": "Update an auto receptionist policy",
          "description": "Updates the policy setting of a specific [auto receptionist](https://support.zoom.us/hc/en-us/articles/360021121312-Managing-Auto-Receptionists-and-Interactive-Voice-Response-IVR-). \n\n**Prerequisites:**\n* Pro or higher account plan with Zoom Phone License\n* Account owner or admin permissions\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations[...]",
          "operationId": "updateAutoReceptionistPolicy",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:update:auto_receptionist_policy:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:update:auto_receptionist_policy:admin"
            ]
          }
        }
      },
      "/phone/auto_receptionists/{autoReceptionistId}/policies/{policyType}": {
        "post": {
          "tags": [
            "Auto Receptionists"
          ],
          "summary": "Add a policy subsetting",
          "description": "Adds a policy subsetting for a specific [auto receptionist](https://support.zoom.us/hc/en-us/articles/360021121312-Managing-Auto-Receptionists-and-Interactive-Voice-Response-IVR-) according to the `policyType`. For example, you can use this API to set up shared access members.<br><br>**Prerequisites:**\n* Pro or higher account plan with Zoom Phone License\n* Account owner or admin permissions\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overvi[...]",
          "operationId": "AddPolicy",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:write:auto_receptionist_policy:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:write:auto_receptionist_policy:admin"
            ]
          }
        },
        "delete": {
          "tags": [
            "Auto Receptionists"
          ],
          "summary": "Delete a policy subsetting",
          "description": "Removes the policy subsetting for a specific [auto receptionist](https://support.zoom.us/hc/en-us/articles/360021121312-Managing-Auto-Receptionists-and-Interactive-Voice-Response-IVR-) according to the `policyType`. For example, you can use this API to remove shared access members.\n\n**Prerequisites:**\n* Pro or higher account plan with Zoom Phone License\n* Account owner or admin permissions\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overv[...]",
          "operationId": "DeletePolicy",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:delete:auto_receptionist_policy:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:delete:auto_receptionist_policy:admin"
            ]
          }
        },
        "patch": {
          "tags": [
            "Auto Receptionists"
          ],
          "summary": "Update a policy subsetting",
          "description": "Updates the policy subsetting of a specific [auto receptionist](https://support.zoom.us/hc/en-us/articles/360021121312-Managing-Auto-Receptionists-and-Interactive-Voice-Response-IVR-) according to the `policyType`. For example, you can use this API to update shared access members.\n\n**Prerequisites:**\n* Pro or higher account plan with Zoom Phone License\n* Account owner or admin permissions\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-ov[...]",
          "operationId": "updatePolicy",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:update:auto_receptionist_policy:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:update:auto_receptionist_policy:admin"
            ]
          }
        }
      },
      "/phone/billing_accounts": {
        "get": {
          "tags": [
            "Billing Account"
          ],
          "summary": "List billing accounts",
          "description": "Retrieves a list of available billing accounts for a Zoom account owner or a user with admin privileges. \n\nIf the [multiple sites](https://support.zoom.us/hc/en-us/articles/360020809672-Managing-multiple-sites) option has been enabled for the account, then `field(site_id)` is required.\n\n**Prerequisites:**\n* Pro or higher account plan with Zoom phone license\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\[...]",
          "operationId": "listBillingAccount",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:list_billing_accounts:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:list_billing_accounts:admin"
            ]
          }
        }
      },
      "/phone/billing_accounts/{billingAccountId}": {
        "get": {
          "tags": [
            "Billing Account"
          ],
          "summary": "Get billing account details",
          "description": "A Zoom account owner or a user with admin privilege can use this API to get information about a billing account.\n\n**Prerequisites:**\n* Pro or higher account plan with Zoom phone license\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:billing_account:admin`\n\n**[Rate Limit Label](https://marketplace.zo[...]",
          "operationId": "GetABillingAccount",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:billing_account:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:billing_account:admin"
            ]
          }
        }
      },
      "/phone/blocked_list": {
        "get": {
          "tags": [
            "Blocked List"
          ],
          "summary": "List blocked lists",
          "description": "Returns all the blocked lists in an acccount. A Zoom account owner or a user with admin privilege can block phone numbers for phone users in an account. Blocked numbers can be inbound (numbers will be blocked from calling in) and outbound (phone users in your account won't be able to dial those numbers). Blocked callers will hear a generic message stating that the person they are calling is not available. \n\n**Prerequisites:**\n* Pro or higher account plan with Zoom ph[...]",
          "operationId": "listBlockedList",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:list_blocked_lists:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:list_blocked_lists:admin"
            ]
          }
        },
        "post": {
          "tags": [
            "Blocked List"
          ],
          "summary": "Create a blocked list",
          "description": "Creates a block list and add a number to the list. \n\nA Zoom account owner or a user with the admin privilege can block phone numbers for phone users in an account. \n\nBlocked numbers can be inbound (numbers will be blocked from calling in) and outbound (phone users in your account won't be able to dial those numbers). \n\nBlocked callers will hear a generic message stating that the person they are calling is not available. \n\n**Prerequisites:**\n* Pro or higher acco[...]",
          "operationId": "addAnumberToBlockedList",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:write:blocked_list:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:write:blocked_list:admin"
            ]
          }
        }
      },
      "/phone/blocked_list/{blockedListId}": {
        "get": {
          "tags": [
            "Blocked List"
          ],
          "summary": "Get blocked list details",
          "description": "Returns the information about a specific blocked list. \n\nA Zoom account owner or a user with admin privilege can block phone numbers for phone users in an account. Blocked numbers can be inbound (numbers will be blocked from calling in) and outbound (phone users in your account won't be able to dial those numbers). Blocked callers will hear a generic message stating that the person they are calling is not available.\n\n**Prerequisites:**\n* Pro or higher account plan [...]",
          "operationId": "getABlockedList",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:blocked_list:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:blocked_list:admin"
            ]
          }
        },
        "delete": {
          "tags": [
            "Blocked List"
          ],
          "summary": "Delete a blocked list",
          "description": "Deletes a blocked list, which removes the associated number from the blocked list. \n\nThe number will be unblocked after the deletion. A Zoom account owner or a user with admin privilege can block phone numbers for phone users in an account. Blocked numbers can be inbound (numbers will be blocked from calling in) and outbound (phone users in your account won't be able to dial those numbers).\n\n**Prerequisites:**\n* Pro or higher account plan with Zoom phone license\n\[...]",
          "operationId": "deleteABlockedList",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:delete:blocked_list:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:delete:blocked_list:admin"
            ]
          }
        },
        "patch": {
          "tags": [
            "Blocked List"
          ],
          "summary": "Update a blocked list",
          "description": "Updates the information in the blocked list.\n\nA Zoom account owner or a user with admin privilege can block phone numbers for phone users in an account. Blocked numbers can be inbound (numbers will be blocked from calling in) and outbound (phone users in your account won't be able to dial those numbers). Blocked callers hear a generic message stating that the person they are calling is not available.\n\n**Prerequisites:**\n* Pro or higher account plan with Zoom phone [...]",
          "operationId": "updateBlockedList",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:update:blocked_list:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:update:blocked_list:admin"
            ]
          }
        }
      },
      "/phone/extension/{extensionId}/call_handling/settings": {
        "get": {
          "tags": [
            "Call Handling"
          ],
          "summary": "Get call handling settings",
          "description": "Returns information about a Zoom Phone's call handling settings. \n\nCall handling settings let you control how your system routes calls during business, closed, or holiday hours. For more information, read our [API guide](https://developers.zoom.us/docs/zoom-phone/call-handling/) or Zoom support article [Customizing call handling settings](https://support.zoom.us/hc/en-us/articles/360059966372-Customizing-call-handling-settings).\n\n**Applicable to user, call queue, au[...]",
          "operationId": "getCallHandling",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:list_call_handling_settings:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:list_call_handling_settings:admin"
            ]
          }
        }
      },
      "/phone/extension/{extensionId}/call_handling/settings/{settingType}": {
        "post": {
          "tags": [
            "Call Handling"
          ],
          "summary": "Add a call handling setting",
          "description": "Adds Zoom Phone call handling subsettings for your phone system. Call handling settings allow you to control how your system routes calls during business, closed, or holiday hours. For more information, see our [API guide](https://developers.zoom.us/docs/api/phone/) or Zoom support article [Customizing call handling settings](https://support.zoom.us/hc/en-us/articles/360059966372-Customizing-call-handling-settings).\n\n**Applicable to user, call queue, auto receptionist[...]",
          "operationId": "addCallHandling",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:write:call_handling_setting:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:write:call_handling_setting:admin"
            ]
          }
        },
        "delete": {
          "tags": [
            "Call Handling"
          ],
          "summary": "Delete a call handling setting",
          "description": "Deletes a Zoom Phone's call handling settings. Call handling settings let you control how your system routes calls during business, closed, or holiday hours. For more information, read our [API guide](https://marketplace.zoom.us/docs/guides/zoom-phone/call-handling/) or Zoom support article [Customizing call handling settings](https://support.zoom.us/hc/en-us/articles/360059966372-Customizing-call-handling-settings).\n\n**Applicable to user, call queue, auto receptionis[...]",
          "operationId": "deleteCallHandling",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:delete:call_handling_setting:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:delete:call_handling_setting:admin"
            ]
          }
        },
        "patch": {
          "tags": [
            "Call Handling"
          ],
          "summary": "Update a call handling setting",
          "description": "Updates a Zoom Phone's call handling setting. \n\nCall handling settings allow you to control how your system routes calls during business, closed, or holiday hours. For more information, read our [Call Handling API guide](https://developers.zoom.us/docs/zoom-phone/call-handling/) or Zoom support article [Customizing call handling settings](https://support.zoom.us/hc/en-us/articles/360059966372-Customizing-call-handling-settings).\n\n**Applicable to user, call queue, au[...]",
          "operationId": "updateCallHandling",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:update:call_handling_setting:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:update:call_handling_setting:admin"
            ]
          }
        }
      },
      "/phone/call_element/{callElementId}": {
        "get": {
          "tags": [
            "Call Logs"
          ],
          "summary": "Get call element",
          "description": "Returns the call element for a given call element ID.\n \n **Prerequisites** \n * A Business or Enterprise account \n * A Zoom Phone license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone_call_log:read`,`phone_call_log:read:admin`,`phone:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:call_log:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-[...]",
          "operationId": "getCallElement",
          "security": [
            {
              "openapi_oauth": [
                "phone_call_log:read",
                "phone_call_log:read:admin",
                "phone:read",
                "phone:read:call_log:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone_call_log:read",
              "phone_call_log:read:admin",
              "phone:read"
            ],
            "x-granular-scopes": [
              "phone:read:call_log:admin"
            ]
          }
        }
      },
      "/phone/call_history": {
        "get": {
          "tags": [
            "Call Logs"
          ],
          "summary": "Get account's call history",
          "description": "Returns an account's new edition of [call logs](https://support.zoom.us/hc/en-us/articles/360021114452-Viewing-Call-Logs).\n\n**Prerequisites** \n* A Business or Enterprise account \n* A Zoom Phone license \n* Account owner or a [role](https://support.zoom.us/hc/en-us/articles/115001078646-Role-Based-Access-Control) with Zoom Phone management\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`,`phone_call_log:read:adm[...]",
          "operationId": "accountCallHistory",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone_call_log:read:admin",
                "phone:read:list_call_logs:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin",
              "phone_call_log:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:list_call_logs:admin"
            ]
          }
        }
      },
      "/phone/call_history/{callHistoryUuid}": {
        "get": {
          "tags": [
            "Call Logs"
          ],
          "summary": "Get call history",
          "description": "Returns information about a [call log](https://support.zoom.us/hc/en-us/articles/360021114452-Viewing-and-identifying-logs).\n\n**Prerequisites** \n* A Business or Enterprise account \n* A Zoom Phone license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`,`phone_call_log:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:call_log:admin`\n\n**[Rate[...]",
          "operationId": "getCallPath",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone_call_log:read:admin",
                "phone:read:call_log:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin",
              "phone_call_log:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:call_log:admin"
            ]
          }
        }
      },
      "/phone/call_history/{callLogId}/client_code": {
        "patch": {
          "tags": [
            "Call Logs"
          ],
          "summary": "Add a client code to a call history",
          "description": "Adds a client code to a [call log](https://support.zoom.us/hc/en-us/articles/360040999352-Assigning-client-codes-to-phone-calls). You can track call logs with a client code. \n\n**Prerequisites**\n* Business or Education account\n* Zoom Phone license \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:update:call_lo[...]",
          "operationId": "addClientCodeToCallHistory",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:update:call_log:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:update:call_log:admin"
            ]
          }
        }
      },
      "/phone/call_history_detail/{callHistoryId}": {
        "get": {
          "tags": [
            "Call Logs"
          ],
          "summary": "Get call history detail",
          "description": " Returns the call history details for a given call log ID [call history](https://support.zoom.us/hc/en-us/articles/360021114452-Viewing-and-identifying-logs). \n \n **Prerequisites** \n * A Business or Enterprise account \n * A Zoom Phone license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone_call_log:read`,`phone_call_log:read:admin`,`phone:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scop[...]",
          "operationId": "getCallHistoryDetail",
          "deprecated": true,
          "security": [
            {
              "openapi_oauth": [
                "phone_call_log:read",
                "phone_call_log:read:admin",
                "phone:read",
                "phone:read:call_log:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone_call_log:read",
              "phone_call_log:read:admin",
              "phone:read"
            ],
            "x-granular-scopes": [
              "phone:read:call_log:admin"
            ]
          }
        }
      },
      "/phone/call_logs": {
        "get": {
          "tags": [
            "Call Logs"
          ],
          "summary": "Get account's call logs",
          "description": "Returns an account's [call logs](https://support.zoom.us/hc/en-us/articles/360021114452-Viewing-Call-Logs).\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license \n* Account owner or a [role](https://support.zoom.us/hc/en-us/articles/115001078646-Role-Based-Access-Control) with Zoom Phone management\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`,`phone_call_log:read:admin`\n\n**[[...]",
          "operationId": "accountCallLogs",
          "deprecated": true,
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone_call_log:read:admin",
                "phone:read:list_call_logs:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin",
              "phone_call_log:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:list_call_logs:admin"
            ]
          }
        }
      },
      "/phone/call_logs/{callLogId}": {
        "get": {
          "tags": [
            "Call Logs"
          ],
          "summary": "Get call log details",
          "description": "Returns information about a [call log](https://support.zoom.us/hc/en-us/articles/360021114452-Viewing-and-identifying-logs).\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`,`phone_call_log:read:admin`,`phone:read`,`phone_call_log:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `p[...]",
          "operationId": "getCallLogDetails",
          "deprecated": true,
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone_call_log:read:admin",
                "phone:read",
                "phone_call_log:read",
                "phone:read:call_log:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin",
              "phone_call_log:read:admin",
              "phone:read",
              "phone_call_log:read"
            ],
            "x-granular-scopes": [
              "phone:read:call_log:admin"
            ]
          }
        }
      },
      "/phone/call_logs/{callLogId}/client_code": {
        "put": {
          "tags": [
            "Call Logs"
          ],
          "summary": "Add a client code to a call log",
          "description": "Adds a client code to a [call log](https://support.zoom.us/hc/en-us/articles/360040999352-Assigning-client-codes-to-phone-calls). You can track call logs with a client code. \n\n**Prerequisites:**\n* Business or Education account\n* Zoom Phone license \n\n\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:updat[...]",
          "operationId": "addClientCodeToCallLog",
          "deprecated": true,
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:update:call_log:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:update:call_log:admin"
            ]
          }
        }
      },
      "/phone/user/{userId}/ai_call_summary/{aiCallSummaryId}": {
        "get": {
          "tags": [
            "Call Logs"
          ],
          "summary": "Get User AI Call Summary Detail",
          "description": "Returns AI call summary details. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`,`phone:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overvi[...]",
          "operationId": "getUserAICallSummary",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read",
                "phone:read:ai_call_summary",
                "phone:read:ai_call_summary:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin",
              "phone:read"
            ],
            "x-granular-scopes": [
              "phone:read:ai_call_summary",
              "phone:read:ai_call_summary:admin"
            ]
          }
        }
      },
      "/phone/users/{userId}/call_history": {
        "get": {
          "tags": [
            "Call Logs"
          ],
          "summary": "Get user's call history",
          "description": "Returns a user's [Zoom phone](https://support.zoom.us/hc/en-us/articles/360001297663-Quickstart-Guide-for-Zoom-Phone-Administrators) call history. \r\n\r\nFor user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\r\n\r\n**Prerequisites** \r\n* A Business or Enterprise account \r\n* A Zoom Phone license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-over[...]",
          "operationId": "phoneUserCallHistory",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone_call_log:read",
                "phone:read:list_call_logs:admin",
                "phone:read:list_call_logs"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin",
              "phone_call_log:read"
            ],
            "x-granular-scopes": [
              "phone:read:list_call_logs:admin",
              "phone:read:list_call_logs"
            ]
          }
        }
      },
      "/phone/users/{userId}/call_history/sync": {
        "get": {
          "tags": [
            "Call Logs"
          ],
          "summary": "Sync user's call history",
          "description": "Syncs a user's [Zoom phone](https://support.zoom.us/hc/en-us/articles/360001297663-Quickstart-Guide-for-Zoom-Phone-Administrators) call history. \n\nFor user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\n**Prerequisites** \n* A Business or Enterprise account\n * A Zoom Phone license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `pho[...]",
          "operationId": "syncUserCallHistory",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read",
                "phone:read:list_call_logs",
                "phone:read:list_call_logs:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin",
              "phone:read"
            ],
            "x-granular-scopes": [
              "phone:read:list_call_logs",
              "phone:read:list_call_logs:admin"
            ]
          }
        }
      },
      "/phone/users/{userId}/call_history/{callLogId}": {
        "delete": {
          "tags": [
            "Call Logs"
          ],
          "summary": "Delete a user's call history",
          "description": "Deletes a user's [call history](https://support.zoom.us/hc/en-us/articles/360021114452-Viewing-and-identifying-logs). \n\nFor user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\n**Prerequisites** \n\n* Belong to a Business or Enterprise account \n* Have a Zoom Phone license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write`,[...]",
          "operationId": "deleteUserCallHistory",
          "security": [
            {
              "openapi_oauth": [
                "phone:write",
                "phone:write:admin",
                "phone_call_log:write",
                "phone_call_log:write:admin",
                "phone:delete:call_log",
                "phone:delete:call_log:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write",
              "phone:write:admin",
              "phone_call_log:write",
              "phone_call_log:write:admin"
            ],
            "x-granular-scopes": [
              "phone:delete:call_log",
              "phone:delete:call_log:admin"
            ]
          }
        }
      },
      "/phone/users/{userId}/call_logs": {
        "get": {
          "tags": [
            "Call Logs"
          ],
          "summary": "Get user's call logs",
          "description": "Returns a user's [Zoom phone](https://support.zoom.us/hc/en-us/articles/360001297663-Quickstart-Guide-for-Zoom-Phone-Administrators) call logs. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:r[...]",
          "operationId": "phoneUserCallLogs",
          "deprecated": true,
          "security": [
            {
              "openapi_oauth": [
                "phone:read",
                "phone:read:admin",
                "phone_call_log:read",
                "phone_call_log:read:admin",
                "phone:read:list_call_logs",
                "phone:read:list_call_logs:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read",
              "phone:read:admin",
              "phone_call_log:read",
              "phone_call_log:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:list_call_logs",
              "phone:read:list_call_logs:admin"
            ]
          }
        }
      },
      "/phone/users/{userId}/call_logs/sync": {
        "get": {
          "tags": [
            "Call Logs"
          ],
          "summary": "Sync user's call logs",
          "description": "Syncs a user's [Zoom phone](https://support.zoom.us/hc/en-us/articles/360001297663-Quickstart-Guide-for-Zoom-Phone-Administrators) call logs. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:rea[...]",
          "operationId": "syncUserCallLogs",
          "deprecated": true,
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read",
                "phone:read:list_call_logs",
                "phone:read:list_call_logs:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin",
              "phone:read"
            ],
            "x-granular-scopes": [
              "phone:read:list_call_logs",
              "phone:read:list_call_logs:admin"
            ]
          }
        }
      },
      "/phone/users/{userId}/call_logs/{callLogId}": {
        "delete": {
          "tags": [
            "Call Logs"
          ],
          "summary": "Delete a user's call log",
          "description": "Deletes a user's [call log](https://support.zoom.us/hc/en-us/articles/360021114452-Viewing-and-identifying-logs). For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\n**Prerequisites:** \n* User must belong to a Business or Enterprise account \n* User must have a Zoom Phone license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `ph[...]",
          "operationId": "deleteCallLog",
          "deprecated": true,
          "security": [
            {
              "openapi_oauth": [
                "phone:write",
                "phone:write:admin",
                "phone_call_log:write",
                "phone_call_log:write:admin",
                "phone:delete:call_log",
                "phone:delete:call_log:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write",
              "phone:write:admin",
              "phone_call_log:write",
              "phone_call_log:write:admin"
            ],
            "x-granular-scopes": [
              "phone:delete:call_log",
              "phone:delete:call_log:admin"
            ]
          }
        }
      },
      "/phone/call_queue_analytics": {
        "get": {
          "tags": [
            "Call Queues"
          ],
          "summary": "List call queue analytics",
          "description": "Returns the call queue analytics overview.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:list_call_queues:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
          "operationId": "callqueueanalytics",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:list_call_queues:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:list_call_queues:admin"
            ]
          }
        }
      },
      "/phone/call_queues": {
        "get": {
          "tags": [
            "Call Queues"
          ],
          "summary": "List call queues",
          "description": "Call queues allow you to route incoming calls to a group of users. For instance, you can use call queues to route calls to various departments in your organization such as sales, engineering, billing, customer service etc.\n Use this API to list Call queues.\n\n\n**Prerequisites:**\n\n* Pro, Business, or Education account\n* Account owner or admin permissions\n* Zoom Phone license\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** [...]",
          "operationId": "listCallQueues",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:list_call_queues:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:list_call_queues:admin"
            ]
          }
        },
        "post": {
          "tags": [
            "Call Queues"
          ],
          "summary": "Create a call queue",
          "description": "[Creates a call queue](https://support.zoom.us/hc/en-us/articles/360021524831-Managing-Call-Queues#h_e81faeeb-9184-429a-aaea-df49ff5ff413). Call queues allow you to route incoming calls to a group of users. For instance, you can use call queues to route calls to various departments in your organization such as sales, engineering, billing, customer service, and so on.\n You can add phone users or common areas to call queues.\n\n**Prerequisites:**\n\n* Pro, Business, or E[...]",
          "operationId": "createCallQueue",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:write:call_queue:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:write:call_queue:admin"
            ]
          }
        }
      },
      "/phone/call_queues/{callQueueId}": {
        "get": {
          "tags": [
            "Call Queues"
          ],
          "summary": "Get call queue details",
          "description": "Routes incoming calls to a group of users and returns information on a specific call queue. \n\nFor instance, you can use call queues to route calls to various departments in your organization such as sales, engineering, billing, customer service, and so on. \n\n\n \n**Prerequisites:**\n\n* Pro, Business, or Education account\n* Account owner or admin permissions\n* Zoom Phone license\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/)[...]",
          "operationId": "getACallQueue",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:call_queue:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:call_queue:admin"
            ]
          }
        },
        "delete": {
          "tags": [
            "Call Queues"
          ],
          "summary": "Delete a call queue",
          "description": "Call queues allow you to route incoming calls to a group of users. For instance, you can use call queues to route calls to various departments in your organization such as sales, engineering, billing, customer service etc.\n Use this API to delete a Call Queue.\n \n**Prerequisites:**\n\n* Pro, Business, or Education account\n* Account owner or admin permissions\n* Zoom Phone license\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):*[...]",
          "operationId": "deleteACallQueue",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:delete:call_queue:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:delete:call_queue:admin"
            ]
          }
        },
        "patch": {
          "tags": [
            "Call Queues"
          ],
          "summary": "Update call queue details",
          "description": "Updates information of a specific call queue. Call queues allow you to route incoming calls to a group of users. For instance, you can use call queues to route calls to various departments in your organization such as sales, engineering, billing, customer service, and so on.\n  \n**Prerequisites:**\n\n* Pro, Business, or Education account\n* Account owner or admin permissions\n* Zoom Phone license\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scop[...]",
          "operationId": "updateCallQueue",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:update:call_queue:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:update:call_queue:admin"
            ]
          }
        }
      },
      "/phone/call_queues/{callQueueId}/members": {
        "get": {
          "tags": [
            "Call Queues"
          ],
          "summary": "List call queue members",
          "description": "Returns a list of call queue members.\n\n\n**Prerequisites:**\n\n* Pro, Business, or Education account\n* Account owner or admin permissions\n* Zoom Phone license\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:list_call_queue_members:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-ref[...]",
          "operationId": "listCallQueueMembers",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:list_call_queue_members:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:list_call_queue_members:admin"
            ]
          }
        },
        "post": {
          "tags": [
            "Call Queues"
          ],
          "summary": "Add members to a call queue",
          "description": "Adds phone users or [common areas](https://support.zoom.us/hc/articles/4481136653709) as members to a specific call queue.\n\n**Prerequisites:**\n* Pro or higher account plan.\n* Zoom Phone license\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:call_queue_member:admin`\n\n**[Rate Limit Label](https://m[...]",
          "operationId": "addMembersToCallQueue",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:write:call_queue_member:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:write:call_queue_member:admin"
            ]
          }
        },
        "delete": {
          "tags": [
            "Call Queues"
          ],
          "summary": "Unassign all members",
          "description": "Removes all members from a call queue who were previously assigned to that call queue. The members could be phone users or [common areas](https://support.zoom.us/hc/articles/4481136653709).\n\n**Prerequisites:**\n\n* Pro or higher account plan.\n* Zoom Phone license\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `p[...]",
          "operationId": "unassignAllMembers",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:delete:call_queue_member:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:delete:call_queue_member:admin"
            ]
          }
        }
      },
      "/phone/call_queues/{callQueueId}/members/{memberId}": {
        "delete": {
          "tags": [
            "Call Queues"
          ],
          "summary": "Unassign a member",
          "description": "Removes a member who was previously added to a call queue. The member could be a phone user or common area. Note that you cannot use this API to unassign a call queue manager. \n\n**Prerequisites:**\n\n* Pro or higher account plan.\n* Zoom Phone license\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:delete:c[...]",
          "operationId": "unassignMemberFromCallQueue",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:delete:call_queue_member:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:delete:call_queue_member:admin"
            ]
          }
        }
      },
      "/phone/call_queues/{callQueueId}/phone_numbers": {
        "post": {
          "tags": [
            "Call Queues"
          ],
          "summary": "Assign numbers to a call queue",
          "description": "Assigns numbers to a call queue. After [buying phone number(s)](https://support.zoom.us/hc/en-us/articles/360020808292#h_007ec8c2-0914-4265-8351-96ab23efa3ad), you can assign it and allow callers to directly dial a number to reach a [call queue](https://support.zoom.us/hc/en-us/articles/360021524831-Managing-Call-Queues).\n\n**Prerequisites:**\n- Pro or higher account plan\n* Account owner or admin permissions\n- Zoom Phone license\n\n**[Scopes](https://developers.zoom.[...]",
          "operationId": "assignPhoneToCallQueue",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:write:call_queue_number:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:write:call_queue_number:admin"
            ]
          }
        },
        "delete": {
          "tags": [
            "Call Queues"
          ],
          "summary": "Unassign all phone numbers",
          "description": "Unbinds all phone numbers that are assigned to a [call queue](https://support.zoom.us/hc/en-us/articles/360021524831-Managing-Call-Queues).  After successful unbinding, the numbers will appear in the [Unassigned tab](https://zoom.us/signin#/numbers/unassigned).\n \n If you only need to unassign a specific phone number, use the Unassign a Phone Number API instead. \n\n**Prerequisites:**\n* Pro or higher account palan\n* Account owner or admin permissions\n* Zoom Phone li[...]",
          "operationId": "unassignAPhoneNumCallQueue",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:delete:call_queue_number:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:delete:call_queue_number:admin"
            ]
          }
        }
      },
      "/phone/call_queues/{callQueueId}/phone_numbers/{phoneNumberId}": {
        "delete": {
          "tags": [
            "Call Queues"
          ],
          "summary": "Unassign a phone number",
          "description": "Unbinds a phone number from a call queue. After assigning a phone number, you can unbind it if you don't want it to be assigned to a [call queue](https://support.zoom.us/hc/en-us/articles/360021524831-Managing-Call-Queues).  After successful unbinding, the number will appear in the [Unassigned tab](https://zoom.us/signin#/numbers/unassigned).\n\n\n**Prerequisites:**\n* Pro or higher account palan\n* Account owner or admin permissions\n* Zoom Phone license \n\n \n\n**[Sc[...]",
          "operationId": "unAssignPhoneNumCallQueue",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:delete:call_queue_number:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:delete:call_queue_number:admin"
            ]
          }
        }
      },
      "/phone/call_queues/{callQueueId}/policies/{policyType}": {
        "post": {
          "tags": [
            "Call Queues"
          ],
          "summary": "Add a policy subsetting to a call queue",
          "description": "Adds the policy subsetting for a specific [call queue](https://support.zoom.us/hc/en-us/articles/360021524831) according to the `policyType`. For example, you can use set up shared access members. \n\n**Prerequisites:** \n* Pro or higher account with Zoom Phone license.\n* Account owner or admin privileges \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/[...]",
          "operationId": "addCQPolicySubSetting",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:write:call_queue_policy:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:write:call_queue_policy:admin"
            ]
          }
        },
        "delete": {
          "tags": [
            "Call Queues"
          ],
          "summary": "Delete a CQ policy setting",
          "description": "Use this API to remove the policy sub-setting for a specific [call queue](https://support.zoom.us/hc/en-us/articles/360021524831) according to the `policyType`. For example, you can use this API to remove shared access members. \n\n**Prerequisites:** \n* Pro or higher account with Zoom Phone license.\n* Account owner or admin privileges \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](h[...]",
          "operationId": "removeCQPolicySubSetting",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:delete:call_queue_policy:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:delete:call_queue_policy:admin"
            ]
          }
        },
        "patch": {
          "tags": [
            "Call Queues"
          ],
          "summary": "Update a call queue's policy subsetting",
          "description": "Updates the policy subsetting for a specific [call queue](https://support.zoom.us/hc/en-us/articles/360021524831) according to the `policyType`. For example, you can use this API to update shared access members.\n\n**Prerequisites:** \n* Pro or higher account with Zoom Phone license.\n* Account owner or admin privileges \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers[...]",
          "operationId": "updateCQPolicySubSetting",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:update:call_queue_policy:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:update:call_queue_policy:admin"
            ]
          }
        }
      },
      "/phone/call_queues/{callQueueId}/recordings": {
        "get": {
          "tags": [
            "Call Queues"
          ],
          "summary": "Get call queue recordings",
          "description": "Use this API to view [call recordings](https://support.zoom.us/hc/en-us/articles/360038521091#h_cbc9f2a3-e06c-4daa-83d4-ddbceef9c77b) from the call queue.\n\n\n**Prerequisites:**\n\n* Pro or higher account with Zoom Phone license.\n* [Automatic call recordings](https://support.zoom.us/hc/en-us/articles/360033511872#h_fcb297bb-14e8-4094-91ca-dc61e1a18734) must be enabled in the Policy Settings for call queues. \n \n\n**[Scopes](https://developers.zoom.us/docs/integration[...]",
          "operationId": "getCallQueueRecordings",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:list_call_queue_recordings:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:list_call_queue_recordings:admin"
            ]
          }
        }
      },
      "/phone/carrier_reseller/numbers": {
        "get": {
          "tags": [
            "Carrier Reseller"
          ],
          "summary": "List phone numbers",
          "description": "Use this API to list phone numbers in a carrier reseller (master) account that can be pushed to its subaccounts.\n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:list_carrier_numbers:admin`\n\n**[Rate Limit Label](https://marketpla[...]",
          "operationId": "listCRPhoneNumbers",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:list_carrier_numbers:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:list_carrier_numbers:admin"
            ]
          }
        },
        "post": {
          "tags": [
            "Carrier Reseller"
          ],
          "summary": "Create phone numbers",
          "description": "Use this API to add phone numbers to a carrier reseller (master) account. Up to 200 numbers at a time. If this API is called in MA mode, it also has functions of distribution.\n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:carr[...]",
          "operationId": "createCRPhoneNumbers",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:write:carrier_number:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:write:carrier_number:admin"
            ]
          }
        },
        "patch": {
          "tags": [
            "Carrier Reseller"
          ],
          "summary": "Activate phone numbers",
          "description": "Use this API to change phone number status to 'active' in a carrier reseller's master account. Up to 200 numbers at a time.\n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:update:carrier_number:admin`\n\n**[Rate Limit Label](https://m[...]",
          "operationId": "activeCRPhoneNumbers",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:update:carrier_number:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:update:carrier_number:admin"
            ]
          }
        }
      },
      "/phone/carrier_reseller/numbers/{number}": {
        "delete": {
          "tags": [
            "Carrier Reseller"
          ],
          "summary": "Delete a phone number",
          "description": "Use this API to delete or unassign a phone number from a carrier reseller account.\n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:delete:carrier_number:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rat[...]",
          "operationId": "deleteCRPhoneNumber",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:delete:carrier_number:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:delete:carrier_number:admin"
            ]
          }
        }
      },
      "/phone/common_areas": {
        "get": {
          "tags": [
            "Common Areas"
          ],
          "summary": "List common areas",
          "description": "Lists common areas under an account.\n\n**Prerequisites**\n\n* Pro or a higher account with Zoom Phone license \n* Account owner or admin permissions\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:common_area:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-l[...]",
          "operationId": "listCommonAreas",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:common_area:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:common_area:admin"
            ]
          }
        },
        "post": {
          "tags": [
            "Common Areas"
          ],
          "summary": "Add a common area",
          "description": "Adds an instance of a common area. You can configure devices shared by users and deployed in shared spaces.\n\n**Prerequisites**\n* Pro or a higher account with Zoom Phone license\n* Account owner or admin permissions\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:common_area:admin`\n\n**[Rate Limit La[...]",
          "operationId": "addCommonArea",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:write:common_area:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:write:common_area:admin"
            ]
          }
        }
      },
      "/phone/common_areas/activation_code": {
        "post": {
          "tags": [
            "Common Areas"
          ],
          "summary": "Generate activation codes for common areas",
          "description": "Generates activation codes for common areas. You can add up to 50 common areas at a time.\n\n**Prerequisites**\n- Pro or a higher account with Zoom Phone license\n- Account owner or admin permissions\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:common_area:admin`\n\n**[Rate Limit Label](https://marketpla[...]",
          "operationId": "Generateactivationcodesforcommonareas",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:write:common_area:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:write:common_area:admin"
            ]
          }
        }
      },
      "/phone/common_areas/activation_codes": {
        "get": {
          "tags": [
            "Common Areas"
          ],
          "summary": "List activation codes",
          "description": "Returns a list of activation code information of the common areas under an account.\n\n**Prerequisites**\n* Pro or a higher account with Zoom Phone license \n* Account owner or admin permissions\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:list_common_area_activation_codes:admin`\n\n**[Rate Limit Label](ht[...]",
          "operationId": "listActivationCodes",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:list_common_area_activation_codes:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:list_common_area_activation_codes:admin"
            ]
          }
        }
      },
      "/phone/common_areas/template_id/{templateId}": {
        "post": {
          "tags": [
            "Common Areas"
          ],
          "summary": "Apply template to common areas",
          "description": "Applies a template to common areas.  You can add up to 50 common areas at a time.\n\n**Prerequisites**\n* Pro or a higher account with Zoom Phone license\n* Account owner or admin permissions\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:apply_template_to_common_areas:admin`\n\n**[Rate Limit Label](http[...]",
          "operationId": "ApplyTemplatetoCommonAreas",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:write:apply_template_to_common_areas:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:write:apply_template_to_common_areas:admin"
            ]
          }
        }
      },
      "/phone/common_areas/{commonAreaId}": {
        "get": {
          "tags": [
            "Common Areas"
          ],
          "summary": "Get common area details",
          "description": "Returns detailed information on the common area.\n\n**Prerequisites**  \n \n* Pro or a higher account with Zoom Phone license\n* Account owner or admin permissions\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:common_area:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate[...]",
          "operationId": "getACommonArea",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:common_area:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:common_area:admin"
            ]
          }
        },
        "delete": {
          "tags": [
            "Common Areas"
          ],
          "summary": "Delete a common area",
          "description": "Removes the common area. \n\n**Prerequisites:**\n* Pro or a higher account with Zoom Phone license.\n* Account owner or admin permissions.\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:delete:common_area:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):*[...]",
          "operationId": "deleteCommonArea",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:delete:common_area:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:delete:common_area:admin"
            ]
          }
        },
        "patch": {
          "tags": [
            "Common Areas"
          ],
          "summary": "Update common area",
          "description": "Updates the common area information.\n\n**Prerequisites**\n\n* Pro or a higher account with Zoom Phone license\n* Account owner or admin permissions\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:update:common_area:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate[...]",
          "operationId": "updateCommonArea",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:update:common_area:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:update:common_area:admin"
            ]
          }
        }
      },
      "/phone/common_areas/{commonAreaId}/calling_plans": {
        "post": {
          "tags": [
            "Common Areas"
          ],
          "summary": "Assign calling plans to a common area",
          "description": "Assigns calling plans to a common area.\n\n**Prerequisites**\n* Pro or a higher account with Zoom Phone license\n* Account owner or admin permissions\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:common_area_calling_plan:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rat[...]",
          "operationId": "assignCallingPlansToCommonArea",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:write:common_area_calling_plan:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:write:common_area_calling_plan:admin"
            ]
          }
        }
      },
      "/phone/common_areas/{commonAreaId}/calling_plans/{type}": {
        "delete": {
          "tags": [
            "Common Areas"
          ],
          "summary": "Unassign a calling plan from the common area",
          "description": "Use this API to unassign a calling plan from the common area.\n\n**Prerequisites:** \n* A Pro or higher account with a Zoom Phone license \n* An account owner or admin permissions \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:delete:common_area_calling_plan:admin`\n\n**[Rate Limit Label](https://marketplac[...]",
          "operationId": "unassignCallingPlansFromCommonArea",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:delete:common_area_calling_plan:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:delete:common_area_calling_plan:admin"
            ]
          }
        }
      },
      "/phone/common_areas/{commonAreaId}/phone_numbers": {
        "post": {
          "tags": [
            "Common Areas"
          ],
          "summary": "Assign phone numbers to a common area",
          "description": "Assigns phone numbers to a common area.\n\n**Prerequisites**\n* Pro or a higher account with Zoom Phone license\n* Account owner or admin permissions\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:common_area_number:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limi[...]",
          "operationId": "assignPhoneNumbersToCommonArea",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:write:common_area_number:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:write:common_area_number:admin"
            ]
          }
        }
      },
      "/phone/common_areas/{commonAreaId}/phone_numbers/{phoneNumberId}": {
        "delete": {
          "tags": [
            "Common Areas"
          ],
          "summary": "Unassign phone numbers from common area",
          "description": "Unassigns a phone number from a common area.\n\n**Prerequisites**\n* A Pro or a higher account with a Zoom Phone license\n* An account owner or admin permissions\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:delete:common_area_number:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-refere[...]",
          "operationId": "unassignPhoneNumbersFromCommonArea",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:delete:common_area_number:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:delete:common_area_number:admin"
            ]
          }
        }
      },
      "/phone/common_areas/{commonAreaId}/pin_code": {
        "patch": {
          "tags": [
            "Common Areas"
          ],
          "summary": "Update common area pin code",
          "description": "Updates the common area pin code.\n\n**Prerequisites**\n\n* Pro or a higher account with Zoom Phone license\n* Account owner or admin permissions, This depends on whether [The PIN cannot be viewed by the admin](https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0069783) is enabled.  \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrati[...]",
          "operationId": "UpdateCommonAreaPinCode",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:update:common_area:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:update:common_area:admin"
            ]
          }
        }
      },
      "/phone/common_areas/{commonAreaId}/settings": {
        "get": {
          "tags": [
            "Common Areas"
          ],
          "summary": "Get common area settings",
          "description": "Returns common area settings.\n\n**Prerequisites:**\n* Pro or a higher account with Zoom Phone license.\n* Account owner or admin permissions.\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:list_common_area_settings:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits[...]",
          "operationId": "getCommonAreaSettings",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:list_common_area_settings:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:list_common_area_settings:admin"
            ]
          }
        }
      },
      "/phone/common_areas/{commonAreaId}/settings/{settingType}": {
        "post": {
          "tags": [
            "Common Areas"
          ],
          "summary": "Add common area setting",
          "description": "Adds the common area setting according to the setting type, specifically for desk phones.\n\n**Prerequisites**\n* Pro or a higher account with Zoom Phone license\n* Account owner or admin permissions\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:common_area_setting:admin`\n\n**[Rate Limit Label](https[...]",
          "operationId": "AddCommonAreaSetting",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:write:common_area_setting:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:write:common_area_setting:admin"
            ]
          }
        },
        "delete": {
          "tags": [
            "Common Areas"
          ],
          "summary": "Delete common area setting",
          "description": "Removes the common area subsetting from desk phones. \n\n**Prerequisites**\n* Pro or a higher account with Zoom Phone license\n* Account owner or admin permissions\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:delete:common_area_setting:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-ref[...]",
          "operationId": "deleteCommonAreaSetting",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:delete:common_area_setting:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:delete:common_area_setting:admin"
            ]
          }
        },
        "patch": {
          "tags": [
            "Common Areas"
          ],
          "summary": "Update common area setting",
          "description": "Updates the common area setting according to the setting type, specifically for desk phones.\n\n**Prerequisites**\n* Pro or a higher account with Zoom Phone license\n* Account owner or admin permissions\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:update:common_area_setting:admin`\n\n**[Rate Limit Label](h[...]",
          "operationId": "UpdateCommonAreaSetting",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:update:common_area_setting:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:update:common_area_setting:admin"
            ]
          }
        }
      },
      "/phone/metrics/call_logs": {
        "get": {
          "tags": [
            "Dashboard"
          ],
          "summary": "List call logs",
          "description": "Returns monthly call logs metrics.\n\nThe call logs that provide a record of all incoming and outgoing calls over Zoom Phone in an account. \n\nYou can use query parameters to filter the response by date, site and MOS(Mean Opinion Score) of the call. \n\n**Prerequisites:**\n* Business or Education account\n* Zoom Phone license \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://deve[...]",
          "operationId": "listCallLogsMetrics",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:list_call_logs:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:list_call_logs:admin"
            ]
          }
        }
      },
      "/phone/metrics/call_logs/{callId}/qos": {
        "get": {
          "tags": [
            "Dashboard"
          ],
          "summary": "Get call QoS",
          "description": "Gets the call quality of service (QoS) data for a call made or received by a Zoom phone user in the account. \n\n**Prerequisites:**\n* Business, or Education account\n* Zoom Phone license   \n   \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:call_qos:admin`\n\n**[Rate Limit Label](https://marketplace.z[...]",
          "operationId": "getCallQoS",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:call_qos:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:call_qos:admin"
            ]
          }
        }
      },
      "/phone/metrics/call_logs/{call_id}": {
        "get": {
          "tags": [
            "Dashboard"
          ],
          "summary": "Get call details from call log",
          "description": "Returns call log details of a specific call. \n\nThe call logs provide a record of all incoming and outgoing calls over Zoom Phone in an account.\n\n **Prerequisites:**\n * Business, or Education account\n * Zoom Phone license \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:call_log:admin`",
          "operationId": "getCallLogMetricsDetails",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:call_log:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:call_log:admin"
            ]
          }
        }
      },
      "/phone/metrics/emergency_services/default_emergency_address/users": {
        "get": {
          "tags": [
            "Dashboard"
          ],
          "summary": "List default emergency address users",
          "description": "Returns the users who provide a default personal emergency address rather than a default site address or default account address.   \n\n**Prerequisites:** \n* Pro or higher account plan with Zoom phone license \n* Account owner or admin permissions\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:default_emerg[...]",
          "operationId": "listUserDefaultEmergencyAddress",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:default_emergency_address:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:default_emergency_address:admin"
            ]
          }
        }
      },
      "/phone/metrics/emergency_services/detectable_personal_location/users": {
        "get": {
          "tags": [
            "Dashboard"
          ],
          "summary": "List detectable personal location users",
          "description": "Returns the users who created one or more detectable personal locations with associated network data. (Exclude users didn't enable Location Permission on client.) \n\n**Prerequisites:** \n* Pro or higher account plan with Zoom phone license \n* Account owner or admin permissions\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview[...]",
          "operationId": "listUserDetectablePersonalLocation",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:detectable_personal_location:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:detectable_personal_location:admin"
            ]
          }
        }
      },
      "/phone/metrics/emergency_services/location_sharing_permission/users": {
        "get": {
          "tags": [
            "Dashboard"
          ],
          "summary": "List users permission for location sharing",
          "description": "Returns users that have enabled location services and allowed location sharing with Zoom applications on client devices. \n\n(Excludes users who are unable to use Nomadic Emergency Services, or users on client versions lower than 5.4.0.) \n\n**Prerequisites:** \n* Pro or higher account plan with Zoom phone license \n* Account owner or admin permissions\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular[...]",
          "operationId": "listUserLocationSharingPermission",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:location_sharing_permission:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:location_sharing_permission:admin"
            ]
          }
        }
      },
      "/phone/metrics/emergency_services/nomadic_emergency_services/users": {
        "get": {
          "tags": [
            "Dashboard"
          ],
          "summary": "List nomadic emergency services users",
          "description": "Returns users who have been enabled for nomadic emergency services.\n\n**Prerequisites:** \n* Pro or higher account plan with Zoom phone license \n* Account owner or admin permissions\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:nomadic_emergency_services:admin`\n\n**[Rate Limit Label](https://marketplace.[...]",
          "operationId": "listUserNomadicEmergencyServices",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:nomadic_emergency_services:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:nomadic_emergency_services:admin"
            ]
          }
        }
      },
      "/phone/metrics/emergency_services/realtime_location/devices": {
        "get": {
          "tags": [
            "Dashboard"
          ],
          "summary": "List real time location for IP phones",
          "description": "Returns currently detected location of IP phones.\n\n**Prerequisites:** \n* Pro or higher account plan with Zoom phone license \n* Account owner or admin permissions\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:realtime_location_devices:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-re[...]",
          "operationId": "listPhoneRealtimelocation",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:realtime_location_devices:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:realtime_location_devices:admin"
            ]
          }
        }
      },
      "/phone/metrics/emergency_services/realtime_location/users": {
        "get": {
          "tags": [
            "Dashboard"
          ],
          "summary": "List real time location for users",
          "description": "Returns the user's currently detected location. (Excludes users who didn't enable location permission on the client.)  \n\n**Prerequisites:** \n* Pro or higher account plan with Zoom phone license \n* Account owner or admin permissions\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:realtime_location_users:ad[...]",
          "operationId": "listUserRealtimeLocation",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:realtime_location_users:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:realtime_location_users:admin"
            ]
          }
        }
      },
      "/phone/metrics/location_tracking": {
        "get": {
          "tags": [
            "Dashboard"
          ],
          "summary": "List tracked locations",
          "description": "Lists the tracked locations. \n\n**Prerequisites:**\n* Pro or higher account plan with Zoom phone license\n* Account owner or admin permissions\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:list_tracked_locations:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#r[...]",
          "operationId": "listTrackedLocations",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:list_tracked_locations:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:list_tracked_locations:admin"
            ]
          }
        }
      },
      "/phone/metrics/past_calls": {
        "get": {
          "tags": [
            "Dashboard"
          ],
          "summary": "List past call metrics",
          "description": " Returns all the call logs metrics of the account from the selected time period. The call logs provide a record of all incoming and outgoing calls over Zoom Phone in an account. You can use query parameters to filter the response by metrics of the call (such as date, phone number, extension number and quality type). \n\n**Prerequisites:**\n* Business, or Education account\n* Zoom Phone license \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-[...]",
          "operationId": "listPastCallMetrics",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:list_call_logs:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:list_call_logs:admin"
            ]
          }
        }
      },
      "/phone/devices/{deviceId}/line_keys": {
        "get": {
          "tags": [
            "Device Line Keys"
          ],
          "summary": "Get device line keys information",
          "description": "Use this API to get information on the Zoom Phone device [line keys](https://support.zoom.us/hc/en-us/articles/4402415568397-Customizing-keys-for-devices-with-multiple-users) settings and position.\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`,`phone:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oa[...]",
          "operationId": "listDeviceLineKeySetting",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read",
                "phone:read:device_line_keys",
                "phone:read:device_line_keys:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:read:admin",
              "phone:read"
            ],
            "x-granular-scopes": [
              "phone:read:device_line_keys",
              "phone:read:device_line_keys:admin"
            ]
          }
        },
        "patch": {
          "tags": [
            "Device Line Keys"
          ],
          "summary": "Batch update device line key position",
          "description": "Use this API to batch update the Zoom Phone device [line key position](https://support.zoom.us/hc/en-us/articles/4402415568397-Customizing-keys-for-devices-with-multiple-users) information.\n\n**Prerequisites:** \n* A Business or Enterprise account \n* A Zoom Phone license\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`,`phone:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-sc[...]",
          "operationId": "batchUpdateDeviceLineKeySetting",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:write",
                "phone:update:device_line_keys",
                "phone:update:device_line_keys:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:write:admin",
              "phone:write"
            ],
            "x-granular-scopes": [
              "phone:update:device_line_keys",
              "phone:update:device_line_keys:admin"
            ]
          }
        }
      },
      "/phone/dial_by_name_directory/extensions": {
        "get": {
          "tags": [
            "Dial by Name Directory"
          ],
          "summary": "List users in directory",
          "description": "Use this API to get users that are in or not in a [directory](https://support.zoom.us/hc/en-us/articles/4404938949389-Using-a-dial-by-name-directory).\n\n**Prerequisites:**\n* Business or Education account\n* Zoom Phone license \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:directory:admin`\n\n**[Rate L[...]",
          "operationId": "ListUsersFromDirectory",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:directory:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:directory:admin"
            ]
          }
        },
        "post": {
          "tags": [
            "Dial by Name Directory"
          ],
          "summary": "Add users to a directory",
          "description": "Use this API to add users to a [directory](https://support.zoom.us/hc/en-us/articles/4404938949389-Using-a-dial-by-name-directory).\n\n**Prerequisites:**\n* Business or Education account\n* Zoom Phone license \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:directory:admin`\n\n**[Rate Limit Label](https[...]",
          "operationId": "AddUsersToDirectory",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:write:directory:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:write:directory:admin"
            ]
          }
        },
        "delete": {
          "tags": [
            "Dial by Name Directory"
          ],
          "summary": "Delete users from a directory",
          "description": "Use this API to delete users from the [directory](https://support.zoom.us/hc/en-us/articles/4404938949389-Using-a-dial-by-name-directory).\n\n**Prerequisites:**\n* Business or Education account\n* Zoom Phone license \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:delete:directory:admin`\n\n**[Rate Limit Labe[...]",
          "operationId": "DeleteUsersFromDirectory",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:delete:directory:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:delete:directory:admin"
            ]
          }
        }
      },
      "/phone/sites/{siteId}/dial_by_name_directory/extensions": {
        "get": {
          "tags": [
            "Dial by Name Directory"
          ],
          "summary": "List users in a directory by site",
          "description": "Use this API to get users that are in or not in a [directory](https://support.zoom.us/hc/en-us/articles/4404938949389-Using-a-dial-by-name-directory) of the specified site.\n\n**Prerequisites:**\n* Business or Education account\n* Zoom Phone license \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:directo[...]",
          "operationId": "ListUsersFromDirectoryBySite",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:directory:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:directory:admin"
            ]
          }
        },
        "post": {
          "tags": [
            "Dial by Name Directory"
          ],
          "summary": "Add users to a directory of a site",
          "description": "Use this API to add users to a [directory](https://support.zoom.us/hc/en-us/articles/4404938949389-Using-a-dial-by-name-directory) of the specified site.\n\n**Prerequisites:**\n* Business or Education account\n* Zoom Phone license \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:directory:admin`\n\n**[R[...]",
          "operationId": "AddUsersToDirectoryBySite",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:write:directory:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:write:directory:admin"
            ]
          }
        },
        "delete": {
          "tags": [
            "Dial by Name Directory"
          ],
          "summary": "Delete users from a directory of a site",
          "description": "Use this API to delete users from a [directory](https://support.zoom.us/hc/en-us/articles/4404938949389-Using-a-dial-by-name-directory) of the specified site.\n\n**Prerequisites:**\n* Business or Education account\n* Zoom Phone license \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:delete:directory:admin`\n[...]",
          "operationId": "DeleteUsersFromDirectoryBySite",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:delete:directory:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:delete:directory:admin"
            ]
          }
        }
      },
      "/phone/emergency_addresses": {
        "get": {
          "tags": [
            "Emergency Addresses"
          ],
          "summary": "List emergency addresses",
          "description": "Lists the emergency addresses.\n\n**Prerequisites:** \n* Pro or a higher account with Zoom Phone license \n* Account owner or admin permissions\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:list_emergency_addresses:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rat[...]",
          "operationId": "listEmergencyAddresses",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:list_emergency_addresses:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:list_emergency_addresses:admin"
            ]
          }
        },
        "post": {
          "tags": [
            "Emergency Addresses"
          ],
          "summary": "Add an emergency address",
          "description": "Adds an emergency address. If the address provided is not an exact match, the system generated corrected address will be used. \n\n**Prerequisites:** \n* Pro or a higher account with Zoom Phone license \n* Account owner or admin permissions\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:emergency_address:a[...]",
          "operationId": "addEmergencyAddress",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:write:emergency_address:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:write:emergency_address:admin"
            ]
          }
        }
      },
      "/phone/emergency_addresses/{emergencyAddressId}": {
        "get": {
          "tags": [
            "Emergency Addresses"
          ],
          "summary": "Get emergency address details",
          "description": "Gets the emergency address information.\n\n**Prerequisites:** \n* Pro or a higher account with Zoom Phone license \n* Account owner or admin permissions  \n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:emergency_address:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-lim[...]",
          "operationId": "getEmergencyAddress",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:emergency_address:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:emergency_address:admin"
            ]
          }
        },
        "delete": {
          "tags": [
            "Emergency Addresses"
          ],
          "summary": "Delete an emergency address",
          "description": "Removes an emergency address.\n\n**Prerequisites:** \n* Pro or a higher account with Zoom Phone license \n* Account owner or admin permissions\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:delete:emergency_address:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-lim[...]",
          "operationId": "deleteEmergencyAddress",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:delete:emergency_address:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:delete:emergency_address:admin"
            ]
          }
        },
        "patch": {
          "tags": [
            "Emergency Addresses"
          ],
          "summary": "Update an emergency address",
          "description": "Updates an emergency address information. If the address provided is not an exact match, the system generated corrected address will be used. \n\n**Prerequisites:** \n* Pro or a higher account with Zoom Phone license \n* Account owner or admin permissions\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:update:eme[...]",
          "operationId": "updateEmergencyAddress",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:update:emergency_address:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:update:emergency_address:admin"
            ]
          }
        }
      },
      "/phone/batch_locations": {
        "post": {
          "tags": [
            "Emergency Service Locations"
          ],
          "summary": "Batch add emergency service locations",
          "description": "Adds emergency service locations in batch. \n\n**Prerequisites:**\n* Pro or higher account plan with Zoom phone license\n* Account owner or admin permissions\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:batch_emergency_locations:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-refe[...]",
          "operationId": "batchAddLocations",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:write:batch_emergency_locations:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:write:batch_emergency_locations:admin"
            ]
          }
        }
      },
      "/phone/locations": {
        "get": {
          "tags": [
            "Emergency Service Locations"
          ],
          "summary": "List emergency service locations",
          "description": "Returns emergency service locations. \n**Note**: When you enable [multiple sites](https://support.zoom.us/hc/en-us/articles/360020809672-Managing-multiple-sites), the `site_id` parameter is required.\n\n**Prerequisites:** \n* Pro or a higher account with Zoom Phone license \n* Account owner or admin permissions\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/i[...]",
          "operationId": "listLocations",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:list_emergency_locations:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:list_emergency_locations:admin"
            ]
          }
        },
        "post": {
          "tags": [
            "Emergency Service Locations"
          ],
          "summary": "Add an emergency service location",
          "description": "Adds an emergency service location.\n\n**Prerequisites:** \n* Pro or a higher account with Zoom Phone license \n* Account owner or admin permissions\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:emergency_location:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limit[...]",
          "operationId": "addLocation",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:write:emergency_location:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:write:emergency_location:admin"
            ]
          }
        }
      },
      "/phone/locations/{locationId}": {
        "get": {
          "tags": [
            "Emergency Service Locations"
          ],
          "summary": "Get emergency service location details",
          "description": "Returns an emergency service location's information.\n\n**Prerequisites:** \n* Pro or a higher account with Zoom Phone license \n* Account owner or admin permissions\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:emergency_location:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference[...]",
          "operationId": "getLocation",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:emergency_location:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:emergency_location:admin"
            ]
          }
        },
        "delete": {
          "tags": [
            "Emergency Service Locations"
          ],
          "summary": "Delete an emergency location",
          "description": "Removes an emergency location.\n\n**Prerequisites:** \n* Pro or a higher account with Zoom Phone license \n* Account owner or admin permissions\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:delete:emergency_location:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-l[...]",
          "operationId": "deleteLocation",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:delete:emergency_location:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:delete:emergency_location:admin"
            ]
          }
        },
        "patch": {
          "tags": [
            "Emergency Service Locations"
          ],
          "summary": "Update emergency service location",
          "description": "Updates an emergency location's information.\n\n**Prerequisites:** \n* Pro or a higher account with Zoom Phone license \n* Account owner or admin permissions\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:update:emergency_location:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate[...]",
          "operationId": "updateLocation",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:update:emergency_location:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:update:emergency_location:admin"
            ]
          }
        }
      },
      "/phone/external_contacts": {
        "get": {
          "tags": [
            "External Contacts"
          ],
          "summary": "List external contacts",
          "description": "Lists the external contacts.\n\n**Prerequisites** \n* Pro or a higher account with Zoom Phone license \n* Account owner or admin permissions\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:list_external_contacts:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-lim[...]",
          "operationId": "listExternalContacts",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:list_external_contacts:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:list_external_contacts:admin"
            ]
          }
        },
        "post": {
          "tags": [
            "External Contacts"
          ],
          "summary": "Add an external contact",
          "description": "Adds an external contact.\n\n**Prerequisites** \n* Pro or a higher account with Zoom Phone license \n* Account owner or admin permissions\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:external_contact:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**[...]",
          "operationId": "addExternalContact",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:write:external_contact:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:write:external_contact:admin"
            ]
          }
        }
      },
      "/phone/external_contacts/{externalContactId}": {
        "get": {
          "tags": [
            "External Contacts"
          ],
          "summary": "Get external contact details",
          "description": "Returns an external contact's information.\n\n**Prerequisites** \n* Pro or a higher account with Zoom Phone license \n* Account owner or admin permissions  \n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:external_contact:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-li[...]",
          "operationId": "getAExternalContact",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:external_contact:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:external_contact:admin"
            ]
          }
        },
        "delete": {
          "tags": [
            "External Contacts"
          ],
          "summary": "Delete an external contact",
          "description": "Removes an external contact.\n\n**Prerequisites:** \n* Pro or a higher account with Zoom Phone license \n* Account owner or admin permissions\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:delete:external_contact:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limit[...]",
          "operationId": "deleteAExternalContact",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:delete:external_contact:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:delete:external_contact:admin"
            ]
          }
        },
        "patch": {
          "tags": [
            "External Contacts"
          ],
          "summary": "Update external contact",
          "description": "Updates an external contact's information.\n\n**Prerequisites** \n* Pro or a higher account with Zoom Phone license \n* Account owner or admin permissions\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:update:external_contact:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limi[...]",
          "operationId": "updateExternalContact",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:update:external_contact:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:update:external_contact:admin"
            ]
          }
        }
      },
      "/phone/extension/{extensionId}/fax/logs": {
        "get": {
          "tags": [
            "Fax"
          ],
          "summary": "Get extension's fax logs",
          "description": "Returns the extension's fax logs.\n\n**Prerequisites**\n* User must belong to a Business or Enterprise account.\n* User must have a Zoom Phone license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read`,`phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:list_fax_log`,`phone:read:list_fax_log:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us[...]",
          "operationId": "Getuser'sfaxlogs",
          "security": [
            {
              "openapi_oauth": [
                "phone:read",
                "phone:read:admin",
                "phone:read:list_fax_log",
                "phone:read:list_fax_log:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read",
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:list_fax_log",
              "phone:read:list_fax_log:admin"
            ]
          }
        }
      },
      "/phone/fax/logs": {
        "get": {
          "tags": [
            "Fax"
          ],
          "summary": "Get account's fax logs",
          "description": "Returns the account's fax logs.\n\n**Prerequisites**\n* User must belong to a Business or Enterprise account.\n* User must have a Zoom Phone license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:list_fax_log:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limi[...]",
          "operationId": "GetAccount'sFaxLogs",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:list_fax_log:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:list_fax_log:admin"
            ]
          }
        }
      },
      "/phone/fax/logs/{faxLogId}": {
        "get": {
          "tags": [
            "Fax"
          ],
          "summary": "Get fax log details",
          "description": "Returns the fax log's details.\n\n**Prerequisites**\n* User must belong to a Business or Enterprise account.\n* User must have a Zoom Phone license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:list_fax_log:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limit[...]",
          "operationId": "GetFaxLogDetails",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:list_fax_log:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:list_fax_log:admin"
            ]
          }
        }
      },
      "/phone/fax/logs/{faxLogId}/file/{fileId}": {
        "get": {
          "tags": [
            "Fax"
          ],
          "summary": "Download fax file",
          "description": "Downloads the fax file.\n\n**Prerequisites*\n* User must belong to a Business or Enterprise account.\n* User must have a Zoom Phone license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read`,`phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:fax_log`,`phone:read:fax_log:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/r[...]",
          "operationId": "Downloadfaxfile",
          "security": [
            {
              "openapi_oauth": [
                "phone:read",
                "phone:read:admin",
                "phone:read:fax_log",
                "phone:read:fax_log:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read",
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:fax_log",
              "phone:read:fax_log:admin"
            ]
          }
        }
      },
      "/phone/firmware_update_rules": {
        "get": {
          "tags": [
            "Firmware Update Rules"
          ],
          "summary": "List firmware update rules",
          "description": "Use this API to get [firmware update rules](https://support.zoom.us/hc/en-us/articles/360054198852-Setting-up-firmware-update-rules).\n\n**Prerequisites:**\n* Business or Education account\n* Zoom Phone license \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:list_firmware_update_rules:admin`\n\n**[Rate L[...]",
          "operationId": "ListFirmwareRules",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:list_firmware_update_rules:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:list_firmware_update_rules:admin"
            ]
          }
        },
        "post": {
          "tags": [
            "Firmware Update Rules"
          ],
          "summary": "Add a firmware update rule",
          "description": "Use this API to add a [firmware update rule](https://support.zoom.us/hc/en-us/articles/360054198852-Setting-up-firmware-update-rules).\n\n**Prerequisites:**\n* Business, or Education account\n* Zoom Phone license \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:firmware_update_rule:admin`\n\n**[Rate Lim[...]",
          "operationId": "AddFirmwareRule",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:write:firmware_update_rule:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:write:firmware_update_rule:admin"
            ]
          }
        }
      },
      "/phone/firmware_update_rules/{ruleId}": {
        "get": {
          "tags": [
            "Firmware Update Rules"
          ],
          "summary": "Get firmware update rule information",
          "description": "Use this API to get the [firmware update rule](https://support.zoom.us/hc/en-us/articles/360054198852-Setting-up-firmware-update-rules) information.\n\n**Prerequisites:**\n* Business or Education account\n* Zoom Phone license \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:firmware_update_rule:admin`\n\n[...]",
          "operationId": "GetFirmwareRuleDetail",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:firmware_update_rule:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:firmware_update_rule:admin"
            ]
          }
        },
        "delete": {
          "tags": [
            "Firmware Update Rules"
          ],
          "summary": "Delete firmware update rule",
          "description": "Use this API to delete the [firmware update rule](https://support.zoom.us/hc/en-us/articles/360054198852-Setting-up-firmware-update-rules).\n\n**Prerequisites:**\n* Business or Education account\n* Zoom Phone license \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:delete:firmware_update_rule:admin`\n\n**[Rat[...]",
          "operationId": "DeleteFirmwareUpdateRule",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:delete:firmware_update_rule:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:delete:firmware_update_rule:admin"
            ]
          }
        },
        "patch": {
          "tags": [
            "Firmware Update Rules"
          ],
          "summary": "Update firmware update rule",
          "description": "Use this API to update a specific [firmware update rule](https://support.zoom.us/hc/en-us/articles/360054198852-Setting-up-firmware-update-rules).\n\n**Prerequisites:**\n* Business, or Education account\n* Zoom Phone license \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:update:firmware_update_rule:admin`\n[...]",
          "operationId": "UpdateFirmwareRule",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:update:firmware_update_rule:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:update:firmware_update_rule:admin"
            ]
          }
        }
      },
      "/phone/firmwares": {
        "get": {
          "tags": [
            "Firmware Update Rules"
          ],
          "summary": "List updatable firmwares",
          "description": "Use this API to get updatable [firmwares](https://support.zoom.us/hc/en-us/articles/360054198852-Setting-up-firmware-update-rules).\n\n**Prerequisites:**\n* Business or Education account\n* Zoom Phone license \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:list_firmwares:admin`\n\n**[Rate Limit Label](ht[...]",
          "operationId": "ListFirmwares",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:list_firmwares:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:list_firmwares:admin"
            ]
          }
        }
      },
      "/phone/group_call_pickup": {
        "get": {
          "tags": [
            "Group Call Pickup"
          ],
          "summary": "List group call pickup objects",
          "description": "Use this API to retrieve a list of [Group Call Pickup](https://support.zoom.us/hc/en-us/articles/360060107472-Setting-up-and-using-group-call-pickup) objects in an account.\n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:list_[...]",
          "operationId": "listGCP",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:list_call_pickup_groups:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:list_call_pickup_groups:admin"
            ]
          }
        },
        "post": {
          "tags": [
            "Group Call Pickup"
          ],
          "summary": "Add a group call pickup object",
          "description": "Use this API to add a [Group Call Pickup](https://support.zoom.us/hc/en-us/articles/360060107472-Setting-up-and-using-group-call-pickup) instance to the account that has the Zoom Phone license assigned. \n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes[...]",
          "operationId": "addGCP",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:write:call_pickup_group:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:write:call_pickup_group:admin"
            ]
          }
        }
      },
      "/phone/group_call_pickup/{groupId}": {
        "get": {
          "tags": [
            "Group Call Pickup"
          ],
          "summary": "Get call pickup group by ID",
          "description": "Use this API to retrieve information on a specific [Group Call Pickup](https://support.zoom.us/hc/en-us/articles/360060107472-Setting-up-and-using-group-call-pickup) object in an account. \n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `[...]",
          "operationId": "GetGCP",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:call_pickup_group:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:call_pickup_group:admin"
            ]
          }
        },
        "delete": {
          "tags": [
            "Group Call Pickup"
          ],
          "summary": "Delete group call pickup objects",
          "description": "Use this API to remove a [Group Call Pickup](https://support.zoom.us/hc/en-us/articles/360060107472-Setting-up-and-using-group-call-pickup) object.\n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:delete:call_pickup_group:admin`\n\[...]",
          "operationId": "deleteGCP",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:delete:call_pickup_group:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:delete:call_pickup_group:admin"
            ]
          }
        },
        "patch": {
          "tags": [
            "Group Call Pickup"
          ],
          "summary": "Update the group call pickup information",
          "description": "Use this API to update a specific [Group Call Pickup](https://support.zoom.us/hc/en-us/articles/360060107472-Setting-up-and-using-group-call-pickup) object information.\n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:update:call_p[...]",
          "operationId": "updateGCP",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:update:call_pickup_group:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:update:call_pickup_group:admin"
            ]
          }
        }
      },
      "/phone/group_call_pickup/{groupId}/members": {
        "get": {
          "tags": [
            "Group Call Pickup"
          ],
          "summary": "List call pickup group members",
          "description": "Use this API to retrieve members of a [call pickup group](https://support.zoom.us/hc/en-us/articles/360060107472-Setting-up-and-using-group-call-pickup) in an account.\n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:call_picku[...]",
          "operationId": "listGCPMembers",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:call_pickup_group_member:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:call_pickup_group_member:admin"
            ]
          }
        },
        "post": {
          "tags": [
            "Group Call Pickup"
          ],
          "summary": "Add members to a call pickup group",
          "description": "Use this API to add members to the specified [Group Call Pickup](https://support.zoom.us/hc/en-us/articles/360060107472-Setting-up-and-using-group-call-pickup) object. \n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:call_pi[...]",
          "operationId": "addGCPMembers",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:write:call_pickup_group_member:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:write:call_pickup_group_member:admin"
            ]
          }
        }
      },
      "/phone/group_call_pickup/{groupId}/members/{extensionId}": {
        "delete": {
          "tags": [
            "Group Call Pickup"
          ],
          "summary": "Remove members from call pickup group",
          "description": "Use this API to remove member from the [Group Call Pickup](https://support.zoom.us/hc/en-us/articles/360060107472-Setting-up-and-using-group-call-pickup) object. \n\n**Prerequisites:** \n* A Pro or higher account plan \n* A Zoom Phone license\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:delete:call_pickup_[...]",
          "operationId": "removeGCPMembers",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:delete:call_pickup_group_member:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:delete:call_pickup_group_member:admin"
            ]
          }
        }
      },
      "/phone/groups/{groupId}/policies/{policyType}": {
        "get": {
          "tags": [
            "Groups"
          ],
          "summary": "Get group policy details",
          "description": "Returns the group policy details.\n\n**Prerequisites**\nPro or higher account plan with Zoom phone license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:group_policy:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
          "operationId": "GetGroupPolicyDetails",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:group_policy:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:group_policy:admin"
            ]
          }
        },
        "patch": {
          "tags": [
            "Groups"
          ],
          "summary": "Update group policy",
          "description": "Updates the group policy.\n\n**Prerequisites** \n* A Business or Enterprise account \n* A Zoom Phone license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:update:group_policy:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
          "operationId": "updateGroupPolicy",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:update:group_policy:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:update:group_policy:admin"
            ]
          }
        }
      },
      "/phone/groups/{groupId}/settings": {
        "get": {
          "tags": [
            "Groups"
          ],
          "summary": "Get group phone settings",
          "description": "Returns group phone settings.\n\n**Prerequisites**\n Account must have a Pro or a higher plan with Zoom Phone license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:group_setting:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
          "operationId": "getGroupPhoneSettings",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:group_setting:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:group_setting:admin"
            ]
          }
        }
      },
      "/phone/auto_receptionists/{autoReceptionistId}/ivr": {
        "get": {
          "tags": [
            "IVR"
          ],
          "summary": "Get auto receptionist IVR",
          "description": "Gets an [interactive voice response (IVR) system](https://support.zoom.us/hc/en-us/articles/360038601971) of the specified auto receptionist.\n\n**Prerequisites:**\n * A Business or Enterprise account \n* A Zoom Phone license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:auto_receptionist_ivr:admin`\n\n**[R[...]",
          "operationId": "getAutoReceptionistIVR",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:auto_receptionist_ivr:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:auto_receptionist_ivr:admin"
            ]
          }
        },
        "patch": {
          "tags": [
            "IVR"
          ],
          "summary": "Update auto receptionist IVR",
          "description": "Updates the [interactive voice response (IVR) system](https://support.zoom.us/hc/en-us/articles/360038601971) of the specified auto receptionist.\n\n**Prerequisites:**\n * A Business or Enterprise account \n* A Zoom Phone license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:update:auto_receptionist_ivr:admin`\[...]",
          "operationId": "updateAutoReceptionistIVR",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:update:auto_receptionist_ivr:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:update:auto_receptionist_ivr:admin"
            ]
          }
        }
      },
      "/phone/extension/{extensionId}/inbound_blocked/rules": {
        "get": {
          "tags": [
            "Inbound Blocked List"
          ],
          "summary": "List an extension's inbound block rules",
          "description": "Returns a list of the given extension's block rule for inbound calls and messaging. \n\nit lists inbound block rule for the given Call Queue, Auto Receptionist, Shared Line Group, Common Area, Zoom Room, or User.\n\n**Prerequisites:**\n* Pro or a higher account with Zoom Phone license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`,`phone:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oa[...]",
          "operationId": "ListExtensionLevelInboundBlockRules",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read",
                "phone:read:list_extension_inbound_block_rules:admin",
                "phone:read:list_extension_inbound_block_rules"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin",
              "phone:read"
            ],
            "x-granular-scopes": [
              "phone:read:list_extension_inbound_block_rules:admin",
              "phone:read:list_extension_inbound_block_rules"
            ]
          }
        },
        "post": {
          "tags": [
            "Inbound Blocked List"
          ],
          "summary": "Add an extension's inbound block rule",
          "description": "Adds the given extension's block rule for inbound calls and messaging. \n\nIt adds the inbound block rule for the given Call Queue, Auto Receptionist, Shared Line Group, Common Area, Zoom Room or User.\n\n**Prerequisites:**\n* Pro or a higher account with Zoom Phone license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`,`phone:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scope[...]",
          "operationId": "AddExtensiontLevelInboundBlockRules",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:write",
                "phone:write:extension_inbound_block_rule:admin",
                "phone:write:extension_inbound_block_rule"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin",
              "phone:write"
            ],
            "x-granular-scopes": [
              "phone:write:extension_inbound_block_rule:admin",
              "phone:write:extension_inbound_block_rule"
            ]
          }
        },
        "delete": {
          "tags": [
            "Inbound Blocked List"
          ],
          "summary": "Delete an extension's inbound block rule",
          "description": "Deletes the given extension's blocked rule for inbound calls and messaging. \n\nUse this API to delete inbound blocked rule for the given Call Queue, Auto Receptionist, Shared Line Group, Common Area, Zoom Room or User.\n\n\n**Prerequisites:**\n* Pro or a higher account with Zoom Phone license\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`,`phone:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/inte[...]",
          "operationId": "DeleteExtensiontLevelInboundBlockRules",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:write",
                "phone:delete:extension_inbound_block_rule:admin",
                "phone:delete:extension_inbound_block_rule"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin",
              "phone:write"
            ],
            "x-granular-scopes": [
              "phone:delete:extension_inbound_block_rule:admin",
              "phone:delete:extension_inbound_block_rule"
            ]
          }
        }
      },
      "/phone/inbound_blocked/extension_rules/statistics": {
        "get": {
          "tags": [
            "Inbound Blocked List"
          ],
          "summary": "List an account's inbound blocked statistics",
          "description": "Returns the list of the statistics of the extensions blocked rule for inbound calls and messaging. (e.g. Call Queue, Auto Receptionist, Shared Line Group, Common Area, Zoom Room and User)\n\n**Prerequisites:**\n* Pro or higher account plan with Zoom phone license\n* Account owner or admin permissions\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations[...]",
          "operationId": "ListAccountLevelInboundBlockedStatistics",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:list_extension_inbound_block_rules_stat:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:list_extension_inbound_block_rules_stat:admin"
            ]
          }
        },
        "delete": {
          "tags": [
            "Inbound Blocked List"
          ],
          "summary": "Delete an account's inbound blocked statistics",
          "description": "Deletes the statistic of extensions blocked rule for inbound calls and messaging. (e.g. Call Queue, Auto Receptionist, Shared Line Group, Common Area, Zoom Room and User)\n\n**Prerequisites:**\n* Pro or higher account plan with Zoom phone license\n* Account owner or admin permissions\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-ov[...]",
          "operationId": "DeleteAccountLevelInboundBlockedStatistics",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:delete:extension_inbound_block_rule_stat:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:delete:extension_inbound_block_rule_stat:admin"
            ]
          }
        }
      },
      "/phone/inbound_blocked/extension_rules/statistics/blocked_for_all": {
        "patch": {
          "tags": [
            "Inbound Blocked List"
          ],
          "summary": "Mark a phone number as blocked for all extensions",
          "description": "Promotes and applies the phone number blocked from the extension level blocked rule to the account level blocked rule. This action is contingent on the statistics of extensions blocked rule. All extensions under the current account block this phone number.\n\n**Prerequisites:**\n* Pro or higher account plan with Zoom phone license\n* Account owner or admin permissions\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:ad[...]",
          "operationId": "MarkPhoneNumberAsBlockedForAllExtensions",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:update:inbound_blocked_for_all:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:update:inbound_blocked_for_all:admin"
            ]
          }
        }
      },
      "/phone/inbound_blocked/rules": {
        "get": {
          "tags": [
            "Inbound Blocked List"
          ],
          "summary": "List an account's inbound block rules",
          "description": "Returns a list of account level inbound block rule for inbound calls and messaging.\n\n**Prerequisites:**\n* Pro or a higher account with Zoom Phone license\n* Account owner or admin permissions\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:read:list_inbound_block_rules:admin`\n\n**[Rate Limit Label](https://mar[...]",
          "operationId": "ListAccountLevelInboundBlockRules",
          "security": [
            {
              "openapi_oauth": [
                "phone:read:admin",
                "phone:read:list_inbound_block_rules:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:read:admin"
            ],
            "x-granular-scopes": [
              "phone:read:list_inbound_block_rules:admin"
            ]
          }
        },
        "post": {
          "tags": [
            "Inbound Blocked List"
          ],
          "summary": "Add an account's inbound block rule",
          "description": "Adds an account level block rule for inbound calls and messaging from a phone number. As a result, all extensions block calls and messages to the phone number.\n\n**Prerequisites:**\n* Pro or a higher account with Zoom Phone license\n* Account owner or admin permissions\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `phone:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `p[...]",
          "operationId": "AddAccountLevelInboundBlockRules",
          "security": [
            {
              "openapi_oauth": [
                "phone:write:admin",
                "phone:write:inbound_block_rule:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "phone:write:admin"
            ],
            "x-granular-scopes": [
              "phone:write:inbound_block_rule:admin"
            ]
          }
        },
        "delete": {
          "tags": [
            "Inbound Blocked List"
          ],
          "summary": "Delete an account's inbound block rule",
[...]
