{
 "openapi": "3.0.0",
 "info": {
  "title": "Revenue Accelerator",
  "description": "The ZRA APIs allow developers to interface with [Zoom Revenue Accelerator](https://developers.zoom.us/docs/zra/) features programmatically. You may see references to 'Zoom IQ', this is Zoom Revenue Accelerator's former name.",
  "termsOfService": "https://zoom.us/docs/en-us/zoom_api_license_and_tou.html",
  "contact": {
   "name": "Zoom Developers",
   "url": "https://developer.zoom.us/"
  },
  "version": "2"
 },
 "servers": [
  {
   "url": "https://api.zoom.us/v2"
  }
 ],
 "paths": {
  "/iq/settings/indicators": {
   "get": {
    "tags": [
     "Accounts"
    ],
    "summary": "Get indicators settings [Deprecated]",
    "description": "Get the account's indicators settings. \n\n **Prerequisites:** \n* The account must be a paid account.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `account:read:admin`,`account:write:admin`,`iq_account:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:read:indicator`,`zra:read:indicator:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limit[...]",
    "operationId": "accountSettingsIndicatorsDeprecated",
    "deprecated": true,
    "security": [
     {
      "openapi_oauth": [
       "account:read:admin",
       "account:write:admin",
       "iq_account:read:admin",
       "zra:read:indicator",
       "zra:read:indicator:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "account:read:admin",
      "account:write:admin",
      "iq_account:read:admin"
     ],
     "x-granular-scopes": [
      "zra:read:indicator",
      "zra:read:indicator:admin"
     ]
    }
   }
  },
  "/zra/settings/indicators": {
   "get": {
    "tags": [
     "Accounts"
    ],
    "summary": "Get indicators settings",
    "description": "Get the account's indicators settings. \n\n **Prerequisites:** \n* The account must be a paid account.\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `account:read:admin`,`account:write:admin`,`iq_account:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:read:indicator`,`zra:read:indicator:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-l[...]",
    "operationId": "accountIndicatorsSettings",
    "security": [
     {
      "openapi_oauth": [
       "account:read:admin",
       "account:write:admin",
       "iq_account:read:admin",
       "zra:read:indicator",
       "zra:read:indicator:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "IQAccountSetting:Read"
     ],
     "x-macro-scopes": [
      "account:read:admin",
      "account:write:admin",
      "iq_account:read:admin"
     ],
     "x-granular-scopes": [
      "zra:read:indicator",
      "zra:read:indicator:admin"
     ]
    }
   }
  },
  "/iq/conversations": {
   "get": {
    "tags": [
     "Conversations"
    ],
    "summary": "List conversations [Deprecated]",
    "description": "List all conversations. \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_conversation:read`,`iq_conversation:write`,`iq_conversation:read:admin`,`iq_conversation:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:read:list_conversations`,`zra:read:list_conversations:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**[...]",
    "operationId": "listConversationsDeprecated",
    "deprecated": true,
    "security": [
     {
      "openapi_oauth": [
       "iq_conversation:read",
       "iq_conversation:write",
       "iq_conversation:read:admin",
       "iq_conversation:write:admin",
       "zra:read:list_conversations",
       "zra:read:list_conversations:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "AllConversations:Read"
     ],
     "x-macro-scopes": [
      "iq_conversation:read",
      "iq_conversation:write",
      "iq_conversation:read:admin",
      "iq_conversation:write:admin"
     ],
     "x-granular-scopes": [
      "zra:read:list_conversations",
      "zra:read:list_conversations:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Conversations"
    ],
    "summary": "Add conversation by file id or download url. [Deprecated]",
    "description": "Add conversation by file ID or third party download URL.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_conversation:write:admin`,`iq_conversation:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:write:conversation`,`zra:write:conversation:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "AddConversationByFileIdOrDownloadUrlDeprecated",
    "deprecated": true,
    "security": [
     {
      "openapi_oauth": [
       "iq_conversation:write:admin",
       "iq_conversation:write",
       "zra:write:conversation",
       "zra:write:conversation:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_conversation:write:admin",
      "iq_conversation:write"
     ],
     "x-granular-scopes": [
      "zra:write:conversation",
      "zra:write:conversation:admin"
     ]
    }
   }
  },
  "/iq/conversations/{conversationId}": {
   "get": {
    "tags": [
     "Conversations"
    ],
    "summary": "Get conversation information [Deprecated]",
    "description": "Get information for a specific conversation. \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_conversation:read`,`iq_conversation:write`,`iq_conversation:read:admin`,`iq_conversation:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:read:conversations:admin`,`zra:read:conversations`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate[...]",
    "operationId": "getConversationInfoDeprecated",
    "deprecated": true,
    "security": [
     {
      "openapi_oauth": [
       "iq_conversation:read",
       "iq_conversation:write",
       "iq_conversation:read:admin",
       "iq_conversation:write:admin",
       "zra:read:conversations:admin",
       "zra:read:conversations"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "AllConversations:Read"
     ],
     "x-macro-scopes": [
      "iq_conversation:read",
      "iq_conversation:write",
      "iq_conversation:read:admin",
      "iq_conversation:write:admin"
     ],
     "x-granular-scopes": [
      "zra:read:conversations:admin",
      "zra:read:conversations"
     ]
    }
   },
   "delete": {
    "tags": [
     "Conversations"
    ],
    "summary": "Delete conversation by conversation ID [Deprecated]",
    "description": "Delete conversation by conversation ID. \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_conversation:write:admin`,`iq_conversation:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:delete:conversations`,`zra:delete:conversations:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "deleteConversationDeprecated",
    "deprecated": true,
    "security": [
     {
      "openapi_oauth": [
       "iq_conversation:write:admin",
       "iq_conversation:write",
       "zra:delete:conversations",
       "zra:delete:conversations:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_conversation:write:admin",
      "iq_conversation:write"
     ],
     "x-granular-scopes": [
      "zra:delete:conversations",
      "zra:delete:conversations:admin"
     ]
    }
   }
  },
  "/iq/conversations/{conversationId}/comments": {
   "get": {
    "tags": [
     "Conversations"
    ],
    "summary": "Get conversation comments [Deprecated]",
    "description": "Get comments for a specific conversation. \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_comment:read`,`iq_comment:write`,`iq_comment:read:admin`,`iq_comment:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:read:list_conversation_comments`,`zra:read:list_conversation_comments:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#r[...]",
    "operationId": "getConversationCommentsDeprecated",
    "deprecated": true,
    "security": [
     {
      "openapi_oauth": [
       "iq_comment:read",
       "iq_comment:write",
       "iq_comment:read:admin",
       "iq_comment:write:admin",
       "zra:read:list_conversation_comments",
       "zra:read:list_conversation_comments:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_comment:read",
      "iq_comment:write",
      "iq_comment:read:admin",
      "iq_comment:write:admin"
     ],
     "x-granular-scopes": [
      "zra:read:list_conversation_comments",
      "zra:read:list_conversation_comments:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Conversations"
    ],
    "summary": "Add new comments to the conversation [Deprecated]",
    "description": "Add new comments to a specific conversation. \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_comment:write`,`iq_comment:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:write:conversation_comment`,`zra:write:conversation_comment:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "addConversationCommentDeprecated",
    "deprecated": true,
    "security": [
     {
      "openapi_oauth": [
       "iq_comment:write",
       "iq_comment:write:admin",
       "zra:write:conversation_comment",
       "zra:write:conversation_comment:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_comment:write",
      "iq_comment:write:admin"
     ],
     "x-granular-scopes": [
      "zra:write:conversation_comment",
      "zra:write:conversation_comment:admin"
     ]
    }
   }
  },
  "/iq/conversations/{conversationId}/comments/{commentId}": {
   "delete": {
    "tags": [
     "Conversations"
    ],
    "summary": "Delete conversation's comment [Deprecated]",
    "description": "Delete comment from a specific conversation. \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_comment:write`,`iq_comment:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:delete:conversation_comment`,`zra:delete:conversation_comment:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "deleteConversationCommentDeprecated",
    "deprecated": true,
    "security": [
     {
      "openapi_oauth": [
       "iq_comment:write",
       "iq_comment:write:admin",
       "zra:delete:conversation_comment",
       "zra:delete:conversation_comment:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_comment:write",
      "iq_comment:write:admin"
     ],
     "x-granular-scopes": [
      "zra:delete:conversation_comment",
      "zra:delete:conversation_comment:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Conversations"
    ],
    "summary": "Edit conversation comment [Deprecated]",
    "description": "Edit a comment for a specific conversation. \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_comment:write`,`iq_comment:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:update:conversation_comment`,`zra:update:conversation_comment:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "editConversationCommentDeprecated",
    "deprecated": true,
    "security": [
     {
      "openapi_oauth": [
       "iq_comment:write",
       "iq_comment:write:admin",
       "zra:update:conversation_comment",
       "zra:update:conversation_comment:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_comment:write",
      "iq_comment:write:admin"
     ],
     "x-granular-scopes": [
      "zra:update:conversation_comment",
      "zra:update:conversation_comment:admin"
     ]
    }
   }
  },
  "/iq/conversations/{conversationId}/content_analysis": {
   "get": {
    "tags": [
     "Conversations"
    ],
    "summary": "Get conversation content analysis [Deprecated]",
    "description": "Get the content analysis for a specific conversation. \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_conversation:read`,`iq_conversation:write`,`iq_conversation:read:admin`,`iq_conversation:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:read:conversation_analysis`,`zra:read:conversation_analysis:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-r[...]",
    "operationId": "getConversationContentAnalysisDeprecated",
    "deprecated": true,
    "security": [
     {
      "openapi_oauth": [
       "iq_conversation:read",
       "iq_conversation:write",
       "iq_conversation:read:admin",
       "iq_conversation:write:admin",
       "zra:read:conversation_analysis",
       "zra:read:conversation_analysis:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_conversation:read",
      "iq_conversation:write",
      "iq_conversation:read:admin",
      "iq_conversation:write:admin"
     ],
     "x-granular-scopes": [
      "zra:read:conversation_analysis",
      "zra:read:conversation_analysis:admin"
     ]
    }
   }
  },
  "/iq/conversations/{conversationId}/interactions": {
   "get": {
    "tags": [
     "Conversations"
    ],
    "summary": "Get conversation interactions [Deprecated]",
    "description": "Get interactions for a specific conversation. \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_conversation:read`,`iq_conversation:write`,`iq_conversation:read:admin`,`iq_conversation:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:read:conversation_participants`,`zra:read:conversation_participants:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-r[...]",
    "operationId": "getConversationInteractionsDeprecated",
    "deprecated": true,
    "security": [
     {
      "openapi_oauth": [
       "iq_conversation:read",
       "iq_conversation:write",
       "iq_conversation:read:admin",
       "iq_conversation:write:admin",
       "zra:read:conversation_participants",
       "zra:read:conversation_participants:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_conversation:read",
      "iq_conversation:write",
      "iq_conversation:read:admin",
      "iq_conversation:write:admin"
     ],
     "x-granular-scopes": [
      "zra:read:conversation_participants",
      "zra:read:conversation_participants:admin"
     ]
    }
   }
  },
  "/iq/conversations/{conversationId}/scorecards": {
   "get": {
    "tags": [
     "Conversations"
    ],
    "summary": "Get conversation scorecards [Deprecated]",
    "description": "Get scorecards for a specific conversation. \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_coaching:read:admin`,`iq_coaching:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:read:conversation_scorecards`,`zra:read:conversation_scorecards:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "getConversationScorecardsDeprecated",
    "deprecated": true,
    "security": [
     {
      "openapi_oauth": [
       "iq_coaching:read:admin",
       "iq_coaching:read",
       "zra:read:conversation_scorecards",
       "zra:read:conversation_scorecards:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_coaching:read:admin",
      "iq_coaching:read"
     ],
     "x-granular-scopes": [
      "zra:read:conversation_scorecards",
      "zra:read:conversation_scorecards:admin"
     ]
    }
   }
  },
  "/iq/conversations/{conversationId}/update_host": {
   "patch": {
    "tags": [
     "Conversations"
    ],
    "summary": "Update conversation host id to new host id by conversation id [Deprecated]",
    "description": "Update the conversation host id.\r\n\r\n**Prerequisite**: \r\nYou must have either `iq_conversation:write:admin` or `iq_conversation:write` permissions.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_conversation:write:admin`,`iq_conversation:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:update:conversation_host`,`zra:update:conversation_host:admin`\n\n**[Rate Limit Label]([...]",
    "operationId": "UpdateconversationhostidtonewhostidbyconversationidDeprecated",
    "deprecated": true,
    "security": [
     {
      "openapi_oauth": [
       "iq_conversation:write:admin",
       "iq_conversation:write",
       "zra:update:conversation_host",
       "zra:update:conversation_host:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_conversation:write:admin",
      "iq_conversation:write"
     ],
     "x-granular-scopes": [
      "zra:update:conversation_host",
      "zra:update:conversation_host:admin"
     ]
    }
   }
  },
  "/iq/files": {
   "post": {
    "tags": [
     "Conversations"
    ],
    "summary": "Upload IQ file [Deprecated]",
    "description": "Upload a file to Zoom Revenue Acclerator. \n\n **Prerequisite:**  \n The caller must be a Zoom Revenue Acclerator-licensed user.\n\n **Note:**  \n* Base URL: `https://fileapi.zoom.us/v2/`.  \n* Rate limit: 20 requests per second per user or 2000 requests per second per IP address. \n* The caller must support HTTP 30x redirects. \n* The caller must retain the Authorization header when redirected to a different hostname. \n\n* Supported video formats: `.mov`, `.mp4`, `.avi`, `.[...]",
    "operationId": "UploadIQFileDeprecated",
    "deprecated": true,
    "security": [
     {
      "openapi_oauth": [
       "iq_conversation:write:admin",
       "iq_conversation:write",
       "zra:write:file",
       "zra:write:file:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_conversation:write:admin",
      "iq_conversation:write"
     ],
     "x-granular-scopes": [
      "zra:write:file",
      "zra:write:file:admin"
     ]
    }
   }
  },
  "/iq/files/multipart": {
   "post": {
    "tags": [
     "Conversations"
    ],
    "summary": "Upload iq multipart file. [Deprecated]",
    "description": "Use this API to upload a multipart file. \n\n **Note:** \n* The base URL for this API is `https://fileapi.zoom.us/v2/`. \n* The rate limit of this API is 20 requests per second or 2000 requests per day per IP address. \n* The caller must support HTTP 30x redirects. \n* The caller must retain the authorization header when redirected to a different hostname. \n* Video can be in `.mov`, `.mp4`, `.avi`, `.wmv` or `H.264` format.\n* Transcript can be in `.vtt`, `.json` format.\n* [...]",
    "operationId": "UploadIqMultipartFileDeprecated",
    "deprecated": true,
    "security": [
     {
      "openapi_oauth": [
       "iq_conversation:write:admin",
       "iq_conversation:write",
       "zra:write:file",
       "zra:write:file:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_conversation:write:admin",
      "iq_conversation:write"
     ],
     "x-granular-scopes": [
      "zra:write:file",
      "zra:write:file:admin"
     ]
    }
   }
  },
  "/iq/files/multipart/upload_events": {
   "post": {
    "tags": [
     "Conversations"
    ],
    "summary": "Initiate and complete a multipart upload. [Deprecated]",
    "description": "Initiate or complete a multipart upload. \n\n **Note:** \n* The base URL for this API is `https://fileapi.zoom.us/v2/`. \n* The rate limit is 20 requests per second or 2000 requests per day per IP address.\n* The caller must support HTTP 30x redirects. \n* The caller must retain the authorization header when redirected to a different hostname. \n* Once initiated the multipart upload must complete within 7 days. \n* The caller must be an iq_listened user. \n* For **account-lev[...]",
    "operationId": "InitiateAndCompleteAMultipartUpload. [Deprecated]",
    "deprecated": true,
    "security": [
     {
      "openapi_oauth": [
       "iq_conversation:write:admin",
       "iq_conversation:write",
       "zra:write:file",
       "zra:write:file:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_conversation:write:admin",
      "iq_conversation:write"
     ],
     "x-granular-scopes": [
      "zra:write:file",
      "zra:write:file:admin"
     ]
    }
   }
  },
  "/iq/users/{userId}/conversations": {
   "post": {
    "tags": [
     "Conversations"
    ],
    "summary": "Add conversation by meeting record url or meeting UUID. [Deprecated]",
    "description": "Add new conversation by meeting recording URL or meeting UUID. If both recording URL and meeting UUID are passed in the request but refer to different meetings, we use the recording URL and ignore the meeting UUID.\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_conversation:write:admin`,`iq_conversation:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:write:conversation`,`[...]",
    "operationId": "addConversationDeprecated",
    "deprecated": true,
    "security": [
     {
      "openapi_oauth": [
       "iq_conversation:write:admin",
       "iq_conversation:write",
       "zra:write:conversation",
       "zra:write:conversation:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_conversation:write:admin",
      "iq_conversation:write"
     ],
     "x-granular-scopes": [
      "zra:write:conversation",
      "zra:write:conversation:admin"
     ]
    }
   }
  },
  "/iq/users/{userId}/conversations/playlists": {
   "get": {
    "tags": [
     "Conversations"
    ],
    "summary": "Get a user's playlist [Deprecated]",
    "description": "Get all playlists for a user. \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_playlist:read`,`iq_playlist:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:read:list_conversation_playlists`,`zra:read:list_conversation_playlists`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "getUserPlaylistDeprecated",
    "deprecated": true,
    "security": [
     {
      "openapi_oauth": [
       "iq_playlist:read",
       "iq_playlist:read:admin",
       "zra:read:list_conversation_playlists",
       "zra:read:list_conversation_playlists"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_playlist:read",
      "iq_playlist:read:admin"
     ],
     "x-granular-scopes": [
      "zra:read:list_conversation_playlists",
      "zra:read:list_conversation_playlists"
     ]
    }
   }
  },
  "/zra/conversations": {
   "get": {
    "tags": [
     "Conversations"
    ],
    "summary": "List conversations",
    "description": "List all conversations. \n\n\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_conversation:read`,`iq_conversation:write`,`iq_conversation:read:admin`,`iq_conversation:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:read:list_conversations`,`zra:read:list_conversations:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits[...]",
    "operationId": "listAllConversations",
    "security": [
     {
      "openapi_oauth": [
       "iq_conversation:read",
       "iq_conversation:write",
       "iq_conversation:read:admin",
       "iq_conversation:write:admin",
       "zra:read:list_conversations",
       "zra:read:list_conversations:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "AllConversations:Read"
     ],
     "x-macro-scopes": [
      "iq_conversation:read",
      "iq_conversation:write",
      "iq_conversation:read:admin",
      "iq_conversation:write:admin"
     ],
     "x-granular-scopes": [
      "zra:read:list_conversations",
      "zra:read:list_conversations:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Conversations"
    ],
    "summary": "Add conversation by file id or download url.",
    "description": "Add conversation by file ID or third party download URL.\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_conversation:write:admin`,`iq_conversation:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:write:conversation`,`zra:write:conversation:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "AddConversationByFileIdOrDownloadUrl",
    "security": [
     {
      "openapi_oauth": [
       "iq_conversation:write:admin",
       "iq_conversation:write",
       "zra:write:conversation",
       "zra:write:conversation:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_conversation:write:admin",
      "iq_conversation:write"
     ],
     "x-granular-scopes": [
      "zra:write:conversation",
      "zra:write:conversation:admin"
     ]
    }
   }
  },
  "/zra/conversations/{conversationId}": {
   "get": {
    "tags": [
     "Conversations"
    ],
    "summary": "Get conversation information",
    "description": "Get information for a specific conversation.\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_conversation:read`,`iq_conversation:write`,`iq_conversation:read:admin`,`iq_conversation:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:read:conversations:admin`,`zra:read:conversations`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-[...]",
    "operationId": "getConversationDetail",
    "security": [
     {
      "openapi_oauth": [
       "iq_conversation:read",
       "iq_conversation:write",
       "iq_conversation:read:admin",
       "iq_conversation:write:admin",
       "zra:read:conversations:admin",
       "zra:read:conversations"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "AllConversations:Read"
     ],
     "x-macro-scopes": [
      "iq_conversation:read",
      "iq_conversation:write",
      "iq_conversation:read:admin",
      "iq_conversation:write:admin"
     ],
     "x-granular-scopes": [
      "zra:read:conversations:admin",
      "zra:read:conversations"
     ]
    }
   },
   "delete": {
    "tags": [
     "Conversations"
    ],
    "summary": "Delete conversation by conversation ID",
    "description": "Delete conversation by conversation ID. \n\n\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_conversation:write:admin`,`iq_conversation:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:delete:conversations`,`zra:delete:conversations:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "deleteConversationById",
    "security": [
     {
      "openapi_oauth": [
       "iq_conversation:write:admin",
       "iq_conversation:write",
       "zra:delete:conversations",
       "zra:delete:conversations:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_conversation:write:admin",
      "iq_conversation:write"
     ],
     "x-granular-scopes": [
      "zra:delete:conversations",
      "zra:delete:conversations:admin"
     ]
    }
   }
  },
  "/zra/conversations/{conversationId}/comments": {
   "get": {
    "tags": [
     "Conversations"
    ],
    "summary": "Get conversation comments",
    "description": "Get comments for a specific conversation. \n\n\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_comment:read`,`iq_comment:write`,`iq_comment:read:admin`,`iq_comment:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:read:list_conversation_comments`,`zra:read:list_conversation_comments:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limi[...]",
    "operationId": "getConversationCommentsById",
    "security": [
     {
      "openapi_oauth": [
       "iq_comment:read",
       "iq_comment:write",
       "iq_comment:read:admin",
       "iq_comment:write:admin",
       "zra:read:list_conversation_comments",
       "zra:read:list_conversation_comments:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_comment:read",
      "iq_comment:write",
      "iq_comment:read:admin",
      "iq_comment:write:admin"
     ],
     "x-granular-scopes": [
      "zra:read:list_conversation_comments",
      "zra:read:list_conversation_comments:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Conversations"
    ],
    "summary": "Add new comments to the conversation",
    "description": "Add new comments to a specific conversation. \n\n\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_comment:write`,`iq_comment:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:read:list_conversation_comments`,`zra:read:list_conversation_comments:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "addConversationComments",
    "security": [
     {
      "openapi_oauth": [
       "iq_comment:write",
       "iq_comment:write:admin",
       "zra:read:list_conversation_comments",
       "zra:read:list_conversation_comments:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_comment:write",
      "iq_comment:write:admin"
     ],
     "x-granular-scopes": [
      "zra:read:list_conversation_comments",
      "zra:read:list_conversation_comments:admin"
     ]
    }
   }
  },
  "/zra/conversations/{conversationId}/comments/{commentId}": {
   "delete": {
    "tags": [
     "Conversations"
    ],
    "summary": "Delete conversation's comment",
    "description": "Delete comment from a specific conversation. \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_comment:write`,`iq_comment:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:delete:conversation_comment`,`zra:delete:conversation_comment:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "deleteConversationCommentById",
    "security": [
     {
      "openapi_oauth": [
       "iq_comment:write",
       "iq_comment:write:admin",
       "zra:delete:conversation_comment",
       "zra:delete:conversation_comment:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_comment:write",
      "iq_comment:write:admin"
     ],
     "x-granular-scopes": [
      "zra:delete:conversation_comment",
      "zra:delete:conversation_comment:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Conversations"
    ],
    "summary": "Edit conversation comment",
    "description": "Edit a comment for a specific conversation. \n\n\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_comment:write`,`iq_comment:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:update:conversation_comment`,`zra:update:conversation_comment:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "editConversationCommentById",
    "security": [
     {
      "openapi_oauth": [
       "iq_comment:write",
       "iq_comment:write:admin",
       "zra:update:conversation_comment",
       "zra:update:conversation_comment:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_comment:write",
      "iq_comment:write:admin"
     ],
     "x-granular-scopes": [
      "zra:update:conversation_comment",
      "zra:update:conversation_comment:admin"
     ]
    }
   }
  },
  "/zra/conversations/{conversationId}/content_analysis": {
   "get": {
    "tags": [
     "Conversations"
    ],
    "summary": "Get conversation content analysis",
    "description": "Get the content analysis for a specific conversation. \n\n\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_conversation:read`,`iq_conversation:write`,`iq_conversation:read:admin`,`iq_conversation:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:read:conversation_analysis`,`zra:read:conversation_analysis:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/a[...]",
    "operationId": "getConversationContentAnalysisById",
    "security": [
     {
      "openapi_oauth": [
       "iq_conversation:read",
       "iq_conversation:write",
       "iq_conversation:read:admin",
       "iq_conversation:write:admin",
       "zra:read:conversation_analysis",
       "zra:read:conversation_analysis:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "AllConversations:Read"
     ],
     "x-macro-scopes": [
      "iq_conversation:read",
      "iq_conversation:write",
      "iq_conversation:read:admin",
      "iq_conversation:write:admin"
     ],
     "x-granular-scopes": [
      "zra:read:conversation_analysis",
      "zra:read:conversation_analysis:admin"
     ]
    }
   }
  },
  "/zra/conversations/{conversationId}/interactions": {
   "get": {
    "tags": [
     "Conversations"
    ],
    "summary": "Get conversation interactions",
    "description": "Get interactions for a specific conversation. \n\n\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_conversation:read`,`iq_conversation:write`,`iq_conversation:read:admin`,`iq_conversation:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:read:conversation_participants`,`zra:read:conversation_participants:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/a[...]",
    "operationId": "getConversationInteraction",
    "security": [
     {
      "openapi_oauth": [
       "iq_conversation:read",
       "iq_conversation:write",
       "iq_conversation:read:admin",
       "iq_conversation:write:admin",
       "zra:read:conversation_participants",
       "zra:read:conversation_participants:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "AllConversations:Read"
     ],
     "x-macro-scopes": [
      "iq_conversation:read",
      "iq_conversation:write",
      "iq_conversation:read:admin",
      "iq_conversation:write:admin"
     ],
     "x-granular-scopes": [
      "zra:read:conversation_participants",
      "zra:read:conversation_participants:admin"
     ]
    }
   }
  },
  "/zra/conversations/{conversationId}/scorecards": {
   "get": {
    "tags": [
     "Conversations"
    ],
    "summary": "Get conversation scorecards",
    "description": "Get scorecards for a specific conversation. \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_coaching:read`,`iq_coaching:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:read:conversation_scorecards`,`zra:read:conversation_scorecards:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "getConversationScorecardsById",
    "security": [
     {
      "openapi_oauth": [
       "iq_coaching:read",
       "iq_coaching:read:admin",
       "zra:read:conversation_scorecards",
       "zra:read:conversation_scorecards:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_coaching:read",
      "iq_coaching:read:admin"
     ],
     "x-granular-scopes": [
      "zra:read:conversation_scorecards",
      "zra:read:conversation_scorecards:admin"
     ]
    }
   }
  },
  "/zra/conversations/{conversationId}/update_host": {
   "patch": {
    "tags": [
     "Conversations"
    ],
    "summary": "Update conversation host id",
    "description": "Update the conversation host id to a new host id by conversation id.\r\n\r\n**Prerequisite**: \r\nYou must have either `iq_conversation:write:admin` or `iq_conversation:write` permissions.\r\n\r\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_conversation:write:admin`,`iq_conversation:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:update:conversation_host`,`zra:update:conve[...]",
    "operationId": "UpdateConversationhostid2NewHostidByConversationId",
    "security": [
     {
      "openapi_oauth": [
       "iq_conversation:write:admin",
       "iq_conversation:write",
       "zra:update:conversation_host",
       "zra:update:conversation_host:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_conversation:write:admin",
      "iq_conversation:write"
     ],
     "x-granular-scopes": [
      "zra:update:conversation_host",
      "zra:update:conversation_host:admin"
     ]
    }
   }
  },
  "/zra/files": {
   "post": {
    "tags": [
     "Conversations"
    ],
    "summary": "Upload IQ file",
    "description": "Upload a file to Zoom Revenue Acclerator. \n\n **Prerequisite:**  \n The caller must be a Zoom Revenue Acclerator-licensed user.\n\n **Note:**  \n* Base URL: `https://fileapi.zoom.us/v2/`.  \n* Rate limit: 20 requests per second per user or 2000 requests per second per IP address. \n* The caller must support HTTP 30x redirects. \n* The caller must retain the Authorization header when redirected to a different hostname. \n\n* Supported video formats: `.mov`, `.mp4`, `.avi`, `.[...]",
    "operationId": "UploadZraFile",
    "security": [
     {
      "openapi_oauth": [
       "iq_conversation:write:admin",
       "iq_conversation:write",
       "zra:write:file",
       "zra:write:file:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_conversation:write:admin",
      "iq_conversation:write"
     ],
     "x-granular-scopes": [
      "zra:write:file",
      "zra:write:file:admin"
     ]
    }
   }
  },
  "/zra/files/multipart": {
   "post": {
    "tags": [
     "Conversations"
    ],
    "summary": "Upload iq multipart file.",
    "description": "Use this API to upload a multipart file. \n\n **Note:** \n* The base URL for this API is `https://fileapi.zoom.us/v2/`. \n* The rate limit of this API is 20 requests per second or 2000 requests per day per IP address. \n* The caller must support HTTP 30x redirects. \n* The caller must retain the authorization header when redirected to a different hostname. \n* Video can be in `.mov`, `.mp4`, `.avi`, `.wmv` or `H.264` format.\n* Transcript can be in `.vtt`, `.json` format.\n* [...]",
    "operationId": "UploadZraMultipartFile.",
    "security": [
     {
      "openapi_oauth": [
       "iq_conversation:write:admin",
       "iq_conversation:write",
       "zra:write:file",
       "zra:write:file:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_conversation:write:admin",
      "iq_conversation:write"
     ],
     "x-granular-scopes": [
      "zra:write:file",
      "zra:write:file:admin"
     ]
    }
   }
  },
  "/zra/files/multipart/upload_events": {
   "post": {
    "tags": [
     "Conversations"
    ],
    "summary": "Initiate and complete a multipart upload.",
    "description": "Initiate or complete a multipart upload. \n\n **Note:** \n* The base URL for this API is `https://fileapi.zoom.us/v2/`. \n* The rate limit is 20 requests per second or 2000 requests per day per IP address.\n* The caller must support HTTP 30x redirects. \n* The caller must retain the authorization header when redirected to a different hostname. \n* Once initiated the multipart upload must complete within 7 days. \n* The caller must be an iq_listened user. \n* For **account-lev[...]",
    "operationId": "InitiateAndCompleteAMultipartUpload",
    "security": [
     {
      "openapi_oauth": [
       "iq_conversation:write:admin",
       "iq_conversation:write",
       "zra:write:file",
       "zra:write:file:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_conversation:write:admin",
      "iq_conversation:write"
     ],
     "x-granular-scopes": [
      "zra:write:file",
      "zra:write:file:admin"
     ]
    }
   }
  },
  "/zra/users/{userId}/conversations": {
   "post": {
    "tags": [
     "Conversations"
    ],
    "summary": "Add conversation by meeting record url or meeting UUID.",
    "description": "Add new conversations by meeting record URL or meeting UUID. If both recording URL and meeting UUID are passed in the request and refer to different meetings, we ignore meeting UUID.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_conversation:write:admin`,`iq_conversation:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:write:conversation`,`zra:write:conversation:admin`\n\n**[[...]",
    "operationId": "addConversationByRecord",
    "security": [
     {
      "openapi_oauth": [
       "iq_conversation:write:admin",
       "iq_conversation:write",
       "zra:write:conversation",
       "zra:write:conversation:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_conversation:write:admin",
      "iq_conversation:write"
     ],
     "x-granular-scopes": [
      "zra:write:conversation",
      "zra:write:conversation:admin"
     ]
    }
   }
  },
  "/zra/users/{userId}/conversations/playlists": {
   "get": {
    "tags": [
     "Conversations"
    ],
    "summary": "Get a user's playlist",
    "description": "Get all playlists for a user. \n\n\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_playlist:read:admin`,`iq_playlist:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:read:list_conversation_playlists`,`zra:read:list_conversation_playlists`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "getUserPlaylists",
    "security": [
     {
      "openapi_oauth": [
       "iq_playlist:read:admin",
       "iq_playlist:read",
       "zra:read:list_conversation_playlists",
       "zra:read:list_conversation_playlists"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_playlist:read:admin",
      "iq_playlist:read"
     ],
     "x-granular-scopes": [
      "zra:read:list_conversation_playlists",
      "zra:read:list_conversation_playlists"
     ]
    }
   }
  },
  "/iq/deals": {
   "get": {
    "tags": [
     "Deals"
    ],
    "summary": "List deals [Deprecated]",
    "description": "List all deals.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_deal:read`,`iq_deal:read:admin`,`iq_deal:write`,`iq_deal:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:read:list_deals`,`zra:read:list_deals:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "listDealsDeprecated",
    "deprecated": true,
    "security": [
     {
      "openapi_oauth": [
       "iq_deal:read",
       "iq_deal:read:admin",
       "iq_deal:write",
       "iq_deal:write:admin",
       "zra:read:list_deals",
       "zra:read:list_deals:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_deal:read",
      "iq_deal:read:admin",
      "iq_deal:write",
      "iq_deal:write:admin"
     ],
     "x-granular-scopes": [
      "zra:read:list_deals",
      "zra:read:list_deals:admin"
     ]
    }
   }
  },
  "/iq/deals/{dealId}": {
   "get": {
    "tags": [
     "Deals"
    ],
    "summary": "Get deal information [Deprecated]",
    "description": "Get information for a specific deal. (deprecated)\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_deal:read`,`iq_deal:read:admin`,`iq_deal:write`,`iq_deal:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:read:deal`,`zra:read:deal:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "getDealInfoDeprecated",
    "deprecated": true,
    "security": [
     {
      "openapi_oauth": [
       "iq_deal:read",
       "iq_deal:read:admin",
       "iq_deal:write",
       "iq_deal:write:admin",
       "zra:read:deal",
       "zra:read:deal:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_deal:read",
      "iq_deal:read:admin",
      "iq_deal:write",
      "iq_deal:write:admin"
     ],
     "x-granular-scopes": [
      "zra:read:deal",
      "zra:read:deal:admin"
     ]
    }
   }
  },
  "/iq/deals/{dealId}/activities": {
   "get": {
    "tags": [
     "Deals"
    ],
    "summary": "Get deal activities [Deprecated]",
    "description": "Get activities for a specific deal. (deprecated)\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_deal:read`,`iq_deal:read:admin`,`iq_deal:write`,`iq_deal:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:read:list_deal_activities`,`zra:read:list_deal_activities:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM[...]",
    "operationId": "getDealActivitiesDeprecated",
    "deprecated": true,
    "security": [
     {
      "openapi_oauth": [
       "iq_deal:read",
       "iq_deal:read:admin",
       "iq_deal:write",
       "iq_deal:write:admin",
       "zra:read:list_deal_activities",
       "zra:read:list_deal_activities:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_deal:read",
      "iq_deal:read:admin",
      "iq_deal:write",
      "iq_deal:write:admin"
     ],
     "x-granular-scopes": [
      "zra:read:list_deal_activities",
      "zra:read:list_deal_activities:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Deals"
    ],
    "summary": "Delete activity from the deal [Deprecated]",
    "description": "Delete specific activity from the deal. Either <b>conversation_id</b> or <b>message_id</b> would be required.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_deal:write:admin`,`iq_deal:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:delete:deal_activity`,`zra:delete:deal_activity:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-lim[...]",
    "operationId": "DeleteActivityFromTheDealDeprecated",
    "deprecated": true,
    "security": [
     {
      "openapi_oauth": [
       "iq_deal:write:admin",
       "iq_deal:write",
       "zra:delete:deal_activity",
       "zra:delete:deal_activity:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_deal:write:admin",
      "iq_deal:write"
     ],
     "x-granular-scopes": [
      "zra:delete:deal_activity",
      "zra:delete:deal_activity:admin"
     ]
    }
   }
  },
  "/zra/deals": {
   "get": {
    "tags": [
     "Deals"
    ],
    "summary": "List deals",
    "description": "List all deals.\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_deal:read`,`iq_deal:read:admin`,`iq_deal:write`,`iq_deal:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:read:list_deals`,`zra:read:list_deals:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "listAllDeals",
    "security": [
     {
      "openapi_oauth": [
       "iq_deal:read",
       "iq_deal:read:admin",
       "iq_deal:write",
       "iq_deal:write:admin",
       "zra:read:list_deals",
       "zra:read:list_deals:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_deal:read",
      "iq_deal:read:admin",
      "iq_deal:write",
      "iq_deal:write:admin"
     ],
     "x-granular-scopes": [
      "zra:read:list_deals",
      "zra:read:list_deals:admin"
     ]
    }
   }
  },
  "/zra/deals/{dealId}": {
   "get": {
    "tags": [
     "Deals"
    ],
    "summary": "Get deal information",
    "description": "Get information for a specific deal.\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_deal:read`,`iq_deal:read:admin`,`iq_deal:write`,`iq_deal:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:read:deal`,`zra:read:deal:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "getDealDetail",
    "security": [
     {
      "openapi_oauth": [
       "iq_deal:read",
       "iq_deal:read:admin",
       "iq_deal:write",
       "iq_deal:write:admin",
       "zra:read:deal",
       "zra:read:deal:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_deal:read",
      "iq_deal:read:admin",
      "iq_deal:write",
      "iq_deal:write:admin"
     ],
     "x-granular-scopes": [
      "zra:read:deal",
      "zra:read:deal:admin"
     ]
    }
   }
  },
  "/zra/deals/{dealId}/activities": {
   "get": {
    "tags": [
     "Deals"
    ],
    "summary": "Get deal activities",
    "description": "Get activities for a specific deal.\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_deal:read`,`iq_deal:read:admin`,`iq_deal:write`,`iq_deal:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:read:list_deal_activities`,`zra:read:list_deal_activities:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "geAllActivitiesFromDeal",
    "security": [
     {
      "openapi_oauth": [
       "iq_deal:read",
       "iq_deal:read:admin",
       "iq_deal:write",
       "iq_deal:write:admin",
       "zra:read:list_deal_activities",
       "zra:read:list_deal_activities:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_deal:read",
      "iq_deal:read:admin",
      "iq_deal:write",
      "iq_deal:write:admin"
     ],
     "x-granular-scopes": [
      "zra:read:list_deal_activities",
      "zra:read:list_deal_activities:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Deals"
    ],
    "summary": "Delete activity from the deal",
    "description": "Delete specific activity from a deal. Use either <b>conversation_id</b> or <b>message_id</b>.\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_deal:write`,`iq_deal:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:delete:deal_activity`,`zra:delete:deal_activity:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MED[...]",
    "operationId": "DeleteActivityFromDeal",
    "security": [
     {
      "openapi_oauth": [
       "iq_deal:write",
       "iq_deal:write:admin",
       "zra:delete:deal_activity",
       "zra:delete:deal_activity:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "AllDeals:Edit"
     ],
     "x-macro-scopes": [
      "iq_deal:write",
      "iq_deal:write:admin"
     ],
     "x-granular-scopes": [
      "zra:delete:deal_activity",
      "zra:delete:deal_activity:admin"
     ]
    }
   }
  },
  "/zra/scheduled": {
   "get": {
    "tags": [
     "ScheduleMeetings"
    ],
    "summary": "List scheduled meetings",
    "description": "List all scheduled meetings for a user.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_conversation:read:admin`,`iq_conversation:read`,`iq_conversation:write`,`iq_conversation:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:read:list_conversations`,`zra:read:list_conversations:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate[...]",
    "operationId": "Listallscheduledmeetings",
    "security": [
     {
      "openapi_oauth": [
       "iq_conversation:read:admin",
       "iq_conversation:read",
       "iq_conversation:write",
       "iq_conversation:write:admin",
       "zra:read:list_conversations",
       "zra:read:list_conversations:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "AllConversations:Read"
     ],
     "x-macro-scopes": [
      "iq_conversation:read:admin",
      "iq_conversation:read",
      "iq_conversation:write",
      "iq_conversation:write:admin"
     ],
     "x-granular-scopes": [
      "zra:read:list_conversations",
      "zra:read:list_conversations:admin"
     ]
    }
   }
  },
  "/iq/teams": {
   "get": {
    "tags": [
     "Teams"
    ],
    "summary": "List Account Teams [Deprecated]",
    "description": "List account teams. Filter by parent team ID or team name. (deprecated)\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_team:read:admin`,`iq_team:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "ListAccountTeamsDeprecated",
    "deprecated": true,
    "security": [
     {
      "openapi_oauth": [
       "iq_team:read:admin",
       "iq_team:read"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_team:read:admin",
      "iq_team:read"
     ]
    }
   }
  },
  "/zra/team": {
   "post": {
    "tags": [
     "Teams"
    ],
    "summary": "Create Team",
    "description": "Please create team one by one, if your account enable hierarchical structure team. We currently do not support concurrent hierarchical team creation\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_team:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:write:team:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY[...]",
    "operationId": "CreateTeam",
    "security": [
     {
      "openapi_oauth": [
       "iq_team:write:admin",
       "zra:write:team:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "TeamManagement:Edit"
     ],
     "x-macro-scopes": [
      "iq_team:write:admin"
     ],
     "x-granular-scopes": [
      "zra:write:team:admin"
     ]
    }
   }
  },
  "/zra/team/unassigned_team_users": {
   "get": {
    "tags": [
     "Teams"
    ],
    "summary": "List Unassigned Team Users",
    "description": "List unassigned team zra users by page\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_team:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:read:unassigned_team_users:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "ListUnassignedTeamUsers",
    "security": [
     {
      "openapi_oauth": [
       "iq_team:read:admin",
       "zra:read:unassigned_team_users:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_team:read:admin"
     ],
     "x-granular-scopes": [
      "zra:read:unassigned_team_users:admin"
     ]
    }
   }
  },
  "/zra/team/{teamId}": {
   "get": {
    "tags": [
     "Teams"
    ],
    "summary": "Get Team Detail",
    "description": "Get team detail, such as team name, team description, team member size and etc.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_team:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:read:team:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "GetTeamDetail",
    "security": [
     {
      "openapi_oauth": [
       "iq_team:read:admin",
       "zra:read:team:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_team:read:admin"
     ],
     "x-granular-scopes": [
      "zra:read:team:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Teams"
    ],
    "summary": "Delete Team",
    "description": "Please delete team one by one, if your account enable hierarchical structure team. We currently do not support concurrent hierarchical team deletion.\r\nAnd if you want to delete flat team, you should make sure that the team members of the target team are empty.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_team:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:delete:te[...]",
    "operationId": "DeleteTeam",
    "security": [
     {
      "openapi_oauth": [
       "iq_team:write:admin",
       "zra:delete:team:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "TeamManagement:Edit"
     ],
     "x-macro-scopes": [
      "iq_team:write:admin"
     ],
     "x-granular-scopes": [
      "zra:delete:team:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Teams"
    ],
    "summary": "Update Team name",
    "description": "Update the team name.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_team:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:update:team:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "UpdateTeam",
    "security": [
     {
      "openapi_oauth": [
       "iq_team:write:admin",
       "zra:update:team:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "TeamManagement:Edit"
     ],
     "x-macro-scopes": [
      "iq_team:write:admin"
     ],
     "x-granular-scopes": [
      "zra:update:team:admin"
     ]
    }
   }
  },
  "/zra/team/{teamId}/access/granted-from": {
   "post": {
    "tags": [
     "Teams"
    ],
    "summary": "Grant additional access to current team",
    "description": "Grants the current team access to view conversation recordings hosted and attended by members of the specified source teams. Once access is granted, managers and members of the current team who have permission to read team conversations will be able to view these recordings. Use this endpoint when other teams choose to share their conversation data with the current team.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_team:write:admin[...]",
    "operationId": "AddSharedFromTeams",
    "security": [
     {
      "openapi_oauth": [
       "iq_team:write:admin",
       "zra:write:team:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "TeamManagement:Edit"
     ],
     "x-macro-scopes": [
      "iq_team:write:admin"
     ],
     "x-granular-scopes": [
      "zra:write:team:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Teams"
    ],
    "summary": "Remove additional access from current team",
    "description": "The target teams stop granting additional access to the current team. If target teams stop, it means the managers/members of current team who have team conversation read permission can no longer view conversation recordings that were both hosted and attended by target teams' members.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_team:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overvi[...]",
    "operationId": "DeleteSharedFromTeams",
    "security": [
     {
      "openapi_oauth": [
       "iq_team:write:admin",
       "zra:delete:team:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "TeamManagement:Edit"
     ],
     "x-macro-scopes": [
      "iq_team:write:admin"
     ],
     "x-granular-scopes": [
      "zra:delete:team:admin"
     ]
    }
   }
  },
  "/zra/team/{teamId}/access/granted-to": {
   "post": {
    "tags": [
     "Teams"
    ],
    "summary": "Grant additional access to target teams",
    "description": "The current team grants additional access to the target teams. If current team granted, it means the managers/members of target teams who have team conversation read permission can view conversation recordings that were both hosted and attended by current team's members.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_team:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:[...]",
    "operationId": "AddSharedToTeams",
    "security": [
     {
      "openapi_oauth": [
       "iq_team:write:admin",
       "zra:write:team:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "TeamManagement:Edit"
     ],
     "x-macro-scopes": [
      "iq_team:write:admin"
     ],
     "x-granular-scopes": [
      "zra:write:team:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Teams"
    ],
    "summary": "Remove additional access from target teams",
    "description": "The current team stops granting additional access to the target teams. If current teams stop, it means the managersor members of target teams who have team conversation read permission can no longer view conversation recordings that were both hosted and attended by current team's members.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_team:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-o[...]",
    "operationId": "DeleteSharedToTeams",
    "security": [
     {
      "openapi_oauth": [
       "iq_team:write:admin",
       "zra:delete:team:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "TeamManagement:Edit"
     ],
     "x-macro-scopes": [
      "iq_team:write:admin"
     ],
     "x-granular-scopes": [
      "zra:delete:team:admin"
     ]
    }
   }
  },
  "/zra/team/{teamId}/parent_team": {
   "patch": {
    "tags": [
     "Teams"
    ],
    "summary": "Move team to new parent",
    "description": "Move current team under a new parent team.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_team:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:update:team:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "MoveTeam",
    "security": [
     {
      "openapi_oauth": [
       "iq_team:write:admin",
       "zra:update:team:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "TeamManagement:Edit"
     ],
     "x-macro-scopes": [
      "iq_team:write:admin"
     ],
     "x-granular-scopes": [
      "zra:update:team:admin"
     ]
    }
   }
  },
  "/zra/team/{teamId}/team_managers": {
   "get": {
    "tags": [
     "Teams"
    ],
    "summary": "List Team Managers",
    "description": "List Team Managers\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_team:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:read:team_managers:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "ListTeamManagers",
    "security": [
     {
      "openapi_oauth": [
       "iq_team:read:admin",
       "zra:read:team_managers:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_team:read:admin"
     ],
     "x-granular-scopes": [
      "zra:read:team_managers:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Teams"
    ],
    "summary": "Assign Team Managers",
    "description": "Add team managers. Make sure your account support hierarchical structure team.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_team:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:write:team_manages:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "AssignTeamManagers",
    "security": [
     {
      "openapi_oauth": [
       "iq_team:write:admin",
       "zra:write:team_manages:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "TeamManagement:Edit"
     ],
     "x-macro-scopes": [
      "iq_team:write:admin"
     ],
     "x-granular-scopes": [
      "zra:write:team_manages:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Teams"
    ],
    "summary": "Unassign Team Managers",
    "description": "Delete team managers. Make sure your account support hierarchical structure team.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_team:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:delete:team_managers:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "UnassignTeamManagers",
    "security": [
     {
      "openapi_oauth": [
       "iq_team:write:admin",
       "zra:delete:team_managers:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "TeamManagement:Edit"
     ],
     "x-macro-scopes": [
      "iq_team:write:admin"
     ],
     "x-granular-scopes": [
      "zra:delete:team_managers:admin"
     ]
    }
   }
  },
  "/zra/team/{teamId}/team_members": {
   "get": {
    "tags": [
     "Teams"
    ],
    "summary": "List Team Members",
    "description": "List team members by page\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_team:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:read:team_members:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "ListTeamMembers",
    "security": [
     {
      "openapi_oauth": [
       "iq_team:read:admin",
       "zra:read:team_members:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_team:read:admin"
     ],
     "x-granular-scopes": [
      "zra:read:team_members:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Teams"
    ],
    "summary": "Assign Team Members",
    "description": "Add one or more users to a team.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_team:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:write:team_members:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "AssignTeamMembers",
    "security": [
     {
      "openapi_oauth": [
       "iq_team:write:admin",
       "zra:write:team_members:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "TeamManagement:Edit"
     ],
     "x-macro-scopes": [
      "iq_team:write:admin"
     ],
     "x-granular-scopes": [
      "zra:write:team_members:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Teams"
    ],
    "summary": "Unassign Team Members",
    "description": "Delete members of the team. Make sure to delete less than 30 users at one time.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_team:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:delete:team_members:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "UnassignTeamMembers",
    "security": [
     {
      "openapi_oauth": [
       "iq_team:write:admin",
       "zra:delete:team_members:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "TeamManagement:Edit"
     ],
     "x-macro-scopes": [
      "iq_team:write:admin"
     ],
     "x-granular-scopes": [
      "zra:delete:team_members:admin"
     ]
    }
   }
  },
  "/zra/teams": {
   "get": {
    "tags": [
     "Teams"
    ],
    "summary": "List Account Teams",
    "description": "List account teams. Filter by parent team ID or team name.\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `iq_team:read:admin`,`iq_team:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zra:read:team_list:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "ListTeams",
    "security": [
     {
      "openapi_oauth": [
       "iq_team:read:admin",
       "iq_team:read",
       "zra:read:team_list:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "iq_team:read:admin",
      "iq_team:read"
     ],
     "x-granular-scopes": [
      "zra:read:team_list:admin"
     ]
    }
   }
  }
 },
 "components": {
  "securitySchemes": {
   "openapi_authorization": {
    "type": "apiKey",
    "name": "Authorization",
    "in": "header"
   },
   "openapi_oauth": {
    "type": "oauth2",
    "flows": {
     "authorizationCode": {
      "authorizationUrl": "/",
      "tokenUrl": "",
      "refreshUrl": "",
      "scopes": {
       "account:read:admin": "account:read:admin",
       "account:write:admin": "account:write:admin",
       "iq_account:read:admin": "iq_account:read:admin",
       "zra:read:indicator": "zra:read:indicator",
       "zra:read:indicator:admin": "zra:read:indicator:admin",
       "iq_conversation:read": "iq_conversation:read",
       "iq_conversation:write": "iq_conversation:write",
       "iq_conversation:read:admin": "iq_conversation:read:admin",
       "iq_conversation:write:admin": "iq_conversation:write:admin",
       "zra:read:list_conversations": "zra:read:list_conversations",
       "zra:read:list_conversations:admin": "zra:read:list_conversations:admin",
       "zra:write:conversation": "zra:write:conversation",
       "zra:write:conversation:admin": "zra:write:conversation:admin",
       "zra:read:conversations:admin": "zra:read:conversations:admin",
       "zra:read:conversations": "zra:read:conversations",
       "zra:delete:conversations": "zra:delete:conversations",
       "zra:delete:conversations:admin": "zra:delete:conversations:admin",
       "iq_comment:write": "iq_comment:write",
       "iq_comment:write:admin": "iq_comment:write:admin",
       "zra:write:conversation_comment": "zra:write:conversation_comment",
       "zra:write:conversation_comment:admin": "zra:write:conversation_comment:admin",
       "iq_comment:read": "iq_comment:read",
       "iq_comment:read:admin": "iq_comment:read:admin",
       "zra:read:list_conversation_comments": "zra:read:list_conversation_comments",
       "zra:read:list_conversation_comments:admin": "zra:read:list_conversation_comments:admin",
       "zra:update:conversation_comment": "zra:update:conversation_comment",
       "zra:update:conversation_comment:admin": "zra:update:conversation_comment:admin",
       "zra:delete:conversation_comment": "zra:delete:conversation_comment",
       "zra:delete:conversation_comment:admin": "zra:delete:conversation_comment:admin",
       "zra:read:conversation_analysis": "zra:read:conversation_analysis",
       "zra:read:conversation_analysis:admin": "zra:read:conversation_analysis:admin",
       "zra:read:conversation_participants": "zra:read:conversation_participants",
       "zra:read:conversation_participants:admin": "zra:read:conversation_participants:admin",
       "iq_coaching:read:admin": "iq_coaching:read:admin",
       "iq_coaching:read": "iq_coaching:read",
       "zra:read:conversation_scorecards": "zra:read:conversation_scorecards",
       "zra:read:conversation_scorecards:admin": "zra:read:conversation_scorecards:admin",
       "zra:update:conversation_host": "zra:update:conversation_host",
       "zra:update:conversation_host:admin": "zra:update:conversation_host:admin",
       "zra:write:file": "zra:write:file",
       "zra:write:file:admin": "zra:write:file:admin",
       "iq_playlist:read": "iq_playlist:read",
       "iq_playlist:read:admin": "iq_playlist:read:admin",
       "zra:read:list_conversation_playlists": "zra:read:list_conversation_playlists",
       "iq_deal:read": "iq_deal:read",
       "iq_deal:read:admin": "iq_deal:read:admin",
       "iq_deal:write": "iq_deal:write",
       "iq_deal:write:admin": "iq_deal:write:admin",
       "zra:read:list_deals": "zra:read:list_deals",
       "zra:read:list_deals:admin": "zra:read:list_deals:admin",
       "zra:read:deal": "zra:read:deal",
       "zra:read:deal:admin": "zra:read:deal:admin",
       "zra:read:list_deal_activities": "zra:read:list_deal_activities",
       "zra:read:list_deal_activities:admin": "zra:read:list_deal_activities:admin",
       "zra:delete:deal_activity": "zra:delete:deal_activity",
       "zra:delete:deal_activity:admin": "zra:delete:deal_activity:admin",
       "iq_team:read:admin": "iq_team:read:admin",
       "iq_team:read": "iq_team:read",
       "iq_team:write:admin": "iq_team:write:admin",
       "zra:write:team:admin": "zra:write:team:admin",
       "zra:read:unassigned_team_users:admin": "zra:read:unassigned_team_users:admin",
       "zra:update:team:admin": "zra:update:team:admin",
       "zra:read:team:admin": "zra:read:team:admin",
       "zra:delete:team:admin": "zra:delete:team:admin",
       "zra:read:team_managers:admin": "zra:read:team_managers:admin",
       "zra:delete:team_managers:admin": "zra:delete:team_managers:admin",
       "zra:write:team_manages:admin": "zra:write:team_manages:admin",
       "zra:delete:team_members:admin": "zra:delete:team_members:admin",
       "zra:write:team_members:admin": "zra:write:team_members:admin",
       "zra:read:team_members:admin": "zra:read:team_members:admin",
       "zra:read:team_list:admin": "zra:read:team_list:admin"
      }
     }
    }
   }
  }
 }
}