{
 "openapi": "3.0.0",
 "info": {
  "title": "Rooms",
  "description": "The Zoom Rooms REST APIs allow you to manage your Zoom Rooms.  For example, you can create new Zoom Rooms, read their current configuration, or make configuration changes.  The Zoom Rooms REST API for [Zoom Room Controls](https://developers.zoom.us/docs/zoom-rooms/)in particular allows you to perform limited active control of a Zoom Room, such as starting or leaving a meeting, changing the mute state, or restarting the Zoom Room, among other capabilities.",
  "termsOfService": "https://zoom.us/docs/en-us/zoom_api_license_and_tou.html",
  "contact": {
   "name": "Zoom Developers"
  },
  "version": "2"
 },
 "servers": [
  {
   "url": "https://api.zoom.us/v2"
  }
 ],
 "paths": {
  "/rooms/controller/apps/config": {
   "post": {
    "tags": [
     "Room Apps"
    ],
    "summary": "Config Zoom Room Controller Apps",
    "description": "Use this API to configure Zoom Room Controller installed Zoom Apps.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:admin`,`room:master`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:write:zoom_apps:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "ConfigZoomRoomControllerApps",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "room:master",
       "zoom_rooms:write:zoom_apps:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomRooms:Edit",
      "SubAccount:Read",
      "SubAccount:Edit"
     ],
     "x-macro-scopes": [
      "room:write:admin",
      "room:master"
     ],
     "x-granular-scopes": [
      "zoom_rooms:write:zoom_apps:admin"
     ]
    }
   }
  },
  "/visitor/invitation": {
   "get": {
    "tags": [
     "Visitor Management"
    ],
    "summary": "Get a list of visitors by location ",
    "description": "List the invitations under a Zoom user account. Visitor management is a software system used to manage the lifecycle of visitors.\n  \n \n**Prerequisite:**  \n \n* Users need to be assigned a visitor management license. \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `visitor_management:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `visitor_management:read:list_invitations`,`vis[...]",
    "operationId": "invitationList",
    "security": [
     {
      "openapi_oauth": [
       "visitor_management:read",
       "visitor_management:read:list_invitations",
       "visitor_management:read:list_invitations:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "visitor_management:read"
     ],
     "x-granular-scopes": [
      "visitor_management:read:list_invitations",
      "visitor_management:read:list_invitations:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Visitor Management"
    ],
    "summary": "Send an invitation",
    "description": "Send a invitation to a visitor. Visitor management is a software system used to manage the visitors' lifecycle. \n  \n \n**Prerequisite:**  \n \n* Users need to be assigned a visitor management license. \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `visitor_management:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `visitor_management:write:invitation`,`visitor_management[...]",
    "operationId": "createInvitation",
    "security": [
     {
      "openapi_oauth": [
       "visitor_management:write:admin",
       "visitor_management:write:invitation",
       "visitor_management:write:invitation:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "visitor_management:write:admin"
     ],
     "x-granular-scopes": [
      "visitor_management:write:invitation",
      "visitor_management:write:invitation:admin"
     ]
    }
   }
  },
  "/visitor/invitation/{invitationId}": {
   "get": {
    "tags": [
     "Visitor Management"
    ],
    "summary": "Invitation details by invitationID",
    "description": "Visitor management is a software system used to manage the lifecycle of visitors. Inviter use this API to get the invitation details. \n  \n \n**Prerequisite:**  \n \n* Users need to be assigned a visitor management license. \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `visitor_management:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `visitor_management:read:invitation_detail[...]",
    "operationId": "getInvitation",
    "security": [
     {
      "openapi_oauth": [
       "visitor_management:read",
       "visitor_management:read:invitation_details",
       "visitor_management:read:invitation_details:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "visitor_management:read"
     ],
     "x-granular-scopes": [
      "visitor_management:read:invitation_details",
      "visitor_management:read:invitation_details:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Visitor Management"
    ],
    "summary": "Delete an Invitation ",
    "description": "Visitor management is a software system used to manage the lifecycle of visitors. Inviter use this API to cancel or delete an invitation. \n  \n \n**Prerequisite:**  \n \n* Users need to be assigned a visitor management license. \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `visitor_management:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `visitor_management:delete:invitation[...]",
    "operationId": "deleteInvitation",
    "security": [
     {
      "openapi_oauth": [
       "visitor_management:write",
       "visitor_management:delete:invitation",
       "visitor_management:delete:invitation:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "visitor_management:write"
     ],
     "x-granular-scopes": [
      "visitor_management:delete:invitation",
      "visitor_management:delete:invitation:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Visitor Management"
    ],
    "summary": "Update an invitation",
    "description": "Update a invitation. Visitor management is a software system used to manage the visitors' lifecycle.\n  \n \n**Prerequisite:**  \n \n* Users need to be assigned a visitor management license. \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `visitor_management:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `visitor_management:update:invitation`,`visitor_management:update:invitatio[...]",
    "operationId": "updateInvitation",
    "security": [
     {
      "openapi_oauth": [
       "visitor_management:write",
       "visitor_management:update:invitation",
       "visitor_management:update:invitation:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "visitor_management:write"
     ],
     "x-granular-scopes": [
      "visitor_management:update:invitation",
      "visitor_management:update:invitation:admin"
     ]
    }
   }
  },
  "/visitor/invitation/{invitationId}/checkin": {
   "post": {
    "tags": [
     "Visitor Management"
    ],
    "summary": "Check in a visitor",
    "description": "Check in an invitation. \n  \n \n**Prerequisite:**  \n \n* Users need to be assigned a visitor management license. \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `visitor_management:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `visitor_management:write:check_in`,`visitor_management:write:check_in:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/ra[...]",
    "operationId": "checkinVisitor",
    "security": [
     {
      "openapi_oauth": [
       "visitor_management:write",
       "visitor_management:write:check_in",
       "visitor_management:write:check_in:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "visitor_management:write"
     ],
     "x-granular-scopes": [
      "visitor_management:write:check_in",
      "visitor_management:write:check_in:admin"
     ]
    }
   }
  },
  "/workspaces": {
   "get": {
    "tags": [
     "Workspaces"
    ],
    "summary": "List workspaces",
    "description": "List a location's workspaces. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:read`,`workspace:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:read:list_workspaces`,`workspace:read:list_workspaces:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "listWorkspaces",
    "security": [
     {
      "openapi_oauth": [
       "workspace:read",
       "workspace:read:admin",
       "workspace:read:list_workspaces",
       "workspace:read:list_workspaces:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "WorkspacesManagement:Read"
     ],
     "x-macro-scopes": [
      "workspace:read",
      "workspace:read:admin"
     ],
     "x-granular-scopes": [
      "workspace:read:list_workspaces",
      "workspace:read:list_workspaces:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Workspaces"
    ],
    "summary": "Create a workspace",
    "description": "Creates workspaces.  \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:write:workspace:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "createWorkspace",
    "security": [
     {
      "openapi_oauth": [
       "workspace:write:admin",
       "workspace:write:workspace:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "workspace:write:admin"
     ],
     "x-granular-scopes": [
      "workspace:write:workspace:admin"
     ]
    }
   }
  },
  "/workspaces/additional_informations": {
   "get": {
    "tags": [
     "Workspaces"
    ],
    "summary": "List workspace additional information with time range",
    "description": "List a location workspaces' additional informations with time range.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:read:admin`,`workspace:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:read:list_workspaces`,`workspace:read:list_workspaces:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "Getaworkspaceadditionalenhancements",
    "security": [
     {
      "openapi_oauth": [
       "workspace:read:admin",
       "workspace:read",
       "workspace:read:list_workspaces",
       "workspace:read:list_workspaces:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "WorkspacesManagement:Read"
     ],
     "x-macro-scopes": [
      "workspace:read:admin",
      "workspace:read"
     ],
     "x-granular-scopes": [
      "workspace:read:list_workspaces",
      "workspace:read:list_workspaces:admin"
     ]
    }
   }
  },
  "/workspaces/assets": {
   "get": {
    "tags": [
     "Workspaces"
    ],
    "summary": "Get all workspace assets",
    "description": "List all workspace assets.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:read:asset:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "Getallworkspaceassets",
    "security": [
     {
      "openapi_oauth": [
       "workspace:read:admin",
       "workspace:read:asset:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "WorkspacesManagement:Read"
     ],
     "x-macro-scopes": [
      "workspace:read:admin"
     ],
     "x-granular-scopes": [
      "workspace:read:asset:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Workspaces"
    ],
    "summary": "Create a workspace asset",
    "description": "Create a new workspace asset.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:write:asset:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "AddaWorkspaceasset",
    "security": [
     {
      "openapi_oauth": [
       "workspace:write:admin",
       "workspace:write:asset:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "workspace:write:admin"
     ],
     "x-granular-scopes": [
      "workspace:write:asset:admin"
     ]
    }
   }
  },
  "/workspaces/assets/{assetId}": {
   "get": {
    "tags": [
     "Workspaces"
    ],
    "summary": "Get a workspace asset",
    "description": "Create a workspace asset based on the asset ID. \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:read:asset:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "get_workspace_asset",
    "security": [
     {
      "openapi_oauth": [
       "workspace:read:admin",
       "workspace:read:asset:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "workspace:read:admin"
     ],
     "x-granular-scopes": [
      "workspace:read:asset:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Workspaces"
    ],
    "summary": "Delete a workspace asset",
    "description": "Delete a workspace asset by asset ID.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:delete:asset:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "DeleteaWorkspaceasset",
    "security": [
     {
      "openapi_oauth": [
       "workspace:write:admin",
       "workspace:delete:asset:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "workspace:write:admin"
     ],
     "x-granular-scopes": [
      "workspace:delete:asset:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Workspaces"
    ],
    "summary": "Edit a workspace asset",
    "description": "Edit the workspace's asset based on asset ID. \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:update:asset:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "PatchWorkspaceasset",
    "security": [
     {
      "openapi_oauth": [
       "workspace:write:admin",
       "workspace:update:asset:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "workspace:write:admin"
     ],
     "x-granular-scopes": [
      "workspace:update:asset:admin"
     ]
    }
   }
  },
  "/workspaces/events": {
   "post": {
    "tags": [
     "Workspaces"
    ],
    "summary": "Check in/out of a reservation",
    "description": "Use this API to check in to or out of a reservation. This API does not support Zoom Room Desk and Common Area Phone Desk. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:write:events`,`workspace:write:events:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-lim[...]",
    "operationId": "reservationEvent",
    "security": [
     {
      "openapi_oauth": [
       "workspace:write:admin",
       "workspace:write:events",
       "workspace:write:events:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "workspace:write:admin"
     ],
     "x-granular-scopes": [
      "workspace:write:events",
      "workspace:write:events:admin"
     ]
    }
   }
  },
  "/workspaces/floormap/files": {
   "post": {
    "tags": [
     "Workspaces"
    ],
    "summary": "Add or Update a Workspace floor map",
    "description": "Use this API to Add or Update a Workspace floor map.  \n\n**Prerequisite:**   The caller must be a Zoom Workspace licensed user\n**Note:**   Base URL: `https://fileapi.zoom.us/v2/`\n* Rate limit: 20 requests per second per user or 2000 requests per second per IP address\n* The caller must support HTTP 30x redirects\n* The caller must retain the Authorization header when redirected to a different hostname\n* JPG/JPEG, 24-bit PNG, PDF\n* Recommended dimensions - 1920 x 1080 (la[...]",
    "operationId": "AddOrUpdateAWorkspaceFloorMap",
    "security": [
     {
      "openapi_oauth": [
       "workspace:write:admin",
       "workspace:write:location",
       "workspace:write:location:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "WorkspacesManagement:Edit"
     ],
     "x-macro-scopes": [
      "workspace:write:admin"
     ],
     "x-granular-scopes": [
      "workspace:write:location",
      "workspace:write:location:admin"
     ]
    }
   }
  },
  "/workspaces/released_workspaces_by_timeout": {
   "get": {
    "tags": [
     "Workspaces"
    ],
    "summary": "List released workspaces by timeout",
    "description": "Lists workspaces that were released due to missing check-in or checkout information. The maximum query time interval is one month.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:read:admin`,`room:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:read:list_release_infos:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#r[...]",
    "operationId": "getWorksapceReservationReleaseInof",
    "security": [
     {
      "openapi_oauth": [
       "workspace:read:admin",
       "room:read:admin",
       "zoom_rooms:read:list_release_infos:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "workspace:read:admin",
      "room:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:read:list_release_infos:admin"
     ]
    }
   }
  },
  "/workspaces/settings": {
   "patch": {
    "tags": [
     "Workspaces"
    ],
    "summary": "Update workspace settings",
    "description": "Updates workspace settings.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:write`,`workspace:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:update:setting:admin`,`workspace:update:setting:master`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "updateWorkspaceSettings",
    "security": [
     {
      "openapi_oauth": [
       "workspace:write",
       "workspace:write:admin",
       "workspace:update:setting:admin",
       "workspace:update:setting:master"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "WorkspacesManagement:Edit"
     ],
     "x-macro-scopes": [
      "workspace:write",
      "workspace:write:admin"
     ],
     "x-granular-scopes": [
      "workspace:update:setting:admin",
      "workspace:update:setting:master"
     ]
    }
   }
  },
  "/workspaces/usage": {
   "get": {
    "tags": [
     "Workspaces"
    ],
    "summary": "Get a location's hot desk usage",
    "description": "Creates a location's [hot desk](https://en.wikipedia.org/wiki/Hot_desking) usage information.  \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:read:admin`,`workspace:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:read:usage`,`workspace:read:usage:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "getHotDeskUsage",
    "security": [
     {
      "openapi_oauth": [
       "workspace:read:admin",
       "workspace:read",
       "workspace:read:usage",
       "workspace:read:usage:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "workspace:read:admin",
      "workspace:read"
     ],
     "x-granular-scopes": [
      "workspace:read:usage",
      "workspace:read:usage:admin"
     ]
    }
   }
  },
  "/workspaces/users/{userId}/calendar/settings": {
   "get": {
    "tags": [
     "Workspaces"
    ],
    "summary": "Get  Workspace Calendar Free/Busy Event",
    "description": "List workspace calendar free or busy event settings.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:read:workspace:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "GetWorkspaceCalendarFree/BusyEvent",
    "security": [
     {
      "openapi_oauth": [
       "workspace:read:admin",
       "workspace:read:workspace:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "WorkspacesManagement:Read"
     ],
     "x-macro-scopes": [
      "workspace:read:admin"
     ],
     "x-granular-scopes": [
      "workspace:read:workspace:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Workspaces"
    ],
    "summary": "Set Workspace Calendar Free/Busy Event",
    "description": "Set calendar free or busy event.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:write:workspace:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "SetCalendarFree/BusyEvent",
    "security": [
     {
      "openapi_oauth": [
       "workspace:write:admin",
       "workspace:write:workspace:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "WorkspacesManagement:Edit"
     ],
     "x-macro-scopes": [
      "workspace:write:admin"
     ],
     "x-granular-scopes": [
      "workspace:write:workspace:admin"
     ]
    }
   }
  },
  "/workspaces/users/{userId}/reservations": {
   "get": {
    "tags": [
     "Workspaces"
    ],
    "summary": "Get a user's workspace's reservations",
    "description": "Retrieves a user's workspace's reservations. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:read:list_reservations:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "userListReservations",
    "security": [
     {
      "openapi_oauth": [
       "workspace:read:admin",
       "workspace:read:list_reservations:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "WorkspacesManagement:Read"
     ],
     "x-macro-scopes": [
      "workspace:read:admin"
     ],
     "x-granular-scopes": [
      "workspace:read:list_reservations:admin"
     ]
    }
   }
  },
  "/workspaces/{locationId}/background": {
   "delete": {
    "tags": [
     "Workspaces"
    ],
    "summary": "Delete Workspace floor map",
    "description": "Use this API to delete a workspace floor map.  \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:write:location`,`workspace:write:location:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`\n\n**Not supported in Gov cluster** ",
    "operationId": "DeleteWorkspaceFloorMap",
    "security": [
     {
      "openapi_oauth": [
       "workspace:write:admin",
       "workspace:write:location",
       "workspace:write:location:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "WorkspacesManagement:Edit"
     ],
     "x-macro-scopes": [
      "workspace:write:admin"
     ],
     "x-granular-scopes": [
      "workspace:write:location",
      "workspace:write:location:admin"
     ]
    }
   }
  },
  "/workspaces/{workspaceId}": {
   "get": {
    "tags": [
     "Workspaces"
    ],
    "summary": "Get a workspace",
    "description": "Creates workspace detail.  \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:read:list_workspaces`,`workspace:read:list_workspaces:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "getWorkspace",
    "security": [
     {
      "openapi_oauth": [
       "workspace:read:admin",
       "workspace:read:list_workspaces",
       "workspace:read:list_workspaces:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "WorkspacesManagement:Read"
     ],
     "x-macro-scopes": [
      "workspace:read:admin"
     ],
     "x-granular-scopes": [
      "workspace:read:list_workspaces",
      "workspace:read:list_workspaces:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Workspaces"
    ],
    "summary": "Delete a workspace",
    "description": "Deletes workspace detail.  \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:delete:workspace:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "deleteWorkspace",
    "security": [
     {
      "openapi_oauth": [
       "workspace:write:admin",
       "workspace:delete:workspace:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "workspace:write:admin"
     ],
     "x-granular-scopes": [
      "workspace:delete:workspace:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Workspaces"
    ],
    "summary": "Update a workspace",
    "description": "Updates workspace detail.  \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:update:workspace:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "updateWorkspace",
    "security": [
     {
      "openapi_oauth": [
       "workspace:write:admin",
       "workspace:update:workspace:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "workspace:write:admin"
     ],
     "x-granular-scopes": [
      "workspace:update:workspace:admin"
     ]
    }
   }
  },
  "/workspaces/{workspaceId}/assignment": {
   "get": {
    "tags": [
     "Workspaces"
    ],
    "summary": "Get a desk assignment",
    "description": "Get a desk assignment.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:read:admin`,`workspace:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:read:assignment`,`workspace:read:assignment:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "Getadeskassignment",
    "security": [
     {
      "openapi_oauth": [
       "workspace:read:admin",
       "workspace:read",
       "workspace:read:assignment",
       "workspace:read:assignment:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "WorkspacesManagement:Read"
     ],
     "x-macro-scopes": [
      "workspace:read:admin",
      "workspace:read"
     ],
     "x-granular-scopes": [
      "workspace:read:assignment",
      "workspace:read:assignment:admin"
     ]
    }
   },
   "put": {
    "tags": [
     "Workspaces"
    ],
    "summary": "Set a desk assignment",
    "description": "Set a desk assignment.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:write:assignment:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "setADeskAssignment",
    "security": [
     {
      "openapi_oauth": [
       "workspace:write:admin",
       "workspace:write:assignment:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "WorkspacesManagement:Edit"
     ],
     "x-macro-scopes": [
      "workspace:write:admin"
     ],
     "x-granular-scopes": [
      "workspace:write:assignment:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Workspaces"
    ],
    "summary": "Delete a desk assignment",
    "description": "Deletes a desk assignment.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:delete:assignment:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "Deleteadeskassignment",
    "security": [
     {
      "openapi_oauth": [
       "workspace:write:admin",
       "workspace:delete:assignment:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "WorkspacesManagement:Edit"
     ],
     "x-macro-scopes": [
      "workspace:write:admin"
     ],
     "x-granular-scopes": [
      "workspace:delete:assignment:admin"
     ]
    }
   }
  },
  "/workspaces/{workspaceId}/qr_code": {
   "get": {
    "tags": [
     "Workspaces"
    ],
    "summary": "Get a workspace QR code",
    "description": "Use this API to get the workspace QR code. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:read:qr:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "getWorkspaceQRCode",
    "security": [
     {
      "openapi_oauth": [
       "workspace:read:admin",
       "workspace:read:qr:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "WorkspacesManagement:Read"
     ],
     "x-macro-scopes": [
      "workspace:read:admin"
     ],
     "x-granular-scopes": [
      "workspace:read:qr:admin"
     ]
    }
   }
  },
  "/workspaces/{workspaceId}/reservations": {
   "get": {
    "tags": [
     "Workspaces"
    ],
    "summary": "Get a workspace's reservations",
    "description": "Retrieves a workspace's reservations. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:read:admin`,`workspace:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:read:list_reservations`,`workspace:read:list_reservations:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "listReservations",
    "security": [
     {
      "openapi_oauth": [
       "workspace:read:admin",
       "workspace:read",
       "workspace:read:list_reservations",
       "workspace:read:list_reservations:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "WorkspacesManagement:Read"
     ],
     "x-macro-scopes": [
      "workspace:read:admin",
      "workspace:read"
     ],
     "x-granular-scopes": [
      "workspace:read:list_reservations",
      "workspace:read:list_reservations:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Workspaces"
    ],
    "summary": "Create a reservation",
    "description": "Creates a workspace reservation.  \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:write`,`workspace:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:write:reservation`,`workspace:write:reservation:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "createReservation",
    "security": [
     {
      "openapi_oauth": [
       "workspace:write",
       "workspace:write:admin",
       "workspace:write:reservation",
       "workspace:write:reservation:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "WorkspacesManagement:Edit"
     ],
     "x-macro-scopes": [
      "workspace:write",
      "workspace:write:admin"
     ],
     "x-granular-scopes": [
      "workspace:write:reservation",
      "workspace:write:reservation:admin"
     ]
    }
   }
  },
  "/workspaces/{workspaceId}/reservations/{reservationId}": {
   "get": {
    "tags": [
     "Workspaces"
    ],
    "summary": "Get a workspace reservation by reservationId",
    "description": "Retrieves a workspace reservation ID.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:read`,`workspace:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:read:reservation`,`workspace:read:reservation:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "GETGetaworkspacereservationbyreservationID",
    "security": [
     {
      "openapi_oauth": [
       "workspace:read",
       "workspace:read:admin",
       "workspace:read:reservation",
       "workspace:read:reservation:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "WorkspacesManagement:Read"
     ],
     "x-macro-scopes": [
      "workspace:read",
      "workspace:read:admin"
     ],
     "x-granular-scopes": [
      "workspace:read:reservation",
      "workspace:read:reservation:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Workspaces"
    ],
    "summary": "Delete a reservation",
    "description": "Deletes a reservation.  \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:write`,`workspace:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:delete:reservation`,`workspace:delete:reservation:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "deleteReservation",
    "security": [
     {
      "openapi_oauth": [
       "workspace:write",
       "workspace:write:admin",
       "workspace:delete:reservation",
       "workspace:delete:reservation:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "workspace:write",
      "workspace:write:admin"
     ],
     "x-granular-scopes": [
      "workspace:delete:reservation",
      "workspace:delete:reservation:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Workspaces"
    ],
    "summary": "Update a reservation",
    "description": "Updates a reservation. This API supports maintaining workspace reservation event of the next `6` months. The `start_time` and `end_time` time range of a single workspace reservation event can be a minimum of `15` minutes and a maximum of `24` hours.  \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:write`,`workspace:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `work[...]",
    "operationId": "updateReservation",
    "security": [
     {
      "openapi_oauth": [
       "workspace:write",
       "workspace:write:admin",
       "workspace:update:reservation",
       "workspace:update:reservation:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "workspace:write",
      "workspace:write:admin"
     ],
     "x-granular-scopes": [
      "workspace:update:reservation",
      "workspace:update:reservation:admin"
     ]
    }
   }
  },
  "/workspaces/{workspaceId}/reservations/{reservationId}/questionnaires": {
   "get": {
    "tags": [
     "Workspaces"
    ],
    "summary": "List workspace reservation questionnaires",
    "description": "List workspace reservation questionnaires.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `workspace:read:reservation:admin`,`workspace:read:reservation:master`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "Listworkspacereservationquestionnaires",
    "security": [
     {
      "openapi_oauth": [
       "workspace:read:admin",
       "workspace:read:reservation:admin",
       "workspace:read:reservation:master"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "WorkspacesManagement:Read"
     ],
     "x-macro-scopes": [
      "workspace:read:admin"
     ],
     "x-granular-scopes": [
      "workspace:read:reservation:admin",
      "workspace:read:reservation:master"
     ]
    }
   }
  },
  "/rooms": {
   "get": {
    "tags": [
     "Zoom Rooms"
    ],
    "summary": "List Zoom Rooms",
    "description": "Zoom Rooms is a software-based room system that provides an integrated experience for audio conferencing, wireless screen sharing and video conferencing. Use this API to list all the existing [Zoom Rooms](https://support.zoom.us/hc/en-us/articles/207483343-Getting-Started-with-Zoom-Rooms) in a Zoom account.  \n   \n \n**Prerequisites:**  \n \n* Pro or a higher plan with [Zoom Room](https://zoom.us/zoomrooms) license.  \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integr[...]",
    "operationId": "listZoomRooms",
    "security": [
     {
      "openapi_oauth": [
       "room:read:admin",
       "zoom_rooms:read:list_rooms:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomRooms:Read"
     ],
     "x-macro-scopes": [
      "room:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:read:list_rooms:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Zoom Rooms"
    ],
    "summary": "Add a Zoom Room",
    "description": "Use this API to [add a Zoom Room](https://support.zoom.us/hc/en-us/articles/202822279-Add-Zoom-Rooms-on-Web-Portal) to a Zoom account.  \n   \n \n**Prerequisites:**  \n \n* Pro or a higher plan with [Zoom Room](https://zoom.us/zoomrooms) license.  \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:write:room:adm[...]",
    "operationId": "addARoom",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:write:room:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomRooms:Edit"
     ],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:write:room:admin"
     ]
    }
   }
  },
  "/rooms/digital_signage": {
   "get": {
    "tags": [
     "Zoom Rooms"
    ],
    "summary": "List digital signage contents",
    "description": "Use this API to return information about a Zoom account's [Zoom Rooms digital signage content](https://support.zoom.us/hc/en-us/articles/360000030683-Zoom-Rooms-digital-signage). You can also view this content in the **Room Management** section's [**Digital Signage Content**](https://zoom.us/digitalsignage#/) tab in the Zoom web portal. \n\n**Prerequisites:** \n* A Pro or a higher account with Zoom Rooms. \n* Existing content in the **Digital Signage Content** tab.\n\n**[Scop[...]",
    "operationId": "listDigitalSignageContent",
    "security": [
     {
      "openapi_oauth": [
       "room:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-macro-scopes": [
      "room:read:admin"
     ]
    }
   }
  },
  "/rooms/events": {
   "patch": {
    "tags": [
     "Zoom Rooms"
    ],
    "summary": "Update E911 digital signage",
    "description": "Display or hide E911 emergency alert text content from [Zoom Rooms digital signage](https://support.zoom.us/hc/en-us/articles/360000030683-Zoom-Rooms-digital-signage).\n\n**Prerequisites:**  \n \n* [Zoom Rooms](https://zoom.us/zoomrooms/software) 5.3.0 or higher\n* Zoom Rooms digital signage must be [enabled](https://support.zoom.us/hc/en-us/articles/360000030683-Zoom-Rooms-Digital-Signage#h_767fbb33-82a8-45a8-8392-a1bfa9687edd)\n\n\n**[Scopes](https://developers.zoom.us/docs[...]",
    "operationId": "manageE911signage",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:update:room_controls:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:update:room_controls:admin"
     ]
    }
   }
  },
  "/rooms/{id}/events": {
   "patch": {
    "tags": [
     "Zoom Rooms"
    ],
    "summary": "Use Zoom Room controls",
    "description": "Controls [Zoom Rooms](https://support.zoom.us/hc/en-us/articles/207483343), including: \n* Room check-in and check-out.\n* Video and audio mute on and off.\n* Incoming meeting request accept or decline.\n* Meeting join, leave, or end.\n* Room restart.\n* Cancellation.\n* Switch between available cameras, speakers or microphones during a meeting.\n* Start or stop screen sharing.\n* Perform speaker volume changes during a meeting.\n\n\n\n**Prerequisites:**\n* [Zoom Rooms](https[...]",
    "operationId": "ZoomRoomsControls",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:update:room_control:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:update:room_control:admin"
     ]
    }
   }
  },
  "/rooms/{id}/settings": {
   "get": {
    "tags": [
     "Zoom Rooms"
    ],
    "summary": "Get Zoom Room settings",
    "description": "Get information on meeting, alert, digital signage or scheduling display settings applied to a specific Zoom Room. By default, only **Meeting Settings** are returned. To view only **Alert Settings**, specify `alert` as the value of the `setting_type` query parameter.   \n**Prerequisites:**   *Zoom Room licenses* Owner or Admin privileges on the Zoom Account.   \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:read:admin`\n\n**[Granul[...]",
    "operationId": "getZRSettings",
    "security": [
     {
      "openapi_oauth": [
       "room:read:admin",
       "zoom_rooms:read:room_settings:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomRooms:Read"
     ],
     "x-macro-scopes": [
      "room:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:read:room_settings:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Zoom Rooms"
    ],
    "summary": "Update Zoom Room settings",
    "description": "Update meeting, alert, digital signage or scheduling display settings applied to a specific Zoom Room. To update **Alert Settings**, specify `alert` as the value of the `setting_type` query parameter. To update **Meeting Settings**, specify `meeting` as the value of the `setting_type` query parameter.   **Prerequisites:**   * Zoom Room licenses.* Owner or Admin privileges on the Zoom Account.   \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/[...]",
    "operationId": "updateZRSettings",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:update:room_settings:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomRooms:Edit"
     ],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:update:room_settings:admin"
     ]
    }
   }
  },
  "/rooms/{roomId}": {
   "get": {
    "tags": [
     "Zoom Rooms"
    ],
    "summary": "Get Zoom Room profile",
    "description": "\nZoom Rooms is a software-based room system that provides an integrated experience for audio conferencing, wireless screen sharing and video conferencing. Use this API to get detailed information on a specific Zoom Room in a Zoom account.\n\n**Prerequisites:**  \n \n* Pro or a higher plan with [Zoom Room](https://zoom.us/zoomrooms) license.  \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:read:admin`\n\n**[Granular Scopes](ht[...]",
    "operationId": "getZRProfile",
    "security": [
     {
      "openapi_oauth": [
       "room:read:admin",
       "zoom_rooms:read:room:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomRooms:Read"
     ],
     "x-macro-scopes": [
      "room:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:read:room:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Zoom Rooms"
    ],
    "summary": "Delete a Zoom Room",
    "description": "[Remove](https://support.zoom.us/hc/en-us/articles/360033432032-Zoom-Room-Device-Profiles#h_e55b2092-c418-4b02-819f-44de51448900) a specific Zoom Room profile from a Zoom account.  \n   \n \n**Prerequisites:**  \n \n* Pro or a higher plan with [Zoom Room](https://zoom.us/zoomrooms) license.  \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-sc[...]",
    "operationId": "deleteAZoomRoom",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:delete:room:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomRooms:Edit"
     ],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:delete:room:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Zoom Rooms"
    ],
    "summary": "Update a Zoom Room profile",
    "description": "Update basic information on a specific Zoom Room in a Zoom account.  \n \n\n**Prerequisites:**  \n \n* Pro or a higher plan with [Zoom Room](https://zoom.us/zoomrooms) license.  \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:update:room:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-refe[...]",
    "operationId": "updateRoomProfile",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:update:room:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomRooms:Edit"
     ],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:update:room:admin"
     ]
    }
   }
  },
  "/rooms/{roomId}/device_profiles": {
   "get": {
    "tags": [
     "Zoom Rooms"
    ],
    "summary": "List device profiles",
    "description": "Returns a list of Zoom Room device profiles.  **Prerequisites:** * A Pro or a higher account with Zoom Rooms.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:read:list_device_profiles:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "getRoomProfiles",
    "security": [
     {
      "openapi_oauth": [
       "room:read:admin",
       "zoom_rooms:read:list_device_profiles:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "room:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:read:list_device_profiles:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Zoom Rooms"
    ],
    "summary": "Create a device profile",
    "description": "Creates a Zoom Room device profile.  **Prerequisites:** * A Pro or a higher account with Zoom Rooms.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:write:device_profile:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "createRoomDeviceProfile",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:write:device_profile:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:write:device_profile:admin"
     ]
    }
   }
  },
  "/rooms/{roomId}/device_profiles/devices": {
   "get": {
    "tags": [
     "Zoom Rooms"
    ],
    "summary": "Get device information",
    "description": "Returns information about a Zoom Room device.  **Prerequisites:** * A Pro or a higher account with Zoom Rooms.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:read:device_profile:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "getRoomDevices",
    "security": [
     {
      "openapi_oauth": [
       "room:read:admin",
       "zoom_rooms:read:device_profile:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "room:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:read:device_profile:admin"
     ]
    }
   }
  },
  "/rooms/{roomId}/device_profiles/{deviceProfileId}": {
   "get": {
    "tags": [
     "Zoom Rooms"
    ],
    "summary": "Get a device profile",
    "description": "Returns a Zoom Room device profile.  **Prerequisites:** * A Pro or a higher account with Zoom Rooms.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:read:admin`,`room:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:read:device_profile:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "getRoomProfile",
    "security": [
     {
      "openapi_oauth": [
       "room:read:admin",
       "room:write:admin",
       "zoom_rooms:read:device_profile:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomRooms:Read"
     ],
     "x-macro-scopes": [
      "room:read:admin",
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:read:device_profile:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Zoom Rooms"
    ],
    "summary": "Delete a device profile",
    "description": "Deletes a Zoom Room device profile.  **Prerequisites:** * A Pro or a higher account with Zoom Rooms.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:delete:device_profile:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "deleteRoomProfile",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:delete:device_profile:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:delete:device_profile:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Zoom Rooms"
    ],
    "summary": "Update a device profile",
    "description": "Updates a Zoom Room device profile.  **Prerequisites:** * A Pro or a higher account with Zoom Rooms.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:update:device_profile:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "updateDeviceProfile",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:update:device_profile:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:update:device_profile:admin"
     ]
    }
   }
  },
  "/rooms/{roomId}/devices": {
   "get": {
    "tags": [
     "Zoom Rooms"
    ],
    "summary": "List Zoom Room devices",
    "description": "List information about the devices that are being used for a specific [Zoom Room](https://support.zoom.us/hc/en-us/articles/207483343-Getting-Started-with-Zoom-Rooms) in an account.\n\n**Prerequisites:**  \n \n* Pro or a higher plan with [Zoom Room](https://zoom.us/zoomrooms) license.  \n \n* Account owner or admin permissions.\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:read:admin`\n\n**[Granular Scopes](https://developers.zo[...]",
    "operationId": "listZRDevices",
    "security": [
     {
      "openapi_oauth": [
       "room:read:admin",
       "zoom_rooms:read:list_devices:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomRooms:Read"
     ],
     "x-macro-scopes": [
      "room:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:read:list_devices:admin"
     ]
    }
   }
  },
  "/rooms/{roomId}/location": {
   "put": {
    "tags": [
     "Zoom Rooms"
    ],
    "summary": "Change a Zoom Room's location",
    "description": "An account owner of a Zoom account can establish a [Zoom Rooms Location Hierarchy](https://support.zoom.us/hc/en-us/articles/115000342983-Zoom-Rooms-Location-Hierarchy) to better organize Zoom Rooms spread across various locations. The location can be structured in a hierarchy with Country being the top-level location, followed by city, campus, building, and floor. Use this API to assign a new location for a Zoom Room. Note that the Zoom Room can be assigned only to the lowes[...]",
    "operationId": "changeZRLocation",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:update:room_location:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomRooms:Edit"
     ],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:update:room_location:admin"
     ]
    }
   }
  },
  "/rooms/{roomId}/sensor_data": {
   "get": {
    "tags": [
     "Zoom Rooms"
    ],
    "summary": "Get Zoom Room sensor data",
    "description": "Retrieves the sensor data from the specified Zoom Room. \n\n   **Prerequisites** \n\n  * Zoom Room licenses\n  * Owner or Admin privileges on the Zoom Account.   \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:read:sensor_data:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits[...]",
    "operationId": "getZRSensorData",
    "security": [
     {
      "openapi_oauth": [
       "room:read:admin",
       "zoom_rooms:read:sensor_data:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "room:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:read:sensor_data:admin"
     ]
    }
   }
  },
  "/rooms/{roomId}/virtual_controller": {
   "get": {
    "tags": [
     "Zoom Rooms"
    ],
    "summary": "Get Zoom Rooms virtual controller URL",
    "description": "Get the Zoom Rooms virtual controller URL. \n\n**Prerequisites:**  \n* Pro or a higher plan with [Zoom Room](https://zoom.us/zoomrooms) license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:read:virtual_controller:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limit[...]",
    "operationId": "getWebzrcUrl",
    "security": [
     {
      "openapi_oauth": [
       "room:read:admin",
       "zoom_rooms:read:virtual_controller:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZRWebController:Edit"
     ],
     "x-macro-scopes": [
      "room:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:read:virtual_controller:admin"
     ]
    }
   }
  },
  "/rooms/account_profile": {
   "get": {
    "tags": [
     "Zoom Rooms Account"
    ],
    "summary": "Get Zoom Room account profile",
    "description": "Get details on the account profile of a Zoom Room. This information can only by accessed either by the Zoom Room Account Owner or a user with Zoom Rooms admin permission. To get information on an individual room profile, use the [**Get Zoom Room profile**](/docs/api-reference/zoom-api/methods#operation/getZRProfile) API. \n\n**Prerequisites:**  \n \n* Zoom account owner or Zoom Rooms admin permissions.  \n \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-[...]",
    "operationId": "getZRAccountProfile",
    "security": [
     {
      "openapi_oauth": [
       "room:read:admin",
       "zoom_rooms:read:account_profile:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "room:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:read:account_profile:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Zoom Rooms Account"
    ],
    "summary": "Update Zoom Room account profile",
    "description": "Update information on the account profile of a Zoom Room. This information can only by accessed either by the Zoom Room Account Owner or a user with Zoom Rooms admin permission. To update information on an individual room profile, use the [**Update a Zoom Room profile**](/docs/api-reference/zoom-api/methods#operation/updateRoomProfile) API. \n\n**Prerequisites:**  \n \n* Zoom account owner or Zoom Rooms admin permissions.  \n \n\n\n\n**[Scopes](https://developers.zoom.us/docs[...]",
    "operationId": "updateZRAccProfile",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:update:account_profile:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:update:account_profile:admin"
     ]
    }
   }
  },
  "/rooms/account_settings": {
   "get": {
    "tags": [
     "Zoom Rooms Account"
    ],
    "summary": "Get Zoom Room account settings",
    "description": "Get details on Account Settings of a Zoom Room. With this API, you can view the **Account Meeting Settings**, **Alert Settings** (Client Alert Settings and Notification Settings), **Digital Signage Settings** or **Scheduling Display Settings** of the Zoom Rooms account. By default, only **Account Meeting Settings** are returned. To view only **Alert Settings**, specify `alert` as the value of the `setting_type` query parameter.  \n   \n \n**Prerequisites:**  \n \n* Zoom Room [...]",
    "operationId": "getZRAccountSettings",
    "security": [
     {
      "openapi_oauth": [
       "room:read:admin",
       "zoom_rooms:read:account_settings:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomRooms:Read"
     ],
     "x-macro-scopes": [
      "room:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:read:account_settings:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Zoom Rooms Account"
    ],
    "summary": "Update Zoom Room account settings",
    "description": "Update account settings applied for Zoom Rooms in a Zoom account. With this API, you can update the **Account Meeting Settings**, **Alert Settings** (Client Alert Settings and Notification Settings), **Digital Signage Settings** or **Scheduling Display Settings** of the Zoom Rooms account by specifying the required setting type in the `setting_type` parameter. To update only **Alert Settings**, specify `alert` as the value of the `setting_type` query parameter and to update o[...]",
    "operationId": "updateZoomRoomAccSettings",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:update:account_settings:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomRooms:Edit"
     ],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:update:account_settings:admin"
     ]
    }
   }
  },
  "/rooms/calendar/services": {
   "get": {
    "tags": [
     "Zoom Rooms Calendar"
    ],
    "summary": "List calendar services",
    "description": "List all the existing [calendar services](https://support.zoom.us/hc/en-us/articles/4409832833037) in a Zoom Room account.  **Prerequisites:** * A Pro or a higher plan with a [Zoom Rooms](https://zoom.us/zoomrooms) license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:read:list_calendar_services:admin`\n\n**[Rate[...]",
    "operationId": "getCalendarServices",
    "security": [
     {
      "openapi_oauth": [
       "room:read:admin",
       "zoom_rooms:read:list_calendar_services:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "room:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:read:list_calendar_services:admin"
     ]
    }
   }
  },
  "/rooms/calendar/services/{serviceId}": {
   "delete": {
    "tags": [
     "Zoom Rooms Calendar"
    ],
    "summary": "Delete a calendar service",
    "description": "Deletes a Zoom Room account's calendar service.  **Prerequisites:** * A Pro or a higher plan with a [Zoom Rooms](https://zoom.us/zoomrooms) license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:delete:calendar_service:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-[...]",
    "operationId": "deleteACalendarService",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:delete:calendar_service:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:delete:calendar_service:admin"
     ]
    }
   }
  },
  "/rooms/calendar/services/{serviceId}/resources": {
   "get": {
    "tags": [
     "Zoom Rooms Calendar"
    ],
    "summary": "List calendar resources by calendar service",
    "description": "List all of a Zoom Room account's [calendar resources](https://support.zoom.us/hc/en-us/articles/4409832833037).  **Prerequisites:** * A Pro or a higher plan with a [Zoom Rooms](https://zoom.us/zoomrooms) license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:read:list_calendar_resources:admin`\n\n**[Rate Limit La[...]",
    "operationId": "getCalendarResourcesByServiceId",
    "security": [
     {
      "openapi_oauth": [
       "room:read:admin",
       "zoom_rooms:read:list_calendar_resources:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "room:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:read:list_calendar_resources:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Zoom Rooms Calendar"
    ],
    "summary": "Add a calendar resource to a calendar service",
    "description": "Use this API to add a [calendar resource](https://support.zoom.us/hc/en-us/articles/4409832833037) to a Microsoft Exchange or Office 365 calendar service in a Zoom Room account. \n\n**Note:** This API does not support adding a calendar resource to a Google calendar service. \n\n **Prerequisites:** \n* A Pro or a higher plan with a [Zoom Rooms](https://zoom.us/zoomrooms) license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:[...]",
    "operationId": "addACalendarResourceToCalendarService",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:write:calendar_resource:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:write:calendar_resource:admin"
     ]
    }
   }
  },
  "/rooms/calendar/services/{serviceId}/resources/{resourceId}": {
   "get": {
    "tags": [
     "Zoom Rooms Calendar"
    ],
    "summary": "Get a calendar resource by ID",
    "description": "List Zoom Room account's [calendar resource](https://support.zoom.us/hc/en-us/articles/4409832833037).  **Prerequisites:** * A Pro or a higher plan with a [Zoom Rooms](https://zoom.us/zoomrooms) license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:read:calendar_resource:admin`\n\n**[Rate Limit Label](https://mar[...]",
    "operationId": "getCalendarResourceById",
    "security": [
     {
      "openapi_oauth": [
       "room:read:admin",
       "zoom_rooms:read:calendar_resource:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "room:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:read:calendar_resource:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Zoom Rooms Calendar"
    ],
    "summary": "Delete a calendar resource",
    "description": "Deletes a Zoom Room account's [calendar resource](https://support.zoom.us/hc/en-us/articles/4409832833037) from a Microsoft Exchange or Office 365 calendar service. **Note:** This API does not support deleting a calendar resource from a Google calendar service.  **Prerequisites:** * A Pro or a higher plan with a [Zoom Rooms](https://zoom.us/zoomrooms) license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:admin`\n\n**[Granul[...]",
    "operationId": "deleteACalendarResource",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:delete:calendar_resource:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:delete:calendar_resource:admin"
     ]
    }
   }
  },
  "/rooms/calendar/services/{serviceId}/sync": {
   "put": {
    "tags": [
     "Zoom Rooms Calendar"
    ],
    "summary": "Start calendar service sync process",
    "description": "Use this API to kick off the sync process for Zoom Room account's calendar service. \n\n **Prerequisites:** \n* A Pro or a higher plan with a [Zoom Rooms](https://zoom.us/zoomrooms) license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:update:calendar_service:admin`\n\n**[Rate Limit Label](https://marketplace.zo[...]",
    "operationId": "syncACalendarService",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:update:calendar_service:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "CalendarIntegration:Edit",
      "ZoomRooms:Edit"
     ],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:update:calendar_service:admin"
     ]
    }
   }
  },
  "/rooms/content/background/contents": {
   "get": {
    "tags": [
     "Zoom Rooms Content"
    ],
    "summary": "List Zoom Rooms background image library contents",
    "description": "Returns a list of Zoom Rooms background image library contents. Maximum number per page 200.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:read:background_library_content:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "ListZoomRoomsbackgroundimagelibrarycontents",
    "security": [
     {
      "openapi_oauth": [
       "room:read:admin",
       "zoom_rooms:read:background_library_content:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomRooms:Read"
     ],
     "x-macro-scopes": [
      "room:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:read:background_library_content:admin"
     ]
    }
   }
  },
  "/rooms/content/background/contents/{contentId}": {
   "get": {
    "tags": [
     "Zoom Rooms Content"
    ],
    "summary": "Get Zoom Rooms background image library content",
    "description": "Return a Zoom Rooms background image library content item.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:read:background_library_content:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "GetZoomRoomsBackgroundImageLibraryContent",
    "security": [
     {
      "openapi_oauth": [
       "room:read:admin",
       "zoom_rooms:read:background_library_content:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomRooms:Read"
     ],
     "x-macro-scopes": [
      "room:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:read:background_library_content:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Zoom Rooms Content"
    ],
    "summary": "Delete Zoom Rooms Background Image Library Content",
    "description": "Deletes a Zoom Rooms background image library content item. Warning: the image will be deleted, and Zoom Rooms using the image will revert to the default background image.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:delete:background_library_content:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/doc[...]",
    "operationId": "DeleteZoomRoomsBackgroundImageLibraryContent",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:delete:background_library_content:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomRooms:Edit"
     ],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:delete:background_library_content:admin"
     ]
    }
   }
  },
  "/rooms/content/background/defaults": {
   "get": {
    "tags": [
     "Zoom Rooms Content"
    ],
    "summary": "List default Zoom Rooms background image library contents",
    "description": "Display a list of Zoom-provided default background images from the background image library.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:read:background_library_content:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "ListDefaultZoomRoomsBackgroundImageLibrarycontents",
    "security": [
     {
      "openapi_oauth": [
       "room:read:admin",
       "zoom_rooms:read:background_library_content:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomRooms:Read"
     ],
     "x-macro-scopes": [
      "room:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:read:background_library_content:admin"
     ]
    }
   }
  },
  "/rooms/content/background/folders": {
   "get": {
    "tags": [
     "Zoom Rooms Content"
    ],
    "summary": "List Zoom Rooms Background Image Library Folders",
    "description": "Returns a list of Zoom Rooms background image library content folders. Maximum number per page 200.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:read:background_library_folder:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "ListZoomRoomsBackgroundLibraryFolders",
    "security": [
     {
      "openapi_oauth": [
       "room:read:admin",
       "zoom_rooms:read:background_library_folder:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomRooms:Read"
     ],
     "x-macro-scopes": [
      "room:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:read:background_library_folder:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Zoom Rooms Content"
    ],
    "summary": "Add Zoom Rooms Background Image Library Folder",
    "description": "Use this API to add a Zoom Rooms background image library content folder. You may create up to 20 folders, maximum.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:write:background_library_folder:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "AddZoomRoomsBackgroundLibraryFolder",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:write:background_library_folder:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomRooms:Edit"
     ],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:write:background_library_folder:admin"
     ]
    }
   }
  },
  "/rooms/content/background/folders/{folderId}": {
   "get": {
    "tags": [
     "Zoom Rooms Content"
    ],
    "summary": "Get Zoom Rooms Background Image Library Folder",
    "description": "Returns a Zoom Rooms background image library folder.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:read:background_library_folder:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "GetZoomRoomsBackgroundLibraryFolder",
    "security": [
     {
      "openapi_oauth": [
       "room:read:admin",
       "zoom_rooms:read:background_library_folder:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomRooms:Read"
     ],
     "x-macro-scopes": [
      "room:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:read:background_library_folder:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Zoom Rooms Content"
    ],
    "summary": "Delete Zoom Rooms Background Image Library Folder",
    "description": "Deletes a Zoom Rooms background image library content folder.  Warning: all images in the folder will be deleted, and Zoom Rooms using those images will revert to the default background image.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:delete:background_library_folder:admin`\n\n**[Rate Limit Label](https://mar[...]",
    "operationId": "DeleteZoomRoomsBackgroundLibraryFolder",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:delete:background_library_folder:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomRooms:Edit"
     ],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:delete:background_library_folder:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Zoom Rooms Content"
    ],
    "summary": "Update Zoom Rooms Background Image Library Folder",
    "description": "Updates a Zoom Rooms background image library content folder.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:update:background_library_folder:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "UpdateaZoomRoomsBackgroundLibraryFolderName",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:update:background_library_folder:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomRooms:Edit"
     ],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:update:background_library_folder:admin"
     ]
    }
   }
  },
  "/rooms/content/digital_signage/contents": {
   "get": {
    "tags": [
     "Zoom Rooms Content"
    ],
    "summary": "List Digital Signage content items",
    "description": "Returns a list of Zoom Rooms digital signage library base folder content items.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:read:digital_signage_library_contents:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "GETListdigitalsignagecontentitems",
    "security": [
     {
      "openapi_oauth": [
       "room:read:admin",
       "zoom_rooms:read:digital_signage_library_contents:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "DigitalSignage:Read"
     ],
     "x-macro-scopes": [
      "room:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:read:digital_signage_library_contents:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Zoom Rooms Content"
    ],
    "summary": "Add a digital signage URL",
    "description": "Use this API to add a URL to the Zoom Rooms digital signage content library.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:write:digital_signage_library_contents:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "AddadigitalsignageURL",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:write:digital_signage_library_contents:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "DigitalSignage:Edit"
     ],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:write:digital_signage_library_contents:admin"
     ]
    }
   }
  },
  "/rooms/content/digital_signage/contents/{contentId}": {
   "get": {
    "tags": [
     "Zoom Rooms Content"
    ],
    "summary": "Get Digital Signage content item",
    "description": "Use this API to get the details of an individual digital signage content item.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:read:digital_signage_library_contents:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "Getdigitalsignagecontentitem",
    "security": [
     {
      "openapi_oauth": [
       "room:read:admin",
       "zoom_rooms:read:digital_signage_library_contents:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "DigitalSignage:Read"
     ],
     "x-macro-scopes": [
      "room:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:read:digital_signage_library_contents:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Zoom Rooms Content"
    ],
    "summary": "Delete a Digital Signage content item",
    "description": "Use this API to delete an individual digital signage content item.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:admin`,`room:write:master`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:write:digital_signage_library_contents:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "Deleteadigitalsignagecontentitem",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "room:write:master",
       "zoom_rooms:write:digital_signage_library_contents:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "DigitalSignage:Edit"
     ],
     "x-macro-scopes": [
      "room:write:admin",
      "room:write:master"
     ],
     "x-granular-scopes": [
      "zoom_rooms:write:digital_signage_library_contents:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Zoom Rooms Content"
    ],
    "summary": "Update a Digital Signage content item attributes",
    "description": "Use this API to update a digital signage content item's attributes.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:write:digital_signage_library_contents:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "Updateadigitalsignagecontentitemattributes",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:write:digital_signage_library_contents:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "DigitalSignage:Edit"
     ],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:write:digital_signage_library_contents:admin"
     ]
    }
   }
  },
  "/rooms/content/digital_signage/folders": {
   "post": {
    "tags": [
     "Zoom Rooms Content"
    ],
    "summary": "Add a digital signage content folder",
    "description": "Use this API to add a Digital Signage Content folder.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:write:digital_signage_library_contents:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "Addadigitalsignagecontentfolder",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:write:digital_signage_library_contents:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "DigitalSignage:Edit"
     ],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:write:digital_signage_library_contents:admin"
     ]
    }
   }
  },
  "/rooms/content/digital_signage/folders/{folderId}": {
   "get": {
    "tags": [
     "Zoom Rooms Content"
    ],
    "summary": "Get Digital Signage content folder",
    "description": "Use this API to get the details of an individual digital signage content folder.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:read:master`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:read:digital_signage_library_contents:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "Getdigitalsignagecontentfolderdetails",
    "security": [
     {
      "openapi_oauth": [
       "room:read:master",
       "zoom_rooms:read:digital_signage_library_contents:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "DigitalSignage:Read"
     ],
     "x-macro-scopes": [
      "room:read:master"
     ],
     "x-granular-scopes": [
      "zoom_rooms:read:digital_signage_library_contents:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Zoom Rooms Content"
    ],
    "summary": "Delete a Digital Signage content folder",
    "description": "Use this API to delete an individual digital signage content folder.  **Note**: All digital signage content items in this folder will also be deleted.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:master`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:write:digital_signage_library_contents:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference[...]",
    "operationId": "Deleteadigitalsignagecontentfolder",
    "security": [
     {
      "openapi_oauth": [
       "room:write:master",
       "zoom_rooms:write:digital_signage_library_contents:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "DigitalSignage:Edit"
     ],
     "x-macro-scopes": [
      "room:write:master"
     ],
     "x-granular-scopes": [
      "zoom_rooms:write:digital_signage_library_contents:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Zoom Rooms Content"
    ],
    "summary": "Update a digital signage content folder",
    "description": "Updates a Digital Signage content folder’s attributes.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:write:digital_signage_library_contents:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "Updateadigitalsignagecontentfolder",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:write:digital_signage_library_contents:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "DigitalSignage:Edit"
     ],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:write:digital_signage_library_contents:admin"
     ]
    }
   }
  },
  "/rooms/content/digital_signage/playlists": {
   "get": {
    "tags": [
     "Zoom Rooms Content"
    ],
    "summary": "List Digital Signage library playlists",
    "description": " Returns a list of Zoom Rooms content library digital signage playlists.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:read:digital_signage_library_playlists:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "ListDigitalSignagelibraryplaylists",
    "security": [
     {
      "openapi_oauth": [
       "room:read:admin",
       "zoom_rooms:read:digital_signage_library_playlists:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "DigitalSignage:Read"
     ],
     "x-macro-scopes": [
      "room:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:read:digital_signage_library_playlists:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Zoom Rooms Content"
    ],
    "summary": "Add a Digital Signage library playlist",
    "description": "Use this API to add a content library Digital Signage Playlist.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:write:digital_signage_library_playlists:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "AddaDigitalSignagelibraryplaylist",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:write:digital_signage_library_playlists:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "DigitalSignage:Edit"
     ],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:write:digital_signage_library_playlists:admin"
     ]
    }
   }
  },
  "/rooms/content/digital_signage/playlists/{playlistId}": {
   "get": {
    "tags": [
     "Zoom Rooms Content"
    ],
    "summary": "Get Digital Signage library playlist",
    "description": "Returns a Zoom Rooms content library digital signage playlist.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:read:digital_signage_library_playlists:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "GetDigitalSignagelibraryplaylist",
    "security": [
     {
      "openapi_oauth": [
       "room:read:admin",
       "zoom_rooms:read:digital_signage_library_playlists:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "DigitalSignage:Read"
     ],
     "x-macro-scopes": [
      "room:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:read:digital_signage_library_playlists:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Zoom Rooms Content"
    ],
    "summary": "Delete Digital Signage library playlist",
    "description": "Delete digital signage library playlist.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:write:digital_signage_library_playlists:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "DeleteDigitalSignagelibraryplaylist",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:write:digital_signage_library_playlists:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "DigitalSignage:Edit"
     ],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:write:digital_signage_library_playlists:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Zoom Rooms Content"
    ],
    "summary": "Update a Digital Signage library playlist",
    "description": "Updates a Zoom Rooms content library digital signage playlist.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:write:digital_signage_library_playlists:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "UpdateaDigitalSignagelibraryplaylist",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:write:digital_signage_library_playlists:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "DigitalSignage:Edit"
     ],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:write:digital_signage_library_playlists:admin"
     ]
    }
   }
  },
  "/rooms/content/digital_signage/playlists/{playlistId}/contents": {
   "get": {
    "tags": [
     "Zoom Rooms Content"
    ],
    "summary": "Get Digital Signage library playlist content items",
    "description": "Returns a Zoom Rooms content library digital signage playlist content items and their metadata.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:read:digital_signage_library_playlists:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "GetDigitalSignagelibraryplaylistcontentitems",
    "security": [
     {
      "openapi_oauth": [
       "room:read:admin",
       "zoom_rooms:read:digital_signage_library_playlists:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "DigitalSignage:Read"
     ],
     "x-macro-scopes": [
      "room:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:read:digital_signage_library_playlists:admin"
     ]
    }
   },
   "put": {
    "tags": [
     "Zoom Rooms Content"
    ],
    "summary": "Update Digital Signage library playlist content items",
    "description": "Updates a Zoom Rooms content library digital signage playlist content items and their metadata.  This API replaces the entire playlist.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:write:digital_signage_library_playlists:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#ra[...]",
    "operationId": "UpdateDigitalSignagelibraryplaylistcontentitems",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:write:digital_signage_library_playlists:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "DigitalSignage:Edit"
     ],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:write:digital_signage_library_playlists:admin"
     ]
    }
   }
  },
  "/rooms/content/digital_signage/playlists/{playlistId}/rooms": {
   "get": {
    "tags": [
     "Zoom Rooms Content"
    ],
    "summary": "List Digital Signage library playlist published rooms",
    "description": "List Digital Signage library playlist published rooms.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:read:digital_signage_library_playlists:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "ListDigitalSignagelibraryplaylistpublishedrooms",
    "security": [
     {
      "openapi_oauth": [
       "room:read:admin",
       "zoom_rooms:read:digital_signage_library_playlists:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "DigitalSignage:Read"
     ],
     "x-macro-scopes": [
      "room:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:read:digital_signage_library_playlists:admin"
     ]
    }
   },
   "put": {
    "tags": [
     "Zoom Rooms Content"
    ],
    "summary": "Update Digital Signage library playlist published rooms",
    "description": "Update Digital Signage library playlist published rooms.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:write:digital_signage_library_playlists:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "UpdateDigitalSignagelibraryplaylistpublishedrooms",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:write:digital_signage_library_playlists:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "DigitalSignage:Edit"
     ],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:write:digital_signage_library_playlists:admin"
     ]
    }
   }
  },
  "/zrbackground/files": {
   "put": {
    "tags": [
     "Zoom Rooms Content"
    ],
    "summary": "Update Zoom Rooms background image library content",
    "description": "Update a Zoom Rooms background image library content. **Prerequisite:**   The caller must be a Zoom Rooms licensed user. **Note:**  * Base URL - `https://fileapi.zoom.us/v2/`.  * Rate limit - 20 requests per second per user or 2000 requests per second per IP address. * The caller must support HTTP 30x redirects. * The caller must retain the Authorization header when redirected to a different hostname. * JPG/JPEG, 24-bit PNG (no alpha) or GIF (ZR Appliance only)* Recommended d[...]",
    "operationId": "UpdateZoomRoomsBackgroundImageLibraryContent",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:update:background_library_content:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomRooms:Edit"
     ],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:update:background_library_content:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Zoom Rooms Content"
    ],
    "summary": "Add Zoom Rooms background image library content",
    "description": "Upload an image to Zoom Room Content Library.  \n**Prerequisite:**   The caller must be a Zoom Room licensed user. \n**Note:**  * Base URL: `https://fileapi.zoom.us/v2/`.  \n* Rate limit: 20 requests per second per user or 2000 requests per second per IP address. \n* The caller must support HTTP 30x redirects. \n* The caller must retain the Authorization header when redirected to a different hostname. \n* JPG/JPEG, 24-bit PNG (no alpha) or GIF (ZR Appliance only)\n* Recommend[...]",
    "operationId": "AddZoomRoomsBackgroundImageLibraryContent",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:write:background_library_content:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomRooms:Edit"
     ],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:write:background_library_content:admin"
     ]
    }
   }
  },
  "/zrdigitalsignage/files": {
   "put": {
    "tags": [
     "Zoom Rooms Content"
    ],
    "summary": "Update a Digital Signage image or video file",
    "description": "Update an image or video content item in the Zoom Rooms digital signage content library.\n**Note**: * Base URL: https://fileapi.zoom.us/v2/.\n\n**Rate limit**: 20 requests per second per user or 2000 requests per second per IP address.\n\nThe caller must support HTTP 30x redirects.\n\nThe caller must retain the Authorization header when redirected to a different hostname.\nJPG/JPEG, 24-bit PNG (no alpha) or GIF (ZR Appliance only).\n\n**Recommended dimensions**\n - 1920 x 108[...]",
    "operationId": "Updateadigitalsignageimageorvideofile",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:write:digital_signage_library_contents:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "DigitalSignage:Edit"
     ],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:write:digital_signage_library_contents:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Zoom Rooms Content"
    ],
    "summary": "Add a digital signage image or video ",
    "description": "Upload an image or video to the Zoom Rooms Digital Signage Content Library.\n**Note**: * Base URL: https://fileapi.zoom.us/v2/\n\n**Rate limit**: 20 requests per second per user or 2000 requests per second per IP address.\nThe caller must support HTTP 30x redirects.\n\nThe caller must retain the Authorization header when redirected to a different hostname.\nJPG/JPEG, 24-bit PNG (no alpha) or GIF (ZR Appliance only)\n\n**Recommended dimensions**:\n\n - 1920 x 1080 (landscape) [...]",
    "operationId": "Adddigitalsignageimageorvideo",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:write:digital_signage_library_contents:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "DigitalSignage:Edit"
     ],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:write:digital_signage_library_contents:admin"
     ]
    }
   }
  },
  "/rooms/{roomId}/devices/{deviceId}": {
   "delete": {
    "tags": [
     "Zoom Rooms Devices"
    ],
    "summary": "Delete a Zoom Room user device",
    "description": "Deletes a Zoom Room device.  **Prerequisites:**     * Pro or a higher plan with [Zoom Room](https://zoom.us/zoomrooms) license.   * Account owner or admin permissions.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:delete:device:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-lim[...]",
    "operationId": "deleteDevice",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:delete:device:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:delete:device:admin"
     ]
    }
   }
  },
  "/rooms/{roomId}/devices/{deviceId}/app_version": {
   "put": {
    "tags": [
     "Zoom Rooms Devices"
    ],
    "summary": "Change Zoom Rooms app version",
    "description": "Use this API to [upgrade or downgrade](https://support.zoom.us/hc/en-us/articles/204675449-Upgrade-or-Downgrade-Zoom-Rooms-Software) the version of your installed Zoom Rooms app on your Mac or Windows device. \n\n**Prerequisites:** \n* A Pro or a higher account with Zoom Rooms. \n* The Zoom Rooms software must be installed on a Mac or a Windows device. This API does not support other devices.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):*[...]",
    "operationId": "changeZoomRoomsAppVersion",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:update:device_app_version:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomRooms:Edit"
     ],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:update:device_app_version:admin"
     ]
    }
   }
  },
  "/rooms/locations": {
   "get": {
    "tags": [
     "Zoom Rooms Location"
    ],
    "summary": "List Zoom Room locations",
    "description": "A Zoom account owner or a Zoom Room administrator can establish a [location hierarchy](https://support.zoom.us/hc/en-us/articles/115000342983-Zoom-Rooms-Location-Hierarchy) to help manage Zoom Rooms that are spread among a variety of locations. Use this API to list the different location types used for Zoom Rooms in an account.  \n   \n \n**Prerequisites:**\n* Account owner or admin permissions.\n* Zoom Rooms Version 4.0 or higher  \n   \n \n\n\n**[Scopes](https://developers.[...]",
    "operationId": "listZRLocations",
    "security": [
     {
      "openapi_oauth": [
       "room:read:admin",
       "zoom_rooms:read:list_locations:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "room:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:read:list_locations:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Zoom Rooms Location"
    ],
    "summary": "Add a location",
    "description": "Add a location to the [location hierarchial structure(s)](https://support.zoom.us/hc/en-us/articles/115000342983-Zoom-Rooms-Location-Hierarchy) of Zoom Rooms in an account.\n\n**Prerequisites:**\n* Account owner or admin permissions.\n* Zoom Rooms Version 4.0 or higher  \n   \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):*[...]",
    "operationId": "addAZRLocation",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:write:location:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:write:location:admin"
     ]
    }
   }
  },
  "/rooms/locations/structure": {
   "get": {
    "tags": [
     "Zoom Rooms Location"
    ],
    "summary": "Get Zoom Room location structure",
    "description": "Get the [location hierarchial structure(s)](https://support.zoom.us/hc/en-us/articles/115000342983-Zoom-Rooms-Location-Hierarchy) applied on the Zoom Rooms in an account.  \n   \n \n**Prerequisites:**  \n \n* Zoom Rooms version 4.0 or higher.\n* Account owner or admin permissions.  \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overvi[...]",
    "operationId": "getZRLocationStructure",
    "security": [
     {
      "openapi_oauth": [
       "room:read:admin",
       "zoom_rooms:read:location_hierarchy:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "room:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:read:location_hierarchy:admin"
     ]
    }
   },
   "put": {
    "tags": [
     "Zoom Rooms Location"
    ],
    "summary": "Update Zoom Rooms location structure",
    "description": "Update the [location hierarchial structure(s)](https://support.zoom.us/hc/en-us/articles/115000342983-Zoom-Rooms-Location-Hierarchy) applied on the Zoom Rooms in an account.  \n   \n \n**Prerequisites:**  \n \n* Zoom Rooms version 4.0 or higher\n* Account owner or admin permissions  \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-over[...]",
    "operationId": "updateZoomRoomsLocationStructure",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:update:location_hierarchy:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:update:location_hierarchy:admin"
     ]
    }
   }
  },
  "/rooms/locations/{locationId}": {
   "get": {
    "tags": [
     "Zoom Rooms Location"
    ],
    "summary": "Get Zoom Room location profile",
    "description": "Each location type of the [Zoom Rooms location hierarchy](https://support.zoom.us/hc/en-us/articles/115000342983-Zoom-Rooms-Location-Hierarchy) has a profile page with information such as the location name, address, support email, and more. Use this API to retrieve information about a specific Zoom Rooms location type, such as the city location of the Zoom Rooms.\n\n**Prerequisite:**  \n \n* Account owner or admin permission.\n* Zoom Rooms version 4.0 or higher.  \n \n\n\n**[[...]",
    "operationId": "getZRLocationProfile",
    "security": [
     {
      "openapi_oauth": [
       "room:read:admin",
       "zoom_rooms:read:location:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomRooms:Read"
     ],
     "x-macro-scopes": [
      "room:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:read:location:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Zoom Rooms Location"
    ],
    "summary": "Delete a location",
    "description": "Remove a location from the [location hierarchial structure(s)](https://support.zoom.us/hc/en-us/articles/115000342983-Zoom-Rooms-Location-Hierarchy) of Zoom Rooms in an account.\n\n**Prerequisites:**\n* Account owner or admin permissions.\n* Zoom Rooms Version 4.0 or higher  \n   \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overvie[...]",
    "operationId": "deleteAZRLocation",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:write:location:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomRooms:Edit"
     ],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:write:location:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Zoom Rooms Location"
    ],
    "summary": "Update Zoom Room location profile",
    "description": "Each location type of the [Zoom Rooms location hierarchy](https://support.zoom.us/hc/en-us/articles/115000342983-Zoom-Rooms-Location-Hierarchy) has a profile page that includes information such as name of the location, address, support email, etc. Use this API to update information about a specific Zoom Rooms location type such as information about the city where the Zoom Rooms is located.\n\n**Prerequisite:**  \n \n* Account owner or admin permission.\n* Zoom Rooms version 4[...]",
    "operationId": "updateZRLocationProfile",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:update:location:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:update:location:admin"
     ]
    }
   }
  },
  "/rooms/locations/{locationId}/location": {
   "put": {
    "tags": [
     "Zoom Rooms Location"
    ],
    "summary": "Change the assigned parent location",
    "description": "An account owner of a Zoom account can establish a [Zoom Rooms Location Hierarchy](https://support.zoom.us/hc/en-us/articles/115000342983-Zoom-Rooms-Location-Hierarchy) to better organize Zoom Rooms spread across various locations. The location can be structured in a hierarchy with Country being the top-level location, followed by city, campus, building, and floor. The location in the lower level in the hierarchy is considered as a child of the location that is a level above [...]",
    "operationId": "changeParentLocation",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:update:location:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:update:location:admin"
     ]
    }
   }
  },
  "/rooms/locations/{locationId}/settings": {
   "get": {
    "tags": [
     "Zoom Rooms Location"
    ],
    "summary": "Get location settings",
    "description": "Get information on meeting, alert, digital signage or scheduling display settings applied to Zoom Rooms located in a specific location. By default, only **Meeting Settings** are returned. To view only **Alert Settings**, specify `alert` as the value of the `setting_type` query parameter.      **Prerequisites:**   * Zoom Room licenses* Owner or Admin privileges on the Zoom Account.   \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:r[...]",
    "operationId": "getZRLocationSettings",
    "security": [
     {
      "openapi_oauth": [
       "room:read:admin",
       "zoom_rooms:read:location_settings:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomRooms:Read"
     ],
     "x-macro-scopes": [
      "room:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:read:location_settings:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Zoom Rooms Location"
    ],
    "summary": "Update location settings",
    "description": "Update meeting, alert, digital signage or scheduling display settings applied to Zoom Rooms located in a specific location. To update **Alert Settings**, specify `alert` as the value of the `setting_type` query parameter. Similarly, to update **Meeting Settings**, specify `meeting` as the value of the `setting_type` query parameter.      \n\n**Prerequisites:**   * Zoom Room licenses* Owner or Admin privileges on the Zoom Account.   \n\n**[Scopes](https://developers.zoom.us/do[...]",
    "operationId": "updateZRLocationSettings",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:update:location_settings:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomRooms:Edit"
     ],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:update:location_settings:admin"
     ]
    }
   }
  },
  "/rooms/locations/{locationId}/tags": {
   "patch": {
    "tags": [
     "Zoom Rooms Tags"
    ],
    "summary": "Assign Tags to Zoom Rooms By Location ID",
    "description": "Use this API to assign Tags to Zoom Rooms by location ID  **Prerequisites:** * A Pro or a higher plan with a [Zoom Rooms](https://zoom.us/zoomrooms) license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:update:room_tag:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate[...]",
    "operationId": "AssignTagsToZoomRoomsByLocationID",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:update:room_tag:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomRooms:Edit"
     ],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:update:room_tag:admin"
     ]
    }
   }
  },
  "/rooms/tags": {
   "get": {
    "tags": [
     "Zoom Rooms Tags"
    ],
    "summary": "List all Zoom Room Tags",
    "description": "List all Zoom Rooms Tags  **Prerequisites:** * A Pro or a higher plan with a [Zoom Rooms](https://zoom.us/zoomrooms) license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:read:list_tags:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "listZoomRoomTags",
    "security": [
     {
      "openapi_oauth": [
       "room:read:admin",
       "zoom_rooms:read:list_tags:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "room:read:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:read:list_tags:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Zoom Rooms Tags"
    ],
    "summary": "Create a new Zoom Rooms Tag",
    "description": "Creates a new Zoom Rooms Tag.  **Prerequisites:** * A Pro or a higher plan with a [Zoom Rooms](https://zoom.us/zoomrooms) license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:write:tag:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "createZoomRoomTag",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:write:tag:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:write:tag:admin"
     ]
    }
   }
  },
  "/rooms/tags/{tagId}": {
   "delete": {
    "tags": [
     "Zoom Rooms Tags"
    ],
    "summary": "Delete Tag",
    "description": "Deletes Tag.  **Prerequisites:** * A Pro or a higher plan with a [Zoom Rooms](https://zoom.us/zoomrooms) license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:delete:tag:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "deleteZoomRoomTag",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:delete:tag:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:delete:tag:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Zoom Rooms Tags"
    ],
    "summary": "Edit Tag",
    "description": "Edits Tag.  **Prerequisites:** * A Pro or a higher plan with a [Zoom Rooms](https://zoom.us/zoomrooms) license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:update:tag:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "editZoomRoomTag",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:update:tag:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:update:tag:admin"
     ]
    }
   }
  },
  "/rooms/{roomId}/tags": {
   "delete": {
    "tags": [
     "Zoom Rooms Tags"
    ],
    "summary": "Un-assign Tags from a Zoom Room",
    "description": "Un-assign Tags from a Zoom Room  **Prerequisites:** * A Pro or a higher plan with a [Zoom Rooms](https://zoom.us/zoomrooms) license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:delete:room_tag:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "unassignZoomRoomTag",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:delete:room_tag:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:delete:room_tag:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Zoom Rooms Tags"
    ],
    "summary": "Assign Tags to a Zoom Room",
    "description": "Use this API to assign Tags to a Zoom Room \n\n **Prerequisites:** \n* A Pro or a higher plan with a [Zoom Rooms](https://zoom.us/zoomrooms) license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `room:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zoom_rooms:update:room_tag:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits)[...]",
    "operationId": "AssignTagsToAZoomRoom",
    "security": [
     {
      "openapi_oauth": [
       "room:write:admin",
       "zoom_rooms:update:room_tag:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomRooms:Edit"
     ],
     "x-macro-scopes": [
      "room:write:admin"
     ],
     "x-granular-scopes": [
      "zoom_rooms:update:room_tag:admin"
     ]
    }
   }
  }
 },
 "components": {
  "securitySchemes": {
   "openapi_authorization": {
    "type": "apiKey",
    "name": "Authorization",
    "in": "header"
   },
   "openapi_oauth": {
    "type": "oauth2",
    "flows": {
     "authorizationCode": {
      "authorizationUrl": "/",
      "tokenUrl": "",
      "refreshUrl": "",
      "scopes": {
       "room:write:admin": "room:write:admin",
       "room:master": "room:master",
       "zoom_rooms:write:zoom_apps:admin": "zoom_rooms:write:zoom_apps:admin",
       "visitor_management:write:admin": "visitor_management:write:admin",
       "visitor_management:write:invitation": "visitor_management:write:invitation",
       "visitor_management:write:invitation:admin": "visitor_management:write:invitation:admin",
       "visitor_management:read": "visitor_management:read",
       "visitor_management:read:list_invitations": "visitor_management:read:list_invitations",
       "visitor_management:read:list_invitations:admin": "visitor_management:read:list_invitations:admin",
       "visitor_management:read:invitation_details": "visitor_management:read:invitation_details",
       "visitor_management:read:invitation_details:admin": "visitor_management:read:invitation_details:admin",
       "visitor_management:write": "visitor_management:write",
       "visitor_management:delete:invitation": "visitor_management:delete:invitation",
       "visitor_management:delete:invitation:admin": "visitor_management:delete:invitation:admin",
       "visitor_management:update:invitation": "visitor_management:update:invitation",
       "visitor_management:update:invitation:admin": "visitor_management:update:invitation:admin",
       "visitor_management:write:check_in": "visitor_management:write:check_in",
       "visitor_management:write:check_in:admin": "visitor_management:write:check_in:admin",
       "workspace:read": "workspace:read",
       "workspace:read:admin": "workspace:read:admin",
       "workspace:read:list_workspaces": "workspace:read:list_workspaces",
       "workspace:read:list_workspaces:admin": "workspace:read:list_workspaces:admin",
       "workspace:write:admin": "workspace:write:admin",
       "workspace:write:workspace:admin": "workspace:write:workspace:admin",
       "workspace:write:asset:admin": "workspace:write:asset:admin",
       "workspace:read:asset:admin": "workspace:read:asset:admin",
       "workspace:update:asset:admin": "workspace:update:asset:admin",
       "workspace:delete:asset:admin": "workspace:delete:asset:admin",
       "workspace:write:events": "workspace:write:events",
       "workspace:write:events:admin": "workspace:write:events:admin",
       "workspace:write:location": "workspace:write:location",
       "workspace:write:location:admin": "workspace:write:location:admin",
       "room:read:admin": "room:read:admin",
       "zoom_rooms:read:list_release_infos:admin": "zoom_rooms:read:list_release_infos:admin",
       "workspace:write": "workspace:write",
       "workspace:update:setting:admin": "workspace:update:setting:admin",
       "workspace:update:setting:master": "workspace:update:setting:master",
       "workspace:read:usage": "workspace:read:usage",
       "workspace:read:usage:admin": "workspace:read:usage:admin",
       "workspace:read:workspace:admin": "workspace:read:workspace:admin",
       "workspace:read:list_reservations:admin": "workspace:read:list_reservations:admin",
       "workspace:delete:workspace:admin": "workspace:delete:workspace:admin",
       "workspace:update:workspace:admin": "workspace:update:workspace:admin",
       "workspace:read:assignment": "workspace:read:assignment",
       "workspace:read:assignment:admin": "workspace:read:assignment:admin",
       "workspace:delete:assignment:admin": "workspace:delete:assignment:admin",
       "workspace:write:assignment:admin": "workspace:write:assignment:admin",
       "workspace:read:qr:admin": "workspace:read:qr:admin",
       "workspace:write:reservation": "workspace:write:reservation",
       "workspace:write:reservation:admin": "workspace:write:reservation:admin",
       "workspace:read:list_reservations": "workspace:read:list_reservations",
       "workspace:read:reservation": "workspace:read:reservation",
       "workspace:read:reservation:admin": "workspace:read:reservation:admin",
       "workspace:update:reservation": "workspace:update:reservation",
       "workspace:update:reservation:admin": "workspace:update:reservation:admin",
       "workspace:delete:reservation": "workspace:delete:reservation",
       "workspace:delete:reservation:admin": "workspace:delete:reservation:admin",
       "workspace:read:reservation:master": "workspace:read:reservation:master",
       "zoom_rooms:write:room:admin": "zoom_rooms:write:room:admin",
       "zoom_rooms:read:list_rooms:admin": "zoom_rooms:read:list_rooms:admin",
       "zoom_rooms:update:room_controls:admin": "zoom_rooms:update:room_controls:admin",
       "zoom_rooms:update:room_control:admin": "zoom_rooms:update:room_control:admin",
       "zoom_rooms:read:room_settings:admin": "zoom_rooms:read:room_settings:admin",
       "zoom_rooms:update:room_settings:admin": "zoom_rooms:update:room_settings:admin",
       "zoom_rooms:read:room:admin": "zoom_rooms:read:room:admin",
       "zoom_rooms:delete:room:admin": "zoom_rooms:delete:room:admin",
       "zoom_rooms:update:room:admin": "zoom_rooms:update:room:admin",
       "zoom_rooms:read:list_device_profiles:admin": "zoom_rooms:read:list_device_profiles:admin",
       "zoom_rooms:write:device_profile:admin": "zoom_rooms:write:device_profile:admin",
       "zoom_rooms:read:device_profile:admin": "zoom_rooms:read:device_profile:admin",
       "zoom_rooms:update:device_profile:admin": "zoom_rooms:update:device_profile:admin",
       "zoom_rooms:delete:device_profile:admin": "zoom_rooms:delete:device_profile:admin",
       "zoom_rooms:read:list_devices:admin": "zoom_rooms:read:list_devices:admin",
       "zoom_rooms:update:room_location:admin": "zoom_rooms:update:room_location:admin",
       "zoom_rooms:read:sensor_data:admin": "zoom_rooms:read:sensor_data:admin",
       "zoom_rooms:read:virtual_controller:admin": "zoom_rooms:read:virtual_controller:admin",
       "zoom_rooms:read:account_profile:admin": "zoom_rooms:read:account_profile:admin",
       "zoom_rooms:update:account_profile:admin": "zoom_rooms:update:account_profile:admin",
       "zoom_rooms:read:account_settings:admin": "zoom_rooms:read:account_settings:admin",
       "zoom_rooms:update:account_settings:admin": "zoom_rooms:update:account_settings:admin",
       "zoom_rooms:read:list_calendar_services:admin": "zoom_rooms:read:list_calendar_services:admin",
       "zoom_rooms:delete:calendar_service:admin": "zoom_rooms:delete:calendar_service:admin",
       "zoom_rooms:write:calendar_resource:admin": "zoom_rooms:write:calendar_resource:admin",
       "zoom_rooms:read:list_calendar_resources:admin": "zoom_rooms:read:list_calendar_resources:admin",
       "zoom_rooms:read:calendar_resource:admin": "zoom_rooms:read:calendar_resource:admin",
       "zoom_rooms:delete:calendar_resource:admin": "zoom_rooms:delete:calendar_resource:admin",
       "zoom_rooms:update:calendar_service:admin": "zoom_rooms:update:calendar_service:admin",
       "zoom_rooms:read:background_library_content:admin": "zoom_rooms:read:background_library_content:admin",
       "zoom_rooms:delete:background_library_content:admin": "zoom_rooms:delete:background_library_content:admin",
       "zoom_rooms:read:background_library_folder:admin": "zoom_rooms:read:background_library_folder:admin",
       "zoom_rooms:write:background_library_folder:admin": "zoom_rooms:write:background_library_folder:admin",
       "zoom_rooms:delete:background_library_folder:admin": "zoom_rooms:delete:background_library_folder:admin",
       "zoom_rooms:update:background_library_folder:admin": "zoom_rooms:update:background_library_folder:admin",
       "zoom_rooms:read:digital_signage_library_contents:admin": "zoom_rooms:read:digital_signage_library_contents:admin",
       "zoom_rooms:write:digital_signage_library_contents:admin": "zoom_rooms:write:digital_signage_library_contents:admin",
       "room:write:master": "room:write:master",
       "room:read:master": "room:read:master",
       "zoom_rooms:write:digital_signage_library_playlists:admin": "zoom_rooms:write:digital_signage_library_playlists:admin",
       "zoom_rooms:read:digital_signage_library_playlists:admin": "zoom_rooms:read:digital_signage_library_playlists:admin",
       "zoom_rooms:write:background_library_content:admin": "zoom_rooms:write:background_library_content:admin",
       "zoom_rooms:update:background_library_content:admin": "zoom_rooms:update:background_library_content:admin",
       "zoom_rooms:delete:device:admin": "zoom_rooms:delete:device:admin",
       "zoom_rooms:update:device_app_version:admin": "zoom_rooms:update:device_app_version:admin",
       "zoom_rooms:read:list_locations:admin": "zoom_rooms:read:list_locations:admin",
       "zoom_rooms:write:location:admin": "zoom_rooms:write:location:admin",
       "zoom_rooms:update:location_hierarchy:admin": "zoom_rooms:update:location_hierarchy:admin",
       "zoom_rooms:read:location_hierarchy:admin": "zoom_rooms:read:location_hierarchy:admin",
       "zoom_rooms:update:location:admin": "zoom_rooms:update:location:admin",
       "zoom_rooms:read:location:admin": "zoom_rooms:read:location:admin",
       "zoom_rooms:read:location_settings:admin": "zoom_rooms:read:location_settings:admin",
       "zoom_rooms:update:location_settings:admin": "zoom_rooms:update:location_settings:admin",
       "zoom_rooms:update:room_tag:admin": "zoom_rooms:update:room_tag:admin",
       "zoom_rooms:write:tag:admin": "zoom_rooms:write:tag:admin",
       "zoom_rooms:read:list_tags:admin": "zoom_rooms:read:list_tags:admin",
       "zoom_rooms:delete:tag:admin": "zoom_rooms:delete:tag:admin",
       "zoom_rooms:update:tag:admin": "zoom_rooms:update:tag:admin",
       "zoom_rooms:delete:room_tag:admin": "zoom_rooms:delete:room_tag:admin"
      }
     }
    }
   }
  }
 }
}