{
  "source": "users",
  "sourceUrl": "https://developers.zoom.us/api-hub/users/methods/endpoints.json",
  "downloadedAt": "2025-12-12T01:50:08.4440724Z",
  "specVersion": "3.0.0",
  "spec": {
    "openapi": "3.0.0",
    "info": {
      "title": "Users",
      "description": "The User APIs allow developers to programatically access data related to users, groups, and contact groups.",
      "termsOfService": "https://zoom.us/docs/en-us/zoom_api_license_and_tou.html",
      "contact": {
        "name": "Zoom Developers",
        "url": "https://developer.zoom.us/"
      },
      "version": "2"
    },
    "servers": [
      {
        "url": "https://api.zoom.us/v2"
      }
    ],
    "paths": {
      "/contacts/groups": {
        "get": {
          "tags": [
            "Contact Groups"
          ],
          "summary": "List contact groups",
          "description": "List [contact groups](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) under an account.\n\n**Prerequisite**: Pro or higher account.  \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_group:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
          "operationId": "contactGroups",
          "security": [
            {
              "openapi_oauth": [
                "contact_group:read:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "contact_group:read:admin"
            ]
          }
        },
        "post": {
          "tags": [
            "Contact Groups"
          ],
          "summary": "Create a contact group",
          "description": "Use this API to create a [contact group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management).\n\n**Prerequisite**: Pro or higher account.  \n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_group:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
          "operationId": "contactGroupCreate",
          "security": [
            {
              "openapi_oauth": [
                "contact_group:write:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "contact_group:write:admin"
            ]
          }
        }
      },
      "/contacts/groups/{groupId}": {
        "get": {
          "tags": [
            "Contact Groups"
          ],
          "summary": "Get a contact group",
          "description": "Get a [contact group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) under an account.\n\n**Prerequisite**: Pro or higher account.  \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_group:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
          "operationId": "contactGroup",
          "security": [
            {
              "openapi_oauth": [
                "contact_group:write:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "contact_group:write:admin"
            ]
          }
        },
        "delete": {
          "tags": [
            "Contact Groups"
          ],
          "summary": "Delete a contact group",
          "description": "Use this API to delete a [contact group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-).\n\n**Prerequisite**: Pro or higher account.  \n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_group:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
          "operationId": "contactGroupDelete",
          "security": [
            {
              "openapi_oauth": [
                "contact_group:write:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "contact_group:write:admin"
            ]
          }
        },
        "patch": {
          "tags": [
            "Contact Groups"
          ],
          "summary": "Update a contact group",
          "description": "Update a [contact group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) under your account.\n\n**Prerequisite**: Pro or higher account.  \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_group:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
          "operationId": "contactGroupUpdate",
          "security": [
            {
              "openapi_oauth": [
                "contact_group:write:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "contact_group:write:admin"
            ]
          }
        }
      },
      "/contacts/groups/{groupId}/members": {
        "get": {
          "tags": [
            "Contact Groups"
          ],
          "summary": "List contact group members",
          "description": "List members in [contact groups](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) under an account.\n\n**Prerequisite**: Pro or higher account.  \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_group:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
          "operationId": "contactGroupMembers",
          "security": [
            {
              "openapi_oauth": [
                "contact_group:read:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "contact_group:read:admin"
            ]
          }
        },
        "post": {
          "tags": [
            "Contact Groups"
          ],
          "summary": "Add contact group members",
          "description": "Use this API to add members to a [contact group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management).\n\n**Prerequisite**: Pro or higher account.  \n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_group:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
          "operationId": "contactGroupMemberAdd",
          "security": [
            {
              "openapi_oauth": [
                "contact_group:write:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "contact_group:write:admin"
            ]
          }
        },
        "delete": {
          "tags": [
            "Contact Groups"
          ],
          "summary": "Remove members in a contact group",
          "description": "Removes members in a [contact group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-).\n\n**Prerequisite**: Pro or higher account.  \n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `contact_group:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
          "operationId": "contactGroupMemberRemove",
          "security": [
            {
              "openapi_oauth": [
                "contact_group:write:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "contact_group:write:admin"
            ]
          }
        }
      },
      "/divisions": {
        "get": {
          "tags": [
            "Divisions"
          ],
          "summary": "List divisions",
          "description": "List divisions under an account.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** ` division:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `division:read:list_divisions:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`\n\n**Not supported in Gov cluster** ",
          "operationId": "listDivisions",
          "security": [
            {
              "openapi_oauth": [
                " division:read:admin",
                "division:read:list_divisions:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "Division:Read"
            ],
            "x-macro-scopes": [
              " division:read:admin"
            ],
            "x-granular-scopes": [
              "division:read:list_divisions:admin"
            ]
          }
        },
        "post": {
          "tags": [
            "Divisions"
          ],
          "summary": "Create a division",
          "description": "Create a division. You can add a maximum of 500 divisions in one account.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `division:wirte:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `division:write:division:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`\n\n**Not supported in Gov cluster** ",
          "operationId": "Createadivision",
          "security": [
            {
              "openapi_oauth": [
                "division:wirte:admin",
                "division:write:division:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "Division:Edit"
            ],
            "x-macro-scopes": [
              "division:wirte:admin"
            ],
            "x-granular-scopes": [
              "division:write:division:admin"
            ]
          }
        }
      },
      "/divisions/{divisionId}": {
        "get": {
          "tags": [
            "Divisions"
          ],
          "summary": "Get a division",
          "description": "Get a division under an account.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `division:wirte:admin`,` division:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `division:read:division:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`\n\n**Not supported in Gov cluster** ",
          "operationId": "Getdivision",
          "security": [
            {
              "openapi_oauth": [
                "division:wirte:admin",
                " division:read:admin",
                "division:read:division:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "Division:Read"
            ],
            "x-macro-scopes": [
              "division:wirte:admin",
              " division:read:admin"
            ],
            "x-granular-scopes": [
              "division:read:division:admin"
            ]
          }
        },
        "delete": {
          "tags": [
            "Divisions"
          ],
          "summary": "Delete a division",
          "description": "Delete an entire division.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `division:wirte:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `division:delete:division:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`\n\n**Not supported in Gov cluster** ",
          "operationId": "Deletedivision",
          "security": [
            {
              "openapi_oauth": [
                "division:wirte:admin",
                "division:delete:division:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "Division:Edit"
            ],
            "x-macro-scopes": [
              "division:wirte:admin"
            ],
            "x-granular-scopes": [
              "division:delete:division:admin"
            ]
          }
        },
        "patch": {
          "tags": [
            "Divisions"
          ],
          "summary": "Update a division",
          "description": "Update a group under your account.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `division:wirte:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `division:update:division:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`\n\n**Not supported in Gov cluster** ",
          "operationId": "Updateadivision",
          "security": [
            {
              "openapi_oauth": [
                "division:wirte:admin",
                "division:update:division:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "Division:Edit"
            ],
            "x-macro-scopes": [
              "division:wirte:admin"
            ],
            "x-granular-scopes": [
              "division:update:division:admin"
            ]
          }
        }
      },
      "/divisions/{divisionId}/users": {
        "get": {
          "tags": [
            "Divisions"
          ],
          "summary": "List division members",
          "description": "List the users of a division under your account.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** ` division:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `division:read:member:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`\n\n**Not supported in Gov cluster** ",
          "operationId": "listDivisionMembers",
          "security": [
            {
              "openapi_oauth": [
                " division:read:admin",
                "division:read:member:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "Division:Read"
            ],
            "x-macro-scopes": [
              " division:read:admin"
            ],
            "x-granular-scopes": [
              "division:read:member:admin"
            ]
          }
        },
        "post": {
          "tags": [
            "Divisions"
          ],
          "summary": "Assign a division",
          "description": "Assign a division to members. A user can belong to only one division.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `division:wirte:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `division:write:member:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`\n\n**Not supported in Gov cluster** ",
          "operationId": "assigndivisionMember",
          "security": [
            {
              "openapi_oauth": [
                "division:wirte:admin",
                "division:write:member:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "Division:Edit"
            ],
            "x-macro-scopes": [
              "division:wirte:admin"
            ],
            "x-granular-scopes": [
              "division:write:member:admin"
            ]
          }
        }
      },
      "/groups": {
        "get": {
          "tags": [
            "Groups"
          ],
          "summary": "List groups",
          "description": "List [groups](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) under an account.\n\n**Prerequisite**: Pro or higher account.  \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `group:read:admin`,`group:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `group:read:list_groups:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-referenc[...]",
          "operationId": "groups",
          "security": [
            {
              "openapi_oauth": [
                "group:read:admin",
                "group:write:admin",
                "group:read:list_groups:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "Group:Read"
            ],
            "x-macro-scopes": [
              "group:read:admin",
              "group:write:admin"
            ],
            "x-granular-scopes": [
              "group:read:list_groups:admin"
            ]
          }
        },
        "post": {
          "tags": [
            "Groups"
          ],
          "summary": "Create a group",
          "description": "Use this API to create a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management). You can add a **maximum** of 100 groups in one account per day, and a maximum of 5000 groups in one account.\n\nIf you enabled a new group via the user interface, you can also choose whether to display the group and set its privacy level.\n\n**Prerequisites**: \n* A Pro or higher account\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/[...]",
          "operationId": "groupCreate",
          "security": [
            {
              "openapi_oauth": [
                "group:write:admin",
                "group:write:group:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "Group:Edit"
            ],
            "x-macro-scopes": [
              "group:write:admin"
            ],
            "x-granular-scopes": [
              "group:write:group:admin"
            ]
          }
        }
      },
      "/groups/{groupId}": {
        "get": {
          "tags": [
            "Groups"
          ],
          "summary": "Get a group",
          "description": "Get a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) under an account.\n\n**Prerequisite**: Pro, Business, or Education account  \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `group:read:admin`,`group:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `group:read:group:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-r[...]",
          "operationId": "group",
          "security": [
            {
              "openapi_oauth": [
                "group:read:admin",
                "group:write:admin",
                "group:read:group:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "Group:Read"
            ],
            "x-macro-scopes": [
              "group:read:admin",
              "group:write:admin"
            ],
            "x-granular-scopes": [
              "group:read:group:admin"
            ]
          }
        },
        "delete": {
          "tags": [
            "Groups"
          ],
          "summary": "Delete a group",
          "description": "Delete an entire [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-). **Prerequisites:** * A Pro, Business, or Education account.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `group:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `group:delete:group:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-l[...]",
          "operationId": "groupDelete",
          "security": [
            {
              "openapi_oauth": [
                "group:write:admin",
                "group:delete:group:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "Group:Edit"
            ],
            "x-macro-scopes": [
              "group:write:admin"
            ],
            "x-granular-scopes": [
              "group:delete:group:admin"
            ]
          }
        },
        "patch": {
          "tags": [
            "Groups"
          ],
          "summary": "Update a group",
          "description": "Update a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) under your account.\n\n**Prerequisite**: Pro, Business, or Education account  \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `group:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `group:update:group:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rat[...]",
          "operationId": "groupUpdate",
          "security": [
            {
              "openapi_oauth": [
                "group:write:admin",
                "group:update:group:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "Group:Edit"
            ],
            "x-macro-scopes": [
              "group:write:admin"
            ],
            "x-granular-scopes": [
              "group:update:group:admin"
            ]
          }
        }
      },
      "/groups/{groupId}/admins": {
        "get": {
          "tags": [
            "Groups"
          ],
          "summary": "List group admins",
          "description": "Use this API to return a list of [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) administrators under your account.\n\n**Prerequisites:** \n* A Pro, Business, or Education account\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `group:read:admin`,`group:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `group:read:administrator:admin`\n\n**[Rate[...]",
          "operationId": "groupAdmins",
          "security": [
            {
              "openapi_oauth": [
                "group:read:admin",
                "group:write:admin",
                "group:read:administrator:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "Group:Read"
            ],
            "x-macro-scopes": [
              "group:read:admin",
              "group:write:admin"
            ],
            "x-granular-scopes": [
              "group:read:administrator:admin"
            ]
          }
        },
        "post": {
          "tags": [
            "Groups"
          ],
          "summary": "Add group admins",
          "description": "Use this API to add administrators to a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) under your account.\n\n**Prerequisites:** \n* A Pro, Business, or Education account\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `group:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `group:write:administrator:admin`\n\n**[Rate Limit Label](https://mark[...]",
          "operationId": "groupAdminsCreate",
          "security": [
            {
              "openapi_oauth": [
                "group:write:admin",
                "group:write:administrator:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "Group:Edit"
            ],
            "x-macro-scopes": [
              "group:write:admin"
            ],
            "x-granular-scopes": [
              "group:write:administrator:admin"
            ]
          }
        }
      },
      "/groups/{groupId}/admins/{userId}": {
        "delete": {
          "tags": [
            "Groups"
          ],
          "summary": "Delete a group admin",
          "description": "Use this API to remove a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) administrator in a Zoom account.\n\n**Prerequisites:** \n* A Pro, Business, or Education account\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `group:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `group:delete:administrator:admin`\n\n**[Rate Limit Label](https://marke[...]",
          "operationId": "groupAdminsDelete",
          "security": [
            {
              "openapi_oauth": [
                "group:write:admin",
                "group:delete:administrator:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "Group:Edit"
            ],
            "x-macro-scopes": [
              "group:write:admin"
            ],
            "x-granular-scopes": [
              "group:delete:administrator:admin"
            ]
          }
        }
      },
      "/groups/{groupId}/channels": {
        "get": {
          "tags": [
            "Groups"
          ],
          "summary": "List group channels",
          "description": "Returns a list of channels for a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) under your account.\n\n**Prerequisite**: \n- Pro, Business, or Education account  \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `group:read:admin`,`group:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `group:read:list_channels:admin`\n\n**[Rate Limit Labe[...]",
          "operationId": "groupChannels",
          "security": [
            {
              "openapi_oauth": [
                "group:read:admin",
                "group:write:admin",
                "group:read:list_channels:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "Group:Read"
            ],
            "x-macro-scopes": [
              "group:read:admin",
              "group:write:admin"
            ],
            "x-granular-scopes": [
              "group:read:list_channels:admin"
            ]
          }
        }
      },
      "/groups/{groupId}/lock_settings": {
        "get": {
          "tags": [
            "Groups"
          ],
          "summary": "Get locked settings",
          "description": "Retrieve a [group's](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) locked settings. \nIf you lock a setting, the group members will not be able to modify it individually. \n\n **Note:** The `force_pmi_jbh_password` field under meeting settings is deprecated as of September 22, 2019. \n\n**Prerequisite**: Pro, Business, or Education account  \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `group:read:ad[...]",
          "operationId": "getGroupLockSettings",
          "security": [
            {
              "openapi_oauth": [
                "group:read:admin",
                "group:write:admin",
                "group:read:lock_settings:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "Group:Read"
            ],
            "x-macro-scopes": [
              "group:read:admin",
              "group:write:admin"
            ],
            "x-granular-scopes": [
              "group:read:lock_settings:admin"
            ]
          }
        },
        "patch": {
          "tags": [
            "Groups"
          ],
          "summary": "Update locked settings",
          "description": "Update a [group's](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) locked settings. If you lock a setting, the group members cannot modify it individually. \n\n **Note:** The `force_pmi_jbh_password` field under meeting settings is deprecated as of September 22, 2019. \n\n**Prerequisite**: Pro, Business, or Education account  \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `group:write:admin`\n\n**[Granu[...]",
          "operationId": "groupLockedSettings",
          "security": [
            {
              "openapi_oauth": [
                "group:write:admin",
                "group:update:lock_settings:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "Group:Edit"
            ],
            "x-macro-scopes": [
              "group:write:admin"
            ],
            "x-granular-scopes": [
              "group:update:lock_settings:admin"
            ]
          }
        }
      },
      "/groups/{groupId}/members": {
        "get": {
          "tags": [
            "Groups"
          ],
          "summary": "List group members ",
          "description": "List the members of a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) under your account.\n\n**Prerequisite**: Pro, Business, or Education account  \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `group:read:admin`,`group:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `group:read:list_members:admin`\n\n**[Rate Limit Label](https://marke[...]",
          "operationId": "groupMembers",
          "security": [
            {
              "openapi_oauth": [
                "group:read:admin",
                "group:write:admin",
                "group:read:list_members:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "Group:Read"
            ],
            "x-macro-scopes": [
              "group:read:admin",
              "group:write:admin"
            ],
            "x-granular-scopes": [
              "group:read:list_members:admin"
            ]
          }
        },
        "post": {
          "tags": [
            "Groups"
          ],
          "summary": "Add group members",
          "description": "Use this API to add users to a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) in your account.\n\n**Prerequisites:** \n* A Pro, Business, or Education account\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `group:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `group:write:member:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/doc[...]",
          "operationId": "groupMembersCreate",
          "security": [
            {
              "openapi_oauth": [
                "group:write:admin",
                "group:write:member:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "Group:Edit"
            ],
            "x-macro-scopes": [
              "group:write:admin"
            ],
            "x-granular-scopes": [
              "group:write:member:admin"
            ]
          }
        }
      },
      "/groups/{groupId}/members/{memberId}": {
        "delete": {
          "tags": [
            "Groups"
          ],
          "summary": "Delete a group member",
          "description": "Use this API to remove a user from a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) in an account.\n\n**Prerequisites:** \n* A Pro, Business, or Education account\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `group:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `group:delete:member:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.u[...]",
          "operationId": "groupMembersDelete",
          "security": [
            {
              "openapi_oauth": [
                "group:write:admin",
                "group:delete:member:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "Group:Edit"
            ],
            "x-macro-scopes": [
              "group:write:admin"
            ],
            "x-granular-scopes": [
              "group:delete:member:admin"
            ]
          }
        },
        "patch": {
          "tags": [
            "Groups"
          ],
          "summary": "Update a group member",
          "description": "Use this API to perform either of the following tasks: \n* Remove a group member from one group and move them to a different group. \n* Set a user's primary group. By default, the primary group is the first group that user is added to.\n\nIf a user is a member of multiple groups, you can [assign the user a primary group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-#h_d07c7dcd-4fd8-485a-b5fe-a322e8d21c09). The user will use the primary group's se[...]",
          "operationId": "updateAGroupMember",
          "security": [
            {
              "openapi_oauth": [
                "group:write:admin",
                "group:update:member:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [],
            "x-macro-scopes": [
              "group:write:admin"
            ],
            "x-granular-scopes": [
              "group:update:member:admin"
            ]
          }
        }
      },
      "/groups/{groupId}/settings": {
        "get": {
          "tags": [
            "Groups"
          ],
          "summary": "Get a group's settings",
          "description": "Get settings for a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-). \n\n**Prerequisite**: Pro, Business, or Education account.\n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `group:read:admin`,`group:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `group:read:settings:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-re[...]",
          "operationId": "getGroupSettings",
          "security": [
            {
              "openapi_oauth": [
                "group:read:admin",
                "group:write:admin",
                "group:read:settings:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "Group:Read"
            ],
            "x-macro-scopes": [
              "group:read:admin",
              "group:write:admin"
            ],
            "x-granular-scopes": [
              "group:read:settings:admin"
            ]
          }
        },
        "patch": {
          "tags": [
            "Groups"
          ],
          "summary": "Update a group's settings",
          "description": "Update settings for a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-). \n\n **Note:**\n The `force_pmi_jbh_password` field under meeting settings is deprecated as of September 22, 2019. \n\n**Prerequisite**: Pro, Business, or Education account  \n  \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `group:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-over[...]",
          "operationId": "updateGroupSettings",
          "security": [
            {
              "openapi_oauth": [
                "group:write:admin",
                "group:update:settings:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "Group:Edit"
            ],
            "x-macro-scopes": [
              "group:write:admin"
            ],
            "x-granular-scopes": [
              "group:update:settings:admin"
            ]
          }
        }
      },
      "/groups/{groupId}/settings/registration": {
        "get": {
          "tags": [
            "Groups"
          ],
          "summary": "Get a group's webinar registration settings",
          "description": "Get webinar registration settings for a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-). \n**Prerequisite**: Pro, Business, or Education account  \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `group:read:admin`,`group:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `group:read:registration_settings:admin`\n\n**[Rate Limit Label](https:[...]",
          "operationId": "groupSettingsRegistration",
          "security": [
            {
              "openapi_oauth": [
                "group:read:admin",
                "group:write:admin",
                "group:read:registration_settings:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "Group:Read"
            ],
            "x-macro-scopes": [
              "group:read:admin",
              "group:write:admin"
            ],
            "x-granular-scopes": [
              "group:read:registration_settings:admin"
            ]
          }
        },
        "patch": {
          "tags": [
            "Groups"
          ],
          "summary": "Update a group's webinar registration settings",
          "description": "Update webinar registration settings for a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-).&lt;p style=&quot;background-color:#FEEFB3; color:#9F6000&quot;&gt;  \n Note:&lt;/b&gt; The `force_pmi_jbh_password` field under meeting settings is planned to be deprecated on September 22, 2019. This field will be replaced by another field that will provide the same functionality.&lt;/p&gt;\n**Prerequisite**: Pro, Business, or Education account  \n[...]",
          "operationId": "groupSettingsRegistrationUpdate",
          "security": [
            {
              "openapi_oauth": [
                "group:write:admin",
                "group:update:registration_settings:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "Group:Edit"
            ],
            "x-macro-scopes": [
              "group:write:admin"
            ],
            "x-granular-scopes": [
              "group:update:registration_settings:admin"
            ]
          }
        }
      },
      "/groups/{groupId}/settings/virtual_backgrounds": {
        "post": {
          "tags": [
            "Groups"
          ],
          "summary": "Upload Virtual Background files",
          "description": "Use this API to [upload Virtual Background files](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background#h_01EJF3YFEWGT8YA0ZJ079JEDQE) for all users in a group to use. \n\n **Prerequisites:** \n* The [Virtual Background feature](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background#h_2ef28080-fce9-4ac2-b567-dc958afab1b7) must be enabled on the account.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** [...]",
          "operationId": "uploadGroupVB",
          "security": [
            {
              "openapi_oauth": [
                "group:write:admin",
                "group:write:virtual_background_files:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "Group:Edit"
            ],
            "x-macro-scopes": [
              "group:write:admin"
            ],
            "x-granular-scopes": [
              "group:write:virtual_background_files:admin"
            ]
          }
        },
        "delete": {
          "tags": [
            "Groups"
          ],
          "summary": "Delete Virtual Background files",
          "description": "Use this API to delete a group's [Virtual Background files](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background#h_01EJF3YFEWGT8YA0ZJ079JEDQE). \n\n **Prerequisites:** \n* The [Virtual Background feature](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background#h_2ef28080-fce9-4ac2-b567-dc958afab1b7) must be enabled on the account.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `group:write:admin`\n\[...]",
          "operationId": "delGroupVB",
          "security": [
            {
              "openapi_oauth": [
                "group:write:admin",
                "group:delete:virtual_background_files:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "Group:Edit"
            ],
            "x-macro-scopes": [
              "group:write:admin"
            ],
            "x-granular-scopes": [
              "group:delete:virtual_background_files:admin"
            ]
          }
        }
      },
      "/users": {
        "get": {
          "tags": [
            "Users"
          ],
          "summary": "List users",
          "description": "Retrieve a list your account's users. \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `user:read`,`user:write`,`user:read:admin`,`user:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `user:read:list_users:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
          "operationId": "users",
          "security": [
            {
              "openapi_oauth": [
                "user:read",
                "user:write",
                "user:read:admin",
                "user:write:admin",
                "user:read:list_users:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "User:Read"
            ],
            "x-macro-scopes": [
              "user:read",
              "user:write",
              "user:read:admin",
              "user:write:admin"
            ],
            "x-granular-scopes": [
              "user:read:list_users:admin"
            ]
          }
        },
        "post": {
          "tags": [
            "Users"
          ],
          "summary": "Create users",
          "description": "Add a new user to your Zoom account. \n\n**Note** These rate limits apply when you use the `create` value for the `action` field. \n* 50 requests per day for **Free** accounts. \n* 1,500 requests per day for **Pro** accounts. \n* 10,000 requests per day for **Business+** accounts. \n\n**Prerequisites** \n* A Pro or higher plan.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `user:write`,`user:write:admin`\n\n**[Granular Scopes](htt[...]",
          "operationId": "userCreate",
          "security": [
            {
              "openapi_oauth": [
                "user:write",
                "user:write:admin",
                "user:write:user:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "User:Edit"
            ],
            "x-macro-scopes": [
              "user:write",
              "user:write:admin"
            ],
            "x-granular-scopes": [
              "user:write:user:admin"
            ]
          }
        }
      },
      "/users/email": {
        "get": {
          "tags": [
            "Users"
          ],
          "summary": "Check a user email",
          "description": "Verify if a user's email is registered with Zoom.  \n   \n \n\n&lt;b&gt;Note: &lt;/b&gt;You can successfully check if a user is a registered Zoom user only if the user **signed up for Zoom via email and is within your account.** If you provide an email address of a user who is not in your account, the value of &quot;existed_email&quot; parameter will be &quot;false&quot; irrespective of whether or not the user is registered with Zoom. The response of this API call will [...]",
          "operationId": "userEmail",
          "security": [
            {
              "openapi_oauth": [
                "user:read",
                "user:write",
                "user:read:admin",
                "user:write:admin",
                "user:read:email",
                "user:read:email:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "User:Read"
            ],
            "x-macro-scopes": [
              "user:read",
              "user:write",
              "user:read:admin",
              "user:write:admin"
            ],
            "x-granular-scopes": [
              "user:read:email",
              "user:read:email:admin"
            ]
          }
        }
      },
      "/users/features": {
        "post": {
          "tags": [
            "Users"
          ],
          "summary": "Bulk update features for users",
          "description": "Update multiple features for a user.  \n\n**Note** This endpoint can process a maximum of 30 users at a time. Furthermore, the endpoint is rate-limited to one request every 10 seconds.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `user:write`,`user:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `user:write:feature:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.[...]",
          "operationId": "bulkUpdateFeature",
          "security": [
            {
              "openapi_oauth": [
                "user:write",
                "user:write:admin",
                "user:write:feature:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "User:Edit"
            ],
            "x-macro-scopes": [
              "user:write",
              "user:write:admin"
            ],
            "x-granular-scopes": [
              "user:write:feature:admin"
            ]
          }
        }
      },
      "/users/me/zak": {
        "get": {
          "tags": [
            "Users"
          ],
          "summary": "Get the user's ZAK",
          "description": "Get the Zoom Access Key (ZAK) for the authenticated user associated with the access token in the API request. Use a ZAK to start or join a meeting on behalf of this user.\n\nZAKs obtained with this endpoint expire five minutes after receipt.\n\nTo get a ZAK for a different user or with a different expiration, use the [Get a user token](https://marketplace.zoom.us/docs/api-reference/zoom-api/methods#operation/userToken) API with the `zak` `type` query parameter.\n\nSee [[...]",
          "operationId": "userZak",
          "security": [
            {
              "openapi_oauth": [
                "user_zak:read",
                "user:read:zak",
                "user:read:zak:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "User:Read"
            ],
            "x-macro-scopes": [
              "user_zak:read"
            ],
            "x-granular-scopes": [
              "user:read:zak",
              "user:read:zak:admin"
            ]
          }
        }
      },
      "/users/summary": {
        "get": {
          "tags": [
            "Users"
          ],
          "summary": "Get user summary",
          "description": "Gets a summary of users, including the number and types of users in the account.\n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `user:read`,`user:write`,`user:read:admin`,`user:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `user:read:summary:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
          "operationId": "userSummary",
          "security": [
            {
              "openapi_oauth": [
                "user:read",
                "user:write",
                "user:read:admin",
                "user:write:admin",
                "user:read:summary:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "User:Read"
            ],
            "x-macro-scopes": [
              "user:read",
              "user:write",
              "user:read:admin",
              "user:write:admin"
            ],
            "x-granular-scopes": [
              "user:read:summary:admin"
            ]
          }
        }
      },
      "/users/vanity_name": {
        "get": {
          "tags": [
            "Users"
          ],
          "summary": "Check a user's PM room",
          "description": "A personal meeting room is a virtual meeting room that can be permanently assigned to a user.\nUse this API to check if a personal meeting room with the given name exists or not.  \n   \n \n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `user:read`,`user:write`,`user:read:admin`,`user:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `user:read:pm_room`,`user:read:pm_room:a[...]",
          "operationId": "userVanityName",
          "security": [
            {
              "openapi_oauth": [
                "user:read",
                "user:write",
                "user:read:admin",
                "user:write:admin",
                "user:read:pm_room",
                "user:read:pm_room:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "User:Read"
            ],
            "x-macro-scopes": [
              "user:read",
              "user:write",
              "user:read:admin",
              "user:write:admin"
            ],
            "x-granular-scopes": [
              "user:read:pm_room",
              "user:read:pm_room:admin"
            ]
          }
        }
      },
      "/users/{userId}": {
        "get": {
          "tags": [
            "Users"
          ],
          "summary": "Get a user",
          "description": "View a user's information on a Zoom account. For user-managed apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter. \r\n**Note:** The `user_info:read` scope is only available when you pass the `me` value for the `$userId` value. \r\n\r\nUsers who have not activated their account will have a `pending` status. These users' `created_at` timestamp will also display the time at which the API c[...]",
          "operationId": "user",
          "security": [
            {
              "openapi_oauth": [
                "user:read",
                "user:write",
                "user:read:admin",
                "user:write:admin",
                "user_profile",
                "user_info:read",
                "user:read:user",
                "user:read:user:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "User:Read"
            ],
            "x-macro-scopes": [
              "user:read",
              "user:write",
              "user:read:admin",
              "user:write:admin",
              "user_profile",
              "user_info:read"
            ],
            "x-granular-scopes": [
              "user:read:user",
              "user:read:user:admin"
            ]
          }
        },
        "delete": {
          "tags": [
            "Users"
          ],
          "summary": "Delete a user",
          "description": "**Disassociate** (unlink) a user or permanently **delete** a user.  \n\n**Disassociating** a user unlinks the user from the associated Zoom account and provides the user their own basic free Zoom account. The disassociated user can then purchase their own Zoom licenses. An account owner or account admin can transfer the user's meetings, webinars, and cloud recordings to another user before disassociation.\n\n\n**Deleting** a user permanently removes the user and their d[...]",
          "operationId": "userDelete",
          "security": [
            {
              "openapi_oauth": [
                "user:write:admin",
                "user:write",
                "user:delete:user",
                "user:delete:user:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "User:Edit"
            ],
            "x-macro-scopes": [
              "user:write:admin",
              "user:write"
            ],
            "x-granular-scopes": [
              "user:delete:user",
              "user:delete:user:admin"
            ]
          }
        },
        "patch": {
          "tags": [
            "Users"
          ],
          "summary": "Update a user",
          "description": "Updates a user's [Zoom profile](https://support.zoom.us/hc/en-us/articles/201363203-My-Profile) information. \n\n**Note**:  \nIf display_name is empty, the API endpoint derives the display_name from the first_name and last_name values. \n\nFor user-level apps, pass [the `me` value](hhttps://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overv[...]",
          "operationId": "userUpdate",
          "security": [
            {
              "openapi_oauth": [
                "user:write:admin",
                "user:write",
                "user:update:user",
                "user:update:user:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "User:Edit"
            ],
            "x-macro-scopes": [
              "user:write:admin",
              "user:write"
            ],
            "x-granular-scopes": [
              "user:update:user",
              "user:update:user:admin"
            ]
          }
        }
      },
      "/users/{userId}/assistants": {
        "get": {
          "tags": [
            "Users"
          ],
          "summary": "List user assistants",
          "description": "List a user's assistants. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\nAssistants are users who the current user has assigned [scheduling privilege](https://support.zoom.us/hc/en-us/articles/201362803-Scheduling-Privilege). These assistants can schedule meetings on behalf of the current user, as well as manage and act as an alternative host for all meetings if t[...]",
          "operationId": "userAssistants",
          "security": [
            {
              "openapi_oauth": [
                "user:read",
                "user:write",
                "user:read:admin",
                "user:write:admin",
                "user_profile",
                "user:read:list_assistants",
                "user:read:list_assistants:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "User:Read"
            ],
            "x-macro-scopes": [
              "user:read",
              "user:write",
              "user:read:admin",
              "user:write:admin",
              "user_profile"
            ],
            "x-granular-scopes": [
              "user:read:list_assistants",
              "user:read:list_assistants:admin"
            ]
          }
        },
        "post": {
          "tags": [
            "Users"
          ],
          "summary": "Add assistants",
          "description": "Assign assistants to a user. \n\nIn the request body, provide either the user's ID or the user's email address. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\nAssistants are the users to whom the current user has assigned [scheduling privileges](https://support.zoom.us/hc/en-us/articles/201362803-Scheduling-Privilege). Assistants can schedule meetings on behalf of[...]",
          "operationId": "userAssistantCreate",
          "security": [
            {
              "openapi_oauth": [
                "user:write:admin",
                "user:write",
                "user:write:assistant",
                "user:write:assistant:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "User:Edit"
            ],
            "x-macro-scopes": [
              "user:write:admin",
              "user:write"
            ],
            "x-granular-scopes": [
              "user:write:assistant",
              "user:write:assistant:admin"
            ]
          }
        },
        "delete": {
          "tags": [
            "Users"
          ],
          "summary": "Delete user assistants",
          "description": "Delete all of the current user's assistants. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\nAssistants are the users who the current user has assigned [scheduling privilege](https://support.zoom.us/hc/en-us/articles/201362803-Scheduling-Privilege). These assistants can schedule meeting on behalf of the current user, and manage and act as an alternative host for al[...]",
          "operationId": "userAssistantsDelete",
          "security": [
            {
              "openapi_oauth": [
                "user:write:admin",
                "user:write",
                "user:delete:assistant",
                "user:delete:assistant:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "User:Edit"
            ],
            "x-macro-scopes": [
              "user:write:admin",
              "user:write"
            ],
            "x-granular-scopes": [
              "user:delete:assistant",
              "user:delete:assistant:admin"
            ]
          }
        }
      },
      "/users/{userId}/assistants/{assistantId}": {
        "delete": {
          "tags": [
            "Users"
          ],
          "summary": "Delete a user assistant",
          "description": "Delete a specific assistant of a user. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\nAssistants are the users who the current user has assigned [scheduling privilege](https://support.zoom.us/hc/en-us/articles/201362803-Scheduling-Privilege). These assistants can schedule meeting on behalf of the current user as well as manage and act as an alternative host for al[...]",
          "operationId": "userAssistantDelete",
          "security": [
            {
              "openapi_oauth": [
                "user:write:admin",
                "user:write",
                "user:delete:assistant",
                "user:delete:assistant:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "User:Edit"
            ],
            "x-macro-scopes": [
              "user:write:admin",
              "user:write"
            ],
            "x-granular-scopes": [
              "user:delete:assistant",
              "user:delete:assistant:admin"
            ]
          }
        }
      },
      "/users/{userId}/collaboration_devices": {
        "get": {
          "tags": [
            "Users"
          ],
          "summary": "List a user's collaboration devices",
          "description": "List a user's collaboration devices. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `user:read`,`user:write`,`user:read:admin`,`user:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `user:read:list_collaboration_devices`[...]",
          "operationId": "listCollaborationDevices",
          "security": [
            {
              "openapi_oauth": [
                "user:read",
                "user:write",
                "user:read:admin",
                "user:write:admin",
                "user:read:list_collaboration_devices",
                "user:read:list_collaboration_devices:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "MobileDeviceManagement:Read"
            ],
            "x-macro-scopes": [
              "user:read",
              "user:write",
              "user:read:admin",
              "user:write:admin"
            ],
            "x-granular-scopes": [
              "user:read:list_collaboration_devices",
              "user:read:list_collaboration_devices:admin"
            ]
          }
        }
      },
      "/users/{userId}/collaboration_devices/{collaborationDeviceId}": {
        "get": {
          "tags": [
            "Users"
          ],
          "summary": "Get collaboration device detail",
          "description": "Get collaboration device detail. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `user:read`,`user:write`,`user:read:admin`,`user:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `user:read:collaboration_device`,`user:rea[...]",
          "operationId": "getCollaborationDevice",
          "security": [
            {
              "openapi_oauth": [
                "user:read",
                "user:write",
                "user:read:admin",
                "user:write:admin",
                "user:read:collaboration_device",
                "user:read:collaboration_device:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "MobileDeviceManagement:Read"
            ],
            "x-macro-scopes": [
              "user:read",
              "user:write",
              "user:read:admin",
              "user:write:admin"
            ],
            "x-granular-scopes": [
              "user:read:collaboration_device",
              "user:read:collaboration_device:admin"
            ]
          }
        }
      },
      "/users/{userId}/email": {
        "put": {
          "tags": [
            "Users"
          ],
          "summary": "Update a user's email",
          "description": "Change a user's [email address](https://support.zoom.us/hc/en-us/articles/201362563-How-Do-I-Change-the-Email-on-My-Account-) on a Zoom account that has managed domain set up. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\n* If the Zoom account in which the user belongs has multiple [managed domains](https://support.zoom.us/hc/en-us/articles/203395207-What-is-Mana[...]",
          "operationId": "userEmailUpdate",
          "security": [
            {
              "openapi_oauth": [
                "user:write:admin",
                "user:write",
                "user:update:email",
                "user:update:email:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "User:Edit"
            ],
            "x-macro-scopes": [
              "user:write:admin",
              "user:write"
            ],
            "x-granular-scopes": [
              "user:update:email",
              "user:update:email:admin"
            ]
          }
        }
      },
      "/users/{userId}/meeting_summary_templates": {
        "get": {
          "tags": [
            "Users"
          ],
          "summary": "Get meeting summary templates",
          "description": "Get a list of meeting summary templates. \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `user:read`,`user:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `user:read:settings`,`user:read:settings:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
          "operationId": "Getmeetingsummarytemplates",
          "security": [
            {
              "openapi_oauth": [
                "user:read",
                "user:read:admin",
                "user:read:settings",
                "user:read:settings:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "User:Read"
            ],
            "x-macro-scopes": [
              "user:read",
              "user:read:admin"
            ],
            "x-granular-scopes": [
              "user:read:settings",
              "user:read:settings:admin"
            ]
          }
        }
      },
      "/users/{userId}/meeting_templates/{meetingTemplateId}": {
        "get": {
          "tags": [
            "Users"
          ],
          "summary": "Get meeting template detail",
          "description": "Retrieve a user's [meeting template](https://support.zoom.us/hc/en-us/articles/360036559151-Meeting-templates). For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `user:read:admin`,`user:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-li[...]",
          "operationId": "getUserMeetingTemplates",
          "security": [
            {
              "openapi_oauth": [
                "user:read:admin",
                "user:read"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "user:read:admin",
              "user:read"
            ]
          }
        }
      },
      "/users/{userId}/password": {
        "put": {
          "tags": [
            "Users"
          ],
          "summary": "Update a user's password",
          "description": "Update the [password](https://support.zoom.us/hc/en-us/articles/206344385-Change-a-User-s-Password) of a user using which the user can login to Zoom. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\nAfter this request is processed successfully, an email notification is sent to the user saying that the password was changed.  \n \n**Prerequisites:**  \n \n* Owner or a[...]",
          "operationId": "userPassword",
          "security": [
            {
              "openapi_oauth": [
                "user:write:admin",
                "user:write",
                "user:update:password",
                "user:update:password:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "User:Edit"
            ],
            "x-macro-scopes": [
              "user:write:admin",
              "user:write"
            ],
            "x-granular-scopes": [
              "user:update:password",
              "user:update:password:admin"
            ]
          }
        }
      },
      "/users/{userId}/permissions": {
        "get": {
          "tags": [
            "Users"
          ],
          "summary": "Get user permissions",
          "description": "Get permissions that have been granted to the user. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\nUsers can be assigned a set of permissions that allows them to access only the pages or information that a user needs to view or edit.\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `user:read`,`user:write`,`user:read:admin`[...]",
          "operationId": "userPermission",
          "security": [
            {
              "openapi_oauth": [
                "user:read",
                "user:write",
                "user:read:admin",
                "user:write:admin",
                "user_profile",
                "user:read:list_permissions",
                "user:read:list_permissions:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "User:Read"
            ],
            "x-macro-scopes": [
              "user:read",
              "user:write",
              "user:read:admin",
              "user:write:admin",
              "user_profile"
            ],
            "x-granular-scopes": [
              "user:read:list_permissions",
              "user:read:list_permissions:admin"
            ]
          }
        }
      },
      "/users/{userId}/picture": {
        "post": {
          "tags": [
            "Users"
          ],
          "summary": "Upload a user's profile picture",
          "description": "Upload a user's profile picture. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\nProvide `multipart/form-data` as the value of the `content-type` header for this request. This API supports `.jpeg` and `.png` file formats.\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `user:write:admin`,`user:write`\n\n**[Granular Scopes]([...]",
          "operationId": "userPicture",
          "security": [
            {
              "openapi_oauth": [
                "user:write:admin",
                "user:write",
                "user:write:profile_picture",
                "user:write:profile_picture:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "User:Edit"
            ],
            "x-macro-scopes": [
              "user:write:admin",
              "user:write"
            ],
            "x-granular-scopes": [
              "user:write:profile_picture",
              "user:write:profile_picture:admin"
            ]
          }
        },
        "delete": {
          "tags": [
            "Users"
          ],
          "summary": "Delete a user's profile picture",
          "description": "Delete a user's profile picture. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter. \n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `user:write:admin`,`user:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
          "operationId": "userPictureDelete",
          "security": [
            {
              "openapi_oauth": [
                "user:write:admin",
                "user:write"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-macro-scopes": [
              "user:write:admin",
              "user:write"
            ]
          }
        }
      },
      "/users/{userId}/presence_status": {
        "get": {
          "tags": [
            "Users"
          ],
          "summary": "Get a user presence status",
          "description": "Returns a user's current status.\n\nUsers in the Zoom desktop client and mobile apps are assigned with a [presence status](https://support.zoom.us/hc/en-us/articles/360032554051-Status-Icons). The presence status displays the user's  availability. \n\nThe available statuses are:\n* **Away**\n* **Do not disturb**\n* **Available**\n* **In a calendar event**\n* **Presenting**\n* **In a Zoom meeting**\n* **On a call**\n* **Out of Office**\n* **Busy**\n* **Offline**\n\nIf th[...]",
          "operationId": "getUserPresenceStatus",
          "security": [
            {
              "openapi_oauth": [
                "user:read",
                "user:read:admin",
                "user:read:presence_status",
                "user:read:presence_status:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "User:Read"
            ],
            "x-macro-scopes": [
              "user:read",
              "user:read:admin"
            ],
            "x-granular-scopes": [
              "user:read:presence_status",
              "user:read:presence_status:admin"
            ]
          }
        },
        "put": {
          "tags": [
            "Users"
          ],
          "summary": "Update a user's presence status",
          "description": "Update a user's presence status. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\nA user's status **cannot** be updated more than once per minute. For example, you can only submit a maximum of one update request per minute for a single user.\n\nUsers in the Zoom desktop client and mobile apps are assigned with a [presence status](https://support.zoom.us/hc/en-us/art[...]",
          "operationId": "updatePresenceStatus",
          "security": [
            {
              "openapi_oauth": [
                "user:write",
                "user:write:admin",
                "user:update:presence_status",
                "user:update:presence_status:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "User:Edit"
            ],
            "x-macro-scopes": [
              "user:write",
              "user:write:admin"
            ],
            "x-granular-scopes": [
              "user:update:presence_status",
              "user:update:presence_status:admin"
            ]
          }
        }
      },
      "/users/{userId}/schedulers": {
        "get": {
          "tags": [
            "Users"
          ],
          "summary": "List user schedulers",
          "description": "List all of a user's schedulers. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\nSchedulers in this context are users who can schedule meetings for the current user. For example, if the current user, the user whose `userId` was passed in the `path` parameter, is **User A**, this API's response will list all users for whom **User A** can schedule and manage meetings[...]",
          "operationId": "userSchedulers",
          "security": [
            {
              "openapi_oauth": [
                "user:read",
                "user:write",
                "user:read:admin",
                "user:write:admin",
                "user_profile",
                "user:read:list_schedulers",
                "user:read:list_schedulers:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "User:Read"
            ],
            "x-macro-scopes": [
              "user:read",
              "user:write",
              "user:read:admin",
              "user:write:admin",
              "user_profile"
            ],
            "x-granular-scopes": [
              "user:read:list_schedulers",
              "user:read:list_schedulers:admin"
            ]
          }
        },
        "delete": {
          "tags": [
            "Users"
          ],
          "summary": "Delete user schedulers",
          "description": "Delete all of a user's schedulers. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\nSchedulers are users on whose behalf the current user (assistant) can schedule meetings for. By calling this API, the current user will no longer be a scheduling assistant of any user. \n\n**Prerequisites:** \n* Current user (assistant) must be under the same account as the scheduler[...]",
          "operationId": "userSchedulersDelete",
          "security": [
            {
              "openapi_oauth": [
                "user:write:admin",
                "user:write",
                "user:delete:scheduler",
                "user:delete:scheduler:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "User:Edit"
            ],
            "x-macro-scopes": [
              "user:write:admin",
              "user:write"
            ],
            "x-granular-scopes": [
              "user:delete:scheduler",
              "user:delete:scheduler:admin"
            ]
          }
        }
      },
      "/users/{userId}/schedulers/{schedulerId}": {
        "delete": {
          "tags": [
            "Users"
          ],
          "summary": "Delete a scheduler",
          "description": "Delete a scheduler. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\nSchedulers are users who the current user (assistant) can schedule meetings on their behalf. By calling this API, the current user will no longer be a scheduling assistant of this scheduler.\n\n**Prerequisites:** \n* Current user must be under the same account as the scheduler.\n\n**[Scopes](https:[...]",
          "operationId": "userSchedulerDelete",
          "security": [
            {
              "openapi_oauth": [
                "user:write:admin",
                "user:write",
                "user:delete:scheduler",
                "user:delete:scheduler:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "User:Edit"
            ],
            "x-macro-scopes": [
              "user:write:admin",
              "user:write"
            ],
            "x-granular-scopes": [
              "user:delete:scheduler",
              "user:delete:scheduler:admin"
            ]
          }
        }
      },
      "/users/{userId}/settings": {
        "get": {
          "tags": [
            "Users"
          ],
          "summary": "Get user settings",
          "description": "Retrieve a user's settings. \nFor user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `user:read`,`user:write`,`user:read:admin`,`user:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `user:read:settings`,`user:read:settings:admi[...]",
          "operationId": "userSettings",
          "security": [
            {
              "openapi_oauth": [
                "user:read",
                "user:write",
                "user:read:admin",
                "user:write:admin",
                "user:read:settings",
                "user:read:settings:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "User:Read"
            ],
            "x-macro-scopes": [
              "user:read",
              "user:write",
              "user:read:admin",
              "user:write:admin"
            ],
            "x-granular-scopes": [
              "user:read:settings",
              "user:read:settings:admin"
            ]
          }
        },
        "patch": {
          "tags": [
            "Users"
          ],
          "summary": "Update user settings",
          "description": "Update a user's settings. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `user:write:admin`,`user:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `user:update:settings`,`user:update:settings:admin`\n\n**[Rate Limit Label](htt[...]",
          "operationId": "userSettingsUpdate",
          "security": [
            {
              "openapi_oauth": [
                "user:write:admin",
                "user:write",
                "user:update:settings",
                "user:update:settings:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "User:Edit"
            ],
            "x-macro-scopes": [
              "user:write:admin",
              "user:write"
            ],
            "x-granular-scopes": [
              "user:update:settings",
              "user:update:settings:admin"
            ]
          }
        }
      },
      "/users/{userId}/settings/virtual_backgrounds": {
        "post": {
          "tags": [
            "Users"
          ],
          "summary": "Upload Virtual Background files",
          "description": "Use this API to [upload a Virtual Background files](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background) to a user's profile. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter. \n\n **Note:** \n* A user profile cannot exceed more than 10 Virtual Background files. \n* You can only upload image files that are in JPG/JPEG, GIF or PNG format. \n* Video fil[...]",
          "operationId": "uploadVBuser",
          "security": [
            {
              "openapi_oauth": [
                "user:write:admin",
                "user:write",
                "user:write:virtual_background_files",
                "user:write:virtual_background_files:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "User:Edit"
            ],
            "x-macro-scopes": [
              "user:write:admin",
              "user:write"
            ],
            "x-granular-scopes": [
              "user:write:virtual_background_files",
              "user:write:virtual_background_files:admin"
            ]
          }
        },
        "delete": {
          "tags": [
            "Users"
          ],
          "summary": "Delete Virtual Background files",
          "description": "Use this API to delete a user's Virtual Background files. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter. \n\n **Prerequisites:** \n* The [Virtual Background feature](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background#h_2ef28080-fce9-4ac2-b567-dc958afab1b7) must be enabled on the account.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/o[...]",
          "operationId": "delUserVB",
          "security": [
            {
              "openapi_oauth": [
                "user:write:admin",
                "user:write",
                "user:delete:virtual_background_files",
                "user:delete:virtual_background_files:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "User:Edit"
            ],
            "x-macro-scopes": [
              "user:write:admin",
              "user:write"
            ],
            "x-granular-scopes": [
              "user:delete:virtual_background_files",
              "user:delete:virtual_background_files:admin"
            ]
          }
        }
      },
      "/users/{userId}/status": {
        "put": {
          "tags": [
            "Users"
          ],
          "summary": "Update user status",
          "description": "[Deactivate](https://support.zoom.us/hc/en-us/articles/115005269946-Remove-User-from-your-Account#h_6a9bc1c3-d739-4945-b1f2-00b3b88fb5cc) an active user or to [reactivate](https://support.zoom.us/hc/en-us/articles/115005269946-Remove-User-from-your-Account#h_16319724-d120-4be6-af5d-31582d134ea0) a deactivated user. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\nAn[...]",
          "operationId": "userStatus",
          "security": [
            {
              "openapi_oauth": [
                "user:write:admin",
                "user:write",
                "user:update:status",
                "user:update:status:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "User:Edit"
            ],
            "x-macro-scopes": [
              "user:write:admin",
              "user:write"
            ],
            "x-granular-scopes": [
              "user:update:status",
              "user:update:status:admin"
            ]
          }
        }
      },
      "/users/{userId}/token": {
        "get": {
          "tags": [
            "Users"
          ],
          "summary": "Get a user's token",
          "description": "Gets a user's Zoom token or Zoom Access Key (ZAK). \n\nFor user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter. \n\n \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `user:read`,`user:write`,`user:read:admin`,`user:write:admin`,`user_profile`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `us[...]",
          "operationId": "userToken",
          "security": [
            {
              "openapi_oauth": [
                "user:read",
                "user:write",
                "user:read:admin",
                "user:write:admin",
                "user_profile",
                "user:read:token",
                "user:read:token:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "User:Read"
            ],
            "x-macro-scopes": [
              "user:read",
              "user:write",
              "user:read:admin",
              "user:write:admin",
              "user_profile"
            ],
            "x-granular-scopes": [
              "user:read:token",
              "user:read:token:admin"
            ]
          }
        },
        "delete": {
          "tags": [
            "Users"
          ],
          "summary": "Revoke a user's SSO token",
          "description": "Revokes a user's SSO token. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\nAfter calling this API, the SSO user will be logged out of their current Zoom session.\n\n\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `user:write:admin`,`user:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-o[...]",
          "operationId": "userSSOTokenDelete",
          "security": [
            {
              "openapi_oauth": [
                "user:write:admin",
                "user:write",
                "user:delete:token",
                "user:delete:token:admin"
              ],
              "openapi_authorization": []
            }
          ],
          "x-extensions": {
            "x-permissions": [
              "User:Edit"
            ],
            "x-macro-scopes": [
              "user:write:admin",
              "user:write"
            ],
            "x-granular-scopes": [
              "user:delete:token",
              "user:delete:token:admin"
            ]
          }
        }
      }
    },
    "components": {
      "securitySchemes": {
        "openapi_authorization": {
          "type": "apiKey",
          "name": "Authorization",
          "in": "header"
        },
        "openapi_oauth": {
          "type": "oauth2",
          "flows": {
            "authorizationCode": {
              "authorizationUrl": "/",
              "tokenUrl": "",
              "refreshUrl": "",
              "scopes": {
                "contact_group:write:admin": "contact_group:write:admin",
                "contact_group:read:admin": "contact_group:read:admin",
                " division:read:admin": " division:read:admin",
                "division:read:list_divisions:admin": "division:read:list_divisions:admin",
                "division:wirte:admin": "division:wirte:admin",
                "division:write:division:admin": "division:write:division:admin",
                "division:read:division:admin": "division:read:division:admin",
                "division:update:division:admin": "division:update:division:admin",
                "division:delete:division:admin": "division:delete:division:admin",
                "division:read:member:admin": "division:read:member:admin",
                "division:write:member:admin": "division:write:member:admin",
                "group:write:admin": "group:write:admin",
                "group:write:group:admin": "group:write:group:admin",
                "group:read:admin": "group:read:admin",
                "group:read:list_groups:admin": "group:read:list_groups:admin",
                "group:update:group:admin": "group:update:group:admin",
                "group:delete:group:admin": "group:delete:group:admin",
                "group:read:group:admin": "group:read:group:admin",
                "group:write:administrator:admin": "group:write:administrator:admin",
                "group:read:administrator:admin": "group:read:administrator:admin",
                "group:delete:administrator:admin": "group:delete:administrator:admin",
                "group:read:list_channels:admin": "group:read:list_channels:admin",
                "group:update:lock_settings:admin": "group:update:lock_settings:admin",
                "group:read:lock_settings:admin": "group:read:lock_settings:admin",
                "group:write:member:admin": "group:write:member:admin",
                "group:read:list_members:admin": "group:read:list_members:admin",
                "group:update:member:admin": "group:update:member:admin",
                "group:delete:member:admin": "group:delete:member:admin",
                "group:update:settings:admin": "group:update:settings:admin",
                "group:read:settings:admin": "group:read:settings:admin",
                "group:update:registration_settings:admin": "group:update:registration_settings:admin",
                "group:read:registration_settings:admin": "group:read:registration_settings:admin",
                "group:write:virtual_background_files:admin": "group:write:virtual_background_files:admin",
                "group:delete:virtual_background_files:admin": "group:delete:virtual_background_files:admin",
                "user:read": "user:read",
                "user:write": "user:write",
                "user:read:admin": "user:read:admin",
                "user:write:admin": "user:write:admin",
                "user:read:list_users:admin": "user:read:list_users:admin",
                "user:write:user:admin": "user:write:user:admin",
                "user:read:email": "user:read:email",
                "user:read:email:admin": "user:read:email:admin",
                "user:write:feature:admin": "user:write:feature:admin",
                "user_zak:read": "user_zak:read",
                "user:read:zak": "user:read:zak",
                "user:read:zak:admin": "user:read:zak:admin",
                "user:read:summary:admin": "user:read:summary:admin",
                "user:read:pm_room": "user:read:pm_room",
                "user:read:pm_room:admin": "user:read:pm_room:admin",
                "user_profile": "user_profile",
                "user_info:read": "user_info:read",
                "user:read:user": "user:read:user",
                "user:read:user:admin": "user:read:user:admin",
                "user:update:user": "user:update:user",
                "user:update:user:admin": "user:update:user:admin",
                "user:delete:user": "user:delete:user",
                "user:delete:user:admin": "user:delete:user:admin",
                "user:read:list_assistants": "user:read:list_assistants",
                "user:read:list_assistants:admin": "user:read:list_assistants:admin",
                "user:write:assistant": "user:write:assistant",
                "user:write:assistant:admin": "user:write:assistant:admin",
                "user:delete:assistant": "user:delete:assistant",
                "user:delete:assistant:admin": "user:delete:assistant:admin",
                "user:read:list_collaboration_devices": "user:read:list_collaboration_devices",
                "user:read:list_collaboration_devices:admin": "user:read:list_collaboration_devices:admin",
                "user:read:collaboration_device": "user:read:collaboration_device",
                "user:read:collaboration_device:admin": "user:read:collaboration_device:admin",
                "user:update:email": "user:update:email",
                "user:update:email:admin": "user:update:email:admin",
                "user:read:settings": "user:read:settings",
                "user:read:settings:admin": "user:read:settings:admin",
                "user:update:password": "user:update:password",
                "user:update:password:admin": "user:update:password:admin",
                "user:read:list_permissions": "user:read:list_permissions",
                "user:read:list_permissions:admin": "user:read:list_permissions:admin",
                "user:write:profile_picture": "user:write:profile_picture",
                "user:write:profile_picture:admin": "user:write:profile_picture:admin",
                "user:update:presence_status": "user:update:presence_status",
                "user:update:presence_status:admin": "user:update:presence_status:admin",
                "user:read:presence_status": "user:read:presence_status",
                "user:read:presence_status:admin": "user:read:presence_status:admin",
                "user:delete:scheduler": "user:delete:scheduler",
                "user:delete:scheduler:admin": "user:delete:scheduler:admin",
                "user:read:list_schedulers": "user:read:list_schedulers",
                "user:read:list_schedulers:admin": "user:read:list_schedulers:admin",
                "user:update:settings": "user:update:settings",
                "user:update:settings:admin": "user:update:settings:admin",
                "user:delete:virtual_background_files": "user:delete:virtual_background_files",
                "user:delete:virtual_background_files:admin": "user:delete:virtual_background_files:admin",
                "user:write:virtual_background_files": "user:write:virtual_background_files",
                "user:write:virtual_background_files:admin": "user:write:virtual_background_files:admin",
                "user:update:status": "user:update:status",
                "user:update:status:admin": "user:update:status:admin",
                "user:read:token": "user:read:token",
                "user:read:token:admin": "user:read:token:admin",
                "user:delete:token": "user:delete:token",
                "user:delete:token:admin": "user:delete:token:admin"
              }
            }
          }
        }
      }
    }
  }
}
