{
 "openapi": "3.0.0",
 "info": {
  "title": "Video Management",
  "description": "Use the Video Management API to manage channels, channel permissions, playlists, and videos.\n\n You can create, delete, update, and list the available channels and playlists. You can add and remove videos from channels and playlists or list the videos in a channel or playlist.",
  "termsOfService": "https://zoom.us/docs/en-us/zoom_api_license_and_tou.html",
  "contact": {
   "name": "Zoom Developers",
   "url": "https://developer.zoom.us/"
  },
  "version": "2"
 },
 "servers": [
  {
   "url": "https://api.zoom.us/v2"
  }
 ],
 "paths": {
  "/video_management/channels": {
   "get": {
    "tags": [
     "Channels"
    ],
    "summary": "List channels",
    "description": "Retrieves the list of channels.\n\n**Prerequisites**:\n* A [Pro or higher account plan](https://www.zoom.us/pricing?).\n* A Zoom Video Management license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt_channels:read`,`video_mgmt_channels:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt:read:list_channels`,`video_mgmt:read:list_channels:admin`\n\n**[Rate Lim[...]",
    "operationId": "listVideoChannels",
    "security": [
     {
      "openapi_oauth": [
       "video_mgmt_channels:read",
       "video_mgmt_channels:read:admin",
       "video_mgmt:read:list_channels",
       "video_mgmt:read:list_channels:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "video_mgmt_channels:read",
      "video_mgmt_channels:read:admin"
     ],
     "x-granular-scopes": [
      "video_mgmt:read:list_channels",
      "video_mgmt:read:list_channels:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Channels"
    ],
    "summary": "Create a channel",
    "description": "Creates a channel for managing videos. \n\n**Prerequisites**:\n* A [Pro or higher account plan](https://www.zoom.us/pricing?).\n* A Zoom Video Management license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt_channels:write`,`video_mgmt_channels:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt:write:channel`,`video_mgmt:write:channel:admin`\n\n**[Rate Lim[...]",
    "operationId": "createChannel",
    "security": [
     {
      "openapi_oauth": [
       "video_mgmt_channels:write",
       "video_mgmt_channels:write:admin",
       "video_mgmt:write:channel",
       "video_mgmt:write:channel:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "video_mgmt_channels:write",
      "video_mgmt_channels:write:admin"
     ],
     "x-granular-scopes": [
      "video_mgmt:write:channel",
      "video_mgmt:write:channel:admin"
     ]
    }
   }
  },
  "/video_management/channels/{channelId}": {
   "get": {
    "tags": [
     "Channels"
    ],
    "summary": "Get channel details",
    "description": "Returns the details of the video channel.\n\n**Prerequisites**:\n* A [Pro or higher account plan](https://www.zoom.us/pricing?).\n* A Zoom Video Management license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt_channels:read`,`video_mgmt_channels:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt:read:channel`,`video_mgmt:read:channel:admin`\n\n**[Rate Limit[...]",
    "operationId": "getChannelDetail",
    "security": [
     {
      "openapi_oauth": [
       "video_mgmt_channels:read",
       "video_mgmt_channels:read:admin",
       "video_mgmt:read:channel",
       "video_mgmt:read:channel:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "video_mgmt_channels:read",
      "video_mgmt_channels:read:admin"
     ],
     "x-granular-scopes": [
      "video_mgmt:read:channel",
      "video_mgmt:read:channel:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Channels"
    ],
    "summary": "Delete channel",
    "description": "Deletes a video channel. \n\n**Prerequisites**:\n* A Pro or higher account plan.\n* A Zoom Video Management license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt_channels:write`,`video_mgmt_channels:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt:delete:channel`,`video_mgmt:delete:channel:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/a[...]",
    "operationId": "DeleteChannel",
    "security": [
     {
      "openapi_oauth": [
       "video_mgmt_channels:write",
       "video_mgmt_channels:write:admin",
       "video_mgmt:delete:channel",
       "video_mgmt:delete:channel:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "video_mgmt_channels:write",
      "video_mgmt_channels:write:admin"
     ],
     "x-granular-scopes": [
      "video_mgmt:delete:channel",
      "video_mgmt:delete:channel:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Channels"
    ],
    "summary": "Update channel",
    "description": "Updates a video channel. \n\n**Prerequisites**:\n* A Pro or higher account plan.\n* A Zoom Video Management license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt_channels:write`,`video_mgmt_channels:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt:update:channel`,`video_mgmt:update:channel:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/a[...]",
    "operationId": "UpdateVideoChannel",
    "security": [
     {
      "openapi_oauth": [
       "video_mgmt_channels:write",
       "video_mgmt_channels:write:admin",
       "video_mgmt:update:channel",
       "video_mgmt:update:channel:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "video_mgmt_channels:write",
      "video_mgmt_channels:write:admin"
     ],
     "x-granular-scopes": [
      "video_mgmt:update:channel",
      "video_mgmt:update:channel:admin"
     ]
    }
   }
  },
  "/video_management/channels/{channelId}/actions": {
   "patch": {
    "tags": [
     "Channels"
    ],
    "summary": " Channel actions",
    "description": "Perform state transition actions on a video channel . \n\n**Prerequisites**:\n* A [Pro or higher account plan](https://www.zoom.us/pricing?).\n* A Zoom Video Management license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt_channels:write`,`video_mgmt_channels:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt:update:channel`,`video_mgmt:update:channel:admi[...]",
    "operationId": "channelActions",
    "security": [
     {
      "openapi_oauth": [
       "video_mgmt_channels:write",
       "video_mgmt_channels:write:admin",
       "video_mgmt:update:channel",
       "video_mgmt:update:channel:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "video_mgmt_channels:write",
      "video_mgmt_channels:write:admin"
     ],
     "x-granular-scopes": [
      "video_mgmt:update:channel",
      "video_mgmt:update:channel:admin"
     ]
    }
   }
  },
  "/video_management/channels/{channelId}/permissions": {
   "get": {
    "tags": [
     "Permissions"
    ],
    "summary": "List channel permissions",
    "description": "Retrieves the list of permissions for a channel. \\n\n**Prerequisites**:\n* A [Pro or higher account plan](https://www.zoom.us/pricing?).\n* A Zoom Video Management license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt_channels:read`,`video_mgmt_channels:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt:read:list_permissions`,`video_mgmt:read:list_permissi[...]",
    "operationId": "listChannelPermissions",
    "security": [
     {
      "openapi_oauth": [
       "video_mgmt_channels:read",
       "video_mgmt_channels:read:admin",
       "video_mgmt:read:list_permissions",
       "video_mgmt:read:list_permissions:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "video_mgmt_channels:read",
      "video_mgmt_channels:read:admin"
     ],
     "x-granular-scopes": [
      "video_mgmt:read:list_permissions",
      "video_mgmt:read:list_permissions:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Permissions"
    ],
    "summary": "Create channel permissions",
    "description": "Creates permissions for the given channel ID. Add users, such as collaborators or viewers, to the channel. \n\n**Prerequisites**:\n* A [Pro or higher account plan](https://www.zoom.us/pricing?).\n* A Zoom Video Management license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt_channels:write`,`video_mgmt_channels:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video[...]",
    "operationId": "createChannelPermissions",
    "security": [
     {
      "openapi_oauth": [
       "video_mgmt_channels:write",
       "video_mgmt_channels:write:admin",
       "video_mgmt:write:permissions",
       "video_mgmt:write:permissions:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "video_mgmt_channels:write",
      "video_mgmt_channels:write:admin"
     ],
     "x-granular-scopes": [
      "video_mgmt:write:permissions",
      "video_mgmt:write:permissions:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Permissions"
    ],
    "summary": "Delete channel permissions",
    "description": "Delete channel permissions. \n\n**Prerequisites**:\n* A [Pro or higher account plan](https://www.zoom.us/pricing?).\n* A Zoom Video Management license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt_channels:write`,`video_mgmt_channels:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt:delete:permissions`,`video_mgmt:delete:permissions:admin`\n\n**[Rate Limi[...]",
    "operationId": "DeleteChannelPermissions",
    "security": [
     {
      "openapi_oauth": [
       "video_mgmt_channels:write",
       "video_mgmt_channels:write:admin",
       "video_mgmt:delete:permissions",
       "video_mgmt:delete:permissions:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "video_mgmt_channels:write",
      "video_mgmt_channels:write:admin"
     ],
     "x-granular-scopes": [
      "video_mgmt:delete:permissions",
      "video_mgmt:delete:permissions:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Permissions"
    ],
    "summary": "Update channel permissions",
    "description": "Updates channel permissions. \n\n**Prerequisites**:\n* A [Pro or higher account plan](https://www.zoom.us/pricing?).\n* A Zoom Video Management license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt_channels:write`,`video_mgmt_channels:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt:update:permissions`,`video_mgmt:update:permissions:admin`\n\n**[Rate Lim[...]",
    "operationId": "updateChannelPermissions",
    "security": [
     {
      "openapi_oauth": [
       "video_mgmt_channels:write",
       "video_mgmt_channels:write:admin",
       "video_mgmt:update:permissions",
       "video_mgmt:update:permissions:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "video_mgmt_channels:write",
      "video_mgmt_channels:write:admin"
     ],
     "x-granular-scopes": [
      "video_mgmt:update:permissions",
      "video_mgmt:update:permissions:admin"
     ]
    }
   }
  },
  "/video_management/channels/{channelId}/playlists": {
   "get": {
    "tags": [
     "Playlists"
    ],
    "summary": "List channel playlists",
    "description": "Retrieves the list of playlists for the channel. \n\n**Prerequisites**:\n* A [Pro or higher account plan](https://www.zoom.us/pricing?).\n* A Zoom Video Management license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt_channels:read`,`video_mgmt_channels:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt:read:list_channel_playlists`,`video_mgmt:read:list_cha[...]",
    "operationId": "ListChannelPlaylists",
    "security": [
     {
      "openapi_oauth": [
       "video_mgmt_channels:read",
       "video_mgmt_channels:read:admin",
       "video_mgmt:read:list_channel_playlists",
       "video_mgmt:read:list_channel_playlists:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "video_mgmt_channels:read",
      "video_mgmt_channels:read:admin"
     ],
     "x-granular-scopes": [
      "video_mgmt:read:list_channel_playlists",
      "video_mgmt:read:list_channel_playlists:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Playlists"
    ],
    "summary": "Add channel playlists ",
    "description": "Adds playlists to the channel. \n\n**Prerequisites**:\n* A [Pro or higher account plan](https://www.zoom.us/pricing?).\n* A Zoom Video Management license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt_channels:write`,`video_mgmt_channels:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt:write:channel_playlists`,`video_mgmt:write:channel_playlists:admin`\n\[...]",
    "operationId": "AddChannelPlaylists",
    "security": [
     {
      "openapi_oauth": [
       "video_mgmt_channels:write",
       "video_mgmt_channels:write:admin",
       "video_mgmt:write:channel_playlists",
       "video_mgmt:write:channel_playlists:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "video_mgmt_channels:write",
      "video_mgmt_channels:write:admin"
     ],
     "x-granular-scopes": [
      "video_mgmt:write:channel_playlists",
      "video_mgmt:write:channel_playlists:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Playlists"
    ],
    "summary": "Delete channel playlists",
    "description": "Removes playlists from the channel. \n\n**Prerequisites**:\n* A [Pro or higher account plan](https://www.zoom.us/pricing?).\n* A Zoom Video Management license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt_channels:write`,`video_mgmt_channels:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt:delete:channel_playlists`,`video_mgmt:delete:channel_playlists:ad[...]",
    "operationId": "DeleteChannelPlaylists",
    "security": [
     {
      "openapi_oauth": [
       "video_mgmt_channels:write",
       "video_mgmt_channels:write:admin",
       "video_mgmt:delete:channel_playlists",
       "video_mgmt:delete:channel_playlists:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "video_mgmt_channels:write",
      "video_mgmt_channels:write:admin"
     ],
     "x-granular-scopes": [
      "video_mgmt:delete:channel_playlists",
      "video_mgmt:delete:channel_playlists:admin"
     ]
    }
   }
  },
  "/video_management/playlists": {
   "get": {
    "tags": [
     "Playlists"
    ],
    "summary": "List playlists",
    "description": "Retrieves the list of playlists for the user. \n\n**Prerequisites**:\n* A [Pro or higher account plan](https://www.zoom.us/pricing?).\n* A Zoom Video Management license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt_playlists:read`,`video_mgmt_playlists:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt:read:list_playlists`,`video_mgmt:read:list_playlists:ad[...]",
    "operationId": "ListPlaylists",
    "security": [
     {
      "openapi_oauth": [
       "video_mgmt_playlists:read",
       "video_mgmt_playlists:read:admin",
       "video_mgmt:read:list_playlists",
       "video_mgmt:read:list_playlists:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "video_mgmt_playlists:read",
      "video_mgmt_playlists:read:admin"
     ],
     "x-granular-scopes": [
      "video_mgmt:read:list_playlists",
      "video_mgmt:read:list_playlists:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Playlists"
    ],
    "summary": "Create a playlist",
    "description": "Creates a playlist for managing videos. \n\n**Prerequisites**:\n* A [Pro or higher account plan](https://www.zoom.us/pricing?).\n* A Zoom Video Management license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt_playlists:write`,`video_mgmt_playlists:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt:write:playlist`,`video_mgmt:write:playlist:admin`\n\n**[Rat[...]",
    "operationId": "createPlaylist",
    "security": [
     {
      "openapi_oauth": [
       "video_mgmt_playlists:write",
       "video_mgmt_playlists:write:admin",
       "video_mgmt:write:playlist",
       "video_mgmt:write:playlist:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "video_mgmt_playlists:write",
      "video_mgmt_playlists:write:admin"
     ],
     "x-granular-scopes": [
      "video_mgmt:write:playlist",
      "video_mgmt:write:playlist:admin"
     ]
    }
   }
  },
  "/video_management/playlists/{playlistId}": {
   "delete": {
    "tags": [
     "Playlists"
    ],
    "summary": "Delete playlist",
    "description": "Deletes a playlist. \n\n**Prerequisites**:\n* A Pro or higher account plan.\n* A Zoom Video Management license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt_playlists:write`,`video_mgmt_playlists:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt:delete:playlist`,`video_mgmt:delete:playlist:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/ap[...]",
    "operationId": "DeletePlaylist",
    "security": [
     {
      "openapi_oauth": [
       "video_mgmt_playlists:write",
       "video_mgmt_playlists:write:admin",
       "video_mgmt:delete:playlist",
       "video_mgmt:delete:playlist:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "video_mgmt_playlists:write",
      "video_mgmt_playlists:write:admin"
     ],
     "x-granular-scopes": [
      "video_mgmt:delete:playlist",
      "video_mgmt:delete:playlist:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Playlists"
    ],
    "summary": "Update playlist",
    "description": "Update playlist. \n\n**Prerequisites**:\n* A [Pro or higher account plan](https://www.zoom.us/pricing?).\n* A Zoom Video Management license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt_playlists:write`,`video_mgmt_playlists:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt:update:playlist`,`video_mgmt:update:playlist:admin`\n\n**[Rate Limit Label](https:[...]",
    "operationId": "UpdatePlaylist",
    "security": [
     {
      "openapi_oauth": [
       "video_mgmt_playlists:write",
       "video_mgmt_playlists:write:admin",
       "video_mgmt:update:playlist",
       "video_mgmt:update:playlist:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "video_mgmt_playlists:write",
      "video_mgmt_playlists:write:admin"
     ],
     "x-granular-scopes": [
      "video_mgmt:update:playlist",
      "video_mgmt:update:playlist:admin"
     ]
    }
   }
  },
  "/video_management/channels/{channelId}/videos": {
   "get": {
    "tags": [
     "Videos"
    ],
    "summary": "List channel videos",
    "description": "Gets a list of the channel's videos. \n\n**Prerequisites**:\n* A [Pro or higher account plan](https://www.zoom.us/pricing?).\n* A Zoom Video Management license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt_channels:read`,`video_mgmt_channels:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt:read:list_channel_videos`,`video_mgmt:read:list_channel_videos:adm[...]",
    "operationId": "ListChannelVideos",
    "security": [
     {
      "openapi_oauth": [
       "video_mgmt_channels:read",
       "video_mgmt_channels:read:admin",
       "video_mgmt:read:list_channel_videos",
       "video_mgmt:read:list_channel_videos:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "video_mgmt_channels:read",
      "video_mgmt_channels:read:admin"
     ],
     "x-granular-scopes": [
      "video_mgmt:read:list_channel_videos",
      "video_mgmt:read:list_channel_videos:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Videos"
    ],
    "summary": "Add channel videos",
    "description": "Adds videos to the channel. \n\n**Prerequisites**:\n* A [Pro or higher account plan](https://www.zoom.us/pricing?).\n* A Zoom Video Management license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt_channels:write`,`video_mgmt_channels:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt:write:channel_videos`,`video_mgmt:write:channel_videos:admin`\n\n**[Rate [...]",
    "operationId": "AddChannelVideos",
    "security": [
     {
      "openapi_oauth": [
       "video_mgmt_channels:write",
       "video_mgmt_channels:write:admin",
       "video_mgmt:write:channel_videos",
       "video_mgmt:write:channel_videos:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "video_mgmt_channels:write",
      "video_mgmt_channels:write:admin"
     ],
     "x-granular-scopes": [
      "video_mgmt:write:channel_videos",
      "video_mgmt:write:channel_videos:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Videos"
    ],
    "summary": "Delete channel videos",
    "description": "Removes videos from the channel. \n\n**Prerequisites**:\n* A [Pro or higher account plan](https://www.zoom.us/pricing?).\n* A Zoom Video Management license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt_channels:write`,`video_mgmt_channels:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt:delete:channel_videos`,`video_mgmt:delete:channel_videos:admin`\n\n*[...]",
    "operationId": "DeleteChannelVideos",
    "security": [
     {
      "openapi_oauth": [
       "video_mgmt_channels:write",
       "video_mgmt_channels:write:admin",
       "video_mgmt:delete:channel_videos",
       "video_mgmt:delete:channel_videos:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "video_mgmt_channels:write",
      "video_mgmt_channels:write:admin"
     ],
     "x-granular-scopes": [
      "video_mgmt:delete:channel_videos",
      "video_mgmt:delete:channel_videos:admin"
     ]
    }
   }
  },
  "/video_management/playlists/{playlistId}/videos": {
   "get": {
    "tags": [
     "Videos"
    ],
    "summary": "List playlist videos",
    "description": "Gets the playlist's list of videos. \n\n**Prerequisites**:\n* A [Pro or higher account plan](https://www.zoom.us/pricing?).\n* A Zoom Video Management license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt_playlists:read`,`video_mgmt_playlists:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt:read:list_playlist_videos`,`video_mgmt:read:list_playlist_videos:[...]",
    "operationId": "ListPlaylistVideos",
    "security": [
     {
      "openapi_oauth": [
       "video_mgmt_playlists:read",
       "video_mgmt_playlists:read:admin",
       "video_mgmt:read:list_playlist_videos",
       "video_mgmt:read:list_playlist_videos:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "video_mgmt_playlists:read",
      "video_mgmt_playlists:read:admin"
     ],
     "x-granular-scopes": [
      "video_mgmt:read:list_playlist_videos",
      "video_mgmt:read:list_playlist_videos:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Videos"
    ],
    "summary": "Add playlist videos",
    "description": "Adds videos to a playlist. \n\n**Prerequisites**:\n* A [Pro or higher account plan](https://www.zoom.us/pricing?).\n* A Zoom Video Management license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt_playlists:write`,`video_mgmt_playlists:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt:write:playlist_videos`,`video_mgmt:write:playlist_videos:admin`\n\n**[Ra[...]",
    "operationId": "AddPlaylistVideos",
    "security": [
     {
      "openapi_oauth": [
       "video_mgmt_playlists:write",
       "video_mgmt_playlists:write:admin",
       "video_mgmt:write:playlist_videos",
       "video_mgmt:write:playlist_videos:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "video_mgmt_playlists:write",
      "video_mgmt_playlists:write:admin"
     ],
     "x-granular-scopes": [
      "video_mgmt:write:playlist_videos",
      "video_mgmt:write:playlist_videos:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Videos"
    ],
    "summary": "Delete playlist videos",
    "description": "Deletes videos from a playlist. \n\n**Prerequisites**:\n* A [Pro or higher account plan](https://www.zoom.us/pricing?).\n* A Zoom Video Management license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt_playlists:write`,`video_mgmt_playlists:write:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt:delete:playlist_videos`,`video_mgmt:delete:playlist_videos:admin`\n[...]",
    "operationId": "DeletePlaylistVideos",
    "security": [
     {
      "openapi_oauth": [
       "video_mgmt_playlists:write",
       "video_mgmt_playlists:write:admin",
       "video_mgmt:delete:playlist_videos",
       "video_mgmt:delete:playlist_videos:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "video_mgmt_playlists:write",
      "video_mgmt_playlists:write:admin"
     ],
     "x-granular-scopes": [
      "video_mgmt:delete:playlist_videos",
      "video_mgmt:delete:playlist_videos:admin"
     ]
    }
   }
  },
  "/video_management/videos": {
   "get": {
    "tags": [
     "Videos"
    ],
    "summary": "List all videos",
    "description": "Retrieves the list of videos or recordings added by the user. \n\n**Prerequisites**:\n* A [Pro or higher account plan](https://www.zoom.us/pricing?).\n* A Zoom Video Management license.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt_videos:read`,`video_mgmt_videos:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `video_mgmt:read:list_videos`,`video_mgmt:read:list_video[...]",
    "operationId": "ListAllVideos",
    "security": [
     {
      "openapi_oauth": [
       "video_mgmt_videos:read",
       "video_mgmt_videos:read:admin",
       "video_mgmt:read:list_videos",
       "video_mgmt:read:list_videos:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "video_mgmt_videos:read",
      "video_mgmt_videos:read:admin"
     ],
     "x-granular-scopes": [
      "video_mgmt:read:list_videos",
      "video_mgmt:read:list_videos:admin"
     ]
    }
   }
  }
 },
 "components": {
  "securitySchemes": {
   "openapi_authorization": {
    "type": "apiKey",
    "name": "Authorization",
    "in": "header"
   },
   "openapi_oauth": {
    "type": "oauth2",
    "flows": {
     "authorizationCode": {
      "authorizationUrl": "/",
      "tokenUrl": "",
      "refreshUrl": "",
      "scopes": {
       "video_mgmt_channels:read": "video_mgmt_channels:read",
       "video_mgmt_channels:read:admin": "video_mgmt_channels:read:admin",
       "video_mgmt:read:list_channels": "video_mgmt:read:list_channels",
       "video_mgmt:read:list_channels:admin": "video_mgmt:read:list_channels:admin",
       "video_mgmt_channels:write": "video_mgmt_channels:write",
       "video_mgmt_channels:write:admin": "video_mgmt_channels:write:admin",
       "video_mgmt:write:channel": "video_mgmt:write:channel",
       "video_mgmt:write:channel:admin": "video_mgmt:write:channel:admin",
       "video_mgmt:read:channel": "video_mgmt:read:channel",
       "video_mgmt:read:channel:admin": "video_mgmt:read:channel:admin",
       "video_mgmt:update:channel": "video_mgmt:update:channel",
       "video_mgmt:update:channel:admin": "video_mgmt:update:channel:admin",
       "video_mgmt:delete:channel": "video_mgmt:delete:channel",
       "video_mgmt:delete:channel:admin": "video_mgmt:delete:channel:admin",
       "video_mgmt:read:list_permissions": "video_mgmt:read:list_permissions",
       "video_mgmt:read:list_permissions:admin": "video_mgmt:read:list_permissions:admin",
       "video_mgmt:update:permissions": "video_mgmt:update:permissions",
       "video_mgmt:update:permissions:admin": "video_mgmt:update:permissions:admin",
       "video_mgmt:delete:permissions": "video_mgmt:delete:permissions",
       "video_mgmt:delete:permissions:admin": "video_mgmt:delete:permissions:admin",
       "video_mgmt:write:permissions": "video_mgmt:write:permissions",
       "video_mgmt:write:permissions:admin": "video_mgmt:write:permissions:admin",
       "video_mgmt:read:list_channel_playlists": "video_mgmt:read:list_channel_playlists",
       "video_mgmt:read:list_channel_playlists:admin": "video_mgmt:read:list_channel_playlists:admin",
       "video_mgmt:delete:channel_playlists": "video_mgmt:delete:channel_playlists",
       "video_mgmt:delete:channel_playlists:admin": "video_mgmt:delete:channel_playlists:admin",
       "video_mgmt:write:channel_playlists": "video_mgmt:write:channel_playlists",
       "video_mgmt:write:channel_playlists:admin": "video_mgmt:write:channel_playlists:admin",
       "video_mgmt_playlists:read": "video_mgmt_playlists:read",
       "video_mgmt_playlists:read:admin": "video_mgmt_playlists:read:admin",
       "video_mgmt:read:list_playlists": "video_mgmt:read:list_playlists",
       "video_mgmt:read:list_playlists:admin": "video_mgmt:read:list_playlists:admin",
       "video_mgmt_playlists:write": "video_mgmt_playlists:write",
       "video_mgmt_playlists:write:admin": "video_mgmt_playlists:write:admin",
       "video_mgmt:write:playlist": "video_mgmt:write:playlist",
       "video_mgmt:write:playlist:admin": "video_mgmt:write:playlist:admin",
       "video_mgmt:delete:playlist": "video_mgmt:delete:playlist",
       "video_mgmt:delete:playlist:admin": "video_mgmt:delete:playlist:admin",
       "video_mgmt:update:playlist": "video_mgmt:update:playlist",
       "video_mgmt:update:playlist:admin": "video_mgmt:update:playlist:admin",
       "video_mgmt:delete:channel_videos": "video_mgmt:delete:channel_videos",
       "video_mgmt:delete:channel_videos:admin": "video_mgmt:delete:channel_videos:admin",
       "video_mgmt:read:list_channel_videos": "video_mgmt:read:list_channel_videos",
       "video_mgmt:read:list_channel_videos:admin": "video_mgmt:read:list_channel_videos:admin",
       "video_mgmt:write:channel_videos": "video_mgmt:write:channel_videos",
       "video_mgmt:write:channel_videos:admin": "video_mgmt:write:channel_videos:admin",
       "video_mgmt:read:list_playlist_videos": "video_mgmt:read:list_playlist_videos",
       "video_mgmt:read:list_playlist_videos:admin": "video_mgmt:read:list_playlist_videos:admin",
       "video_mgmt:write:playlist_videos": "video_mgmt:write:playlist_videos",
       "video_mgmt:write:playlist_videos:admin": "video_mgmt:write:playlist_videos:admin",
       "video_mgmt:delete:playlist_videos": "video_mgmt:delete:playlist_videos",
       "video_mgmt:delete:playlist_videos:admin": "video_mgmt:delete:playlist_videos:admin",
       "video_mgmt_videos:read": "video_mgmt_videos:read",
       "video_mgmt_videos:read:admin": "video_mgmt_videos:read:admin",
       "video_mgmt:read:list_videos": "video_mgmt:read:list_videos",
       "video_mgmt:read:list_videos:admin": "video_mgmt:read:list_videos:admin"
      }
     }
    }
   }
  }
 }
}