{
 "openapi": "3.0.0",
 "info": {
  "title": "Virtual Agent",
  "description": "Zoom Virtual Agent APIs enable you to build artificial intelligence (AI) and chatbot solutions for your website. \n\n Your website users can expect immediate responses to their queries at any time. As a result, Zoom Virtual Agent deploys support to your users faster and reduces the workload for your live agents. \n\n All endpoints are available through `https` at `api.zoom.us/v2/`.",
  "termsOfService": "https://zoom.us/docs/en-us/zoom_api_license_and_tou.html",
  "contact": {
   "name": "Zoom Developers",
   "url": "https://developer.zoom.us/"
  },
  "version": "2"
 },
 "servers": [
  {
   "url": "https://api.zoom.us/v2"
  }
 ],
 "paths": {
  "/km/kbs/{kbId}/articles": {
   "get": {
    "tags": [
     "Knowledge Management"
    ],
    "summary": "Get articles",
    "description": "Returns multiple knowledge base articles.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zva:read:km_kbs`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zva:read:list_km_articles`,`zva:read:list_km_articles:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "GetArticles",
    "security": [
     {
      "openapi_oauth": [
       "zva:read:km_kbs",
       "zva:read:list_km_articles",
       "zva:read:list_km_articles:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomKnowledgeBaseKnowledgeBases:Read",
      "AIStudioKnowledgeBases:Read"
     ],
     "x-macro-scopes": [
      "zva:read:km_kbs"
     ],
     "x-granular-scopes": [
      "zva:read:list_km_articles",
      "zva:read:list_km_articles:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Knowledge Management"
    ],
    "summary": "Create article",
    "description": "Creates a knowledge base article.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zva:write:km_kbs`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zva:write:km_article`,`zva:write:km_article:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "CreateArticle",
    "security": [
     {
      "openapi_oauth": [
       "zva:write:km_kbs",
       "zva:write:km_article",
       "zva:write:km_article:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomKnowledgeBaseKnowledgeBases:Edit",
      "AIStudioKnowledgeBases:Edit"
     ],
     "x-macro-scopes": [
      "zva:write:km_kbs"
     ],
     "x-granular-scopes": [
      "zva:write:km_article",
      "zva:write:km_article:admin"
     ]
    }
   }
  },
  "/km/kbs/{kbId}/articles/{articleId}": {
   "get": {
    "tags": [
     "Knowledge Management"
    ],
    "summary": "Get article",
    "description": "Returns a knowledge base article.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zva:read:km_kbs`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zva:read:km_article`,`zva:read:km_article:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "GetArticle",
    "security": [
     {
      "openapi_oauth": [
       "zva:read:km_kbs",
       "zva:read:km_article",
       "zva:read:km_article:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomKnowledgeBaseKnowledgeBases:Read",
      "AIStudioKnowledgeBases:Read"
     ],
     "x-macro-scopes": [
      "zva:read:km_kbs"
     ],
     "x-granular-scopes": [
      "zva:read:km_article",
      "zva:read:km_article:admin"
     ]
    }
   },
   "put": {
    "tags": [
     "Knowledge Management"
    ],
    "summary": "Update article",
    "description": "Updates a knowledge base article.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zva:write:km_kbs`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zva:update:km_article`,`zva:update:km_article:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "UpdateArticle",
    "security": [
     {
      "openapi_oauth": [
       "zva:write:km_kbs",
       "zva:update:km_article",
       "zva:update:km_article:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomKnowledgeBaseKnowledgeBases:Edit",
      "AIStudioKnowledgeBases:Edit"
     ],
     "x-macro-scopes": [
      "zva:write:km_kbs"
     ],
     "x-granular-scopes": [
      "zva:update:km_article",
      "zva:update:km_article:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Knowledge Management"
    ],
    "summary": "Delete article",
    "description": "Deletes a knowledge base article.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zva:write:km_kbs`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zva:delete:km_article`,`zva:delete:km_article:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "DeleteArticle",
    "security": [
     {
      "openapi_oauth": [
       "zva:write:km_kbs",
       "zva:delete:km_article",
       "zva:delete:km_article:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomKnowledgeBaseKnowledgeBases:Edit",
      "AIStudioKnowledgeBases:Edit"
     ],
     "x-macro-scopes": [
      "zva:write:km_kbs"
     ],
     "x-granular-scopes": [
      "zva:delete:km_article",
      "zva:delete:km_article:admin"
     ]
    }
   }
  },
  "/km/kbs/{kbId}/sync": {
   "post": {
    "tags": [
     "Knowledge Management"
    ],
    "summary": "Create sync request",
    "description": "Creates a sync request for the specified knowledge base\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zva:write:km_kbs`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zva:update:km_kb:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "CreateSyncRequest",
    "security": [
     {
      "openapi_oauth": [
       "zva:write:km_kbs",
       "zva:update:km_kb:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomKnowledgeBaseKnowledgeBases:Edit",
      "AIStudioKnowledgeBases:Edit"
     ],
     "x-macro-scopes": [
      "zva:write:km_kbs"
     ],
     "x-granular-scopes": [
      "zva:update:km_kb:admin"
     ]
    }
   }
  },
  "/km/kbs/{kbId}/sync/{syncId}": {
   "get": {
    "tags": [
     "Knowledge Management"
    ],
    "summary": "Get sync",
    "description": "Returns the details of a knowledge base sync.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zva:read:km_kbs`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zva:read:km_kb:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "GetSync",
    "security": [
     {
      "openapi_oauth": [
       "zva:read:km_kbs",
       "zva:read:km_kb:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [
      "ZoomKnowledgeBaseKnowledgeBases:Read",
      "AIStudioKnowledgeBases:Read"
     ],
     "x-macro-scopes": [
      "zva:read:km_kbs"
     ],
     "x-granular-scopes": [
      "zva:read:km_kb:admin"
     ]
    }
   }
  },
  "/virtual_agent/report/engagements": {
   "get": {
    "tags": [
     "Report"
    ],
    "summary": "Get ZVA engagements",
    "description": "Generates a list of ZVA engagements.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zva_report:read`,`zva_report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zva:read:list_engagements:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "GetZVAEngagements",
    "security": [
     {
      "openapi_oauth": [
       "zva_report:read",
       "zva_report:read:admin",
       "zva:read:list_engagements:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zva_report:read",
      "zva_report:read:admin"
     ],
     "x-granular-scopes": [
      "zva:read:list_engagements:admin"
     ]
    }
   }
  },
  "/virtual_agent/report/engagements/query_details": {
   "get": {
    "tags": [
     "Report"
    ],
    "summary": "Get ZVA query details",
    "description": "Returns a list of ZVA engagement query details.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zva_report:read`,`zva_report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zva:read:list_queries:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "GetZVAQueryDetails",
    "security": [
     {
      "openapi_oauth": [
       "zva_report:read",
       "zva_report:read:admin",
       "zva:read:list_queries:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zva_report:read",
      "zva_report:read:admin"
     ],
     "x-granular-scopes": [
      "zva:read:list_queries:admin"
     ]
    }
   }
  },
  "/virtual_agent/report/engagements/variables": {
   "get": {
    "tags": [
     "Report"
    ],
    "summary": "Get ZVA variable details",
    "description": "Get a list of ZVA engagement variable details.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zva_report:read`,`zva_report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zva:read:list_variables:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "GetZVAengagementvariabledetails",
    "security": [
     {
      "openapi_oauth": [
       "zva_report:read",
       "zva_report:read:admin",
       "zva:read:list_variables:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zva_report:read",
      "zva_report:read:admin"
     ],
     "x-granular-scopes": [
      "zva:read:list_variables:admin"
     ]
    }
   }
  },
  "/virtual_agent/report/surveys": {
   "get": {
    "tags": [
     "Report"
    ],
    "summary": "Get ZVA Surveys",
    "description": "Returns a list of ZVA engagement surveys.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zva_report:read`,`zva_report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zva:read:list_surveys:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "GetZVASurveys",
    "security": [
     {
      "openapi_oauth": [
       "zva_report:read",
       "zva_report:read:admin",
       "zva:read:list_surveys:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zva_report:read",
      "zva_report:read:admin"
     ],
     "x-granular-scopes": [
      "zva:read:list_surveys:admin"
     ]
    }
   }
  },
  "/virtual_agent/report/transcripts": {
   "get": {
    "tags": [
     "Report"
    ],
    "summary": "Get ZVA transcripts",
    "description": "Generates a list of ZVA transcripts.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zva_report:read`,`zva_report:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `zva:read:list_transcripts:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "GetZVATranscripts",
    "security": [
     {
      "openapi_oauth": [
       "zva_report:read",
       "zva_report:read:admin",
       "zva:read:list_transcripts:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "x-extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "zva_report:read",
      "zva_report:read:admin"
     ],
     "x-granular-scopes": [
      "zva:read:list_transcripts:admin"
     ]
    }
   }
  }
 },
 "components": {
  "securitySchemes": {
   "openapi_authorization": {
    "type": "apiKey",
    "name": "Authorization",
    "in": "header"
   },
   "openapi_oauth": {
    "type": "oauth2",
    "flows": {
     "authorizationCode": {
      "authorizationUrl": "/",
      "tokenUrl": "",
      "refreshUrl": "",
      "scopes": {
       "zva:write:km_kbs": "zva:write:km_kbs",
       "zva:write:km_article": "zva:write:km_article",
       "zva:write:km_article:admin": "zva:write:km_article:admin",
       "zva:read:km_kbs": "zva:read:km_kbs",
       "zva:read:list_km_articles": "zva:read:list_km_articles",
       "zva:read:list_km_articles:admin": "zva:read:list_km_articles:admin",
       "zva:update:km_article": "zva:update:km_article",
       "zva:update:km_article:admin": "zva:update:km_article:admin",
       "zva:delete:km_article": "zva:delete:km_article",
       "zva:delete:km_article:admin": "zva:delete:km_article:admin",
       "zva:read:km_article": "zva:read:km_article",
       "zva:read:km_article:admin": "zva:read:km_article:admin",
       "zva:update:km_kb:admin": "zva:update:km_kb:admin",
       "zva:read:km_kb:admin": "zva:read:km_kb:admin",
       "zva_report:read": "zva_report:read",
       "zva_report:read:admin": "zva_report:read:admin",
       "zva:read:list_engagements:admin": "zva:read:list_engagements:admin",
       "zva:read:list_queries:admin": "zva:read:list_queries:admin",
       "zva:read:list_variables:admin": "zva:read:list_variables:admin",
       "zva:read:list_surveys:admin": "zva:read:list_surveys:admin",
       "zva:read:list_transcripts:admin": "zva:read:list_transcripts:admin"
      }
     }
    }
   }
  }
 }
}